### ISSUE TITLE
stuck at create new app

### ISSUE THREAD

**Issue by GHfan** [web2py/web2py#1014]
Hi, i'm new to web2py, i've stuck creating new app for a while, and i did some google, yet not solved...
Here is it.
### first try
When i hit the create button use the name 'one' in 'site' page, which give me this:
```python
  File "/Users/gavin/code/open_source/web2py/gluon/packages/dal/pydal/adapters/base.py", line 737, in insert
    raise e
ValueError: INSERT INTO appcreate(name) VALUES ('one');
```
I have no idea what's wrong , but i thought there could be a folder created by web2py, but i was wrong. Then let's debug it.

### try again
I put a 'import pdb;pdb.set_trace()'  under the function site() in applications/admin/controllers/default.py  , which gave me this:
```bash
(Pdb) Tcl_WaitForEvent: Notifier not initialized
```
Then i relized that Tkinter is running and pdb will not function.And i have no experience using TKinter, so i give up.

### third try
I find a command-line option "-S APPNAME, --shell=APPNAME" will create the app if not exist , looks great , which turn out drive me crazy......
The program is not working when i hit ENTER, it shows in the terminal like this:
```bash
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2015
Version 2.11.2-stable+timestamp.2015.05.30.11.29.46
Database drivers available: sqlite3, imaplib, pyodbc, pymysql, pg8000
application one does not exist, create (y/n)?y^M^M^M
```
what???
I don't know if that was my shell's wrong configation or what?

### another try?
I'm going insane...
The only way i can thought now is try a NON-GUI start up and put pdb in the code like my second try, which is a way to go and what i'm doing now...
The command is 
```bash
 python web2py.py --nogui -a '111111'
```
-a set the admin password

I'm just not comfortable with a vary start like this, and NOT EASY for me...
So, please anybody can tell me what is the problem? 
And if there is a debug mode for easy develop?
And what if i dont't want the admin way to develop my application?

**Comment by mdipierro** [comment]
And you using web2py stable from the web2py or web2py from Git? You should use the former. The git version is a work in progress.

**Comment by GHfan** [comment]
Oh...I'm using Git, i tried the source code downloaded from the website, it's working now, thanks~
