### ISSUE TITLE
SQLFORM.factory uses fieldname instead of  rname in form.vars

### ISSUE THREAD

**Issue by macfiron** [web2py/web2py#1015]
I specified a table definition and  a form like this:
db.define_table('tiatpi',Field('MyFieldName', rname='twistedFunnyRecordName'))
form = SQLFORM.factory(db.tiatpi)

Then I entered a value into the field and upon successful form.process().accepted i did:
logging.warn(gluon.contrib.simplejson.dumps(form.vars))

The output looked like:
WARNING:root:{"MyFieldName": "foo", "id": 1}

The expected output would have been:
WARNING:root:{"twistedFunnyRecordName": "foo", "id": 1}

I'm not sure, if this is an issue with DAL or web2py.
produced with web2py_version: 2.11.2-stable+timestamp.2015.05.30.16.33.24

**Comment by niphlod** [comment]
that's exactly what is expected to happen. everything works with the "normal name" while the database interactions are done using the "funny" one. the translation happens just one step away from the database, in both senses (i.e. when you query the db for records and when you insert/update them)

db.tiapi.insert(MyFieldName='abc') 

is the only way to insert records, even if it translates to a

insert into tiapi (twistedfunnyrecordname) values ('abc')
