### ISSUE TITLE
DAL selecting fields and table that is not on query

### ISSUE THREAD

**Issue by leonardopf** [web2py/web2py#1020]
I don't know if this could be a risk or if it is the expected behaviour in those cases. 
Someone else can reproduce this?

If i do this on my table:
>>> db(db.IE_pessoa.id>0).select(db.auth_user.first_name)
<Rows (1)>
it returns the data on auth_user, even when not explicit in the table on query. And the table has not any relation with auth_user.

Tested too on the version for testers(2.11.2-stable+timestamp.2015.05.30.16.33.24) on the site:
Create a test application;
create a simple table:
db.define_table('test',
                Field('test_name')
                )
register a user;
populate the table(if the query is empty it not returns the table on the select):
>>> a = db(db.test.id>0).select(db.auth_user.first_name)
>>> print a
auth_user.first_name
>>> db.test.insert(test_name='test')
1L
>>> print db(db.test.id>0).select(db.auth_user.first_name)
auth_user.first_name
leonardo

**Comment by mdipierro** [comment]
I can confirm this behavior but if you look at the generated SQL:

    In [4]: print db(db.test.id>0)._select(db.auth_user.first_name)
    SELECT  auth_user.first_name FROM test, auth_user WHERE (test.id > 0);

Web2py interpret it as a join, returns the cross product between the tables, then filters the column you want. In my opinion this is correct.
