### ISSUE TITLE
Caching recursive selects for references can lead to incorrect "represent" values

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1024]
Commit https://github.com/web2py/web2py/commit/d1ec005924b10e0c738040586acaaa200db9d244 introduced caching of "represent" values for reference fields in SQLTABLE, SQLFORM.grid, and the grid ExportClass:

Unfortunately, this approach assumes all reference fields have the default "represent" function generated automatically by the DAL, which depends only on the ID value stored in the reference field and not on any other fields in the record. As a result, the cache key used to identify common "represent" values is based only on the reference field value itself. This approach fails if the user has defined a custom "represent" function that depends on other fields in the record.

For example, suppose we have:

    db.mytable.myref.represent = lambda v, r: A(v.some_field, _href=URL('edit_record', r.id))

If the first record of mytable has values {id: 1, myref: 5}, then the value A(..., _href=URL('edit_record', 1)) will be stored in repr_cache['myref'][5] .

Now if a subsequent record has values {id: 10, myref: 5}, then the value stored in repr_cache['myref'][5] will be retrieved (because the value 5 of the represent field matches the cache key from the earlier record), but it will be incorrect, because the correct value should be A(..., _href=URL('edit_record', 10)).

The problem is that the key (5 in this case) does not uniquely identify the returned value of the represent function, which depends not only on the value 5, but also on the value of r.id.

This feature should either be reverted or fixed to accommodate custom "represent" functions.

**Comment by abastardi** [comment]
Rather than caching the output of "represent" functions for reference fields only in this limited context, maybe it would be useful to add a DAL feature that enables DAL-wide caching to be turned on and off. Something like:

    db._cache_all(True, cache=cache.ram, cacheable=True)
    [some code that does lots of repetitive queries]
    db._cache_all(False)

When caching is turned off, all cached values should be cleared (so the cache doesn't grow too large).

The grid row-assembly code could be wrapped as above, so all queries in "represent" attributes would be cached automatically.

**Comment by niphlod** [comment]
I thought I was extra-careful caching only the 'reference' Fields that IMHO should have been idempotent. 
In my normal usage, even other things are idempotent and should have been cached, but I guess I left out the corner case of a custom represent on the 'reference' itself.
Granted, it was a one-time shot to avoid recursion in the heaviest components of web2py, and would have been nice to have it by default.
Guess that "1 step forward, 2 step back" is the de-facto rule when everyone can make a lambda out of anything, so nothing can be cached. 
Another sad day for performance, in the spirit of leaving the 1% free to do whatever they want.
Revert the patch, and everything will work out fine.

**Comment by mdipierro** [comment]
Can't we simply detect if the represent is the default one? We could have a method that implements the default validator we can can check before deciding when to cache.

**Comment by mdipierro** [comment]
This is fixed in trunk by disabling the feature for non-default represent functions.
