### ISSUE TITLE
fpdf not determining between PIL and Pillow

### ISSUE THREAD

**Issue by tB0nE** [web2py/web2py#1026]
If you upgrade to Pillow from PIL, you need to alter the code in fpdf in order for it to work correctly. In order to have it to try to import the Pillow method after it attempts PIL, add this:

    try:
        if Image == None:
            from PIL import Image
    except:
        Image = None

Below this:

    try:
        # Check if PIL is available, necessary for JPEG support.
        import Image
    except ImportError:
        Image = None

**Comment by mdipierro** [comment]
It is my understanding that Pillow is a replacement for PIL and the latter should be uninstalled to avoid conflicts.

**Comment by tB0nE** [comment]
That is correct, however PIL and Pillow work differently, which means you have to alter fpdf.py in gluon before Pillow will work. This is bit of a hassle. If you add the code above you don't have to, it will work with either.

**Comment by niphlod** [comment]
reported to https://github.com/reingart/pyfpdf/issues/46 . Follow there the developments, then we can merge back the results.
