### ISSUE TITLE
Orderby: Sorting records according to multiple fields

### ISSUE THREAD

**Issue by amir-beheshty** [web2py/web2py#1027]
orderby can accept *multiple* fields by concatenating them with a "|". See the [official web2py docs](http://www.web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#orderby--groupby--limitby--distinct--having-orderby_on_limitby-left-cache):

However when I used this code:

    db(db.my_table.id == user_id).select(orderby=~db.my_table.isCurrent | db.my_table.endYear | db.my_table.endMonth)

The return sorted the records based on isCurrent column only. The rest of the fields were ignored.

This code worked though:

    db(db.my_table.id == user_id).select(orderby="my_table.isCurrent DESC, my_table.endYear DESC, my_table.endMonth DESC")

**Comment by cassiobotaro** [comment]
Your query should be like db(db.my_table.id == user_id).select(orderby=~db.my_table.isCurrent | ~db.my_table.endYear | ~db.my_table.endMonth)

If you want to see the generated sql use `_select`  db(db.my_table.id == user_id)._select(orderby=~db.my_table.isCurrent | ~db.my_table.endYear | ~db.my_table.endMonth) before run the code properly.

**Comment by amir-beheshty** [comment]
I see. Thanks for clarifying that. I suppose a similar example would be useful for the official docs to devoid confusion.
