### ISSUE TITLE
sqlhtml.py Formwidget issue and solution

### ISSUE THREAD

**Issue by AnneVerme** [web2py/web2py#1033]
In sqlhtml.py line 119 I added form-control to _class = 'generic-widget' to solve an issue when a form contains errors. In that case the options widget is rendered with class = 'generic-widget' instead of
class =  'generic-widget form-control'

**Comment by ShySec** [comment]
What is the issue?

**Comment by niphlod** [comment]
closing for lack of replies. Feel free to reopen in case the bug still stands.
