### ISSUE TITLE
Issue with add_group when auth_user doesnt have records

### ISSUE THREAD

**Issue by Nastrand** [web2py/web2py#1035]
Hello!

I've notices an issue with the add_group function, in my models i have a configuration file that creates groups every time the database is created, something like this:

if not db(db.auth_group).count():
    auth.add_group('manager', 'manage user stuff')

and when in try to run my app without tables (the app creating the tables for first time) i get this error:

<class 'gluon.contrib.pymysql.err.IntegrityError'> (1452, u'Cannot add or update a child row: a foreign key constraint fails (`database`.`auth_event`, CONSTRAINT `auth_event_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`) ON DELETE CASCADE)')

i've been testing and this error happens because when the application creates a new group via add_group, tries to create a event inside the auth_event table, but one of the field of the auth_event table points to auth_user, and auth_user at table creation is empty, so doesnt exist any foreign key that the app cant set to that field

I'm using MySQL 5.5 and web2py 2.11.2 on a linux mint 16 environment.

**Comment by BuhtigithuB** [comment]
And why not just do : db.auth_group.insert(role='manager',
description='manager user stuff')

??

I don't think you will get error that way... I guess auth.add_group() is
intent to work that way since it makes use of auth which is to be activated
to be used... And you need to have to user in order to be able to track
event origin...

Richard

**Comment by Nastrand** [comment]
@BuhtigithuB That solved my problem, but i think this still is a bug.

**Comment by BuhtigithuB** [comment]
I don't think, why it could be a bug? As I said, auth.somemethods() expect
that you have activate the built-in authentication mechanism of web2py...
If there is no user there no way you can track event of them... Should we
make the user_id field not mandatory in auth_event? Maybe, I guess it could
solve your problem... But to me you make a wrong usage of add_group()...
Why would you add a group with auth.add_group() if auth is not activated
and if you have no user... But it could be argue that auth_event should log
event even if there is no user... The question is does it make sens to log
event without knowing who made the request?

But think about it, should we create a specific add function out of the box
for each table you want to do an insertion??

**Comment by Nastrand** [comment]
@BuhtigithuB hmm... i agree with you, i'll close this issue.
