### ISSUE TITLE
IS_NOT_EMPTY returns stripped value

### ISSUE THREAD

**Issue by susu** [web2py/web2py#1038]
IS_NOT_EMPTY validator strips the value
**UPDATE**: and returns the stripped value.

Web2py version: v2.5.1

(Caused a PITA issue at customer. The subsequent validator got a stripped value, and accepted it, however it would not accept the unstripped value, a dirty hacky workaround would be to swap the two validator.)

**Comment by niphlod** [comment]
2.5.1 is from jun 2013. test for it on the latest and then get back if the same bug is found...

**Comment by susu** [comment]
At the moment I could not upgrade to the latest, but it still does, according to this:
https://github.com/web2py/web2py/blob/5775d2788d765db2ea85efeb346f51064ab18459/gluon/validators.py#L947

Furthermore, I've found that has even a doctest!
https://github.com/web2py/web2py/blob/5775d2788d765db2ea85efeb346f51064ab18459/gluon/validators.py#L968

OMG, is it a feature? :scream:

(For completeness: it is written to database **unstripped**!)

**Comment by niphlod** [comment]
evidently, it's not a bug but a requirement.

**Comment by jklundell** [comment]
> On 6 Aug 2015, at 6:06 AM, Marton Suranyi <notifications@github.com> wrote:
> 
> At the moment I could not upgrade to the latest, but it still does, according to this:
> https://github.com/web2py/web2py/blob/5775d2788d765db2ea85efeb346f51064ab18459/gluon/validators.py#L947 <https://github.com/web2py/web2py/blob/5775d2788d765db2ea85efeb346f51064ab18459/gluon/validators.py#L947>
> Furthermore, I've found that has even a doctest!
> https://github.com/web2py/web2py/blob/5775d2788d765db2ea85efeb346f51064ab18459/gluon/validators.py#L968 <https://github.com/web2py/web2py/blob/5775d2788d765db2ea85efeb346f51064ab18459/gluon/validators.py#L968>
> OMG, is it a feature? 
> 
> (For completeness: it is written to database unstripped!)
> 
> 

I can see the logic for it (and for that matter I may well have written the doctest, if not the empty-test). It makes sense if you interpret “is empty” to mean that the content of the field is semantically empty in the specific context of that element. Note the optional regex to define exactly what that means, and the built-in cases for NULL/None, a string with non-whitespace characters in it, or an empty list.

It does return the stripped string, fwiw; I have no idea whether that’s what ends up getting written.

**Comment by susu** [comment]
@jklundell I am not sure if I'm understand well, but my basic problem that the validator actually returns the stripped value. The next validator in the row will receive that modified value, and accepted it (but it would not accept the original, unstripped value). Maybe the name of the issue is misleading, I've updated that.

I think this is an ugly side-effect of ``IS_NOT_EMPTY`` validator. Maybe it should be called ``IS_NOT_EMPTY_AND_STRIP_VALUE`` to express this behaviour better.

@niphlod Requirement for exactly what?

**Comment by niphlod** [comment]
@susu : sorry, rephrasing: if there's a test, believe me, it's because someone is using the behaviour as a specific feature. 
Given the grand-lack of tests on web2py in general, the ones that are there have been definitively put to avoid regressions. 
That being said, a validator that changes the value is not a great thing and the naming could be better, but I don't think - at least if someone doesn't come up with the original requirement - change the behaviour in a snap.

**Comment by jklundell** [comment]
> On 6 Aug 2015, at 7:39 AM, niphlod <notifications@github.com> wrote:
> 
> @susu <https://github.com/susu> : sorry, rephrasing: if there's a test, believe me, it's because someone is using the behaviour as a specific feature. 
> Given the grand-lack of tests on web2py in general, the ones that are there have been definitively put to avoid regressions. 
> That being said, a validator that changes the value is not a great thing and the naming could be better, but I don't think - at least if someone doesn't come up with the original requirement - change the behaviour in a snap.
> 


Unfortunately that’s also true of several other “validators”. See for example IS_LOWER &c.

**Comment by susu** [comment]
Ok, now I understand. I think I will introduce our "side-effect free" validator.
