### ISSUE TITLE
Possible bug in 2.12.2 when including a .css file in a HTML email template

### ISSUE THREAD

**Issue by jicho** [web2py/web2py#1041]
Hi,

I've just updated my project to Web2py 2.12.2 and found a little issue that wasn't there in my previouse versie 2.10.something...

I render a HTML template for the 'reset password' email like this:

```
auth.messages.reset_password = response.render('templates/email/reset_password.html',
                                               base_url='http://' + request.env.http_host,
                                               portal_name=site_settings.portal_name,
                                               password_url=URL(r=request, c='default', f='choose_new_password') + '?key=%(key)s')
```

The template itself looks like this:

```
<html>
    <head>
       {{include 'templates/email/includes/css.html'}}
   </head>

    {{include 'templates/email/includes/body_top.html'}}
        <p>
            Click on the URL
            <a href="{{=base_url}}{{=password_url}}">{{=base_url}}{{=password_url}}</a>
        </p>
    {{include 'templates/email/includes/body_bottom.html'}}
</html>
```

After disabling the includes and partial css format in the css.html I've discovered that the following lines in css.html:

```
<style type="text/css">
    table {
        width: 100%;
        border-collapse: collapse;
    }
</style>
```

Is causing this error:

```
unsupported format character ';' (0x3b) at index 397
```

When I change "100%;" into, for example, "100px;" the error is gone... downside it that the layout of the email is also 'gone' ;)

It this a bug? Or do I need to do things differently and did is work by accident in previous versions of Web2Py?

**Comment by jicho** [comment]
Looks like this line in tools.py on line 3481, here to be exact:

```
message=self.messages.reset_password % d):
```

When I remove "% d" everything works find, of course the key isn't replaced... Another route is to escape the % in the included css, so when I change "width: 100%;" into "width: 100%%;" the problem is solved. Although that's not a solution since the css is used on more places :(

Any idea how to solve this without tricks?

**Comment by niphlod** [comment]
uhm. probably unrelated but worth to mention....the syntax for render is render(view, vars), not render(view, var1, var2, var3). did you try following the specific docs ?

**Comment by jicho** [comment]
@niphlod the render(view, var1, var2, var3) solution was found somewhere at Google, works great ;) Looking at the specs... It isn't according to the specs, so I've changed is in my code. 

Thanks for pointing it out.

BTW: This isn't the solution for my issue.

**Comment by niphlod** [comment]
"found on google" vs "it's the documented one" will help when your app will break because a code modification will lead to the latter to be the only way to do it. But I hear you. the problem is due to template evaluation because of the reset_password, which is meant to be sent as a text email rather than html. I can't really find an easy way around it rather than escaping the relevant bits of css.

**Comment by jicho** [comment]
You're right about that! At the time I didn't find the solution in the docs ;)

So the problem is that I want more with the email then allowed :) No Web2Py bug found, I'm doing something that is possible but was not intended to do.

Can I leave this issue open so it can become a feature request? Or do you want me to close it?

Thanks for your input.

**Comment by baddev** [comment]
Hi,

You can solve this by escaping python special characters like in a normal python template.

Kind regards,
