### ISSUE TITLE
alignment of readonly fields in forms

### ISSUE THREAD

**Issue by mdipierro** [web2py/web2py#1043]
https://groups.google.com/forum/#!topic/web2py/6Qbcr8nuey8

**Comment by giova23** [comment]
Thanks for the fix. It worked well for all fields, except for the numeric ones. 
We fixed that by adding int, long, float near basestring in the patch:

From:
+            elif controls is None or isinstance(controls, basestring):
+                _controls = P(controls, _class="form-control-static %s" % col_class)

To:
+            elif controls is None or isinstance(controls, (basestring,int,long, float)):
+                _controls = P(controls, _class="form-control-static %s" % col_class)
