### ISSUE TITLE
Browser auto-fill can corrupt data while using admin database interface

### ISSUE THREAD

**Issue by dkleissa** [web2py/web2py#1045]
When viewing/editing a record using the admin panel, browser auto-fill can sometimes populate fields without you realizing it.  I think auto-fill should be disabled for all fields when using the database management interface.  Something like this could do:

    $(document).ready(function() {
        $(":input").attr("autocomplete","off");
    });

**Comment by dkleissa** [comment]
This is actually starting to cause real problems for me and I imagine others. Has anyone else had problems with this?  I tried adding the above script to appadmin.html when editing a record, but it doesn't seem to solve the problem using chrome or safari.  Seems to work OK in firefox though.

**Comment by niphlod** [comment]
closed by https://github.com/web2py/web2py/commit/b0373297e0a2071180510b20867d7e881ebb32a7
