### ISSUE TITLE
Avoid asking for credentials when user is logged in and user/login?_next present in URL

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1052]
I will send a PR

**Comment by BuhtigithuB** [comment]
Link to thread : https://groups.google.com/d/msg/web2py/wTzEiCJ1yF4/ioqCqiuTOQUJ

Consider not accepting this PR if Anthony solution is better, here : https://groups.google.com/d/msg/web2py/wTzEiCJ1yF4/AmCHwUUFpLUJ

**Comment by niphlod** [comment]
#1053 was merged, so this needs closing.
