### ISSUE TITLE
drop down menus disappear if response.static_version contains alphabets.

### ISSUE THREAD

**Issue by saifuddinrangwala** [web2py/web2py#1055]
I do not understand the purpose of static_version however below line in models/db.py causes all the drop down menus to disappear in the welcome app.

response.static_version = '0.0.0 beta'

**Comment by niphlod** [comment]
from the book

    Notice that the URL starts with "/myapp/static/", followed by a version number composed by an
    underscore and 3 integers separated by a period (as described in SemVer), then followed by the
    filename. Also notice that you do not have to create a "_1.2.3/" folder.

to keep the regex simple and fast, it MUST be an underscore, followed by 3 integers separated by a dot.
