### ISSUE TITLE
form.add_button('Back', URL('other_page'))

### ISSUE THREAD

**Issue by benlawraus** [web2py/web2py#1063]
When I add 
form.add_button('Back', URL('other_page'))
to a controller 'show_post()', it automatically redirects to 'other_page' without showing the view 'show_post.html'

**Comment by amerikan** [comment]
```
form.add_button('Back, URL('your_controller_here', 'show_post'))
```

**Comment by niphlod** [comment]
@benlawraus : just checked and I can't reproduce: unless you can post a complete example I'm going to close this in a few days

**Comment by cpascu01** [comment]
@benlawraus Do you have a redirect to URL('other_page') somewhere before you add it to the form?  I just found something like this in a project I'm working on and saw that was my issue.

**Comment by niphlod** [comment]
closing for lack of replies: feel free to reopen (with more details) if the bug still stands
