### ISSUE TITLE
Unable to store XML in session.flash

### ISSUE THREAD

**Issue by maxcrystal** [web2py/web2py#1067]
In Welcome app's default controller replace `response.flash = T("Hello World")` with
```
session.flash = XML('Hello <b>World</b>')
redirect(URL('user', args='login'))
```
The result is flash with "Hello \<b>World\</b>".

If you comment out the following part of code in html.py everything works OK. The flash shows "Hello **World**".
```
670 def XML_unpickle(data):
671     return marshal.loads(data)
672
673
674 def XML_pickle(data):
675     return XML_unpickle, (marshal.dumps(str(data)),)
676     copy_reg.pickle(XML, XML_pickle, XML_unpickle)
```

**Comment by leonelcamara** [comment]
In fact this error is easy to see.

    >>> a = XML('hello <b>world</b>')
    >>> import cPickle as pickle
    >>> b = pickle.dumps(a)
    >>> pickle.loads(b)
    'hello <b>world</b>'
    >>> c = pickle.loads(b)
    >>> type(a)
    <class 'gluon.html.XML'>
    >>> type(c)
    <type 'str'>

It's converting it to a string. The easiest fix seems to be just to delete the lines for copy_reg as XML seems to be pickable perfectly fine without it.

**Comment by maxcrystal** [comment]
Or maybe convert unpickled data back to XML: replace `return marshal.loads(data)` with `return XML(marshal.loads(data))`

**Comment by erilyth** [comment]
Using XML(marsha.loads(data)) would be better as we could store strings in the pickle just like before

**Comment by mdipierro** [comment]
in trunk
