### ISSUE TITLE
auth functionality broken when using session.secure()

### ISSUE THREAD

**Issue by timrichardson** [web2py/web2py#1070]
Authentication doesn't work when using sessions.secure() on trunk.
Interactions such as logging in with correct or incorrect passwords fail silently.

This can be replicated in the welcome app by doing: 

```

if not request.env.web2py_runtime_gae:
    ## if NOT running on Google App Engine use SQLite or other DB
    db = DAL(myconf.take('db.uri'), pool_size=myconf.take('db.pool_size', cast=int), check_reserved=['all'])
    session.secure()
```

reproducible for me on sqlite or postgres, regardless of where sessions are stored (database or file)

**Comment by timrichardson** [comment]
This is not a bug but perhaps incomplete documentation since the book says this setting sends cookies only over https, and I am using a standard development environment: using rocket over http on localhost.
 
 Suggestion: that  session.secure()  be modified to treat a localhost database as a secure connection, because other aspects of web2py that are by default restricted to https on a remote server are available on localhost.

**Comment by niphlod** [comment]
it's not that web2py sends cookies only to https, but marks cookies as usable by the browser only if in a https page. It's a w3c standard, not a web2py problem.

The book can - only - say
"""
session.secure() marks cookies to be used with https pages only. Beware of enabling it while developing, which happens usually over http.
"""
