### ISSUE TITLE
Allow partial compilation of an app if some views fail to compile

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1075]
Currently, if a single view fails to compile, the compilation of the entire app fails. This means that if you want to use a condition {{extend}} in a single view, you cannot compile the app at all. Instead, we should allow the rest of the app to compile, with just the failed views remaining uncompiled.

I submitted a patch for this a long time ago (see https://groups.google.com/d/msg/web2py-developers/GhvqakUaujA/iTj0_uP76XcJ), but it was never applied. At this point, it may need to be tweaked, but since we now allow Python expressions in the {{extend}} statement, it makes sense to allow this.

**Comment by kszys** [comment]
I just run into the exactly same problem - I would like to see this working as well.

**Comment by mdipierro** [comment]
Your fix is in trunk!
