### ISSUE TITLE
IS_IN_DB validator introduced bug in master when formating lambda labels

### ISSUE THREAD

**Issue by mikcat** [web2py/web2py#1079]
In branch master pulled today
In gluon/validators.py
Line 583
It reads
self.labels = [self.label(r) for r in records.render]
But should be (I think)
self.labels = [self.label(r) for r in records]

Otherwise you get an "'instancemethod' object is not iterable" error when using this kind of format
format=lambda r: '%s (%s)' % (r.nom, r.granja.nom)

for models defined like
db.define_table("granja",
                Field('nom', 'string', length=1024, required=True, unique=True),
                Field('descripcio', 'text')
                , format='%(nom)s')

db.define_table("sitja",
                Field('nom', 'string', length=1024, required=True, unique=True),
                Field('granja', 'reference granja', required=True)
                , format=lambda r: '%s (%s)' % (r.nom, r.granja.nom))

db.define_table("corral",
                Field('nom', 'string', length=1024, required=True, unique=True),
                Field('sitja', 'reference sitja', required=True),
                Field('tipus', 'string', required=True)
                , format='%(nom)s')

\# This IS_IN_DB fails with error "'instancemethod' object is not iterable"
db.corral.sitja.requires=IS_IN_DB(db, db.sitja.id, db.sitja._format, zero=T('choose one'))

**Comment by niphlod** [comment]
uhm. this is the specific offending commit https://github.com/web2py/web2py/commit/65c87386c12513bbcf32674861ead171260c95ed . @mdipierro : do you recall why was it merged ?

**Comment by niphlod** [comment]
the blamed commit was reverted. see https://github.com/web2py/web2py/commit/65c87386c12513bbcf32674861ead171260c95ed#commitcomment-14371259 and https://github.com/web2py/web2py/issues/1097
