### ISSUE TITLE
Automatically adding the "btn-default" class to all buttons can cause styling conflicts

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1083]
[Here](https://github.com/web2py/web2py/blob/R-2.12.3/applications/welcome/static/js/web2py-bootstrap3.js#L9) in web2py-bootstrap3.js, the "btn-default" class is automatically added to all buttons:

     $('button', target).addClass('btn btn-default');

However, this causes conflicts with other styles, such as "btn-primary".

In general, we should probably avoid automatic changes to generic elements that are not namespaced with "web2py" or "w2p". So, we might also consider an alternative to adding the "btn" class to all buttons [here](https://github.com/web2py/web2py/blob/R-2.12.3/applications/welcome/static/js/web2py.js#L78) in web2py.js.

**Comment by niphlod** [comment]
Given that this is a specific fix for bs3 to avoid change lots of core code, some things needs to be considered. (we're STILL missing a nice way to override widgets on a per-app/per-framework basis).
What I'm astonished to see is users reporting that CSS doesn't work as supposed. IMHO (and just tried) btn-whatever (with whatever not being "default") overrides for all intents and purposes "btn-default" styling, just because "btn-default" is the 1st styling in bootstrap's stylesheet, with all the other following those statements.
In fact, a "btn btn-default btn-primary" is styled exactly as "btn btn-primary". 

Anyway, for the sake of "let's do it just where is needed" we can change 

$('button', target).addClass('btn btn-default')

to

$('button[class="^btn"]', target).addClass('btn btn-default')

and call it a fix ?

**Comment by abastardi** [comment]
In the current stable release, the welcome app uses bootstrap-theme.min.css, and in there, we have:

    .btn-default{text-shadow:0 1px 0 #fff;...}

The text-shadow attribute of the btn-default class is *not* overridden by the btn-primary class in this case, so we get blurry text in any btn-primary button.

In the current master, it appears this problem has been superficially fixed, as the bootstrap-theme.min.css file has been removed entirely from the app. However, the underlying issue still persists -- depending on the particular Bootstrap theme being used, there is no guarantee that btn-primary will always override all of the btn-default styles, so we should not count on that behavior.

**Comment by niphlod** [comment]
ok, uber-customization killed the cat.
All onboard with changing that line to 

$('button[class="^btn"]', target).addClass('btn btn-default')

to circumvent the issue ?

**Comment by abastardi** [comment]
>    $('button[class="^btn"]', target).addClass('btn btn-default')

That would still turn `"btn btn-primary"` into `"btn btn-primary btn-default"`.

**Comment by niphlod** [comment]
okay, maybe my selector fu is abandoning me. 
My idea was "add the class if the class doesn't start with btn"

**Comment by abastardi** [comment]
OK, I thought you meant `class^="btn"` (i.e., add it to elements that *do* start with "btn").

Anyway, I think we still have a problem. There is a line in web2py.js that adds the "btn" class to all buttons automatically, so if we change this line to ignore buttons that already start with "btn", then it will never add the "btn-default" class, so we might as well just delete the line in that case.

I think the long-term solution is just to avoid this automatic manipulation of classes in JS and instead (a) provide a way to ensure any web2py generated DOM (i.e., forms, grid, menu) can be customized with the appropriate classes for the CSS framework being used, and (b) expect the user to specify their own classes explicitly for any markup they manually create. Just because Bootstrap is being used, we shouldn't force every single button to have a "btn" class if that's not part of the original markup.

In the short term, maybe only add "btn-default" in case none of the alternatives are already there (i.e., btn-primary, btn-success, btn-info, btn-warning, btn-danger, btn-link).

**Comment by niphlod** [comment]
halt. 
that piece in web2py.js is not used anymore, it should be overridden by web2py-bootstrap3.js. Granted, the same fix we apply to web2py-boostrap3.js needs to be applied to web2py.js too. IMHO adding that not to every button but to every button that doesn't have a class starting with "btn" is a good workaround: granted, as you noticed it's just a workaround but I don't think we're going to see any change in how web2py generates the DOM in the near future (see different widgets, grid decoupling, html5 attributes, etc etc etc)

**Comment by abastardi** [comment]
Oops, right. So sure, I think your workaround will be sufficient for now.
