### ISSUE TITLE
Cookie parsing stopped after first invalid cookie

### ISSUE THREAD

**Issue by paultuckey** [web2py/web2py#1084]
If there is one invalid cookie in a request header then cookie processing is stopped.  This means if a user happens to have an invalid cookie in the header before the web2py `session_id_xxx` cookie, then an exception is thrown and the session cookie will be ignored and a new session issued.

In `main.py` (line 429) I have replaced this block:

    try:
        request.cookies.load(env.http_cookie)
    except Cookie.CookieError, e:
        pass  # invalid cookies

With this block:

    for single_cookie in env.http_cookie.split('; '):
        try:
            request.cookies.load(single_cookie)
        except Cookie.CookieError:
            pass  # single invalid cookie ignore

And it fixes the issue, only the invalid cookies are ignored.

**Comment by niphlod** [comment]
who is injecting cookies ? This fix seems to take the last valid cookie...rather than fixing the issue it seems to circumvent something that shouldn't happen, introducing a behaviour that is not that easy to debug.

**Comment by paultuckey** [comment]
Apologies for not explaining it very well.  Nobody is injecting cookies, some users just happen to have them on a parent domain because of other systems.

Other site: bad-system.example.com (sets invalid cookie2 for domain .example.com)
My site: api.example.com (receives invalid cookie2 because parent domain is the same)

Here is an example before patching:

```
env.http_cookie = "cookie1=abc; cookie2=x汉语y; session_id_main=2:sdfdsf67ads67csd;"
```

After web2py parses the cookies only `cookie1` is returned.  This is because an ignored exception was raised when `cookie2` was parsed, and parsing is stopped.

After the patch above `cookie1` and `session_id_main` are returned (`cookie2` is skipped as it is invalid).

Note, `cookies.load` parses the string and *adds* the cookie to the list.

**Comment by niphlod** [comment]
oh, perfect ,thanks for explaining. I guess the only thing that is missing is... is '; ' the correct separator ?
or it's better to use just ';' ?

**Comment by paultuckey** [comment]
It looks like it would be best to go with ';'.

https://tools.ietf.org/html/rfc6265#section-2.2
