### ISSUE TITLE
OFV latest install missing CSS and git integration doesn't work as well

### ISSUE THREAD

**Issue by h901039** [web2py/web2py#1085]
Just installed the latest OFV image and didn't do any special additions to the box. The entire page is just pure 404 for CSS and images, functionality still works but everything is in error.

Then following your instructions for git integration have failed. No matter what I try all I always get is "requires gitpython module". Installed that so many times pure your web instructions it's gotten old already. Everything shows its successfully installed but web2py just doesn't wish to work with it at all.

**Comment by niphlod** [comment]
OVF what ? From where ?

**Comment by niphlod** [comment]
closing for lack of replies. Feel free to reopen (with more details) if it's a real issue.
