### ISSUE TITLE
encode issue on globals.py - json 

### ISSUE THREAD

**Issue by sharkguto** [web2py/web2py#1089]
Hi guys,

I have create some threads on web2py groups without answer.

I found a bug on globals.py. When i send a application/json with encode iso-8859-1 i got no post_vars.... always came empty.

as following images, when I send a json without special chars it works, however when i send with "ç", bring me nothing.

![](https://lh3.googleusercontent.com/-r8GjAiTok5M/VimiJvEYNRI/AAAAAAAACW8/PTjxELAaWfM/s1600/2015_10_23_00_11_54_SoapUI_5.2.1.png)

![](https://lh3.googleusercontent.com/-rA7DHfSXQvE/Vimh6wzWrwI/AAAAAAAACWk/Xrs-cgv8Dc4/s1600/2015-10-23%2B00_14_44-Editing%2BAddUpdateAddress.png)

![](https://lh3.googleusercontent.com/-FxF8JOqBBes/Vimh7ddrGtI/AAAAAAAACWs/a_Vb4dKM3ZA/s1600/2015-10-23%2B00_05_56-SoapUI%2B5.2.1.png)

 

 

This is my fix:

post_vars = self._post_vars = Storage()
        body = self.body
        #import copy
        #body2 = copy.copy(self.body) #self.body
        # if content-type is application/json, we must read the body
        is_json = env.get('content_type', '')[:16] == 'application/json'
        #body2 = body.read()
        #body.seek(0)
        if is_json:
            try:
                json_vars = sj.load(body)
                #print json_vars
            except Exception, e:
                #print str(e)
                body.seek(0)
                body2 = body.read()

                try:
                    print chardet.detect(body2)['encoding']
                    body_encoded = body2.decode(chardet.detect(body2)['encoding']).encode('utf-8')
                    json_vars = sj.loads(body_encoded)
                except Exception, e:
                    print str(e)
                    json_vars = {}
                # incoherent request bodies can still be parsed "ad-hoc"
                #json_vars = {"oloko":str(e)}
                pass
            # update vars and get_vars with what was posted as json
            if isinstance(json_vars, dict):
                post_vars.update(json_vars)

![image](https://cloud.githubusercontent.com/assets/3118165/10708014/a9f5f616-79d9-11e5-8bd8-79f19caf8e13.png)

I do not know if this solution is the better, but solve my problem.
Sorry about my english, i am not native.

U guys can take a look on this issue for the next release?

Grateful for attention

Gustavo M Freitas

**Comment by niphlod** [comment]
closed for lack of detailed replies in web2py-users. Feel free to open a new thread if the bug still stands, this time with a minimal app and a minimal client to replicate the issue

**Comment by sharkguto** [comment]
niphlod,
Thanks for answered the bug.

related with you comment:

"closed for lack of detailed replies in web2py-users. Feel free to open a new thread if the bug still stands, this time with a minimal app and a minimal client to replicate the issue"

the problem is on globals.py. when I sent any special char on json, using SOAPUI on windows, the encode sent to web2py is not utf-8, so I need to convert from win-12xx to utf-8 under globals.py file.

This fix, solved my problem, i think it was nice to share with the community and see it, on the next web2py version.

however,...

thanks buddy for reply
