### ISSUE TITLE
Exceptions in validators are masked in gluon.html

### ISSUE THREAD

**Issue by jobbogamer** [web2py/web2py#1105]
Came across an issue recently where I was passing the wrong arguments to `IS_IN_DB()` and it was throwing an exception. The problem is, in [gluon/html.py](https://github.com/web2py/web2py/blob/master/gluon/html.py#L1860), any exceptions from validators are being caught, and then a new exception, containing no details of the actual problem, is being raised.

Not only is this detrimental to bug-hunting – it took me a long time to realise that I was passing the wrong arguments to the validator – but it's also not clear to someone using validators for the first time that this isn't just "what happens" when a validator rejects input. My first thought was simply that the exception should be caught, and then manual form error processing should be done.

In my opinion, exceptions raised lower down in the framework should not be masked higher up, unless the new exception contains the original information plus _more details_.

**Comment by jobbogamer** [comment]
Just knowing where the exception is from isn't always enough to work out what the problem is. Being told "there's an error here" isn't nearly as informative and conducive to actually fixing issues as "you passed this object in, but this function expects this type of object".

And to your other point, from a user's perspective **any** stack trace is cryptic and confusing, so what difference does it make that it contains different text that's actually helpful to the developer?

**Comment by niphlod** [comment]
and in fact the stack trace is masked to the user. it just points to THE validator on THAT field.

**Comment by jobbogamer** [comment]
Viewing the stack trace requires you to log in to the admin interface, so the user can't actually see the stack trace. So modifying the exception is just a detriment to the developer, and isn't affecting the user at all.

Why not include the original exception's message in the exception thrown in http.py? Then it's the best of both worlds, showing the field and validator where the error occurred, and what the actual error was.

**Comment by jobbogamer** [comment]
"Error in validator: field:some_field <validators.IS_NOT_IN_DB object at 0x1125e4990>, error was: ''Rows' object is not callable'"

**Comment by niphlod** [comment]
hold on. 
Are you saying html.py should NOT intercept the exception and raise an exception, so the user gets back a ticket ?

**Comment by jobbogamer** [comment]
It should either:

- Not intercept the exception, and let the original exception propagate upwards, or
- Intercept the exception and throw its own exception, but include the message from the original exception

**Comment by niphlod** [comment]
IMHO

- not intercept the exception --> user gets a ticket back, really not user friendly
- intercept and thrown its own --> not useful to the user, just for the developer

PS: you're making a case for IS_IN_DB() but changing the global behaviour means changing it for EVERY validator

**Comment by jobbogamer** [comment]
It's already throwing its own exception though:

```python
for k, validator in enumerate(requires):
    try:
        (value, errors) = validator(value)
    except:
        msg = "Validation error, field:%s %s" % (name,validator)
        raise Exception(msg)
```

(lines 1885 to 1860 of html.py)

**Comment by niphlod** [comment]
yep, that is more user-friendly than a ticket (that is "protected" by the admin app) or than exposing the complete stack trace potentially revealing your code to any casual user hitting the page.

**Comment by jobbogamer** [comment]
I'm not entirely sure what you mean. From my usage, the new exception is still creating a ticket?
