### ISSUE TITLE
Sqlform grid record count says 'Query unsupported' when using groupby on MSSQL

### ISSUE THREAD

**Issue by timnyborg** [web2py/web2py#1112]
def fetch_count() tries to count a subquery, resulting in the SQL error:
No column name was specified for column 1 of '_tmp'

**Comment by niphlod** [comment]
what adapter are you using ?

**Comment by timnyborg** [comment]
mssql3n or mssql4n

About to post a fix, which is a simple change

**Comment by niphlod** [comment]
for t-sql adhering there shouldn't be problems
