### ISSUE TITLE
expected routes.py location changes when using -f (specify apps directory) option

### ISSUE THREAD

**Issue by houdinihound** [web2py/web2py#1117]
`routes.py` is generally expected to be in the web2py root directory.  

However, if the -f startup option is used to specify a different location for the `applications` directory, then web2py loads the root file, but afterwards looks for the `routes.py` file in that new location instead of the usual root location.  When it does not find the file in the new location, it falls back to out-of-the-box routing defaults (e.g. goes to welcome app) and  ignores the settings in the `routes.py` file that exists in the web2py root directory.

Another observation is that web2py places the `httpserver.pid` and `parameters_NNNN.py` files in this new directory, whereas those files (should?) normally be in the web2py root directory as well.

Observe the 2 rewrite messages below on server startup and which `routes.py` it is using (1st one is root path, 2nd is applications path as passed with -f option):
```
2015-12-04 10:42:51,732 - DEBUG - [rewrite.py, line116, pid5394, MainThread] - URL rewrite is on. configuration in /home/jose/python-environments/crm/lib/web2py/routes.py
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2015
Version 2.12.3-stable+timestamp.2015.08.19.00.18.03
Database drivers available: sqlite3, psycopg2, pg8000, pymysql, imaplib
please visit:
	http://192.168.1.21:8020/
use "kill -SIGTERM 5394" to shutdown the web2py server

2015-12-04 10:42:51,773 - DEBUG - [rewrite.py, line116, pid5394, MainThread] - URL rewrite is on. configuration in /home/jose/projects/crm/routes.py
```

**Workaround**
Copy the web2py root directory `routes.py` file to the new `applications` directory.  Or create a symlink in the new directory to the file in the root directory.

**Comment by niphlod** [comment]
to put it frankly, nobody ever documented properly what -f does. IMHO the fact that it disregards the one in web2py's root is a feature, not a bug. 
It just so happens that I'm reviewing the -f option for other similar issues and opened a thread on https://groups.google.com/d/msg/web2py-developers/uJoQeUlCABw/-MCXocwGAgAJ . Nobody replied so far, so I'm just going to patch everything in a few days following the lead of my brain.

**Comment by houdinihound** [comment]
Thanks for the quick reply.  Right, I can see how it could be a feature...  I guess the main thing then is when you finalize how it is expected to work then please update the documentation (in multiple places where the -f option is referred to as well as where the routes.py and app routes.py is discussed) so it reflects this benefit/feature/side-effect/unintended consequence/absolute horror depending on your viewpoint ;)

**Comment by mdipierro** [comment]
I agree. Feature, not bug. The point was to separate code (web2py) and user provided apps (including routes).
