### ISSUE TITLE
Softcron failing systematically...

### ISSUE THREAD

**Issue by kszys** [web2py/web2py#1119]
I have been trying to enable `softcron` recently, and got an error every time the cron should run for any application:

    2015-12-06 12:50:36,644 - web2py.cron - WARNING - WEB2PY CRON Call returned code 1:
    invalid placeholder/--set value

Does not seem to be a problem with the application, though, as the `extcron` works fine.

I am using stable version of web2py (2.12.3) on FreeBSD 10.1 with uwsgi. I enabled the `softcron` in `wsgihangler.py`. I tried debugging a bit, but it does not seem to be related to the things that were in the action that was supposed to run. Simply nothing happened except the error above in the web2py log.

At the same time - as mentioned above - the same cron for the same applications works fine, if `extcron` is used.

**Comment by mdipierro** [comment]
Please do not use softcron. Use the scheduler instead. We are deprecating the built-in cron because the unpredictable memory usage.

**Comment by kszys** [comment]
Right. The problem I have with the scheduler is that it seems to be task-driven. You can set the task, and it will be executed when a worker is available. I use it for some things, like sending e-mails, etc. However, I have no clear idea how to replicate the behavior of cron with the scheduler, i.e., how to ensure that an action will be run at certain time and with certain frequency (e.g., I am running some check every 5 min) 

Maybe this is possible, but I have not found a description of such scenario in the book, and I could not come up with a way to achieve it with the scheduler. I think that if a clear example how to replace a typical cron job with a scheduler was available, it would make it much easier to adopt the scheduler.

**Comment by niphlod** [comment]
tasks can be set to repeat themselves.

chapter 03 of the book explains it all

a task that is scheduled to be repeated every 5 minutes "a-la-cron" can be queued with

repeats=0, period=300, prevent_drift=True

If you need to dip your toes further, look at https://github.com/niphlod/w2p_scheduler_tests

**Comment by kszys** [comment]
Thanks! I will take a look!

**Comment by kszys** [comment]
I do not want to complain, but:

I re-read the chapter about the scheduler, but I still do not know how to make sure a recurrent task is scheduled **once** the web2py is restarted and then continues with specific frequency. Do I have to queue it manually through appadmin? Do I have to do it again after every reboot/restart of the application? Far from being clear... I still believe a simple end-to-end example of replacing typical cron jobs (@reboot?, how to schedule the recurrent task at application restart, etc.) with the scheduler would greatly help.

Until then, I think, I will stick with cron for the moment...

**Comment by niphlod** [comment]
you leave the task queued, with repeats=0, timeout=300, prevent_drift=True. 
Given the scheduler is an external process, completely separated from the "http" environment, you choose when to start or restart the scheduler process at will.

**Comment by mdipierro** [comment]
I am closing this because we do not wish to support softcron any longer.
