### ISSUE TITLE
Wiki: "extra" parameter does not work if resolve=False 

### ISSUE THREAD

**Issue by mweissen** [web2py/web2py#1121]
About the built-in wiki:

If there is the line

      auth.wiki(resolve=False)

in db.py, it is not possible to use the extra-Parameter in `auth.wiki(extra=...)` - it  does not work.

I think in gluon/tools.py (def wiki(..)) one line is missing.
` self._wiki.settings.extra=extra or {}`
 I have added it:

        if not hasattr(self, '_wiki'):
            self._wiki = Wiki(self, render=render,
                              manage_permissions=manage_permissions,
                              force_prefix=force_prefix,
                              restrict_search=restrict_search,
                              env=env, extra=extra or {},
                              menu_groups=menu_groups,
                              templates=templates,
                              migrate=migrate,
                              controller=controller,
                              function=function,
                              groups=groups)
        else:
            
            self._wiki.env.update(env or {})
            self._wiki.settings.extra=extra or {}

I have tried it and it works as expected. Maybe there are side effects?

**Comment by mdipierro** [comment]
this was fixed.
