### ISSUE TITLE
compute field not working when default value is set

### ISSUE THREAD

**Issue by alex0834** [web2py/web2py#1128]
db.define_table('trip',
    Field('driving_time_before', 'integer', notnull=True, default=0),
    Field('driving_time_after', 'integer', notnull=True, default=0),
    Field('driving_time', 'integer', compute=lambda r: r['driving_time_before']+r['driving_time_after'], notnull=True, default=0))

db.trip.insert(driving_time_after=10, driving_time_before=10)

does not compute the driving_time. This worked fine with web2py 2.9. but after upgrading to 2.12.3 it fails. The problem is in dal/pydal/objects.py line 708:
fields = self._defaults(fields)

because driving_time does have a default value, self._defaults returns the field and thus it does not get computed further on.

the default value for driving_time does not really make sense here (I added it out of habit) but it definitely should not stop it from getting computed.

Alex

**Comment by cassiobotaro** [comment]
Fixed in https://github.com/web2py/pydal/commit/dcfb5f58aa1ff1c87b349c31e67f14a4d9774ebe

**Comment by cassiobotaro** [comment]
@alex0834 @mdipierro Can we close this issue?

**Comment by mdipierro** [comment]
Yes
