### ISSUE TITLE
select(distinct=...) may produce faulty sql for sqlite

### ISSUE THREAD

**Issue by pembeci** [web2py/web2py#1129]
This one works:
```python
In [45]: db().select(db.player.country, distinct = True)
Out[45]: <Rows (40)>

In [46]: db._lastsql
Out[46]: 'SELECT DISTINCT player.country FROM player;'
```
But the other option given [in the book](http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#orderby--groupby--limitby--distinct--having-orderby_on_limitby-left-cache) does not:
```python
In [47]: db().select(db.player.country, distinct = db.player.country)
OperationalError: near "ON": syntax error

In [48]: db._lastsql
Out[48]: 'SELECT DISTINCT ON (player.country) player.country FROM player;'

```

I didn't test it with other DB engines since I don't currently have one installed.

**Comment by cassiobotaro** [comment]
@gi0baro I think it's pydal related.

**Comment by gi0baro** [comment]
@cassiobotaro yep seems to me too. Can you open up an issue on pyDAL?
