### ISSUE TITLE
XML allowed_attributes is not respected

### ISSUE THREAD

**Issue by amerikan** [web2py/web2py#1130]
2.10.3-stable+timestamp.2015.04.02.21.42.07
(Running on Rocket 1.2.6, Python 2.7.10) 

Simple script to reproduce:
```python
print XML('It\'s time to do the demo<script>alert("xss");</script> <a href="http://localhost:8000/page?id=7" class="at-mention">link</a>',
                               sanitize=True,
                               permitted_tags=['a'],
                               allowed_attributes={'a': ['href', 'class']})
```

**Expected:**
`It's time to do the demo&lt;script&gt;alert(&quot;xss&quot;);&lt;/script&gt; <a class="at-mention" href="http://localhost:8000/page?id=7">link</a>`

**Actual:**
`It's time to do the demo&lt;script&gt;alert(&quot;xss&quot;);&lt;/script&gt; <a class="at-mention">link</a>`

As you can see the `href` attribute gets removed even though I added it to the allowed_attributes dictionary, it does however, retain the `class` attribute. Is this a bug or expected behavior? Thanks!

**Comment by amerikan** [comment]
I tested it on v2.12.3 and it seems to be fixed.

**Comment by amerikan** [comment]
I just tested it on `2.13.4-stable+timestamp.2015.12.26.04.59.39` and it's again stripping out the `href` attribute. Any ideas?

**Comment by amerikan** [comment]
```python
print XML('It\'s time to do the demo <a href="http://localhost:8000/page?id=7" class="at-mention">link 1</a> <a href="http://localhost:8000/page?id=7" class="at-mention">link 2</a>',
                      sanitize=True,
                      permitted_tags=['a'],
                      allowed_attributes={'a': ['href', 'class']})
```

Is showing as:
```
It's time to do the demo <a class="at-mention">link 1</a> <a class="at-mention">link 2</a>
```

Why is the `href` getting stripped out? Should it be?

**Comment by mdipierro** [comment]
This is correct. It is for security. Look at the function url_is_acceptable in gluon/sanitizer.py The link but be a valid link to the same app. Perhaps we should relax this feature? Let's discuss on web2py-developers.

**Comment by amerikan** [comment]
@mdipierro oh ok. Is it documented book? I read this section http://web2py.com/books/default/chapter/29/05/the-views#XML but didn't see anywhere saying link should be to same app. If we can add that, it would be less puzzling.

**Comment by mdipierro** [comment]
localhost is invalid form outside the host itself. This will work: http://127.0.0.1:8000/page?id=7 True
