### ISSUE TITLE
Manual upload fails when db.table.field.store returns unicode

### ISSUE THREAD

**Issue by pembeci** [web2py/web2py#1131]
When I tried manual upload [as described in the book](http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#More-on-uploads), there was an error although the file was copied to the application `uploads` folder. I noticed that for some reason `db.table.field.store` was returning a `unicode` string on my system instead of `str` as the new filename. So I believe [this part of the codebase](https://github.com/web2py/pydal/blob/3131f834ef0e4176a54944516269da3683243713/pydal/objects.py#L689-L693 ) will be corrected like:

```python
    def _attempt_upload(self, fields):
        for field in self:
            if field.type == 'upload' and field.name in fields:
                value = fields[field.name]
                # if not (value is None or isinstance(value, str)):
                if not (value is None or isinstance(value, str) or isinstance(value, unicode)):
```

**Comment by cassiobotaro** [comment]
@pembeci It's related to pydal, can you move your ticket to [pydal issues](https://github.com/web2py/pydal)? 

@gi0baro I think the correction is:
```diff
def _attempt_upload(self, fields):
        for field in self:
            if field.type == 'upload' and field.name in fields:
                value = fields[field.name]
-                if not (value is None or isinstance(value, str)):
+                if not (value is None or isinstance(value, basestring):
```
Can you guide to apply this PR with tests?

**Comment by pembeci** [comment]
@cassiobotaro I did that (web2py/pydal#319). I wasn't aware that there was a seperate repo for pydal. Shall I close this one now or wait for the commit?
