### ISSUE TITLE
Unexpected behavior using less than (<) in XML

### ISSUE THREAD

**Issue by amerikan** [web2py/web2py#1133]
Here's a simple test case:
```
{{=XML("You see me <hiyou", sanitize=True)}}
```
The above results in `You see me `and not `You see me <hiyou` as expected.

Tested on `2.10.3-stable+timestamp.2015.04.02.21.42.07` and on `2.12.3-stable+timestamp.2015.08.19.00.18.03`

**Comment by cassiobotaro** [comment]
When sanitize is True, xml  is not a simple text escape, it will validate allowed tags inside your text, permitted attributes and  remove open tags(like '<hiyou').

Look some examples:
```python
>>> print(XML(' You see me <b> <test', sanitize=True))
You see me <b> </b>
>>> print(XML('You see me <a>Test</a>', sanitize=True))
You see me Tetse
>>> print(XML('You see me <a href="#">Test</a>', sanitize=True))
You see me <a href="#">Test</a>
```
Remember that you can define permitted tags and attributes.

Maybe what you want is `xmlescape`.  [xmlescape docs](http://web2py.com/books/default/chapter/29/05/the-views#xmlescape)

**Comment by amerikan** [comment]
Some more examples:

```
{{=XML('<b> <junk in the trunk', sanitize=True)}}
{{=XML('<b> <junk in the trunk </b>', sanitize=True)}}
{{=XML('You see me <a>Test</a>', sanitize=True)}}
{{=XML('You see me <a href="#">Test</a>', sanitize=True)}}
{{=XML('text before <3', sanitize=True)}}
{{=XML('text before <z', sanitize=True)}}
{{=XML('<1 text after', sanitize=True)}}
{{=XML('<z text after', sanitize=True)}}
```

Output:
```
<b> </b>
<b> &lt;junk&gt;</b>
You see me Test
You see me Test
text before &lt;3
text before
&lt;1 text after
#nothing outputted
```

To me it seems any time there's a less-than (<) followed by an alpha character then it automatically considers it a tag even if it is not followed by greater-than (>).

For example the way it is, it considers `<a`, `<blah`, etc. as tags. I think it should only consider them as tags if they are followed by a `>`.

**Comment by cassiobotaro** [comment]
If you allow open tags you can open a security flaw. Sanitize is to avoid [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting). 
To escape text use [xmlescape](http://web2py.com/books/default/chapter/29/05/the-views#xmlescape)

**Comment by mdipierro** [comment]
Cassio is right. Behavior is correct.
