### ISSUE TITLE
Web2py and Couchbase

### ISSUE THREAD

**Issue by waiandtgabriel** [web2py/web2py#1134]
Hi,

I want to expose an couchbase bucket where I save some XML files generated in my web2py controller. I know I could maybe use MongoDB but I had a requirement for using Couchbase.

Is there an official connector for Couchbase? I couldn't find it in the DAL documentation. 

I am trying this working around:
````
from couchbase import Couchbase
cb = Couchbase.connect(bucket='mybucket', host='localhost', port=8091)
#this works but we got a message saying it is depreciated
# DeprecationWarning: Couchbase.connect() is deprecated. Use Bucket() instead
````
But I got a message saying it is depreciated and I should use this instead:
````
cb = Bucket(bucket='mybucket', host='localhost', port=8091)
````
But then I got an error:
````
<type 'exceptions.NameError'> name 'Bucket' is not defined
````

Any other suggestion , workarounds on Web2Py connecting to couchbase, specially for being exposed by an API? Thanks!

**Comment by cassiobotaro** [comment]
Unfornatelly DAL don't have support to couchbase yet , but feel free if you want to develop and submit a PR at [pydal](https://github.com/web2py/pydal).
Anyway, you have to import bucket like this `from couchbase.bucket import Bucket`.
And then you can do `cb = Bucket('couchbase://localhost/default')`.

**Comment by niphlod** [comment]
feel free to open an issue over at [pydal](https://github.com/web2py/pydal)

**Comment by waiandtgabriel** [comment]
May I reopen that? I am moving forward with my API exposure and I am not using DAL, I am using Python Bucket connection with Couchbase but I have the following issue that is related with Web2Py API exposure:

I have a main function generating random XML files and they stored properly into couchbase, the as expected, but when exposing what I get in this couchbase I got the the XML without the tags. Below you have the details.

````
@request.restful()
def api():
    def GET():
        key = main() #generate random XML and returns the key
        value = cb.get(key).value #get value stored into couchbase
        sys.stderr.write(value) #print on the console for testing 
        # This is printing the right XML file in the console with namespaces etc
        return value if value else None
    return dict(GET=GET)
````

Then when I access my API url I got the right information without the XML tags.

What is stored (E.G.):
"<messageTISS><cabecalho><identificacaoTransacao><date>2016-01-02<..."

What I got when accessing the API function through the browser:
2016-01-021820263.02.0170000...

Thank you!

**Comment by niphlod** [comment]
forget couchbase and try with fixed values: what's the output ?

**Comment by waiandtgabriel** [comment]
Thanks. I guess is just that the browser is thinking its html code. I will adjust that in the front-end system that will connect to this API, but I guess I have what I want in the web2py side.
