### ISSUE TITLE
ldap_auth.py: syntax error with 2.13.2-stable+timestamp.2015.12.18.11.00.46

### ISSUE THREAD

**Issue by pgastinger** [web2py/web2py#1138]
Hi, 

very easy to reproduce (Python 2.6.6 on RHEL6):
```python
myserver:/tmp/web2py/gluon/contrib/login_methods>python ldap_auth.py
  File "ldap_auth.py", line 435
    update_or_insert_values = {f: update_or_insert_values[f] for f in fields}
                                                               ^
SyntaxError: invalid syntax
```

I changed the corresponding line to:
```python
update_or_insert_values = {f: [update_or_insert_values[f] for f in fields]}
```

I seems to work for now, but I am not sure if this breaks anything else. It definitely needs further testing.

I am somewhat surprised that a syntax error can make it into a released version.

**Comment by BuhtigithuB** [comment]
What you write doesn't make sens... You kind of embed and list comprehension inside or partially inside of dict comprehension... It shouldn't lead to the same thing... f, is not even known out side the braket of you embed list comprehension...

**Comment by BuhtigithuB** [comment]
There is surely somethings in how you use ldap_auth that lead to this issue... Which LDAP implementation do you use? AD, OpenLDAP, etc.

Can you show your "auth.settings.login_methods" ldap definition/initialization...

**Comment by pgastinger** [comment]
It seems to be a problem with python 2.6. I download the latest web2py-zip, unzipped it and tried following with my python 2.6.9 (on Linux mint):
```python
peda@peda-desktop /tmp/Python-2.6.9 $ ./python ../web2py/gluon/contrib/login_methods/ldap_auth.py 
  File "../web2py/gluon/contrib/login_methods/ldap_auth.py", line 435
    update_or_insert_values = {f: update_or_insert_values[f] for f in fields}
                                                               ^
SyntaxError: invalid syntax
```
If I try to do that with python 2.7.6:
```python
peda@peda-desktop /tmp $ python web2py/gluon/contrib/login_methods/ldap_auth.py 
```

It seems to be an issue with Python 2.6.x.

**Comment by BuhtigithuB** [comment]
Rigth : http://stackoverflow.com/questions/7276511/are-there-dictionary-comprehensions-in-python-problem-with-function-returning

New in python 2.7... Can you upgrade?

If not try this : 

update_or_insert_values = dict(((f, update_or_insert_values[f]) for f in fields))

Ref: http://stackoverflow.com/questions/1747817/create-a-dictionary-with-list-comprehension-in-python

**Comment by pgastinger** [comment]
Thanks for the fast response. Unfortunately, I can't upgrade. RHEL/CentOS 6 (and even 5) is still widely deployed and the default python version is 2.6.x. (Although there are packages for 2.7, but an upgrade is not feasible). 

Python 2.6 is still supported by web2py, is it possible to revert to a previous version which worked with 2.6 or replace the line in the repository and release a new version? (Or otherwise you would have to drop support for 2.6). Thank you.
