### ISSUE TITLE
Post-validation string field form.vars are being overwritten

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1140]
Commit https://github.com/web2py/web2py/commit/2a245d36f4e4d43d7b2251d73811497239b21a51 introduced a bug. Prior to this commit, it was possible to change the values in form.vars within the onvalidation callback. However, for string/text fields, this commit reverts to the values from the original request.post_vars (in order to preserve unicode text), overwriting any changes made during onvalidation.

We will need an alternative fix for the unicode problem that does not interfere with changes made to form.vars.

**Comment by abastardi** [comment]
If we don't have a quick fix for the unicode issue, we should probably at least revert that commit, as this breaks backward compatibility.

**Comment by mdipierro** [comment]
OK. for now it was reverted.

**Comment by mdipierro** [comment]
I do not want to fix sqlform bugs any more. We will deprecate it.
