### ISSUE TITLE
Web2py stable version

### ISSUE THREAD

**Issue by cassiobotaro** [web2py/web2py#1148]
The last stable version is 2.13.4, but [VERSION](https://github.com/web2py/web2py/blob/R-2.13.4/VERSION) file is already 2.13.3.

**Comment by niphlod** [comment]
@mdipierro: I can issue a PR but it'd be better if you check your makefile et similia

**Comment by niphlod** [comment]
@mdipierro : ping! VERSION still reports 

     Version 2.13.3-stable+timestamp.2015.12.24.08.08.22 ATM

**Comment by mdipierro** [comment]
yes. this is a bug. will be fixed in next version not in current version.
