### ISSUE TITLE
jwt implementation doesn't calculate utc epoch correctly

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#1156]
a mistypo.

now = time.mktime(datetime.datetime.utcnow().timetuple())

should be

a. now = time.mktime(datetime.datetime.now().timetuple())
OR
b. calendar.timegm(datetime.datetime.utcnow().timetuple())

calendar though would be a new import to put in tools.py . Does anyone have a reccomendation for one or the other form ?

**Comment by niphlod** [comment]
refresh tokens doesn't work either (once #1149 gets merged). will tackle in a PR as soon as 1149 is merged

**Comment by sPyOpenSource** [comment]
web2py version R-2.15.1-4 still have this problem.
