### ISSUE TITLE
Problems with the validator IS_DATE() and appadmin.

### ISSUE THREAD

**Issue by Marcelo-Theodoro** [web2py/web2py#1159]
I'm running web2py 2.12.3 and I think I found a bug(or maybe I'm just doing something really wrong)

The error happens when I use the validator IS_DATE(format='%d/%m/%Y') in a table definition. Ex:

    db.define_table('people',
                    Field('people_date', requires=IS_DATE(format='%d/%m/%Y')))

Now I insert a new record to the table 'people' through the appadmin(like 10/10/2010). After that when try to go to the page *appadmin/select/db?query=db.people.id>0*, the error happens. 

About the error:

>Traceback (most recent call last):
  File "/home/marcelotheodoro/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/marcelotheodoro/web2py/applications/teste/views/appadmin.html", line 175, in <module>
    {{if ram['bytes'] > 524287:}}
  File "/home/marcelotheodoro/web2py/gluon/sqlhtml.py", line 3283, in \_\_init\_\_
    r = str(field.formatter(r))
  File "/home/marcelotheodoro/web2py/gluon/packages/dal/pydal/objects.py", line 1615, in formatter
    value = item.formatter(value)
  File "/home/marcelotheodoro/web2py/gluon/validators.py", line 2200, in formatter
    year = value.year
AttributeError: 'str' object has no attribute 'year'

> Function argument list
(self=<gluon.validators.IS_DATE object>, value='2000-12-11')

**Comment by cassiobotaro** [comment]
IS_DATE validator expect a date as argument when formatter is called. At the example people_date is a string.
```python
db.define_table('people',
                Field('people_date', 'date', requires=IS_DATE(format='%d/%m/%Y')))
```
It's a solution, but we still with a problem when people_date is a string.

**Comment by niphlod** [comment]
IMHO not. a Field which gets applied an IS_DATE validator NEEDS to be a 'date' field.
