### ISSUE TITLE
Admin flash/alert message not working under 2.13.4

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1165]
flash become w2p_flash, but it still flash in admin/views/layout.html

**Comment by uhelp** [comment]
After upgrading to 2.13.4 the flash in admin app is unclickable and hence always on top.

**Comment by uhelp** [comment]
forgot to say, that when i hoover over the flashmsg then there is no text and no  link. But if i try to save an edited file the text "properly saved..." is displayed and it links to https://www.example.com/admin/default/edit/testing/models/menu.py?id=models__menu__py#

**Comment by BuhtigithuB** [comment]
Solve here : https://github.com/web2py/web2py/pull/1164
