### ISSUE TITLE
Double-inheritance fail

### ISSUE THREAD

**Issue by RekGRpth** [web2py/web2py#1173]
These double-inheritance models
```python
db.define_table('a',
    Field('a_name', notnull=True, length=128),
)
db.define_table('b',
    Field('a', type='reference a', ondelete='NO ACTION', notnull=True, unique=True),
    Field('b_name', notnull=True, length=128),
    primarykey=['a'],
)
db.define_table('c',
    Field('b', type='reference b', ondelete='NO ACTION', notnull=True, unique=True),
    Field('c_name', notnull=True, length=128),
    primarykey=['b'],
)
```
cause exceptions.KeyError 'foreign_key'

**Comment by RekGRpth** [comment]
For example, I have 4 classes: Abonent, Person, Company and Provider.
Person and Company are (sublasses of) Abonents, and Provider is (subclasses of) Company.
In django I can write
```python
class Abonent(models.Model): pass
class Person(Abonent): pass
class Company(Abonent): pass
class Provider(Company):pass
```
and in wep2py I want write
```python
db.define_table('abonent')
db.define_table('person', Field('abonent', db.abonent), primarykey=['abonent'])
db.define_table('company', Field('abonent', db.abonent), primarykey=['abonent'])
db.define_table('provider', Field('company', db.company), primarykey=['company'])
```
but it fails

**Comment by niphlod** [comment]
first and foremost, pydal has [its own repo and its own issues](https://github.com/web2py/pydal/issues), so I'd incourage to post there any bug.

Second, if you read the [book](http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#markmin_LegacyDatabases) you'd notice several gotchas, but one should pop up

"""
Referencing fields must use the reference tablename.fieldname format.
"""
Closing this. Feel free to reopen on pydal's repo if even after reading the book you have issues.
