### ISSUE TITLE
LDAP / AD Login method updating Auth table issue.

### ISSUE THREAD

**Issue by preactive** [web2py/web2py#1178]
Currently with LDAP / AD when I have user sign in it create two rows in the auth table records.
Users would have to sign in initally and log out and log back in for the application to have group records  and such attached to the appropriate auth record.

Previously worked @ ver. 2.12.3

please see the following for additional details: https://groups.google.com/forum/#!topic/web2py/o2BY16DPVZM 

What I did to resolve was:

ldap_auth.py ~line 425 added " 'username': username " to the "update_or_insert_values" dictionary 

update_or_insert_values = {'first_name': store_user_firstname,
                                           'last_name': store_user_lastname,
                                           'email': store_user_mail,
                                           'username': username}

ldap_auth.py ~line 429 added " ,'username' " to the fields array

fields = ['first_name', 'last_name', 'email','username']

After that only 1 row is created.   And a new single sign in works without the need to log out and back in.

I am not a programming method wizard.  I don't know how this fix affects the other methods besides 'ad' in the LDAP module as what I changed is in the scope of the 'if manage_user:' block ~line 402

Additional info:

How I call LDAP / AD:

#http://www.computerperformance.co.uk/Logon/LDAP_attributes_active_directory.htm
#http://www.web2pyslices.com/slice/show/1468/how-to-set-up-web2py-ldap-with-windows-active-directory
#http://www.web2pyslices.com/slice/show/1715/authentication-and-group-control-with-active-directory-ldap
#ldap authentication and not save password on web2py

from gluon.contrib.login_methods.ldap_auth import ldap_auth
auth.settings.login_methods = [ldap_auth(mode='ad',
   manage_groups= True,
   db = db,
   manage_user = True,
   user_firstname_attrib = 'cn:1',
   user_lastname_attrib = 'sn',
   group_member_attrib = 'member',
   group_filterstr = 'objectClass=Group',
   server='corp.something.com',
   base_dn='DC=corp,DC=something,DC=com')]

**Comment by BuhtigithuB** [comment]
Please come to the mailing-list... It's not clear what the problem is if
any and what the expect behavior...

Let talk then we update the status of this ticket instead of using the
github ticket thread as a forum.

Thanks

Richard

**Comment by preactive** [comment]
Hello Richard,

Not to be rude but the problem is stated in the my first sentence above.  Two entries(rows) are being created every time a new user logs in on the db.auth_user table.

I was directed here by Massimo Di Pierro in the link _FROM_ the web forum which I provided in the initial comment.

What I did not provide above is the specific path and file which the proposed fix it to take place:
[web2py/gluon/contrib/login_methods/ldap_auth.py](https://github.com/web2py/web2py/blob/master/gluon/contrib/login_methods/ldap_auth.py)

There seems to have been an overhaul of the LDAP Login method from the version I listed above in which it previously _worked_ in the ways advertised in the slices I listed. 

Please re-read the initial comment.  Thank-you

**Comment by BuhtigithuB** [comment]
How do you login? Username or email (as username)? There is a none issue
about the duplication issue when you log with email... To workaround that
you need to prevent user from login with email if you use username (first
part of the email username@domain...). There is no easy way to fix that
issue without hacking in web2py auth class and in ldap_auth at the same
time tooo validate user input... This issue is known to  occur when you
configure web2py to use  username as login.

Richard

**Comment by preactive** [comment]
We login via username.  There is no @domain.com when we login.

And what is wrong with modifying the two lines I showed in ldap_auth.py.  

All that my suggestion is doing is writing the additional field of 'username' with variable 'username' on the updates or inserts that happens on between lines 422 - 442

As I noted above this was working previously with no hacks.

**Comment by BuhtigithuB** [comment]
Related commit that may be the cause of the issue : https://github.com/BuhtigithuB/web2py/commit/0036d9c45bdf476d858fa00dd69e854c4623858b

**Comment by preactive** [comment]
I commented the line in the removed line block which I believe is missing after the dry method was applied.
