### ISSUE TITLE
Bug: auth.login() clears response.post_vars

### ISSUE THREAD

**Issue by codylandry** [web2py/web2py#1180]
When using auth.login() in its own action, response.post_vars becomes an empty storage object after the call, so when submitting the login form, the post_vars are not available below the call. 

`def login():`
    `print response.post_vars #prints them fine when submitting the form`
    `form = auth.login()`
    `print response.post_vars # prints Storage({})`

**Comment by leonelcamara** [comment]
Err either the login form was called without being submitted, so you're at first just displaying it, in which case the request.post_vars is an empty storage. Or, you have submitted the login form, then you're redirected in which case that line isn't executed at all. Either way it should be request.post_vars not response. I suggest this issue be closed.
