### ISSUE TITLE
'Compile application' doesn't compile modules

### ISSUE THREAD

**Issue by pfctdayelise** [web2py/web2py#1184]
Is there a reason or they just haven't been added to  `compile_application` yet?

Thanks.

**Comment by BuhtigithuB** [comment]
@mdipierro or @niphlod : This one requires an answer...

**Comment by mdipierro** [comment]
This would require a major refactoring. Perhaps in web3py.

**Comment by leonelcamara** [comment]
Do they even need to be compiled by compile application? They will be compiled by Python itself and it will only happen once.

**Comment by BuhtigithuB** [comment]
Won't fix and close it?

:)

**Comment by mdipierro** [comment]
won't fix.

**Comment by BuhtigithuB** [comment]
Can we use more "Labels"? There is a label for won't fix available by default...

Can we be allowed using it without granting more privileges so we can better sort the issues out?

Thanks

**Comment by niphlod** [comment]
ping me if you need to manage some issues. Anyway a closed issue with a "won't fix" statement at the end by a core developer is not needing a "wontfix" label ....

**Comment by BuhtigithuB** [comment]
will do... You are rigth, but with label it can be retrievable more
easily... thanks anyway...
