### ISSUE TITLE
Compiled application doesn't handle default controllers well

### ISSUE THREAD

**Issue by pfctdayelise** [web2py/web2py#1185]
If I run 'compile application' from the admin menu, controller files get written out like `controllers.default.version.pyc`. If I visit `/version` in the browser I get a 404, because web2py is looking for a file called `controllers.version.index.pyc`.

`compileapp.py:compile_controllers` should handle the default controllers specially to preserve the URL routing.

(In particular, this is a pain given the [difficulty](http://stackoverflow.com/questions/26434323/remove-default-controller-from-auth) of having the magic Auth/user behaviour happen on a non-default controller.)

**Comment by mdipierro** [comment]
I believe this is the correct behavior and there should be a 404. It is the same if you do not "compile application". Unless I misunderstand the issue. Please reopen if I misunderstood.

**Comment by pfctdayelise** [comment]
It was *not* the same if the app was uncompiled. But I just tried to reproduce it with 2.14.2 and failed. Maybe I had some strange routes stuff previously, I will have to double check. Thanks.
