### ISSUE TITLE
[Feature Request] Pass onvalidation dict to smartgrid

### ISSUE THREAD

**Issue by sinaisix** [web2py/web2py#1188]
As per [this thread](https://groups.google.com/forum/#!topic/web2py/WG28up_5YCs) on the forums, a smartgrid can be passed a limited set of params as dict to be passed to child grids. However, onvalidation isn't part of the params that can be passed to child grids via a dict. 

This is problematic because then it means a child grid created cannot have any custom validation done, for instance, to enforce multi-column unique constraints. 

I humbly request that onvalidation be part of the smartgrid params that can be passed to child tables via a dict.

**Comment by mdipierro** [comment]
Can you submit a patch for this? I will take it.
