### ISSUE TITLE
autocomlete widget fix

### ISSUE THREAD

**Issue by RekGRpth** [web2py/web2py#1190]
```diff
diff --git a/gluon/sqlhtml.py b/gluon/sqlhtml.py
index 6adc4d1..097c737 100644
--- a/gluon/sqlhtml.py
+++ b/gluon/sqlhtml.py
@@ -736,7 +736,7 @@ class AutocompleteWidget(object):
         if self.is_reference:
             key2 = self.keyword + '_aux'
             key3 = self.keyword + '_auto'
-            attr['_class'] = 'string'
+            attr['_class'] = 'string form-control'
             name = attr['_name']
             if 'requires' in attr:
                 del attr['requires']
```

**Comment by BuhtigithuB** [comment]
@RekGRpth : What is fixing by this patch exactly?

**Comment by RekGRpth** [comment]
It is fix displaying autocomplete widget in forms

**Comment by leonelcamara** [comment]
This isn't really a bug or issue, if you want to adapt the AutocompleteWidget to bootstrap you can subclass it or add the form-control class manually.

**Comment by BuhtigithuB** [comment]
Considering Leonel explanation that this issue should be closed.

**Comment by niphlod** [comment]
@leonelcamara , @BuhtigithuB : I don't really have time to test but is AutocompleteWidget correctly shown with "bootstrap formstyles" ? if anyone confirms it, I'll close this.
