### ISSUE TITLE
Scheduler - Prevent Drift and Failed Runs - Next Run Time not progressing.

### ISSUE THREAD

**Issue by bmeredyk** [web2py/web2py#1191]
Please refer to this thread over on the main web2py usergroup. https://groups.google.com/forum/#!topic/web2py/khykEwJJrmY

I believe that there is a bug in gluon/scheduler.py which is causing tasks that utilize the Prevent Drift option to run repeatedly when a run fails. Prevent Drift utilizes a times_run variable when calculating when the next run should occur, however when tasks do not complete successfully this count does not currently get incremented which means that the next run time doesn't get moved forward and thus the task just gets picked up again almost immediately.  Review of the relevant source code suggests to me that the error is occurring in the section between lines 911 and 932 and that a new line should be inserted between lines 930 & 931 to update the times_run value as is done on line 914 for successful runs.

```
#gluon/scheduler.py starting at line 911
        if task_report.status == COMPLETED:
            d = dict(status=status,
                     next_run_time=task.next_run_time,
                     times_run=task.times_run,
                     times_failed=0
                     )
            db(st.id == task.task_id).update(**d)
            if status == COMPLETED:
                self.update_dependencies(db, task.task_id)
        else:
            st_mapping = {'FAILED': 'FAILED',
                          'TIMEOUT': 'TIMEOUT',
                          'STOPPED': 'FAILED'}[task_report.status]
            status = (task.retry_failed
                      and task.times_failed < task.retry_failed
                      and QUEUED or task.retry_failed == -1
                      and QUEUED or st_mapping)
            db(st.id == task.task_id).update(
                times_failed=db.scheduler_task.times_failed + 1,
                next_run_time=task.next_run_time,
                times_run=task.times_run, #<-- Insert this line to fix
                status=status
            )

```
Please review this suggested bug fix and consider for inclusion.

**Comment by bmeredyk** [comment]
See discussion at https://groups.google.com/forum/#!topic/web2py-developers/JC_bzRE6qo8 as the above fix won't completely work.

**Comment by niphlod** [comment]
will look into it ASAP
