### ISSUE TITLE
Auth.get_or_create_user does not pass the correct object to register_onaccept

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1192]
The `register_onaccept` callback expects a form object, which should include a `.vars` attribute containing all of the user fields, including the `id`. Instead, `Auth.get_or_create_user` passes a dictionary of user fields (excluding the `id` field). This means a callback written to work with the standard form-based registration will not work when calling `Auth.register_bare` (which uses `Auth.get_or_create_user`).

A fix would be for `Auth.get_or_create_user` to pass a `Storage` object with a `.vars` attribute containing the `user` Row object (which includes the `id` field).

See http://stackoverflow.com/questions/35504306/web2py-how-to-programmatically-register-users/35518991?noredirect=1#comment58754615_35518991.

**Comment by mdipierro** [comment]
The only real problem here is that it is not passing the ID. I changed it so that it is passing a user instead of the form. This should not break backward compatibility.

**Comment by abastardi** [comment]
I don't see your fix, but although passing a user will not break backward compatibility, it also won't fully fix the problem. With this fix, if you want to use `register_onaccept` with both the usual registration process as well as with `Auth.register_bare`, you would have to add some conditional logic to check the object passed in (as in one case, you would access the user attributes via `the_object.vars.attribute` and in the other case via `the_object.attribute`).

**Comment by mdipierro** [comment]
please check it.

**Comment by abastardi** [comment]
Looks good.
