### ISSUE TITLE
Updating form.vars does not work

### ISSUE THREAD

**Issue by Mentalleap** [web2py/web2py#1197]
Hello!

I'm trying to save the original name of an uploaded file. I use the code from here:
http://web2py.com/books/default/chapter/29/07/forms-and-validators#SQLFORM-and-uploads

When debugging, it seems that the value in form.vars.org_name gets overwritten with "" when form.process() is called.

For me this is a very critical bug since I need to process the file with its original filename. Any fix or workaround is higly appreciated.

Thank you 

Here my db:

`db.define_table('ck_client',
    Field('description', type='string', requires = [IS_NOT_EMPTY(error_message='cant be empty'), IS_ALPHANUMERIC(error_message='must be alphanumeric')] ),
    Field('ip', unique=True, type='string', requires = [IS_IPV4(error_message='must be ip'), IS_NOT_IN_DB(db, 'ck_client.ip')]),
    Field('mac', unique=True, type='string', requires = [IS_MATCH('^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$', error_message='must be mac'), IS_NOT_IN_DB(db, 'ck_client.mac')]),
    Field('uuid', unique=True, type='string', requires = [IS_MATCH('([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}?)', error_message='must be uuid'),IS_NOT_IN_DB(db, 'ck_client.uuid')]),
    Field('enabled', type='boolean', default=True),
    Field('enabled_from', requires = IS_TIME(error_message='must be time!'), default='00:00'),
    Field('enabled_to', requires = IS_TIME(error_message='must be time!'), default='00:00'),
    Field('deleted', type='boolean', default=False),
    Field('org_name', type='string'),
    Field('bootimage', type='upload'),
    format='%(name)s')
`

Here the controller:

`@auth.requires_login()
def client_create():
    db.ck_client_new.default = request.args(0)
    form = SQLFORM(db.ck_client_new, keepvalues=True)
    form.add_button('Cancel', URL('clients'))
    if request.vars.bootimage != None:
        form.vars.org_name = request.vars.bootimage.filename
    if form.process().accepted:
        response.flash = 'form accepted'
    elif form.errors:
        response.flash = 'form has errors'
    return locals()
`

**Comment by BuhtigithuB** [comment]
Hello Mentalleap,

I think I have the same issue as you can you explain a little bit more how
you issue arrive... What I do experiment with upload fields is that
thumbnail compute upload field entry get delete on form submit that failed
when there is no input update to the form, so bassically submitting a form
without change in it.

Is that the condition that trigger you problem?

**Comment by niphlod** [comment]
tried to replicate the issue, but it's the code that is wrong. 

If you're going to copy/paste the book, IMHO the bast path to follow is to copy it properly, understand it, and then augment it step by step, so you get instant return of what you're doing wrong.

Brief summary....

Giving
```
db.define_table('person',
    Field('name', requires=IS_NOT_EMPTY()),
    Field('image_filename'),
    Field('image', 'upload'))
```
as a model, and 

```
def display_form():
    record = db.person(request.args(0)) or redirect(URL('index'))
    url = URL('download')
    form = SQLFORM(db.person, record, deletable=True,
                   upload=url, fields=['name', 'image'])
    if request.vars.image!=None:
        form.vars.image_filename = request.vars.image.filename
    if form.process().accepted:
        response.flash = 'form accepted'
    elif form.errors:
        response.flash = 'form has errors'
    return dict(form=form)
```

as a controller....

the trick is really keeping the "image_filename" out of the form (code passes "fields" to keep it away), so it can get set by the "request.vars.image.filename" before form.process().accepted .
If you keep it in the form, the submitted value (probably the empty field you're not compiling) will overwrite in form.process() the ".filename" value you set earlier in the code

Feel free to reopen if you can't make the example in the book working.
