### ISSUE TITLE
Site renewal

### ISSUE THREAD

**Issue by michele-comitini** [web2py/web2py#1202]
The website has an oldish style, as much that it seems almost unmaintained. @mdipierro can we move to your (no offense ;-) ) stupid.css?

**Comment by mdipierro** [comment]
if people like stupid.css... why not? Let me play with it a few more days to declare it somewhat stable.

**Comment by encompass** [comment]
And drop bootstrap?

**Comment by mdipierro** [comment]
definitively yes for admin and examples. Not sure about welcome.

**Comment by mdipierro** [comment]
Done for example. Did you check it. Looks ok?
