### ISSUE TITLE
Update All Languages does not include Markmin strings

### ISSUE THREAD

**Issue by vinyldarkscratch** [web2py/web2py#1206]
I've been trying to figure out why some strings in my website aren't showing up in the language files.  After digging around, I found out that the admin panel's "Update All Languages" does not include any Markmin ```T.M()``` strings.  Is there an easy way to tell the function to include Markmin strings, preferably without modifying Gluon?

**Comment by vinyldarkscratch** [comment]
Update: it turns out that it's not just Markmin that isn't updating -- the files and language entries are not being modified, period.  This is happening with two of my applications, by the way, and has started happening since web2py 2.13.4.

**Comment by vinyldarkscratch** [comment]
After talking in PMs with Massimo, it sounds like there hasn't been logic to detect it in the first place, which confused me since I've seen Markmin strings appear in my translation files on default.py.  Would love to see this fixed!

**Comment by mdipierro** [comment]
This should now work. Please help me check it.

**Comment by vinyldarkscratch** [comment]
Checked over it, and I see what was going on with this: ```T.M()``` is what is adding the strings into the translation files (if it can't find it, it's adding it in with the key ```@markdown: Text Goes Here```); Update All Languages wasn't what was ever detecting it in the first place.  Seems it's only adding it to the language file that is called for, i.e. it adds it to de.py when German is requested but not cs.py.

The logic of commit 11da1ed did not resolve the issue as ```T.M()``` is looking for the strings that start with ```@markdown;```, however it _did_ take it one step closer to fixing.
