### ISSUE TITLE
smartgrid example problem - add record

### ISSUE THREAD

**Issue by JoeCodeswell** [web2py/web2py#1214]
This problem is MORE FULLY DOCUMENTED here: https://groups.google.com/d/msg/web2py/IUB8C8ew1Eg/NZidjawNBwAJ

It occurs on web2py version = 2.13.4-stable+timestamp.2015.12.26.04.59.39 on both Windows10 & Linux . 

Jim S says, "I cut your db.py, default.py and manage_songs.html code and pasted into a new app and it worked fine for me. ... So, I think your sample code is just fine.  My version is Version 2.13.3-stable".

BOTTOM LINE PROBLEM: The Smart Grid Example Code Add Record Button yields an error when accessed from Firefox & Opera. Here are the messages.

Firefox: "The page isn't redirecting properly. Firefox has detected that the server is redirecting the request for this address in a way that will never complete."

Opera: "The page isn't redirecting properly. Firefox has detected that the server is redirecting the request for this address in a way that will never complete."

Thanks for a GREAT FRAMEWORK.

Love and peace,
Joe

**Comment by leonelcamara** [comment]
I cannot replicate this issue with your example code.

**Comment by niphlod** [comment]
neither do I. 

@JoeCodeswell : will close this in a few days if no further details are posted.

**Comment by JoeCodeswell** [comment]
Certainly, guys. Please feel free to close.

Thanks for the blessings.

Love and peace,
Joe
