### ISSUE TITLE
auth.signature doesnt gets filled if its running within a scheduler task

### ISSUE THREAD

**Issue by AlfonsoSerra** [web2py/web2py#1247]
System Info:
Windows 7 64, Local rocket server, Mysql 5.5.24
Version 2.12.3-stable+timestamp.2015.08.19.00.18.03

Steps to reproduce:
-Create a user and login into your application.
-Create a table with auth.signature
-Create a function that inserts a few records using db.mytable.update_or_insert(query, **insertdata)
-Create a controller with auth.requires_login and run the function as a task using the Scheduler.
-Run the scheduler.
-Visit the controller's url to trigger the task

After the task is done auth.signature is missing created_by and modified_by fields.

**Comment by niphlod** [comment]
who should be put there ? the scheduler doesn't do any login....

**Comment by AlfonsoSerra** [comment]
The task runs from a controller which does login and performs db changes on tables with auth.signatures, which leads to incorrect values in the db and defeats the purpose of having auth.signature at all.

The scheduled task should be aware if it was ran by a user. Which also helps to audits security and bussines logic.

**Comment by niphlod** [comment]
ahem.... the task is QUEUED by a controller. it's executed in a TOTALLY different process which doesn't have any auth "references" whatsoever ...

**Comment by AlfonsoSerra** [comment]
I understand its a different process and doesnt have auth references, but does that mean that if we use the scheduler for long running db insertions can't we use auth.signature on tables?

DAL still is present in the execution evironment and thats the issue, why auth shouldnt when one of the main reasons of using the scheduler is the one described above? How should we perform long running db insertions on tables with auth signatures? isnt it worth to consider this?

Thanks

**Comment by niphlod** [comment]
auth is there (as DAL, etc etc): the underlying "issue" is that the external process is not a user, doesn't know anything about it and so auth is not "filled" with any data. 
IMHO all that it takes is:
- make your task accept an user_id parameter
- use that parameter to fill auth.user_id at the very beginning (sort of "impersonation" here)
- queue the task with the current auth.user_id as a parameter

it should be enough to fill any column that takes "auth.user_id" as the default, as created_by and modified_by.

**Comment by AlfonsoSerra** [comment]
Ok thanks, that will do, ill try.
