### ISSUE TITLE
About OPTGROUP Helper

### ISSUE THREAD

**Issue by josejachuf** [web2py/web2py#1258]
From book:

>>> print `SELECT('a', OPTGROUP('b', 'c'))`
```
<select>
  <option value="a">a</option>
  <optgroup>
    <option value="b">b</option>
    <option value="c">c</option>
  </optgroup>
</select>
```

I hope something similar to (http://www.w3schools.com/tags/tag_optgroup.asp):

```
<select>
  <optgroup label="Swedish Cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
  </optgroup>
  <optgroup label="German Cars">
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </optgroup>
</select> 
```

I think a syntax that includes the label argument:
>>> print ```
SELECT(		
		OPTGROUP(_label='Swedish Cars', 
			OPTION('Volvo', _value='volvo'),
			OPTION('Saab', _value='saab'),
			), 
		OPTGROUP(_label='German Cars',
			OPTION('Mercedes', _value='mercedes'),
			OPTION('Audi', _value='audi'),			
			)
		)
```

```
<select>
  <optgroup label="Swedish Cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
  </optgroup>
  <optgroup label="German Cars">
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </optgroup>
</select> 
```

**Comment by BuhtigithuB** [comment]
You have an error in your code in Python you can't have non-keyed argument after a keyed argument...

`SyntaxError: non-keyword arg after keyword arg`

Ref: http://www.programiz.com/python-programming/function-argument

Try this :
```python
SELECT(OPTGROUP(OPTION('Volvo', _value='volvo'),
                OPTION('Saab', _value='saab'),
                _label='Swedish Cars'),
    OPTGROUP(OPTION('Mercedes', _value='mercedes'),
             OPTION('Audi', _value='audi'),
             _label='German Cars')).xml()
```

Which should give you :
```html
<select>
    <optgroup label="Swedish Cars">
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
    </optgroup>
    <optgroup label="German Cars">
        <option value="mercedes">Mercedes</option>
        <option value="audi">Audi</option></optgroup>
</select>
```

**Comment by BuhtigithuB** [comment]
I had answer you on Github : https://github.com/web2py/web2py/issues/1258

Richard

**Comment by josejachuf** [comment]
You are right. Thank you so much
