### ISSUE TITLE
AttributeError: 'DAL' object has no attribute

### ISSUE THREAD

**Issue by butsyk** [web2py/web2py#1266]
Hello,

web2py: Version 2.14.3-stable+timestamp.2016.03.26.23.02.02
dal: 16.03

I've just updated to the last version and received the bug:
(previous version worked fine)

Table - page
Field('name', notnull=True),
Field('parent', 'integer', default=0, requires=IS_EMPTY_OR(IS_IN_DB(self.db, 'page.id', '%(name)s')),

AttributeError: 'DAL' object has no attribute 'page'

**Comment by leonelcamara** [comment]
Shouldn't parent be "reference page", not integer, and not have a default value at all?  
  
Anyway it does seem like a DAL bug since page is indeed defined.

**Comment by BMarvi** [comment]
same here!
upgrading from 2.12.3 to 2.14.3 broke compatibility with my application. 
Tried all versions so found out that last good versions was 2.13.4 and first broken is 2.14.1

My exact error:
AttributeError: 'DAL' object has no attribute 'trunks'

my relevant db.py sections:

```python
db  = DAL('mysql://user:password@192.168.1.111/dbname',  pool_size=myconf.take('db.pool_size', cast=int), check_reserved=['mysql'],lazy_tables = True,
db.define_table('sedi',
                Field('name',            length=100, requires=IS_NOT_EMPTY()),
                Field('dominio',         'reference domini', writable=False, readable=False, default=lambda:session.domain ),
                Field('dipartimento',    'reference dipartimenti'),
                Field('trunk',           'reference trunks', ondelete='SET NULL', requires=IS_EMPTY_OR(IS_IN_DB(db, 'trunks.id','%(id)s - %(name)s'))),
                format='%(name)s',
                common_filter = lambda query: db.sedi.dominio==session.domain,
                )
db.define_table('trunks',
                Field('dominio',            'reference domini', writable=False, readable=False, default=lambda:session.domain ),
                Field('name',               length = 100, requires=IS_NOT_EMPTY()),
                Field('enabled',            'boolean', default = False),
                format='%(name)s',
                common_filter = lambda query: db.trunks.dominio == session.domain,
                )
```

**Comment by BMarvi** [comment]
Tried to isolate the probelmatic file.
Seems to be `gluon/validators.py`

**Comment by BuhtigithuB** [comment]
trunks should maybe come before sedi??

**Comment by BMarvi** [comment]
In this simple case would resolve the problem. But in the complete application I have many others tables and relations in a way that at least one relation must come before the table that refers to. 
With the parameter `lazy_tables = True` would not be an issue, until version 2.14.1....

**Comment by leonelcamara** [comment]
Yes apparently IS_IN_DB stopped being lazy when evaluating the field. I'm looking at it, this issue is very easy to reproduce. Just put this pretty commonly used table in your db.py

```
db.define_table('category',
    Field('parent_id', 'reference category', requires=IS_EMPTY_OR(IS_IN_DB(db, 'category.id', '%(name)s'))),
    Field('name')
)
```

**Comment by BuhtigithuB** [comment]
I think it  can come from 2.13.4, I remember having noticed something
strange when try using a old app removing migrate=False... It may come from
earlier version since I use to set migrate=False since a long time...

**Comment by leonelcamara** [comment]
I have a fix for it, let me just add a test for it to make sure it doesn't happen again.

**Comment by leonelcamara** [comment]
@butsyk @BMarvi done, thanks for reporting the issue. Here's the pull request with the fix https://github.com/web2py/web2py/pull/1293
