### ISSUE TITLE
Possible upload filenames truncate issue depending of filesystem

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1285]
Here it mention about issue possibly occuring depending of the filesystem:

https://github.com/mdipierro/web2py-book/issues/277

I didn't fine any issue related to this possible problem neither for pyDAL, there is no listed issue open or close...

Not sure if it a web2py issue or pyDAL though...

**Comment by leonelcamara** [comment]
It's a documentation issue. In the sense that people using some very old or obscure operating system may need to deal with it. It's not a web2py issue.

**Comment by niphlod** [comment]
since it's tracked on https://github.com/mdipierro/web2py-book/issues/277 , I'm closing this
