### ISSUE TITLE
Bug Report: Typo in tools.py

### ISSUE THREAD

**Issue by ourway** [web2py/web2py#1286]
https://github.com/web2py/web2py/blob/master/gluon/tools.py#L4515

is_ctive should be is_active.  Preventing scheduler tasks from running correctly.

**Comment by niphlod** [comment]
To be fair it prevents that operation to be succesful in any environment...

**Comment by leonelcamara** [comment]
Fixed it here https://github.com/web2py/web2py/pull/1287
