### ISSUE TITLE
admin disabled because unable to access password file

### ISSUE THREAD

**Issue by sbourgeois1** [web2py/web2py#1301]
I implemeted a web2py upgrade to version 2.14.5 (I skipped 2 upgrades on the getup server), and 'git push' of my app (txp) to the paas getup server.
Problem: 'admin disabled because unable to access password file'
Here is how to reproduce the problem: 
https://web2py-txp.getup.io/welcome, sign in or login, then click on 'my sites' 
I get the same message from the URL https://web2py-txp.getup.io/txp/appadmin/index

Which file contains the password? In which application and in which position in the directory structure? How can I create this file? What should I put in it?

Thanks in advance for any suggestion.
Serge

**Comment by BuhtigithuB** [comment]
Can you try that : 

```bash
sudo -u www-data python -c "from gluon.main import save_password; save_password('123456',443)"
```

Ref: https://groups.google.com/d/msg/web2py/Fs2Y65nJkM0/Yxp88BNKHUEJ

**Comment by BuhtigithuB** [comment]
Did it works? If so, please close this issue...

**Comment by sbourgeois1** [comment]
Thank you very much.No, I didn't had the correct authorization, but I used the following turaround:1. First, I had to discover the correct port on the server.
For this, I changed (temporaly) the following source:wsgi/applications/web2py/applications/admin/model/access.py
line 46: (uncomment following lines with comments and vice versa)
        #port = int(request.env.server_port or 0)# ajout sbo
        #location = '../parameters_%i.py' % port # ajout sbo
raise HTTP(
            200, T('admin disabled because unable to access password file')) # del sbo 200,
           #    200, T('admin disabled because unable to access password file at %s' % (location)) )) # ajout sbo
I 'git pushed' this change on the server to catch the port in the error message => in my case, port was 80

2.. On my pc, I copied the file 'wsgiweb2py/applications/parameters_8000.py' to 'wsgiweb2py/applications/parameters_80.py' 
 and undid the previous change done in step 1
I 'git pushed' the file wsgiweb2py/applications/parameters_80.py and the reset the 'access.py' file to its initial content.
=> now it works (with the same password for the admin than on my pc).
 Hope this can help!
Serge Bourgeois
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr

 
      De : BuhtigithuB <notifications@github.com>
 À : web2py/web2py <web2py@noreply.github.com> 
Cc : sbourgeois1 <serge.bourgeois@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Jeudi 21 avril 2016 14h23
 Objet : Re: [web2py/web2py] admin disabled because unable to access password file (#1301)
   
Did it works? If so, please close this issue...—

**Comment by BuhtigithuB** [comment]
I don't understand why you would need to do such a thing...

**Comment by sbourgeois1** [comment]
To have the admin working, the system controls that the file containing the password exists.The program making this control is in the application 'admin', in the directory 'models'. The python source is access.py
The password is stored (in a crypted way) in a file called parameters_xxx.py, where xxx in the port number on which the admin application is running.
The normal was (for me) to maintain the data on the Paas server is to use git.
But I had 2 problems: 
1: The port number is used as a suffix in the parameter file.
which port was used ? => I changed the access.py file to see where this program was looking for the parameters file.
2. Create this file => I copied an existing file available on my pc with the appropriate file name.
I'm not a system expert. So, There are probably more straitforward solutions, but at least, what I did worked...
If you can suggest any alternative, thanks for the next time...
Best regards
Serge Bourgeois
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr

 
      De : BuhtigithuB <notifications@github.com>
 À : web2py/web2py <web2py@noreply.github.com> 
Cc : sbourgeois1 <serge.bourgeois@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Jeudi 21 avril 2016 16h07
 Objet : Re: [web2py/web2py] admin disabled because unable to access password file (#1301)
   
I don't understand why you would need to do such a thing...—

**Comment by BuhtigithuB** [comment]
As long as you don't leave this change there, I guess there is no problem... if you have the file (but to my understanding you don't) you can just rename it... Or generate a new one with the command I provide... I don't understand why you wouldn't know on which port you access you site... 80 (http), 443 (https) in prod are regular ports and in dev 8000 is the regular port and you shouldn't have issue in dev... Password file is only useful for granting access to admin app in production web2py instance...

**Comment by sbourgeois1** [comment]
Hello,
Thanks for your support and your feed back!
Of course as already said, I reversed (in the second git push I made) the temporary change I made to admin/models/access.py : my principle is to never touch to the web2py sources.

I tried the command you provided (with port 443), without success, because I don't have the right ro run it on the PaaS. And, surprisingly - for me-  the port is 80, even when I use https to connect to the web2py app on the Paas. The admin call comes from another web2py (welcome for instance, by clicking on 'site'). I guess that for performance reasons, for internal server calls, the http url is used instead of https?
 Thanks again,
Serge
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr

 
      De : BuhtigithuB <notifications@github.com>
 À : web2py/web2py <web2py@noreply.github.com> 
Cc : sbourgeois1 <serge.bourgeois@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Jeudi 21 avril 2016 17h14
 Objet : Re: [web2py/web2py] admin disabled because unable to access password file (#1301)
   
As long as you don't leave this change there, I guess there is no problem... if you have the file (but to my understanding you don't) you can just rename it... Or generate a new one with the command I provide... I don't understand why you wouldn't know on which port you access you site... 80 (http), 443 (https) in prod are regular ports and in dev 8000 is the regular port and you shouldn't have issue in dev... Password file is only useful for granting access to admin app in production web2py instance...—

**Comment by BuhtigithuB** [comment]
You can generate the file anywhere (let say your local machine) then copy
it... Please close this issue then...
