### ISSUE TITLE
IPV6 validators tests failing

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1302]
======================================================================
FAIL: test_IS_IPADDRESS (test_validators.TestValidators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_validators.py", line 1055, in test_IS_IPADDRESS
    self.assertEqual(rtn, ('2001::126c:8ffa:fe22:b3af', None))
AssertionError: Tuples differ: ('2001::126c:8ffa:fe22:b3af', ... != ('2001::126c:8ffa:fe22:b3af', ...

First differing element 1:
Enter valid IP address
None

- ('2001::126c:8ffa:fe22:b3af', 'Enter valid IP address')
+ ('2001::126c:8ffa:fe22:b3af', None)

======================================================================
FAIL: test_IS_IPV6 (test_validators.TestValidators)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_validators.py", line 980, in test_IS_IPV6
    self.assertEqual(rtn, ('2001::126c:8ffa:fe22:b3af', None))
AssertionError: Tuples differ: ('2001::126c:8ffa:fe22:b3af', ... != ('2001::126c:8ffa:fe22:b3af', ...

First differing element 1:
Enter valid IPv6 address
None

- ('2001::126c:8ffa:fe22:b3af', 'Enter valid IPv6 address')
+ ('2001::126c:8ffa:fe22:b3af', None)

----------------------------------------------------------------------
Ran 36 tests in 0.056s

FAILED (failures=2)

**Comment by BuhtigithuB** [comment]
Don't know why these tests fails as according to other tool like this : http://www.helpsystems.com/intermapper/ipv6-test-address-validation

The address seems valid... Also is_routeable=True setting all the other flag to false...

```python
        if self.is_routeable:
            self.is_private = False
            self.is_link_local = False
            self.is_reserved = False
            self.is_multicast = False
```

**Comment by leonelcamara** [comment]
It is a valid IPV6 address but it is not local. Isn't this just because the validator is being passed is_link_local=True hence it is not valid given the restrictions?

**Comment by BuhtigithuB** [comment]
Maybe should try an IPV6 valid address then!!

**Comment by niphlod** [comment]
can we close this ? I can't replicate the problem...

**Comment by BuhtigithuB** [comment]
Yes, will reopen if I fall on it again...
