### ISSUE TITLE
Local testing soap fail with

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1303]
testRegisterAndLogin (gluon.tests.test_web.TestWeb) ... Changed session ID welcome
Changed session ID welcome
Changed session ID welcome
Changed session ID welcome
ok
testSoap (gluon.tests.test_web.TestWeb) ... ERROR:gluon.contrib.pysimplesoap.server:Traceback (most recent call last):
  File "/home/version_nightly/web2py/gluon/contrib/pysimplesoap/server.py", line 184, in dispatch
    ret = function(**args)
  File "/home/version_nightly/web2py/applications/examples/controllers/soap_examples.py", line 26, in division
    return a / b
ZeroDivisionError: float division by zero

ERROR:gluon.contrib.pysimplesoap.server:Traceback (most recent call last):
  File "/home/version_nightly/web2py/gluon/contrib/pysimplesoap/server.py", line 184, in dispatch
    ret = function(**args)
  File "/home/version_nightly/web2py/applications/examples/controllers/soap_examples.py", line 26, in division
    return a / b
ZeroDivisionError: float division by zero

**Comment by niphlod** [comment]
it's expected to fail.

**Comment by BuhtigithuB** [comment]
It can then be closed, I guess I miss read the test output and now that I think about it only one error were reported at the end of the tests which was bugging me...

**Comment by niphlod** [comment]
you touched committed the changes the last time on the file : this goes a long way in realizing that reading and writing unittests vs pep8ing them is the real deal :-P

https://github.com/web2py/web2py/blob/master/gluon/tests/test_web.py#L142

**Comment by BuhtigithuB** [comment]
Your comment is free, as I just report a false positive because I read test output rapidly... As far as I know, my pep8ing didn't break anything... But I will excuse you for that as you seems to ignore when keep your mouth shut ;-P cheer!

**Comment by niphlod** [comment]
np.
