### ISSUE TITLE
Local testing scheduler fails

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1304]
======================================================================
FAIL: testRetryFailed (gluon.tests.test_scheduler.TestsForSchedulerRunner)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gluon/tests/test_scheduler.py", line 351, in testRetryFailed
    self.assertEqual(a[1], True, msg=a[0])
AssertionError: task status completed

----------------------------------------------------------------------
Ran 259 tests in 110.832s

FAILED (failures=1, skipped=1)

**Comment by niphlod** [comment]
"local" what ?

**Comment by BuhtigithuB** [comment]
When I run : 
```bash
python web2py --run_system_test
```
on my own machine

**Comment by niphlod** [comment]
auto-resolved ?

**Comment by BuhtigithuB** [comment]
I didn't close it, I don't understand...

**Comment by BuhtigithuB** [comment]
Ok, I think I press wrong button, I just realize that button change state...

**Comment by leonelcamara** [comment]
@niphlod @gi0baro  I think this may be related to the DAL changes as the error I'm getting in the scheduler tests is **unable to open database file**, we could fix the scheduler tests to work but there's probably some backwards compatibility problem with the DAL as the tests always ran fine locally before. The bug is probably related with the folder option the DAL has which should be where the sqliteadapter would look for the db file.

**Comment by gi0baro** [comment]
@leonelcamara I didn't change the behaviour of the folders with pyDAL, so I'm not sure the problem is related to the folders..

**Comment by leonelcamara** [comment]
I'm guessing this only happens on windows.

**Comment by chenl** [comment]
I see this problem on my Ubuntu 14.04 box.

**Comment by niphlod** [comment]
uhm. I'm improving tests and soon will commit a PR. Not seeing that on a windows box while implementing, I'll make sure it works on ubuntu before making the actual PR.

**Comment by chenl** [comment]
I have also looked at this test.
It seem to be flaky. My current guess is that exec_sched might return after only one of demo2 and demo8 tasks finished, after which a demo8 artefact file might linger on and make subsequent runs fail consistently.

**Comment by leonelcamara** [comment]
@niphlod I've found that this error (and many others, it's sort of random which one is triggered) can be caused by having another web2py running at the same time (in my case I've forgotten the web2py I use to develop apps running), I now believe that's the cause for some of the random failures.

**Comment by niphlod** [comment]
Smells fishy...they are a totally different processes not even sharing the
db...
Is this still happening on current master?

**Comment by leonelcamara** [comment]
Nevermind, I can't replicate this, I'm probably getting superstitious about the seemingly random (of course they arent) scheduler tests failures.

**Comment by niphlod** [comment]
I pinpointed the root cause on travis, which has to do with extremely unreliable performances. I'm thinking to add a separate run which is allowed to fail just on travis for this reason. Local testing though should NEVER fail (counting #1315 in)

**Comment by chenl** [comment]
I think this or #1315 should be re-opened.
I can see the same fail on my host after cloning a fresh copy.
