### ISSUE TITLE
expire_sessions.py in admin app

### ISSUE THREAD

**Issue by sherdim** [web2py/web2py#1309]
By default admin app in the dist  has nested directory scheme for session files
but current  expire_sessions.py in the cron directory supports the old all-in-one-directory scheme

So it confuses new customers.  
Possible actions:
- remove this example cron task to examples dir
- update it to match nested scheme
- tune admin app for old plain directory session scheme (admin is not for production - has a little sessions)

**Comment by ilvalle** [comment]
I'd go for the second option. Would you post a PR ?
