### ISSUE TITLE
Cannot queue tasks from the web2py shell

### ISSUE THREAD

**Issue by msasad** [web2py/web2py#1323]
This has been tested on the following two versions of web2py
Version 2.14.5-stable+timestamp.2016.04.14.03.26.16
Version 2.12.3-stable+timestamp.2015.08.19.00.18.03

Below are the contents of my db.py file:
<pre>from gluon.scheduler import Scheduler
db = DAL('mysql://web2py:baadal@10.0.0.111/web2py')
  scheduler = Scheduler(db)                                                          
                                                                                     
def task():
      import time
      with file('/tmp/test', 'w') as f:
          f.writelines(time.asctime())`
</pre>

and from the shell I try to queue the task like so:
<pre>scheduler.queue_task(task, repeats=5, period=30)</pre>

But this doesn't work. Upon inspection I found that the entry for the task was not being
created in the scheduler_task table.

However, making the same call from a controller or a model works fine.

Another thing noticed was that scheduled tasks are not run strictly according to the specified.
Although, I set the task to run every 30 seconds, the gap between two consecutive runs was
anything between 0 seconds to one minute.

**Comment by leonelcamara** [comment]
Did you db.commit() after queuing the task?

**Comment by niphlod** [comment]
definitely a db.commit() is missing. As for "the gap was anything between 0 seconds and one minute" please read about prevent_drift at http://web2py.com/books/default/chapter/29/04/the-core#Tasks

**Comment by msasad** [comment]
Indeed, I didn't do db.commit()
Thanks.
