### ISSUE TITLE
show_if is not compatible with recent pydal

### ISSUE THREAD

**Issue by ilvalle** [web2py/web2py#1324]
With recent pydal refactory introduced by @gi0baro cond.op.__name__ is in lower case, while before was in upper case. See https://github.com/web2py/web2py/blob/master/gluon/sqlhtml.py#L109

This breaks any app using show_if since a ```RuntimeError("Not Implemented Error")``` exception is raised.

**Comment by gi0baro** [comment]
@ilvalle thank you for the catch. I was not aware of that function. Will fix it asap.
