### ISSUE TITLE
web2py returns 400 bad request when issuing an HTTP PATCH request

### ISSUE THREAD

**Issue by msasad** [web2py/web2py#1331]
I am trying to run an action using HTTP PATCH request, but instead of executing the controller function, web2py simply returns HTTP error 400.

P.S. Everywhere that I read about web2py, I find only HTTP GET, POST, PUT and DELETE methods only. Are other methods even supported by web2py? If they are not enabled by default, is there any configuration to enable them?

**Comment by kirsn** [comment]
Are you trying this with the default rocket webserver?
Or do you have web2py configured with Apache / Nginx / similar webservers?

Based on the code that I see for the rocket webserver, I see that it doesn't have 'PATCH' as a request method. See line: https://github.com/web2py/web2py/blob/327c40cd1721025653504d8f49a8dd592a0e8438/gluon/rocket.py#L1205
Not sure if this is 'working as designed' or needs to be addressed.

If you are using any other webserver, I think the webserver provides configuration options to allow the methods you require.
You may also find this discussion to provide a little more context on web2py supported HTTP methods: https://groups.google.com/forum/#!searchin/web2py/patch$20head/web2py/IqJxYLR6b1g/LwrfF-rkEdQJ

**Comment by msasad** [comment]
I was trying it with the default webserver.
I'll try it with apache and let you know if it works.

**Comment by msasad** [comment]
I tried it with apache web server and it works fine.
