### ISSUE TITLE
<type 'exceptions.AttributeError'> 'PowerFormWizard' object has no attribute 'readonly'

### ISSUE THREAD

**Issue by pregenie** [web2py/web2py#1343]
Just running the example to see if I want to use the more complex wizard or roll my own from your previous examples.  Got this error.  If you are aware of it great.  Thank you for everything you both do to improve our ability as programmers to deliver.

**Comment by niphlod** [comment]
PowerFormWizard is not part of web2py, it's a third-party plugin. 
You can open a thread on the [mailing list](https://groups.google.com/forum/#!forum/web2py) to see if the original author or someone will reply.
