### ISSUE TITLE
gluon/scheduler.py - "format"  in  "db.define_table('scheduler_task',..."

### ISSUE THREAD

**Issue by tsouras** [web2py/web2py#1347]
please replace this line "format='%(task_name)s')"
with this line "format='(%(id)s) %(task_name)s')"

**Comment by niphlod** [comment]
what's the pressing reason behind this request ?

**Comment by tsouras** [comment]
I just think it is more easy (for me at least) to manage the scheduler using appadmin and/or custom SQLFORM.grid() views.

**Comment by niphlod** [comment]
okay, nothing major then. I'll fix before the next scheduler release which introduces a juicy new feature. Feel free to ping again in two weeks if you don't see it fixed in trunk.
