### ISSUE TITLE
sqlite date

### ISSUE THREAD

**Issue by ilvalle** [web2py/web2py#1356]
Current pydal v16.06.09 is not backward compatible since date fields in aggregated function are no longer parsed.
```
from pydal import DAL, Field
from datetime import datetime
db=DAL('sqlite:memory')
db.define_table('tt', Field('dd', 'date'))
db.tt.insert(dd=datetime.today())
r = db(db.tt).select(db.tt.dd.min()).first()
print type(r[db.tt.dd.min()])
```
returns ```<type 'str'>```. With former pydal the same returned ```<type 'datetime.date'>```.
@gi0baro is it due to the new refactory?

**Comment by gi0baro** [comment]
@ilvalle yes this is probably due to the refactoring. Will check this on the weekend.

**Comment by gi0baro** [comment]
@ilvalle this seems to be an python SQLite issue, since it doesn't detects and converts datetime field when using aggregation functions.
Will push a *forced* parsing of datetime and date fields on SQLite parser. This should be moved to pydal issues anyway.

**Comment by ilvalle** [comment]
ok, would you also add the example I posted as unittest to avoid future regression?

**Comment by gi0baro** [comment]
@ilvalle sure.

**Comment by niphlod** [comment]
closing since https://github.com/web2py/pydal/pull/375 tracks it
