### ISSUE TITLE
_default_router and args_match

### ISSUE THREAD

**Issue by zpo** [web2py/web2py#1362]
gluon/rewrite.py

I am not sure if it is a bug, but I encountered problems when I tried to pass base64 encoded strings in url.

Current default regex is:
```args_match = r'([\w@ -]|(?<=[\w@ -])[.=])*$',         # legal arg in args```
I had to override it as below for my purposes:
```args_match=r'([\w@ -]|(?<=[\w@ -])[.=]=?)*$'```

Maybe more liberal regex should be set as a default one?

**Comment by cassiobotaro** [comment]
See example here:

https://github.com/web2py/web2py/blob/master/examples/routes.parametric.example.py#L93-94

**Comment by zpo** [comment]
I have studied the example. The thing is that the default regex is not valid for base64 strings. The problem occurs when '==' sequence is used to inform last group contains only one byte. With '=' every request is valid.
