### ISSUE TITLE
ReferenceError: web2py is not defined

### ISSUE THREAD

**Issue by manuelep** [web2py/web2py#1364]
Applying the validator IS_STRONG to a table field I noticed that I got this error in the browser console:

> ReferenceError: web2py is not defined1 web2py-bootstrap3.js:14:6

The problem is resolved applying the patch suggested [here](https://groups.google.com/forum/#!topic/web2py/cIUMfdmUC4M) by @abastardi simply rewriting the [line](https://github.com/web2py/web2py/blob/master/applications/welcome/static/js/web2py-bootstrap3.js#L14) with the code:
`$.web2py.validate_entropy($(this));`

Thanks!
    Manuele Pesenti

**Comment by ilvalle** [comment]
@manuelep would you post a PR?
