### ISSUE TITLE
fpdf error on moving an application

### ISSUE THREAD

**Issue by mweissen** [web2py/web2py#1372]
Set's say I have an application MyApp which uses fpdf. This application is installed on a usb-stick and the drive letter is "D". Everything works fine. 

Now we take this usb-stick to another compter and the usb-stick gets the drive letter "E". fpdf fails with an error like 

```
<type 'exceptions.IOError'> [Errno 2] No such file or directory:
'D:\\MyApp\\web2py\\gluon\\contrib\\fpdf\\font\\arialnb.ttf'
```

Why? fpdf has created a file "arialnb.pkl" and this file contains the **absolute path** 
`D:\\MyApp\\web2py\\gluon\\contrib\\fpdf\\font\\arialnb.ttf`

**The best solution would be not to use an absolute path.**
My solution is "quick and dirty":

File fpdf.py, line 427 ff:
```
            name = ''
            if os.path.exists(unifilename):
                fh = open(unifilename)
                try:
                    font_dict = pickle.load(fh)
                finally:
                    fh.close()
            else:
                ttf = TTFontFile()
                ttf.getMetrics(ttffilename)
```        

change to:
            
```
            name = ''
            ttffile_found = False  <<########
            if os.path.exists(unifilename):
                fh = open(unifilename)
                try:
                    font_dict = pickle.load(fh)
                    ttffile_found = os.path.isfile(font_dict['ttffile'])  <<#######
                finally:
                    fh.close()
            if not ttffile_found:  <<##########
                ttf = TTFontFile()
```

This solution is not very beautiful, **but it works.**

Regards Martin Wweissenboeck

**Comment by ilvalle** [comment]
fpdf has been updated recently, can you check if this issue is still valid running web2py master?

**Comment by mweissen** [comment]
For this Project I have installed a new copy of web2py (Windows), Version
2.14.6.

fpdf.py in this version shows Version 1.7.1, last update 2012-08-16:

# * Software: FPDF for python
# * Version:  1.7.1
# * Date:     2010-09-10
# * Last update: 2012-08-16
# * License:  LGPL v3.0

Is there any newer Version?

2016-06-26 15:35 GMT+02:00 ilvalle <notifications@github.com>:

> fpdf has been updated recently, can you check if this issue is still valid
> running web2py master?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/web2py/web2py/issues/1372#issuecomment-228601673>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA_v0TGGXdo5PVOYwtQA2JaI6YUCiERvks5qPoATgaJpZM4I-ivB>
> .
>
​Regards, Martin​

**Comment by ilvalle** [comment]
A new version of web2py that includes the updated fpdf hasn't been released yet. As a result you have to checkout the current development branch.

**Comment by mdipierro** [comment]
We should make https://github.com/reingart/pyfpdf a package like we did for dal.

**Comment by niphlod** [comment]
I don't agree: we don't maintain pyfpdf and pyfpdf is a contrib module.
For all contribs, either we:
- depend on it, so requirements.txt will take care of installing them (and it gets just packaged in binaries as part of the python library)
- not depend on it, and we ship it because we just want something that works unzipping

In any case, making it a package won't solve the issue that web2py needs to keep track of working and non-working releases (either the shipped or the required) for each and every release. Subpackaging doesn't automagically update the required packages without releasing a new web2py ^_^

@mdipierro : I'd close this if you don't have further notes.

**Comment by niphlod** [comment]
ok, closing. just a last mention to @mdipierro to avoid trumping using "tacit approval" guerrilla methods .
