### ISSUE TITLE
Automatic creation of "wiki_editor" role is broken

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1389]
The change made at https://github.com/web2py/web2py/commit/2f0de8d8a08401ff32534bd38ff9925dd9990231#diff-27d81880c098645f12c4d0f5afb17f1aL6453 needs to be reverted. The original code correctly sets the value of `gid` in all cases (whether or not the "wiki_editor" group already exists). However, the new code fails to define `gid` in the case where the "wiki_editor" group doesn't yet exist, resulting in an UnboundLocalError. It's not clear why the original code was changed, except perhaps to favor an `if/else` block over a ternary expression.

**Comment by mdipierro** [comment]
This was fixed in 225a2861
