### ISSUE TITLE
"download" file does not include --recursive

### ISSUE THREAD

**Issue by MarkProDev** [web2py/web2py#1391]
I downloaded the web2py from the source download link and I got the following error:
Traceback (most recent call last):
  File "web2py.py", line 21, in <module>
    import gluon.widget
  File "c:\web2py-master\gluon\__init__.py", line 29, in <module>
    "You can also download a complete copy from http://www.web2py.com."
RuntimeError: web2py depends on pydal, which apparently you have not installed.
Probably you cloned the repository using git without '--recursive'
To fix this, please run (from inside your web2py folder):

     git submodule update --init --recursive

You can also download a complete copy from http://www.web2py.com.

**Comment by niphlod** [comment]
when you refer to "the source download link" what is the uri you're referring to ?

**Comment by cassiobotaro** [comment]
Already documented @MarkProDev : https://github.com/web2py/web2py/blob/master/README.markdown#important-reminder-about-this-git-repo

**Comment by MarkProDev** [comment]
re: "the source download link" when you select the Git Repository link
from:
http://www.web2py.com/init/default/download
select the clone or download button
then click "download zip"
this zip should have all the source files recursively.

I was able to work around the issue by getting the source code from the
link on the main screen or by using git manually with the recursive command
option.  I didn't notice the main screen link at first because I am
planning to develop so I went to the developer's buttons first.

**Comment by niphlod** [comment]
exactly what @cassiobotaro said: github DOESN'T include pydal recursively (not in the source, nor in the archive, which is just a zip of the source): if you want to use the source, you should do what is reported on the README, and there's NO WAY around it (until github does something)
