### ISSUE TITLE
env vars in appconfig.ini

### ISSUE THREAD

**Issue by laminko** [web2py/web2py#1395]
Environment variables support in appconfig.ini.

Discussion: https://groups.google.com/forum/m/#!topic/web2py/3x_aLR3a5iE

**Comment by mdipierro** [comment]
Instead of
[db]
uri=%(MY_DB_URL)s

Use

[db]
uri = {MY_DB_URL}

and when you use it:

myconf.get('uri').format(os.environ)

**Comment by laminko** [comment]
Thank you.

**Comment by laminko** [comment]
Hi, @mdipierro .

`os.environ` should have unpacked notation `**`. Because I got the error and found the solution in python doc: `.format(**dict)`.
