### ISSUE TITLE
Book DAL classes not migrated to pyDAL

### ISSUE THREAD

**Issue by dartg** [web2py/web2py#1401]
Since pyDAL is now a separate project, there're some classes in the [Chapter 6](http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer) that are no longer inside the `gluon.sql` module. Specifically:

- `gluon.sql.Table`

- `gluon.sql.Field`

- `gluon.sql.Row`

- `gluon.sql.Rows`

Should be replaced with:

- `pydal.objects.Table`

- `pydal.objects.Field`

- `pydal.objects.Row`

- `pydal.objects.Rows`

**Comment by niphlod** [comment]
tracked at https://github.com/mdipierro/web2py-book/issues/337
