### ISSUE TITLE
portalocker crashes py3

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#1403]
need to integrate 
https://github.com/WoLpH/portalocker
or
https://sourceforge.net/p/roundup/code/ci/default/tree/roundup/backends/portalocker.py

with our own (that has "specialized" GAE "additions")

**Comment by niphlod** [comment]
see https://github.com/web2py/web2py/pull/1402

**Comment by ilvalle** [comment]
I understood it was ok. At this point, also pydal is involved.
Would you update https://github.com/web2py/web2py/issues/1353?

**Comment by niphlod** [comment]
yep, pydal's and web2py's portalocker are the same and exhibit the same behaviour (and would anyone have took a look at warnings during unittest it would have popped up sooner). what should I update ?

**Comment by ilvalle** [comment]
Has it been fixed?

**Comment by niphlod** [comment]
With a twist but yes

Il 04 set 2016 07:56, "ilvalle" <notifications@github.com> ha scritto:
