### ISSUE TITLE
Single quote in ajax_error_500 message translation breaks jQuery

### ISSUE THREAD

**Issue by matclab** [web2py/web2py#1407]
in views/web2py_ajax.html, we can read:
```
 var ajax_error_500 = '{{=T.M('An error occured, please [[reload %s]] the page') % URL(args=request.args, vars=request.get_vars) }}'
    //--></script>
```

but using a translation like: 
```
"Une erreur s'est produite, merci de [[recharger %s]] la page"
```

Produces an error in javascript because of a simple quote in a simple quote delimited string. As a consequence, jQuery is not loaded and ajax is not working.

As a workaround, I replaced the quote with a similar looking UTF-8 character, but other people may fall in the same trap.

**Comment by kirsn** [comment]
Instead of introducing a unicode string in the translation, woult it be possible for you to change the views/web2py_ajax.html to ` var ajax_error_500 = **"**{{=T.M('An error occured, please [[reload %s]] the page') % URL(args=request.args, vars=request.get_vars) }}**"**`. Basically replace the `'` with `"`. 

If that sorts out the issue, then you could raise a PR, or send the code change (as a patch) to the developers.

**Comment by matclab** [comment]
Replacing the outer quote with double quotes didn't solved the problem either (raises another error)… 
I have not my code at hand, but I'll try to reproduce the problem with the double quotes and report it here.

**Comment by matclab** [comment]
I'm afraid it doesn't work, as it produces something like:
'''
var ajax_error_500 = "An error occured, please <a href="/admin/default/edit/welcome/controllers/default.py?id=controllers__default__py">reload</a> the page"
'''
Which is not syntactically valid javascript.
I guess the workaround is to stick with a single quote and escape the quote in the translated string.

**Comment by niphlod** [comment]
as @ilvalle noticed on top of @matclab , there's a deeper issue that who coded T.M and changed the stupid "reload me" message left us as a christmas present. It seems we need to address this wasting cpu at each and every request.
(see https://github.com/web2py/web2py/commit/e5355b5b12a7de1ee93bee6ab91fd2b79260706a#commitcomment-19157698)

**Comment by niphlod** [comment]
aha, found a way.
To be fair, I was never a fan of ASSIGNJS until now, and I seem to recall bashing @mdipierro about it. I stand corrected (not that this is the first time, but I like to praise as much as bashing :-P)
It's the only way to properly escape without having a global json serializer injected in the view.
a PR is on the way.

**Comment by mdipierro** [comment]
:-) Usually I am the one who is wrong. So this make me happy.

**Comment by matclab** [comment]
Thanks… 
I've learned the existence of ASSIGNJS…
