### ISSUE TITLE
GAE fake_migrate .table issue

### ISSUE THREAD

**Issue by frog42** [web2py/web2py#1412]
If you have fake_migrate=True and define a new table, then push to GAE, you will never be able to use that new table's name for anything else because GAE doesn't offer access to a directory storing the *.table files.  Any attempt to do a regular migrate after that will show the table doesn't exist (of course) and web2py will not attempt to create a table in SQL because it thinks it already exists due to the .table file existing in web2py_filesystem on GAE.

Currently the only solution I know is to connect to Cloud SQL via IPv4 and manually delete the .table entry.

**Comment by niphlod** [comment]
@mdipierro : again, needs immediate checking. If not, I'll close the issue in one or two weeks as nobody else deals with GAE.

**Comment by mdipierro** [comment]
Yes. This is how is works on GAE.  There is no way around.
