### ISSUE TITLE
using web2py with Passenger

### ISSUE THREAD

**Issue by jtkorb** [web2py/web2py#1413]
I'm using web2py on [Dreamhost ](https://www.dreamhost.com/)with the recommended [Phusion Passenger](https://www.phusionpassenger.com/) as the  deployment web server.  I configured the web2py [handlers/wsgihandler.py](https://github.com/web2py/web2py/blob/master/handlers/wsgihandler.py) as recommended by Dreamhost users (adding lines to launch python in a virtual environment), creating passenger_wsgi.py.  With just these edits, Passenger reported a timeout error from the application (web2py).  

The Passenger [debugging startup page](https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems) notes that Passenger uses stdout for communication with the application and assumes that it is not "closed, overwritten, or redirected" by the application.  

Web2py overwrites stdout with stderr on line 31 in wsgihandler.py.  When I comment out this line, web2py (and Passenger) startup just fine and seem to work, although I haven't done much testing beyond startup.

So, my question is, is this line necessary?  If so, is there a fix to make this setup work properly?  If web2py requires both file descriptors pointing to the same place, maybe set stderr = stdout instead?

**Comment by niphlod** [comment]
@mdipierro : any insights on why https://github.com/web2py/web2py/blob/master/handlers/wsgihandler.py#L35 is stricly needed ?

**Comment by mdipierro** [comment]
Yes. For Google App Engine.

**Comment by niphlod** [comment]
ahem. why do we have a gaehandler.py then ?! :D

**Comment by mdipierro** [comment]
You are right. I guess it is not critically necessary. We could remove it.

**Comment by niphlod** [comment]
will be fixed in https://github.com/web2py/web2py/pull/1459 . @jtkorb thanks for reporting, and sorry for taking so long to have it fixed ..........................

**Comment by jtkorb** [comment]
Thanks, glad to get it fixed!
