### ISSUE TITLE
CSRF/concurrency issues with sessions in db (e.g. GAE)

### ISSUE THREAD

**Issue by anssih** [web2py/web2py#1414]
With GAE sessions are stored in database and there is no locking like with file-based sessions.

Because concurrent requests are possible, e.g. the following can happen:
1. Request 1 begins, Session is retrieved from DB.
2. Request 2 begins, Session is retrieved from DB.
3. R1 stores r1key = r1value in the Session.
4. R1 ends, Session is stored to DB
5. R2 stores r2key = r2value in the Session.
6. R2 ends, Session is stored to DB.

In the end the session does not actually contain r1key, only r2key.

This can easily happen, for example, with CSRF keys when the user opens multiple records for editing in separate tabs from a table record listing. When the user tries to save their changes (not all at once), they may be silently discarded as the CSRF key was not found in the DB anymore (related: is the silency on purpose?).

In GAE, with the lowest instance class F1, just moderate complexity will result in requests taking hundreds of milliseconds, so there is quite a large window for the issue to trigger.

I'm not immediately sure what exactly could or should be done for this. At minimum it should be documented, though.

**Comment by niphlod** [comment]
@mdipierro : as I feel you're the only one from core devs to push for GAE compat, can you look at this ? if what is described is true, once again I can't fathom how can a web2py app can run on GAE without issues ^_^

**Comment by mdipierro** [comment]
Yes this can happen when sessions are stored on GAE datastore (nothing that can be done). Not if they are stored in GAE sql.
