### ISSUE TITLE
smartgrid: form.elements '_title' should not be translated

### ISSUE THREAD

**Issue by sbourgeois1** [web2py/web2py#1417]
Translating the '_title' prevent to do something like this in the controller: 
form.elements(_title='Add record to database', replace '')
since in the html, in French, we retreive  title = "Ajouter un élément à la base de données". So, the replacement of the _title cannot be done!.
Here under the html code :
&lt;span class="buttontext button" title="Ajouter un élément à la base de données"&gt;Ajouter un élément &lt;/span&gt;

**Comment by niphlod** [comment]
Are you asking to being able to pass your own "title" to every "standard" button on the grid ? Is it really that troublesome ?
If not so, why can't you just use the translation system to come up with what you want instead of using form.elements on server-side ? 
The misuse of server-side DOM operations is being quite a PITA. It doesn't take that much javascript experience to let it execute client-side and sidestep the "issue", saving tons of CPU.

**Comment by sbourgeois1** [comment]
Ok, let me give you an example, based on a smartgrid.
As you know, for each row of the grid, you can edit records, by clicking on a hyperlink made with A((SPAN(' ', _class = "iconpen icon-pencil glyphicon glyphicon-pencil" ),SPAN( 'Edit'))), _href = URL( ...

Now, imagine you simply want to keep theicon-pencil and remove the 'Edit' text from the hyperlink.
=> you can do this in the controller:     form.elements(_title='Edit', replace = '')
This is working, until you switch the language, because after switching the 'Edit' is translated.
Now, if you look into the html code in the view, you can see the  _title (variable name = 'Edit', and variable value also 'Edit') have both been translated! 

We have this in the view:
<span class="buttontext button" title="Éditer">Éditer</span>
We should have this:

<span class="buttontext button" title="Editer">Éditer</span>

Hope this is clear now... Serge Bourgeois
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr

 
      De : niphlod <notifications@github.com>
 À : web2py/web2py <web2py@noreply.github.com> 
Cc : sbourgeois1 <serge.bourgeois@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Lundi 8 août 2016 21h43
 Objet : Re: [web2py/web2py] smartgrid: form.elements '_title' should not be translated (#1417)
   
Are you asking to being able to pass your own "title" to every "standard" button on the grid ? Is it really that troublesome ?
If not so, why can't you just use the translation system to come up with what you want instead of using form.elements on server-side ? 
The misuse of server-side DOM operations is being quite a PITA. It doesn't take that much javascript experience to let it execute client-side and sidestep the "issue", saving tons of CPU.—

**Comment by niphlod** [comment]
ahem. doesn't showbuttontext=False accomplish the wanted result ?

**Comment by sbourgeois1** [comment]
YES!!! Thanks a lot for your answer!!! Kind regards,Serge
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr

 
      De : niphlod <notifications@github.com>
 À : web2py/web2py <web2py@noreply.github.com> 
Cc : sbourgeois1 <serge.bourgeois@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mardi 9 août 2016 13h21
 Objet : Re: [web2py/web2py] smartgrid: form.elements '_title' should not be translated (#1417)
   
ahem. doesn't showbuttontext=False accomplish the wanted result ?—
