### ISSUE TITLE
template.py - doctest correction, and minor PEP8 changes

### ISSUE THREAD

**Issue by kirsn** [web2py/web2py#1435]
Am trying to use the `template.py` in my project. Before using it, I thought I'll just run the doctest present within it. 
I see this error when running it.
```
**********************************************************************
File "d:\code\...\template.py", line 872, in __main__.render
Failed example:
    render(content=''''a"'bc''')
Expected:
    'a"'bc'
Got:
    '\'a"\'bc'
**********************************************************************
1 items had failures:
   1 of  12 in __main__.render
***Test Failed*** 1 failures.
```

I'll send a PR for this, which includes some minor PEP8 changes.

**Comment by niphlod** [comment]
since you're refactoring already, it should go in a proper unittest

**Comment by kirsn** [comment]
Will work on this as a unit-test. I realized that I won't be able to complete this in the next couple of weeks. 
Do we leave this open, so that I come back to it later? Or close / re-open, when am ready? 
Please suggest.

**Comment by niphlod** [comment]
Leave the issue open, close the pr and make a new one when it's ready

**Comment by kirsn** [comment]
Thanks, will do. No PR open anyway.

**Comment by niphlod** [comment]
closing this as eveything is already in a unittest. #1461 pep8ized the module, too.
