### ISSUE TITLE
examples application - slow scroll page in Firefox browser

### ISSUE THREAD

**Issue by carpaIdea** [web2py/web2py#1437]
With reference to
https://groups.google.com/d/msg/web2py/AWd6eMh9j6k/o2cqTdpuEgAJ

Possibile solution
This css rule in stupid.ccs should be enough in order to  prevent android horizontal scrolling
`html, body {max-width: 100vw; overflow-x: hidden}`

The issue should disappear by commented out (or removing) in applications/examples/views/layout.html

```
 <script>
    // prevent android horizontal scrolling
    window.addEventListener("scroll", function(){window.scroll(0, window.pageYOffset);}, false);
  </script>
```

but you have to test if it works in android devices.

**Comment by niphlod** [comment]
@mdipierro : moved to https://github.com/mdipierro/stupid.css/issues/11 as you're the only moving force behind stupid.css at this point.

@carpaIdea : feel free to post stupid.css-related bugs there
