### ISSUE TITLE
to_unicode not imported

### ISSUE THREAD

**Issue by pjryan126** [web2py/web2py#1442]
This module calls to_unicode() from the gluon._compat module in line 3500, but to_unicode() is not imported. it should be included in line 22.

``
from gluon._compat import StringIO, unichr, urllib_quote, iteritems, basestring, long, unicodeT, to_native, to_unicode
``

**Comment by ilvalle** [comment]
which module?

**Comment by pjryan126** [comment]
Sorry -- gluon.sqlhtml.py

**Comment by ilvalle** [comment]
Will post a quick fix for the import. Although it requires unittests for preventing other issues on both py27 & py35.
