### ISSUE TITLE
Double invert of Expression fails

### ISSUE THREAD

**Issue by iiijjjii** [web2py/web2py#1444]
The problem with a double invert of an Expression instance is back. It was originally discussed here:

https://groups.google.com/forum/?hl=en#!topic/web2py/VGNsa21wvrc

Ideally these should be the equivalent:

    db.person.name
    ~~db.person.name

But instead we get this:

    str(db.person.name)      'person.name'
    str(~db.person.name)     'person.name DESC'
    str(~~db.person.name)    'person.name DESC DESC'

Regards,
Jim

**Comment by niphlod** [comment]
a) it should be reported in web2py/pydal repo
b) what's the need behind the request ?

**Comment by iiijjjii** [comment]
I created an issue in pydal, #416, and included an explanation of how I use it.

**Comment by niphlod** [comment]
so this can be closed as its tracked at https://github.com/web2py/pydal/issues/416
