### ISSUE TITLE
Auth messages: unable_send_email vs. unable_to_send_email

### ISSUE THREAD

**Issue by dartg** [web2py/web2py#1455]
Is there any reason to have both messages? They have the same value by default ("Unable to send email") (see [tools.py:1576](https://github.com/web2py/web2py/blob/59315c874de729c3d52904c0e5aa425157b1a726/gluon/tools.py#L1576)) but the code sometimes uses the former and sometimes the later.

**Comment by niphlod** [comment]
it's probably a typo that needs fixing.
