### ISSUE TITLE
 No translation for pygraphviz library not found

### ISSUE THREAD

**Issue by kelsa-pi** [web2py/web2py#1472]
in language file:
pygraphviz library not found': 'pygraphviz biblioteka nije pronađena',

web2py show:
Graph Model
pygraphviz library not found

**Comment by willimoa** [comment]
Just completed a Pull Request for a d3 based graph model.   Once tested and accepted, it should fix this issue.   Note I have left the graphviz code as is.   Some people want to keep it and it should work as is, but it could be removed.

**Comment by willimoa** [comment]
Resubmitted my first dodgy Pull Request.  This is now added to web2py.   Graphviz code is still there and should still display if the library is present.  Otherwise you'll get the d3 model.
This Issue should now be closed.

**Comment by ilvalle** [comment]
We should move to a js only approach. Admin app should be cleaned from any code regarding graphviz. @willimoa would you post a new PR with such changes?

**Comment by willimoa** [comment]
Sure.

**Comment by ilvalle** [comment]
@kelsa-pi pygraphviz is no longer necessary, see https://github.com/web2py/web2py/pull/1622
This issue can be closed

**Comment by BuhtigithuB** [comment]
I understand that we move to 3djs... Although right now the models
rendering that been created with 3djs is unusable as an ERM graph... It in
3D which you have to move nodes to try to see something properly and it
impossible to print the ERM properly for analysing the database schema you
can barely analysing it with the live instance of the 3djs created graph...
I search in the 3djs examples didn't find anything already doing something
similar to what pygraphviz was doing... To me there is an usability
regression here... Any plan to improve that?
