### ISSUE TITLE
Scheduler - request.is_scheduler = None instead of True

### ISSUE THREAD

**Issue by bmeredyk** [web2py/web2py#1484]
When you access request.is_scheduler from outside of the scheduler you get False as one would expect. However, while running scheduler tasks request.is_scheduler = None instead of True. The current None value seems strange/non-intuitive.

```
#this won't work
if request.is_scheduler:
   #do special scheduler stuff

#To really know if you're running under the scheduler you must use this which makes no sense
if request.is_scheduler == None:
   #do special scheduler stuff
```
 
This has been the case for a while and is still happening with the latest git trunk

**Comment by abastardi** [comment]
I think this should fix it:

At https://github.com/web2py/web2py/blob/master/gluon/scheduler.py#L480, change:

                _env = env(a=a, c=c, import_models=True)

to: 

                _env = env(a=a, c=c, import_models=True, extra_request=dict(is_scheduler=True))

**Comment by niphlod** [comment]
yep, it does. A PR is on the way. @bmeredyk : this is probably due because usually one needs that condition to avoid executing a piece of code in the web-environment. But I see the point of consistency
