### ISSUE TITLE
webclient lose the session when session.forget is used

### ISSUE THREAD

**Issue by matclab** [web2py/web2py#1505]
When `session.forget` is added to an action like `index` we can observe that on subsequent call a logged user is logged out.

To reproduce, modify  `TestWeb.testRegisterAndLogin` in gluon/tests/test_web.py (tryed on  commit e6a3081b42ecd58441419930266baf286561c4c7) so as adding `session.forget(response)` at the first line of the `index` controller.

The test is run with :

```
python2 -m unittest -v gluon.tests.test_web.TestWeb.testRegisterAndLogin
```

And fails with :

```
======================================================================
FAIL: testRegisterAndLogin (gluon.tests.test_web.TestWeb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gluon/tests/test_web.py", line 92, in testRegisterAndLogin
    self.assertTrue('Welcome Homer' in client.text)
AssertionError: False is not true

----------------------------------------------------------------------
```

Which seems unexpected according to the google group exchanges about this subject.

I'd like to help, but I have only a rough idea of the expected behaviour of a browser with respect to cookies, sessions and headers… Link to documentation is welcomed.

**Comment by abastardi** [comment]
Here's the relevant discussion: https://groups.google.com/forum/#!topic/web2py/kRMZayGxzHA
