### ISSUE TITLE
Wiki is not stable in "stable version"

### ISSUE THREAD

**Issue by cassiobotaro** [web2py/web2py#1509]
If you download the stable version in web2py.com, version 2.14.6, the wiki funcionality is broken with the follow ticket:
```python
auth.add_membership(gid)
UnboundLocalError: local variable 'gid' referenced before assignment
```
This seems already fixed in master. Maybe a 2.14.7 with this ffixed can be releasead.

**Comment by niphlod** [comment]
if it has already been fixed ... why raising a ticket ?

**Comment by cassiobotaro** [comment]
Because if someone download the "stable version" on the website, the wiki funcionality is broken.

**Comment by niphlod** [comment]
yeah, and lots of other things fixed since the last stable. 
Here we fix errors on web2py's master code, not backport fix to stable releases ^_^
