### ISSUE TITLE
Setting obj.foo = None actually doesn't delete foo

### ISSUE THREAD

**Issue by dartg** [web2py/web2py#1510]
The `Storage` documentation says:

> A Storage object is like a dictionary except `obj.foo` can be used in addition to `obj['foo']`, and setting obj.foo = None deletes item foo.

Actually doing `obj.foo = None` just changes the value of `obj` to `None`, which is not deleting the item if you rely in `Storage.__contains__`. Instead, only `del obj.foo` really deletes the item.

```
>>> a = Storage()
>>> a.something = 1
>>> "something" in a
True
>>> a.something = None
>>> "something" in a
True
>>> del a.something
>>> "something" in a
False
```

**Comment by mdipierro** [comment]
This needs to be fixed in the doc. we change the behavior to make it faster.
