### ISSUE TITLE
Provide a way to locate applications outside the web2py tree

### ISSUE THREAD

**Issue by BrenBarn** [web2py/web2py#1517]
See mailing list thread [here](https://groups.google.com/d/topic/web2py/tdpbnXMsxlg/discussion).  The issue is that sometimes a web2py application is only one part of a larger project.  The current design of web2py forces the entire application to reside inside the web2py directory subtree.  The `folders=` config option can be used to move the `applications` directory outside the web2py dir, but each app still needs to be located inside that global apps directory.

What is needed is a way to specify an arbitrary directory for each app individually.  Each app should be able to stored anywhere in the file system, and there should be a way to tell web2py where to find it if it's not in the default apps directory.

**Comment by remcoboerma** [comment]
Aren't symlinks and directory junctions invented for exactly this purpose?

**Comment by BrenBarn** [comment]
As I mentioned on the thread, using filesystem-level solutions like that has drawbacks.  It means that other non-web2py actions (e.g., searching or deleting a directory tree) could recurse into the app directory, although one purpose of putting the app elsewhere would be to separate it from such things.

But basically, the point of this ticket is to say that the notion of "apps available to web2py" should be conceptually decoupled from "directories in this particular subtree".  I don't want my app directory to behave as if it were in the web2py directory; I want web2py to behave as if it doesn't matter where my app directory is.  There are things I want to do on the filesystem that that I don't want web2py to care about; there are things I want to do with web2py that I don't want to have to represent directly in the filesystem.  web2py should just have a mapping between application names and arbitrary directories.

**Comment by mdipierro** [comment]
I do not want to encourage this. Not at this time.
