### ISSUE TITLE
form resubmission in refresh or reload

### ISSUE THREAD

**Issue by Narendra-Kumar** [web2py/web2py#1521]
Form will be resubmitted if I refresh or reload the page. I didnot use Form or SQLForm to display or update data from database. Please help.

**Comment by leonelcamara** [comment]
That is really just the way browsers work so this is not really a web2py issue. The simplest way to prevent it is to simply redirect the user after he submits a form.

**Comment by niphlod** [comment]
BTW: for so obvious bugs maybe check first in #web2py-users
