### ISSUE TITLE
MSSQL connectivity

### ISSUE THREAD

**Issue by Narendra-Kumar** [web2py/web2py#1522]
DAL cannot connect MSSQL database, I used all three possibility uri strings give in web2py documents http://www.web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#Connection-strings--the-uri-parameter. Please help.

**Comment by niphlod** [comment]
check on [web2py-users](https://groups.google.com/forum/#!forum/web2py) before creating issues that are not existant .... mssql works perfectly fine.
