### ISSUE TITLE
New app not visible until server reload

### ISSUE THREAD

**Issue by dartg** [web2py/web2py#1528]
Create a new app using **admin**, for example, **newapp** and go to `http://127.0.0.1:8000/newapp`. You'll get:

> invalid function (default/newapp)

(Considering the default app doesn't have a function called `newapp`).

To get the new app working is necessary to hit **stop server** and then **start server**. I think this is an issue with the latest version, since I remember creating an app in previous versions and getting them working instantly.

Tested on Windows 8 with web2py 2.14.6.

**Comment by JunyanHe** [comment]
There is an button named "Reload routes" at up-right corner on admin site(http://127.0.0.1:8000/admin). You could use this and need not restart server.

**Comment by dartg** [comment]
However, the point is, routes should be reloaded automatically when a new application is created, like in previous versions. I think this is a bug.

**Comment by mdipierro** [comment]
problem is web2py does not know that a new application is created. It could be created form the shell.

**Comment by mdipierro** [comment]
On second thought.... this is a bug. I will fix it.
