### ISSUE TITLE
Appadmin orderby invalid syntax

### ISSUE THREAD

**Issue by leonardopf** [web2py/web2py#1535]
When i click on a column to chose it's order by, the get query is submitting it with quotes which show an alert saying 'invalid syntax'. Removing the quotes of get vars make it work again
![captura de tela de 2016-11-23 22 23 41](https://cloud.githubusercontent.com/assets/3034354/20582795/88343a76-b1cb-11e6-8396-01bc5c180cab.png)
![captura de tela de 2016-11-23 22 24 22](https://cloud.githubusercontent.com/assets/3034354/20582811/9aa97d60-b1cb-11e6-813d-74bc12e93f78.png)

Using:
Version 2.14.6-stable+timestamp.2016.05.09.19.18.48 - (From git)
pip freeze:
CDDB==1.4
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
defusedxml==0.4.1
docutils==0.12
dropbox==7.1.1
feedparser==5.1.3
html5lib==0.999
lxml==3.4.0
mercurial==3.1.2
mutagen==1.25.1
ndg-httpsclient==0.3.2
numpy==1.8.2
pexpect==3.2
Pillow==2.6.1
ply==3.4
psycopg2==2.5.4
pyasn1==0.1.7
pycparser==2.10
pycups==1.9.63
pycurl==7.19.5
Pygments==2.0.1
pygobject==3.14.0
pygpgme==0.3
pyinotify==0.9.4
pyOpenSSL==0.14
pysmbc==1.0.15.3
python-apt==0.9.3.12
python-dateutil==2.2
python-debian==0.1.27
python-debianbts==1.11
python-musicbrainz2==0.7.4
pyxdg==0.25
quodlibet==3.2.2
reportbug==6.6.3
reportlab==3.1.8
requests==2.12.1
roman==2.0.0
six==1.8.0
SOAPpy==0.12.22
typing==3.5.2.2
urllib3==1.9.1
uTidylib==0.2
wstools==0.4.3

**Comment by mdipierro** [comment]
This was fixed. Make sure you have latest last and a compatible (recent) appadmin.py
