### ISSUE TITLE
Create a new app from command line options

### ISSUE THREAD

**Issue by Marlysson** [web2py/web2py#1537]
Proposal to create a command to create a new applications from command line by example:

python web2py.py newapp name_app

without need copy and paste welcome application or access admin application from browser.

Or already exists this?

Just a proposal .. may be that this not be necessary.

**Comment by tomcam** [comment]
I love this idea for a variety of reasons. The best one for marketing is that it's what people are used to with Django, Laravel, etc. I think it would also be good to allow controllers, models, and views to be created from the command line. Yes, I totally know how easy it is to do these things in the web2py IDE. It's marketing-- a matter of what people expect, not what's logical.

**Comment by Marlysson** [comment]
Great .. This make easy start with web2py, who came from others framework..

Open the doors.. And how the programmer already stay in the command line , use them..

**Comment by manuelep** [comment]
Il 26/11/16 22:45, Marlysson Silva ha scritto:
>
> Proposal to create a command to create a new applications from command
> line by example:
>
> python web2py.py newapp name_app
>
What about move the welcome app to a separete github project and clone
from it?

Off course the main project would be manteined in sync with this, and
the welcome app would be managed as a sub project just the same as pyDAL
I guess...

    M.

**Comment by Marlysson** [comment]
> What about move the welcome app to a separete github project and clone
from it?

Separate why?

Just with the welcome app don't would be possible to use the command "newapp", would it ?

Has that modify the core ( gluon ) of the web2py..

**Comment by mdipierro** [comment]
You can do

```
python web2py.py -S newapp
```

or 

```
mkdir applications/newapp
cp -r applications/welcome/* applications/newapp
```

**Comment by Marlysson** [comment]
Ohh , I was reading the documentation and read the description of ```-S```: 

> -S APPNAME, --shell=APPNAME  = run web2py in interactive shell or IPython (if
> installed) with specified appname (if app does not
> exist it will be created). APPNAME like a/c/f (c,f
> optional)

Just the command isn't more explicit in the sense of "create a new app" in start of development .. and no access a ```--shell``` firstly .. 

Question of the semantics of the development process

**Comment by mdipierro** [comment]
You are right. want to try make a PR else I can do this but not a priority for 1.15.1

**Comment by Marlysson** [comment]
Sure .. I can ..

I will analyse the code to do this.. And doing it , would remove the behavior of the create a new app if run -S to nonexistent app .. raising an exception maybe..

**Comment by mdipierro** [comment]
Do not change the behavior for -S. Just add a new option to create.
