### ISSUE TITLE
setup-web2py-nginx-uwsgi-ubuntu.sh doesn't enable systemd record for uwsgi

### ISSUE THREAD

**Issue by wish7code** [web2py/web2py#1545]
setup-web2py-nginx-uwsgi-ubuntu.sh is intended to setup a complete ubuntu/nginx/uwsgi stack.

Previous versions of this script worked perfectly with an upstart record for the uwsgi emperor created and enabled on boot.

Current master version creates a systemd record for uwsgi emperor, **but doesn't enabled it.**
Upon next boot user will see a BAD GATEWAY error, as the uwsgi service isn't running

What's missing here is a call to

**systemctl enable emperor.uwsgi.service**

which would restore previous behaviour.

Version: script from github web2py master
OS: Ubuntu 16.04

**Comment by wish7code** [comment]
Sorry, I just discovered that this has been reported before with #1443 already, althought the fix shown there is not yet in the master branch..

**Comment by BuhtigithuB** [comment]
You can submit you PR against the other issue if you want...
