### ISSUE TITLE
multiple strikeouts in markmin are not rendered correctly

### ISSUE THREAD

**Issue by yaminle** [web2py/web2py#1547]
## description of the behaviour

When trying to render as html
``~~strikeout~~ and ~~another strikeout~~``
the result is:
``<p><del>strikeout~~ and ~~strikeout</del></p>``
the correct result should be:
``<p><del>strikeout</del> and <del>strikeout</del></p>``

code:
```python
>>> from gluon.contrib import markmin
>>> markmin.markmin2html.render("~~strikeout~~ and ~~strikeout~~")
'<p><del>strikeout~~ and ~~strikeout</del></p>'
```
## web2py version

(as stated in the file ``web2py/VERSION``)
Version 2.14.6-stable+timestamp.2016.05.10.00.21.47

## reason for incorrect rendering
incorrect regular expression in ``web2py/gluon/contrib/markmin/markmin2hmtl.py``, line 550

## fix:
replacing ``regex_del = re.compile(r'~~(?P<t>[^\s*]+( +[^\s*]+)*)~~')``
by ``regex_del = re.compile(r'~~(?P<t>[^\s~]+( +[^\s~]+)*)~~')``

**Comment by ilvalle** [comment]
Would you post a pull request with the proposed fixed?
