### ISSUE TITLE
web-based shell not working

### ISSUE THREAD

**Issue by kristjanvalur** [web2py/web2py#1552]
admin/controllers/shell.py isn't working.  All output is returned as "None".
After much digging, I traced the problem to this line in compileapp.py/run_controller_in():
`response = current.response`
The problem is that the shell controller creates its own environment to run the command in, modifying current.response.
Changing this line to:
`response = environment["response"]`
Fixes the problem.  This is also arguably more clear since "environment["response"]._vars is undoubtably the intended target of the controller, a tls global is not required to access it.

A separate is arguably that env() (as called from shell.py/callback()) creates a new environment, "current" is clobbered, and not restored after calling gluon.contrib.shell.run()

**Comment by ilvalle** [comment]
@kristjanvalur https://github.com/web2py/web2py/issues/1565 has been merged, would you close this commit?
