### ISSUE TITLE
Enable file uploads via Ajax components

### ISSUE THREAD

**Issue by abastardi** [web2py/web2py#1556]
web2py.js currently uses jQuery `.serialize()` when submitting forms via Ajax, which does not allow files to be uploaded. We should instead consider using the [`FormData` API](https://developer.mozilla.org/en-US/docs/Web/API/FormData), as outlined [here](http://blog.teamtreehouse.com/uploading-files-ajax), which would allow file uploads.

**Comment by ilvalle** [comment]
The only thing I see to discuss is that formdata is supported on IE 10.0+. Is it worth to drop IE <10 support?
@abastardi what do you think? @ms42Q would you try to post a PR ?

**Comment by leonelcamara** [comment]
I think we would need to have serialize as a fallback, sadly lots of people still need to support older IE versions

**Comment by abastardi** [comment]
Yeah, just check whether `typeof(FormData) !== 'undefined'`, and fall back to `.serialize()` otherwise.

**Comment by abastardi** [comment]
OK, I submitted a PR: https://github.com/web2py/web2py/pull/1666

**Comment by leonelcamara** [comment]
@mdipierro this can be closed since #1666 was merged

**Comment by mdipierro** [comment]
thanks
