### ISSUE TITLE
Some Service types lumped together incorrectly

### ISSUE THREAD

**Issue by BrenBarn** [web2py/web2py#1560]
In gluon.tools, the Service class defines a number of attributes run_procedures, json_procedures, etc., for storing different types of service functions.  However, some of the decorator methods store the decorated functions in an incorrect place.  For instance:

```
    def csv(self, f):
        """
        Example:
            Use as::

                service = Service()
                @service.csv
                def myfunction(a, b):
                    return a + b
                def call():
                    return service()

            Then call it with::

                wget http://..../app/default/call/csv/myfunction?a=3&b=4

        """
        self.run_procedures[f.__name__] = f
        return f
```

You can see at the end it is putting it in `run_procedures`, but this is the `csv` decorator, so it should be putting it in `csv_procedures`.  The `xml` decorator likewise stores the function it gets under `run_procedures` rather than `xml_procedures`.  In fact, the `csv_procedures` and `xml_procedures` attributes are never used at all.

More worrisome, both `serve_csv` and `serve_xml` actually look in `run_procedures` rather than `csv_procedures` or `xml_procedures` to see if the passed service is valid.  This means that if you define a function with `@service.csv`, you will be able to access it with a URL like `.../call/run/my_function`, and vice versa.  Effectively there is no distinction between "run", CSV, and xml services.  This can potentially lead to strange errors; you can for instance define a `@service.run` function that doesn't return data in a CSV format, which will cause an error if you try to access it via `../call/csv` since the handler is unable to parse it as CSV.

Looking at git blame, it appears the error has been present for several years (maybe since Service was added?), but apparently hasn't been noticed.

**Comment by ilvalle** [comment]
@BrenBarn https://github.com/web2py/web2py/pull/1566 has been merged, would you close this issue?
