### ISSUE TITLE
Provide a way to write "service" functions that accept *args/**kwargs

### ISSUE THREAD

**Issue by BrenBarn** [web2py/web2py#1561]
Currently, if you write a "service" function using the decorators like `@service.json`, etc., it can't usefull accept varargs.  This is because the `universal_caller` function in gluon.tools only passes arguments that explicitly correspond to named arguments in the service function's signature.  (This in turn is likely because `universal_caller` is working based on things like `co_argcount`, which doesn't provide a way to see whether a function accepts varargs.)  See mailing list discussion [here](https://groups.google.com/forum/#!topic/web2py/Xlrobpwv5Aw).

It would be nice to be able to write a service function that accepts arbitrary `*args` and/or `**kwargs`, passed as part of the URL path or as URL parameters, respectively.

Since `universal_caller` is a standalone function, this would probably require creating a new analogue of the Service class that rewrites the various `serve_*` methods to use a different function instead.  (Modifying `Service` directly could change the behavior of existing code.)  The simplest alternative is just:

```
def new_universal_caller(f, *a, **b):
    f(*a, **b)
```

This is basically what `request.restful` does.

If we do want to maintain the convention of passing only accepted arguments, we could use something like this:

```
def new_universal_caller(f, *a, **b):  
    argspec = inspect.getargspec(f)

    requiredArgs = argspec.args if argspec.defaults is None else argspec.args[0:-len(argspec.defaults)] 

    # if it accepts *args, we pass all positional arguments, otherwise only the number it accepts
    args = a if argspec.varargs is not None else a[:len(argspec.args)]
    
    # if it accepts **kwargs, we pass all keyword arguments, otherwise only those it accepts
    kwargs = b if argspec.keywords is not None else {argName: b[argName] for argName in argspec.args if argName in b}
       
    # it's an error to pass an argument both positionally and by keyword
    if any(argName in argspec.args[:len(args)] for argName in kwargs):
        raise HTTP(404, "Argument passed positionally and by keyword")
    # if we didn't get enough positional arguments, any missing ones must have been passed by keyword
    if any(argName not in kwargs for argName in requiredArgs[len(args):]):
        raise HTTP(404, "Not enough arguments passed")
    # otherwise, ok
    else:
        return f(*args, **kwargs)
```

`inspect.getargspec` provides a way to tell if the function accepts varargs or not.

One question is: is there a reason that the existing `Service` class doesn't just pass all arguments to the service function?  Or would it be better to just pass them all, as `request.restful` does, and accept that an exception will be raised if the arguments aren't right?

**Comment by ilvalle** [comment]
@BrenBarn https://github.com/web2py/web2py/pull/1566 has been merged, would you close this issue?
