### ISSUE TITLE
Adding extra form elements does not pass value in SQLFORM.grid

### ISSUE THREAD

**Issue by grakkpl** [web2py/web2py#1564]
I am using web2py 2.14.6.

The following instruction works great for SQLFORM:
http://web2py.com/books/default/chapter/29/07/forms-and-validators#Adding-extra-form-elements-to-SQLFORM

...and partially for SQLFORM.grid (you can **add** additional fields) but the value from the extra element is not passed in the form:

> After submission, `form.vars.agree` will contain the status of the checkbox, which could then be used in an onvalidation function, for instance.

**for SQLFORM.grid `form.vars.agree `does not exist in the onvalidation/oncreate/onupdate.**

**Comment by mdipierro** [comment]
This can be done:
```
grid = SQLFORM.grid()
if grid.create_form:
    grid.create_form[0].insert(-1,my_extra_element)
if grid.update_form:
    grid.update_form[0].insert(-1,my_extra_element)
```
