### ISSUE TITLE
Windows Cron error when enabling

### ISSUE THREAD

**Issue by AmpingGood** [web2py/web2py#1572]
When enabling Cron on windows from CMD with:
web2py.exe -K AppName

The following error is displayed

C:\Windows\System32>web2py.exe -K TrackingApp
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2017
Version 2.14.6-stable+timestamp.2016.05.10.00.21.47
Database drivers available: psycopg2, pymysql, imaplib, MySQLdb, sqlite3, pyodbc
starting single-scheduler for "AppName"...
Traceback (most recent call last):
  File "C:\Program Files\web2py\gluon\shell.py", line 273, in run
    exec(python_code, _env)
  File "<string>", line 1, in <module>
AttributeError: 'thread._local' object has no attribute '_scheduler'

**Comment by niphlod** [comment]
Ti;dr: don't ever use cron on web2py. It is officially deprecated.

Il 14 feb 2017 3:51 PM, "AmpingGood" <notifications@github.com> ha scritto:

**Comment by ilvalle** [comment]
Perhaps a note about the deprecation of cron can be added in the book.
@mdipierro would you close the issue?
