### ISSUE TITLE
IS_EMAIL does not handle Internationalized Domain Names

### ISSUE THREAD

**Issue by matclab** [web2py/web2py#1582]
[Internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) allows for unicode characters in domain names.

As thus IS_EMAIL default regex should be updated to allow for such domain, else it would for example prevent people with mail addresses on IDN to subscribe.

**Comment by matclab** [comment]
[RFC 5336 §3.3](https://tools.ietf.org/html/rfc5336#section-3.3) Precise the extended mail address syntax to support for IDN.

**Comment by matclab** [comment]
So, a UTF8 string is permitted. That string MUST NOT contain any of the       ASCII characters (either graphics or controls) that are not permitted in "atext"; it is otherwise unrestricted.

Where:
```
atext           =       ALPHA / DIGIT / ; Any character except controls,
                        "!" / "#" /     ;  SP, and specials.
                        "$" / "%" /     ;  Used for atoms
                        "&" / "'" /
                        "*" / "+" /
                        "-" / "/" /
                        "=" / "?" /
                        "^" / "_" /
                        "`" / "{" /
                        "|" / "}" /
                        "~"
```

(See RFC 5322)

**Comment by ilvalle** [comment]
IS_EMAIL is based on a complex REGEX, see https://github.com/web2py/web2py/blob/b2e03c9dee935d46cb9512f0595dc2dacddb5166/gluon/validators.py#L1159
Related to this https://docs.python.org/2/library/codecs.html#module-encodings.idna
