### ISSUE TITLE
eclipse+pydev breakpoint not work with the latest cloned web2py.

### ISSUE THREAD

**Issue by liuyibing45** [web2py/web2py#1587]
My computer is win7 x64. I am using eclipse(4.6.2) ,pydev(5.5.0), python(2.7.13) and the web2py latest cloned from the github. Compared with the 2.14.6 stable version web2py, the latest cloned web2py has many additonal files which I guess may be used for compiling and debugging. However when I debug my application which based on the latest cloned web2py, the breakpoint I set in my controller/default/index  not stop. Only the breakpoint in the web2py.py can work. This is very confusing. So I change the web2py to the 2.14.6 stable version  and the breakpoint is ok.  What should I do with the latest cloned web2py to make the breakpoint work under the eclipse+pydev?

**Comment by gerencia** [comment]
Same issue here with Win10.

**Comment by ilvalle** [comment]
I guess https://github.com/web2py/web2py/pull/1630 fixed this issue too. @liuyibing45 @gerencia would you mind testing trunk?

**Comment by mdipierro** [comment]
@gerencia can you help us test whether this ifixed?

**Comment by gerencia** [comment]
Tested, works good now.

**Comment by mdipierro** [comment]
Thanks!
