### ISSUE TITLE
Virtual Fields do not appear to work with Autocomplete widget

### ISSUE THREAD

**Issue by btbonval** [web2py/web2py#1588]
I've seen a few posts in the mailing list where people could not figure out how to get a Virtual Field to work in the Autocomplete widget. Most just say it isn't supported. One post noted that `db=db(db.table)` should be included into the Autocomplete widget. That certainly helps, but I see an error.

```
Set object has no attribute __getitem__
```

This is because `db(db.table)` is a Set object, and the following code won't work with a Set object:
https://github.com/web2py/web2py/blob/9978e63621d8f14e5d93ae5feb767b200a77e797/gluon/sqlhtml.py#L693-L697

Notice that the Autocomplete widget actively looks for `Field.Virtual`, so it seems like it is supported.

What I don't understand is line 697: `field.tablename`. Clearly, `field` is a `Virtual.Field` based on line 695, and the virtual field class seems to always have `tablename` set to `None` (at least in the most recent release R-2.14.6). Regardless of my `Set` error above, I'm not sure I understand why this chunk of code is written this way.

I must be missing something about virtual fields to make them work with Autocomplete, but I have not been able to find anything in the mailing list or Github issues. A dive into the code only raises more questions, like why bother with `field.tablename` if it is guaranteed to be `None`?

**Comment by abastardi** [comment]
`Field.Virtual` takes a `table_name` argument, so you must specify the table name in order for this to work. Assuming that corrects the problem, maybe close this issue and instead open one with the web2py book repo to document all the arguments to `Field.Virtual` and especially not the need to specify `table_name` in order for various other features to work properly.

It may also be possible to alter pydal.objects.Table so it automatically adds the `.tablename` attribute to virtual fields when they are included in the original table definition (as it does for standard fields). Of course, this would still not help with virtual fields that are defined after the main table definition.

**Comment by mdipierro** [comment]
Can this be closed?

**Comment by abastardi** [comment]
I added an issue to the book repo, so I think we can close this one.
