### ISSUE TITLE
field.set_attributes(..) could return the instance

### ISSUE THREAD

**Issue by dz0** [web2py/web2py#1595]
Would let the code be  more straightforward -- example, when passing the "decorated" field to the function...
Now I have to   "scatter" the code in two places for each field...

https://github.com/web2py/pydal/compare/master...dz0:patch-1

**Comment by ilvalle** [comment]
Would you open a PR on https://github.com/web2py/pydal?

**Comment by ilvalle** [comment]
@mdipierro https://github.com/web2py/pydal/pull/458 has been merged, this issue can be close
