### ISSUE TITLE
trouble with handling request.vars.checkbox list

### ISSUE THREAD

**Issue by frankclaessen** [web2py/web2py#1597]
Hi all,

This is my first question for the list; up to now i have been lurking and learning mainly. 
I think it is fair to say I am not an experienced python programmer so - this might just be my lack of knowledge. Forgive me please if my question shows just that.

I built a form that enables users to choose more than 1 row through a checkbox.
This form and the subsequent handling just works fine, as long as I choose more than 1 row.

If you want to take a look at  the piece of code from the view below  - the value for the box is the ID of the table-record:

---
         {{for lijst in lijsten:}}
            <tr>
                <td>{{=lijst.methode.titel}}</td>
                <td>{{=lijst.woordenlijst.titel}}</td>
                <td style="width:100px">{{=lijst.woordenlijst.taal_links}}</td>
                <td style="width:100px">{{=lijst.woordenlijst.taal_rechts}}</td>
                <td><input type="checkbox" name="keuzelijst" value="{{=lijst.woordenlijst.id}}"/></td> !!!!! 
            </tr>
        {{pass}}
---

If I however choose just one row that has an ID say 38 --> then the following happens when dealing with the choices:

---
   if request.vars:
        for x in range(len(request.vars.keuzelijst)):
            db.lijst_ovh.insert(gebruiker=auth.user_id,wlijst=request.vars.keuzelijst[x],overhoring=currentOvh)
---
First of all: the length of request.vars.keuzelijst appears to be 2 ??
The ID (38) is being split into 2 separate values: first loop  3 and the next loop 8

So what am I doing wrong here?

I hope you can help me with this 

Regards

Frank Claessen

**Comment by frankclaessen** [comment]
Hi all, Frank again. I have been debugging more and found the cause for this error:

If there is just one choice, the type is str (string) and if there is more than one choice, the type is list.
That's why the length is 2 if there is just one choice!

So there is a need to test the type after the choices have been made and act accordingly.

I found the same comment regarding the use of selectables for SQLFORM.grid by the way - someone in 2014 reported the same problem.

Regards

Frank

p.s. not sure if this still should be considered an issue ??

**Comment by mdipierro** [comment]
This is not a bug it is by design. It is up to you to check whether you received a string or a list before computing len(). Anyway, thanks for checking with us. :-)
