### ISSUE TITLE
URL having character | in fragment part, does not pass IS_URL validator

### ISSUE THREAD

**Issue by gauravvichare** [web2py/web2py#1598]
`IS_URL()` validator doesn't accepts following url and similar google group urls. 
Example: https://groups.google.com/forum/#!searchin/web2py/url$20validation$20problem|sort:relevance/web2py/69KmsrYAF44/Sgk_hA_6TlcJ

Character | should be allowed in fragment part of the url

**Comment by kirsn** [comment]
My guess, is that `|` should be included in the code at this line: https://github.com/web2py/web2py/blob/master/gluon/validators.py#L1610
This change seems to work, though am not aware of the implications:
` GENERIC_URL_VALID = re.compile(r"[A-Za-z0-9;/?\|:@&=+$,\-_\.!~*'\(\)%#]+$")`

**Comment by ilvalle** [comment]
@kirsn would you post a PR with the proposed fixed and an unittest for `|`

**Comment by leonelcamara** [comment]
That fix is not correct as that would allow | anywhere in the URL. It should only be allowed in the fragment.

**Comment by kirsn** [comment]
Wondering if using https://pypi.python.org/pypi/rfc3987 could help, instead of rolling our own URI / IRI validation logic?
