### ISSUE TITLE
how can fix the administrator issue. i fed the wrong administrator password and now it can't allow me to access the admin side

### ISSUE THREAD

**Issue by dengsang** [web2py/web2py#1600]

**Comment by michele-comitini** [comment]
If you can access on local machine (127.0.0.1) on port 8000
go in web2py dir and start web2py:

python web2py.py -a '<put your new password here>'

point your browser at http://127.0.0.1:8000/admin

and use the new password.


Il venerdì 31 marzo 2017, dengsang <notifications@github.com> ha scritto:

**Comment by leonelcamara** [comment]
You may also have to edit applications/admin/private/hosts.deny and remove the line with your IP if you got blocked.

**Comment by dengsang** [comment]
Actually i was blocked. kindly give the procedure on who to do the same

**Comment by leonelcamara** [comment]
I've already given you the procedure, edit hosts.deny with any text editor and remove the line with your IP.

@dengsang do you mean we should put it in the book?  

If so, and your issue is solved, please open an issue in [web2py-book](https://github.com/web2py/web2py-book) and close this one.
