### ISSUE TITLE
Error while view graph model - admin application

### ISSUE THREAD

**Issue by Marlysson** [web2py/web2py#1605]
When I gone view the Graph model in admin application show that `pygraphviz` library is required.

Didn't would be better already include this library in dependencies's framework?

This missing break any feature that uses this library from admin app

## Details:

Version 2.14.6-stable+timestamp.2016.05.10.00.21.47

## Error:

```python
<type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'AGraph'
```

Probably include the library solve this.

**Comment by leonelcamara** [comment]
It's not a dependency of the framework it's a dependency of that specific feature in the admin application. It's not possible to bundle because pygraphviz depends on graphviz which is not python.

**Comment by Marlysson** [comment]
@leonelcamara All right. But being in the framework it's expected that the features works .. Or that exists some way to use them.

I will try install it.

**Comment by ilvalle** [comment]
The best is to switch to d3, an example has been proposed by @willimoa see https://github.com/willimoa/welcome_d3.
A pull request to replace the current graph with this new one is very welcome.

**Comment by Marlysson** [comment]
Great! .. I'll take a look.
