### ISSUE TITLE
select returns records from a table different of my select

### ISSUE THREAD

**Issue by lben** [web2py/web2py#1611]
Hi, I have this table:

`db.define_table('contrato',
                Field('empleado_id', 'reference empleado'),
                Field('empresa_id', 'reference empresa', label='Empresa', requires=IS_IN_DB(db(db.empresa.id.belongs(get_id_empresas_usuario_logueado())),
                                                                                            'empresa.id', '%(razon_social)s')),
                Field('tipo_contrato_id', 'reference tipo_contrato', label='Tipo de Contrato'),
                Field('estado', 'string', default='Activo', requires=IS_IN_SET(['Pendiente','Activo','Vencido','Terminado','Liquidado']) ),
                Field('fecha_inicio', 'date', required=True),
                Field('fecha_fin', 'date'),
                format=lambda registro: format_contrato(registro),
                common_filter=lambda query: db.contrato.empresa_id.belongs(get_id_empresas_usuario_logueado()))`

Inside a component I run this select:
`contratos = db(db.contrato.empleado_id == id_empleado).select(db.contrato.id,
                                                                      db.contrato.tipo_contrato_id,
                                                                      orderby=db.contrato.estado)`
When I inspect the 'contratos' variable value using the pycharm debugger I have noted that it returns a Row object for the 'auth_group' table and the 'role' column of that table.

Going further on my debugging I have noticed that in the adapters/base.py the table name changes from contratos to auth_group. I don't understand very well the code inside that file but it seems that there is a bug somewhere.

Can anyone help me with this? let it be reproducing the error, explaining the code or something? If this is a bug please fix it! Thanks!

**Comment by lben** [comment]
Ok, after further analysis I noticed that in my common_filter I execute this method: get_id_empresas_usuario_logueado() which have this line:
`grupos = db().select(db.auth_group.role)`
it seems that this query executes last and overrides my original query so I add this lines to my model so I run this query only one time and before every other query:
`if session.ids_empresas_usuario_logueado is None or len(session.ids_empresas_usuario_logueado) == 0:
    session.ids_empresas_usuario_logueado = get_id_empresas_usuario_logueado()`

That way I have fixed my problem, dont know if this is the way of doing it (using sessions) but I think that the common_filter queries dont need to override the original query.
I hope this helps someone in my situation and if this is a problem with web2py this can be addressed.

**Comment by leonelcamara** [comment]
Using the session for this seems fine although I would probably put it there on login_onaccept.  
  
As for why the common_filter was causing the problem, was your common filter returning a Query as it should? Can we see the original code for it?

**Comment by mdipierro** [comment]
I do not think there is a bug here.
