### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [web2py/web2py#1612]
Is web2py fully Python 3 compatible?

**Comment by kirsn** [comment]
There is work going on in this direction. There is an open issue: https://github.com/web2py/web2py/issues/1353. 

Also, try to follow some of the conversation on the web2py google group - https://groups.google.com/forum/#!forum/web2py - to get a better perspective.
 This for example: https://groups.google.com/forum/#!searchin/web2py/python$203|sort:relevance/web2py/2YB-cZ3mww8/sF93modxBgAJ

**Comment by Tset-Noitamotua** [comment]
Thanks! I'll check that out.

**Comment by ilvalle** [comment]
@Tset-Noitamotua we are close to support python 3.5, the best is to test master branch and report any issue. The open issue with few things to do is https://github.com/web2py/web2py/issues/1353
For now you can close this issue.

**Comment by nickysavage** [comment]
So if I learn Web2py will I always have to wait a three period for the program to work with a new release of python? Python 3.5 was released in 2015. We are now up to 3.6.4.
Does this mean that web2py is not open source or that it does not have enough people that contribute to it? 
I think I will stick to Django.

**Comment by kirsn** [comment]
@nickysavage it would help the web2py community, and possibly you in your evaluation of web2py, if you can try running the code under `master` branch in python 3.x. Your experience with that, or any bug reports would help.
