### ISSUE TITLE
Is it possible to build a realtime chat application with web2py?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [web2py/web2py#1615]
Is it possible to build a realtime chat application with web2py?

If so, can anybody point to some beginner friendly examples or tutorials please.

**Comment by Tset-Noitamotua** [comment]
... I found this one by googling: [w2pchat][]

[w2pchat]: https://github.com/rpedroso/w2pchat

**Comment by Marlysson** [comment]
There are this tutorial:

[Youtube video](https://www.youtube.com/watch?v=MUWy-NSrvNQ)

By @brunorocha . And he uses websockets.

**Comment by Tset-Noitamotua** [comment]
Unfortunately I don't understand Bruno :( - his video is not in English.

**Comment by Marlysson** [comment]
Try repeat what he do..

It funny : A english person needing to something that isn't english :D .
We ( other countries ) read and watching content and videos in english (repeating and learning)  .. Try this.. 
If you don't achive speak me your dificulty..

**Comment by BuhtigithuB** [comment]
Example is pretty self explaining if you follow study the code and the
demonstration. Put the vid on pause as needed.

Notice, I don't think github is the proper channel to ask such kind of
question... Please close the ticket over github and come back on the google
groups mailing-list.

Thank you

Richard

**Comment by Tset-Noitamotua** [comment]
Ok. I'll try. Thank you.
