### ISSUE TITLE
auth.settings.username_case_sensitive = False not usable on python 3

### ISSUE THREAD

**Issue by DonaldMcC** [web2py/web2py#1619]
The above setting results in an invalid email message ie fails validation so while you can register you can't then log back in again on python3 only.

**Comment by ilvalle** [comment]
Can you elaborate a little more the issue?
Mind that setting `auth.settings.username_case_sensitive = False` forces username to be converted to lowercase and there are no differences between py27/py35.

**Comment by DonaldMcC** [comment]
Wasn't much more too it - basically if I put that line in model file then it gave me the error when validating the login form.  However I have pulled down latest version as of today with the auth refactor and problem no longer recurrs so closed the issue
