### ISSUE TITLE
It cost a long time to load page

### ISSUE THREAD

**Issue by snakeli** [web2py/web2py#1627]
I have about 4 client connect to the server, every client will upload data by @service.xmlrpc every 3 - 6 second. However it lead to long time to load webpage, even an empty page, it cost about 6-10 second to load it.
Seems it will execute models every time client upload dates. does it influence the cpu usage? I checked the CPU(top), python CPU usage is about 110%(quad-core)。

**Comment by niphlod** [comment]
Models are executed at each and every request (that's the whole beauty of
them)... But unless something terribly wrong is going on on your app, 10
seconds to load a page are definitely tuo much. A normal-complexity web app
usually takes 50-60 ms to load

Il 08 mag 2017 13:43, "Junjun.Li" <notifications@github.com> ha scritto:

**Comment by leonelcamara** [comment]
Probably a lock is causing this problem. Try calling session.forget(response) as soon as you can if you don't need to save things in the session.

**Comment by kirsn** [comment]
@snakeli .. some questions:
how are you starting web2py (cmd line or web2py dialog), and on which platform (OSX, *nix) is this? 
How big is the data that your client uploads? And are you using the default rocket server, or a different web server setup?
Are you seeing the high CPU soon after starting web2py, or only when the client invokes the server?

**Comment by mdipierro** [comment]
I am closing this since this kind of discussions belong to the baling list.
