### ISSUE TITLE
The integrated web-based debugger is broken with current MASTER branch

### ISSUE THREAD

**Issue by nicozanf** [web2py/web2py#1629]
I've found that the integrated web-based debugger functionality (http://web2py.com/books/default/chapter/29/03/overview?search=debugger#Integrated-web-based-debugger) is broken with current MASTER branch - while it works fine with the current static source.

In particular, adding the lines:

```
from gluon.debug import dbg
dbg.set_trace()
```
 
to the standard Welcome app gives the following traceback (with Python 2.7 and 3.5, too)

<type 'exceptions.AttributeError'> Qdb instance has no attribute 'Frontend'

  File "/home/nicoz/web2py-master.27/gluon/restricted.py", line 216, in restricted
    exec(ccode, environment)
  File "/home/nicoz/web2py-master.27/applications/admin/controllers/debug.py:interact", line 238, in <module>
  File "/home/nicoz/web2py-master.27/gluon/globals.py", line 405, in <lambda>
    self._caller = lambda f: f()
  File "/home/nicoz/web2py-master.27/applications/admin/controllers/debug.py:interact", line 49, in interact
  File "/home/nicoz/web2py-master.27/gluon/debug.py", line 131, in run
    dbg.Frontend.run(self)
AttributeError: Qdb instance has no attribute 'Frontend'
In file: /home/nicoz/web2py-master.27/applications/admin/controllers/debug.py

I've wrote this to Mariano Reingart, and he told me that it looks like a naming collision, and to try to comment the following line (gluon/debug.py:190):

https://github.com/web2py/web2py/blob/master/gluon/debug.py#L190

For example:

# dbg = dbg_debugger

But this didn't work either, giving the traceback:

  File "/home/nicoz/web2py-static.27/gluon/main.py", line 447, in wsgibase
    gluon.debug.dbg.do_debug(mainpyfile=request.folder)
AttributeError: 'module' object has no attribute 'dbg'

**Comment by ilvalle** [comment]
@nicozanf would you mind to check https://github.com/ilvalle/web2py/tree/fix_1629

**Comment by nicozanf** [comment]
Ciao Paolo,

yes, this resolve the problem, with python 2.7 and 3.5, too! 

But unfortunately the resulting layout is missing the "code listing" frame - see the attached screenshots... Is it possible to fix this one also?

Grazie,
Nico

This is the working static version:
![break_ko](https://cloud.githubusercontent.com/assets/2276743/25973409/3bebcf2c-36a4-11e7-8e38-154b7476ac96.png)

This is with your fix on the current MASTER:
![break_ok](https://cloud.githubusercontent.com/assets/2276743/25973408/3be2ad84-36a4-11e7-8819-17c77649aa60.png)

**Comment by ilvalle** [comment]
try now

**Comment by nicozanf** [comment]
YES, this fixes also the missing "code listing" frame. Now it works perfectly, with both python 2.7 and 3.5 on Ubuntu 16.10.

The issue can be closed, at least when the fix will be pulled to the master branch.

Thanks,
Nico
