### ISSUE TITLE
heroku ADAPTERS error

### ISSUE THREAD

**Issue by huangyuku** [web2py/web2py#1635]
I'm looking to use Heroku for deployment of my web2py project. However, when I add 
`from gluon.contrib.heroku import get_db`
`db = get_db(name=None, pool_size=myconf.get('db.pool_size'))`

I get a ticket with the error:

> File "/Users/huangyu/dev/web2py/gluon/contrib/heroku.py", line 10, in <module>
    from pydal.adapters import ADAPTERS, PostgreSQLAdapter
ImportError: cannot import name ADAPTERS

It looks like web2py has moved on from using ADAPTERS? Has that been replaced by 
`@adapters.register_for('postgres')`

But the heroku file has not been updated.

**Comment by leonelcamara** [comment]
@huangyuku Can you check if this fixes your issues? I don't really use heroky.

https://github.com/leonelcamara/web2py/blob/fixheroku/gluon/contrib/heroku.py

**Comment by leonelcamara** [comment]
@huangyuku ping! Can you test:
https://github.com/web2py/web2py/pull/1682

For me, please.
