### ISSUE TITLE
Minor bug in access.py

### ISSUE THREAD

**Issue by tbear** [web2py/web2py#1648]
In 'admin/models/dkaccess.py' there is a (mostly harmless) error in line 55:13.  Specifically, a '-' (minus) where there should be an '=' (assignment operator).

    elif not _config.get('password'):
        ret = False  # Tanny Bear fixed was 'ret - False'.
    elif _config['password'].startswith('pam_user:'):

**Comment by leonelcamara** [comment]
Make a pull request and fix it, you already have everything 👍
