### ISSUE TITLE
remain py2.6 stuff that can be delete

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/web2py#1664]
Here :
https://github.com/web2py/web2py/blob/0d646fa5e7c731cb5c392adf6a885351e77e4903/gluon/import_all.py#L86

py26_deprecated is used before been declared...

Since we drop py2.6 : https://groups.google.com/d/msg/web2py-developers/xz5o_CF4GOo/ZJm0HImTAAAJ

Shall we delete those line??

I send a PR if you take it...

**Comment by leonelcamara** [comment]
Yes please delete those lines, they won't even work because py26_deprecated doesn't exist.

**Comment by BuhtigithuB** [comment]
Done!

**Comment by BuhtigithuB** [comment]
I adjusted comment a bit too...
