### ISSUE TITLE
SQLFORM.factory - Field is already bound to a table

### ISSUE THREAD

**Issue by rpedroso** [web2py/web2py#1672]
**web2py 2.15.0b1**

SQLFORM.factory problem

Put in a controller:

    def index():

        db = DAL('sqlite:memory')

        db.define_table('table1',
                Field('f1'),
                )

        form = SQLFORM.factory(db.table1.f1) 
        return form

This gives an exception:

    (...)

    File "web2py-2.15.0b1/gluon/packages/dal/pydal/objects.py", line 1633, in bind
        'Field %s is already bound to a table' % self.longname)
    ValueError: Field table1.f1 is already bound to a table

Using instead:

    form = SQLFORM.factory(db.table1) 

Doesn't raise any error.

Maybe a pydal issue???

**Comment by rpedroso** [comment]
It's seems to be this pydal commit:
https://github.com/web2py/pydal/commit/fedd0c75ff1f84ce863a8785b31c762d9c3e55af#diff-68220c912f02a03fd8bce58415479334R1642

**Comment by tbellembois** [comment]
I have the same issue.
Removing the lines also solved it.
