### ISSUE TITLE
graph model didn't show the erd like in previous version

### ISSUE THREAD

**Issue by sugizo** [web2py/web2py#1674]
go to http://127.0.0.1:8000/welcome/appadmin/d3_graph_model
graph model didn't show the erd like in previous version :
- relation between table not shown
- table fields shown is stacked with another table name

**Comment by willimoa** [comment]
Hi Sugizo,
There will be differences as the layout approach is different.   Can you specify which tables/fields are causing issues, or add a screen shot please.  
Thanks
Andrew W

**Comment by willimoa** [comment]
HI, I've run welcome and I can see the issue.  Checking it out now.

**Comment by willimoa** [comment]
Fixed.  css file path was incorrect.   Pull Request raised.

**Comment by leonelcamara** [comment]
@mdipierro this can be closed now that #1677 was merged

**Comment by mdipierro** [comment]
Thank you Leonel.
