### ISSUE TITLE
Python 3 compatibility need to retain integer division in sqlhtml.py

### ISSUE THREAD

**Issue by DonaldMcC** [web2py/web2py#1680]
There are two lines currently 408 and 474 in gluon/sqlhtml.py which I believe need to be changed from

        rows = totals / cols
to
        rows = totals // cols
This is only for python 3 to avoid iterating over a float a few lines further down the file - but possibly a more general search for / operators should also be carried out in case there are other similar instances in other files.

**Comment by BuhtigithuB** [comment]
% ag ' / '
scripts/access.wsgi
12:#   WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py

scripts/zip_static_files.py
39:    print 'saved %s KB' % (int(tsave) / 1000.0)

scripts/sessions2trash.py
194:            10 ** 6) / 10 ** 6

scripts/cpdb.py
110:             text) / width)))])

scripts/nginx_scgi.conf
88:                location / {

scripts/setup-web2py-nginx-uwsgi-centos7.sh
163:        location / {
189:        location / {

scripts/setup-web2py-fedora.sh
307:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py
345:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py

scripts/setup-web2py-nginx-uwsgi-ubuntu.sh
75:        location / {
102:        location / {

scripts/setup-web2py-fedora-ami.sh
304:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py
342:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py

scripts/setup-web2py-nginx-uwsgi-centos64.sh
61:        location / {
88:        location / {
% ag ' / '
scripts/access.wsgi
12:#   WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py

scripts/zip_static_files.py
39:    print 'saved %s KB' % (int(tsave) / 1000.0)

scripts/sessions2trash.py
194:            10 ** 6) / 10 ** 6

scripts/cpdb.py
110:             text) / width)))])

scripts/nginx_scgi.conf
88:                location / {

scripts/setup-web2py-nginx-uwsgi-centos7.sh
163:        location / {
189:        location / {

scripts/setup-web2py-fedora.sh
307:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py
345:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py

scripts/setup-web2py-nginx-uwsgi-ubuntu.sh
75:        location / {
102:        location / {

scripts/setup-web2py-fedora-ami.sh
304:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py
342:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py

scripts/setup-web2py-nginx-uwsgi-centos64.sh
61:        location / {
88:        location / {

scripts/setup-web2py-nginx-uwsgi-on-centos.sh
188:  location / {
200:  location / {

scripts/setup-web2py-ubuntu.sh
93:  WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py
124:  WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py

scripts/setup-web2py-centos7.sh
200:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py
240:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py

scripts/setup-web2py-debian-sid.sh
88:  WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py
125:  WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py

scripts/setup-web2py-nginx-uwsgi-opensuse.sh
43:        location / {
66:        location / {

gluon/fileutils.py
197:    """Turns any expression/path into a valid filename. replaces / with
_ and

gluon/validators (copie).py
286:        maxsize: maximum allowed length / size
287:        minsize: minimum allowed length / size
2961:        string) * math.log(alphabet) / 0.6931471805599453  #
math.log(2)
3211:        lastdot: which dot should be used as a filename / extension
separator:
3212:            True means last dot, eg. file.png -> file / png
3213:            False means first dot, eg. file.tar.gz -> file / tar.gz
3304:    forms (str, int, list / tuple), allowing setup of multiple address
ranges::
3638:    forms (str, int, list / tuple), allowing setup of multiple address
ranges::

gluon/tools.py
111:    Class for configuring and sending emails with alternative text /
html
364:                the messages with can be a file name / string or
365:                a list of file names / strings (PEM format)
674:                    self.error = "Something went wrong on certificate /
private key loading: <%s>" % str(e)
1766:                if (now - auth.last_visit).seconds > (auth.expiration
/ 10):
5163:        -32601: ("Method not found", "The method does not exist / is
not available."),
5531:        return T('%d years' + suffix) % int(dt.days / 365)
5535:        return T('%d months' + suffix) % int(dt.days / 30)
5539:        return T('%d weeks' + suffix) % int(dt.days / 7)
5547:        return T('%d hours' + suffix) % int(dt.seconds / 3600)
5551:        return T('%d minutes' + suffix) % int(dt.seconds / 60)
6474:            size = (1.5 * (c - b) / max(a - b, 1) + 1.3)

gluon/contrib/ipaddress.py
1600:              If the mask (portion after the / in the argument) is
given in

gluon/contrib/sms_utils.py
21:    'EinsteinPCS / Airadigm Communications': '@einsteinsms.com',

gluon/contrib/spreadsheet.py
486:            key = 'r%sc%s' % (k / self.cols, k % self.cols)

gluon/contrib/pg8000/core.py
635:    return d_pack(timegm(v.timetuple()) + v.microsecond / 1e6 -
EPOCH_SECONDS)
690:    seconds = v.microseconds / 1000.0 / 1000.0

gluon/contrib/feedparser.py
3026:        year = 100 * int(time.gmtime()[0] / 100) + int(year)

gluon/contrib/markmin/markmin2html.py
1503:        print("%s loops, best of 3: %.3f ms per loop" % (loops, t /
1000 * loops))

gluon/contrib/imageutils.py
48:                    ((self.nx - img.size[0]) / 2, (self.ny -
img.size[1]) / 2))

gluon/contrib/user_agent_parser.py
513:                    "NT 5.2": "Server 2003 / XP x64",

gluon/contrib/memcache/memcache.py
418:        @param time: number of seconds any subsequent set / update
473:        @param time: number of seconds any subsequent set / update
commands
719:                # set_multi supports int / long keys.

gluon/contrib/populate.py
172:                        options, random.randint(0, len(options) - 1) /
2)]
225:                        ids[tablename], random.randint(0, n - 1) / 2)]
233:                        options, random.randint(0, len(options) - 1) /
2)]

gluon/contrib/timecollect.py
37:                perc = delta / total_time * 100

gluon/contrib/redis_scheduler.py
382:        limit = len(all_workers) * (50 / (len(wkgroups) or 1))
451:                                          timeout=60 /
len(self.group_names))

gluon/contrib/redis_cache.py
181:        bucket_key = "%s:%s" % (cache_set_key, expire_at / 60)
188:        # print 'that will expire on %s' % (bucket_key,
time.ctime(((expire_at / 60) + 1) * 60))
197:        p.expireat(bucket_key, ((expire_at / 60) + 1) * 60)

gluon/contrib/fpdf/ttfonts.py
304:        scale = 1000 / float(unitsPerEm)
370:        self.stemV = 50 + int(pow((usWeightClass / 65.0),2))
377:        self.italicAngle = self.read_short() + self.read_ushort() /
65536.0
612:            # cmap - Character to glyph mapping - Format 4 (MS / )

gluon/contrib/fpdf/fpdf.py
104:            self.k = 72 / 25.4
106:            self.k = 72 / 2.54
115:        self.fw = self.fw_pt / self.k
116:        self.fh = self.fh_pt / self.k
130:        self.w = self.w_pt / self.k
131:        self.h = self.h_pt / self.k
133:        margin = 28.35 / self.k
136:        self.c_margin = margin / 10.0
138:        self.line_width = .567 / self.k
397:            w = w * self.font_stretching / 100.0
398:        return w * self.font_size / 1000.0
778:                        adj = -(self.ws * self.k) * 1000 /
self.font_size_pt
870:                l += self.get_string_width(c, True) /
self.font_size*1000.0
955:                l += self.get_string_width(c, True) /
self.font_size*1000.0
1724:            self.fw = self.fw_pt / self.k
1725:            self.fh = self.fh_pt / self.k
1737:            self.w = self.w_pt / self.k
1738:            self.h = self.h_pt / self.k
1982:        narrow = w / 3.0

gluon/contrib/fpdf/html.py
64:            return int(length[:-1]) * total / 101.0
66:            return int(length) / 6.0
353:            self.h = size / 72.0*25.4

gluon/contrib/fpdf/template.py
161:            ##m_k = 72 / 2.54
226:        ##m_k = 72 / 2.54

gluon/contrib/pyaes/README.md
196:decrypted = decrypter.feed(ciphertext[:len(ciphertext) / 2])
197:decrypted += decrypter.feed(ciphertext[len(ciphertext) / 2:])

gluon/contrib/pymysql/connections.py
170:        return float(self.seed1) / float(self.max_value)
1450:                    # This behavior is different from TEXT / BLOB.

gluon/contrib/pymysql/tests/test_issues.py
441:        """ Test binary / geometry types. """

gluon/contrib/autolinks.py
20:Microsoft PowerPoint 2007 / 2010 (.PPTX)

gluon/contrib/pypyodbc.py
450:        # only iODBC uses utf-32 / UCS4 encoding data, others normally
use utf-16 / UCS2
633:Types mapping, applicable for 32-bit and 64-bit Linux / Windows / Mac
OS X.

gluon/contrib/pysimplesoap/xmlsec.py
103:        # use faster libxml2 / lxml canonicalization function if
available

gluon/contrib/pysimplesoap/client.py
97:        # extract the base directory / url for wsdl relative imports:
105:        # shortcut to print all debugging info and sent / received xml
messages

gluon/contrib/pysimplesoap/helpers.py
44:    # check / append a valid schema if not given:
156:            # extract type information from xml attributes / children:
219:                # not a simple python type / conversion function not
available
223:                # simple / complex type, postprocess later

gluon/rocket.py
1041:        self.grow_threshold = int(max_threads / 10) + 2

gluon/utils.py
159:    128 / 4: 'md5',
160:    160 / 4: 'sha1',
161:    224 / 4: 'sha224',
162:    256 / 4: 'sha256',
163:    384 / 4: 'sha384',
164:    512 / 4: 'sha512',

gluon/authapi_CODE_FOR_UPDATE_USER_GROUPS.py
126:                if (now - auth.last_visit).seconds > (auth.expiration /
10):

gluon/validators.py
285:        maxsize: maximum allowed length / size
286:        minsize: minimum allowed length / size
2956:        string) * math.log(alphabet) / 0.6931471805599453  #
math.log(2)
3206:        lastdot: which dot should be used as a filename / extension
separator:
3207:            True means last dot, eg. file.png -> file / png
3208:            False means first dot, eg. file.tar.gz -> file / tar.gz
3299:    forms (str, int, list / tuple), allowing setup of multiple address
ranges::
3633:    forms (str, int, list / tuple), allowing setup of multiple address
ranges::

gluon/packages/dal/tests/nosql.py
1166:            self.assertEqual(db(db.tt.aa / 3 == 0).select(db.tt.bb)[0].bb,
uv[2])

gluon/packages/dal/tests/sql.py
1249:            self.assertEqual(db(db.tt.aa / 3 == 0).select(db.tt.bb)[0].bb,
uv[2])

gluon/packages/dal/pydal/dialects/base.py
405:        return '(%s / %s)' % (

gluon/packages/dal/pydal/contrib/mockimaplib.py
103:        result[1][0] -> int last message id / mailbox lenght

gluon/packages/dal/pydal/adapters/mongo.py
83:            self.server_version[0] + self.server_version[1] / 10.0)

gluon/widget.py
577:            value = self.p0[1:] + [10 + 90.0 / math.sqrt(1 +
data.count('\n'))]

gluon/cache.py
304:                    Windows doesn't allow \ / : * ? "< > | in filenames.

gluon/scheduler.py
1334:        limit = len(all_workers) * (50 / (len(wkgroups) or 1))

gluon/sqlhtml.py
408:        rows = totals / cols
474:        rows = totals / cols

gluon/authapi (copie).py
126:                if (now - auth.last_visit).seconds > (auth.expiration /
10):

gluon/authapi.py
118:                if (now - auth.last_visit).seconds > (auth.expiration /
10):

handlers/cgihandler.py
15:    ScriptAlias / /path/to/cgihandler.py/
20:  ScriptAlias / /users/www-data/web2py/cgihandler.py/

scripts/setup-web2py-nginx-uwsgi-on-centos.sh
188:  location / {
200:  location / {

scripts/setup-web2py-ubuntu.sh
93:  WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py
124:  WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py

scripts/setup-web2py-centos7.sh
200:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py
240:  WSGIScriptAlias / /opt/web-apps/web2py/wsgihandler.py

scripts/setup-web2py-debian-sid.sh
88:  WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py
125:  WSGIScriptAlias / /home/www-data/web2py/wsgihandler.py

scripts/setup-web2py-nginx-uwsgi-opensuse.sh
43:        location / {
66:        location / {

gluon/fileutils.py
197:    """Turns any expression/path into a valid filename. replaces / with
_ and

gluon/validators (copie).py
286:        maxsize: maximum allowed length / size
287:        minsize: minimum allowed length / size
2961:        string) * math.log(alphabet) / 0.6931471805599453  #
math.log(2)
3211:        lastdot: which dot should be used as a filename / extension
separator:
3212:            True means last dot, eg. file.png -> file / png
3213:            False means first dot, eg. file.tar.gz -> file / tar.gz
3304:    forms (str, int, list / tuple), allowing setup of multiple address
ranges::
3638:    forms (str, int, list / tuple), allowing setup of multiple address
ranges::

gluon/tools.py
111:    Class for configuring and sending emails with alternative text /
html
364:                the messages with can be a file name / string or
365:                a list of file names / strings (PEM format)
674:                    self.error = "Something went wrong on certificate /
private key loading: <%s>" % str(e)
1766:                if (now - auth.last_visit).seconds > (auth.expiration
/ 10):
5163:        -32601: ("Method not found", "The method does not exist / is
not available."),
5531:        return T('%d years' + suffix) % int(dt.days / 365)
5535:        return T('%d months' + suffix) % int(dt.days / 30)
5539:        return T('%d weeks' + suffix) % int(dt.days / 7)
5547:        return T('%d hours' + suffix) % int(dt.seconds / 3600)
5551:        return T('%d minutes' + suffix) % int(dt.seconds / 60)
6474:            size = (1.5 * (c - b) / max(a - b, 1) + 1.3)

gluon/contrib/ipaddress.py
1600:              If the mask (portion after the / in the argument) is
given in

gluon/contrib/sms_utils.py
21:    'EinsteinPCS / Airadigm Communications': '@einsteinsms.com',

gluon/contrib/spreadsheet.py
486:            key = 'r%sc%s' % (k / self.cols, k % self.cols)

gluon/contrib/pg8000/core.py
635:    return d_pack(timegm(v.timetuple()) + v.microsecond / 1e6 -
EPOCH_SECONDS)
690:    seconds = v.microseconds / 1000.0 / 1000.0

gluon/contrib/feedparser.py
3026:        year = 100 * int(time.gmtime()[0] / 100) + int(year)

gluon/contrib/markmin/markmin2html.py
1503:        print("%s loops, best of 3: %.3f ms per loop" % (loops, t /
1000 * loops))

gluon/contrib/imageutils.py
48:                    ((self.nx - img.size[0]) / 2, (self.ny -
img.size[1]) / 2))

gluon/contrib/user_agent_parser.py
513:                    "NT 5.2": "Server 2003 / XP x64",

gluon/contrib/memcache/memcache.py
418:        @param time: number of seconds any subsequent set / update
473:        @param time: number of seconds any subsequent set / update
commands
719:                # set_multi supports int / long keys.

gluon/contrib/populate.py
172:                        options, random.randint(0, len(options) - 1) /
2)]
225:                        ids[tablename], random.randint(0, n - 1) / 2)]
233:                        options, random.randint(0, len(options) - 1) /
2)]

gluon/contrib/timecollect.py
37:                perc = delta / total_time * 100

gluon/contrib/redis_scheduler.py
382:        limit = len(all_workers) * (50 / (len(wkgroups) or 1))
451:                                          timeout=60 /
len(self.group_names))

gluon/contrib/redis_cache.py
181:        bucket_key = "%s:%s" % (cache_set_key, expire_at / 60)
188:        # print 'that will expire on %s' % (bucket_key,
time.ctime(((expire_at / 60) + 1) * 60))
197:        p.expireat(bucket_key, ((expire_at / 60) + 1) * 60)

gluon/contrib/fpdf/ttfonts.py
304:        scale = 1000 / float(unitsPerEm)
370:        self.stemV = 50 + int(pow((usWeightClass / 65.0),2))
377:        self.italicAngle = self.read_short() + self.read_ushort() /
65536.0
612:            # cmap - Character to glyph mapping - Format 4 (MS / )

gluon/contrib/fpdf/fpdf.py
104:            self.k = 72 / 25.4
106:            self.k = 72 / 2.54
115:        self.fw = self.fw_pt / self.k
116:        self.fh = self.fh_pt / self.k
130:        self.w = self.w_pt / self.k
131:        self.h = self.h_pt / self.k
133:        margin = 28.35 / self.k
136:        self.c_margin = margin / 10.0
138:        self.line_width = .567 / self.k
397:            w = w * self.font_stretching / 100.0
398:        return w * self.font_size / 1000.0
778:                        adj = -(self.ws * self.k) * 1000 /
self.font_size_pt
870:                l += self.get_string_width(c, True) /
self.font_size*1000.0
955:                l += self.get_string_width(c, True) /
self.font_size*1000.0
1724:            self.fw = self.fw_pt / self.k
1725:            self.fh = self.fh_pt / self.k
1737:            self.w = self.w_pt / self.k
1738:            self.h = self.h_pt / self.k
1982:        narrow = w / 3.0

gluon/contrib/fpdf/html.py
64:            return int(length[:-1]) * total / 101.0
66:            return int(length) / 6.0
353:            self.h = size / 72.0*25.4

gluon/contrib/fpdf/template.py
161:            ##m_k = 72 / 2.54
226:        ##m_k = 72 / 2.54

gluon/contrib/pyaes/README.md
196:decrypted = decrypter.feed(ciphertext[:len(ciphertext) / 2])
197:decrypted += decrypter.feed(ciphertext[len(ciphertext) / 2:])

gluon/contrib/pymysql/connections.py
170:        return float(self.seed1) / float(self.max_value)
1450:                    # This behavior is different from TEXT / BLOB.

gluon/contrib/pymysql/tests/test_issues.py
441:        """ Test binary / geometry types. """

gluon/contrib/autolinks.py
20:Microsoft PowerPoint 2007 / 2010 (.PPTX)

gluon/contrib/pypyodbc.py
450:        # only iODBC uses utf-32 / UCS4 encoding data, others normally
use utf-16 / UCS2
633:Types mapping, applicable for 32-bit and 64-bit Linux / Windows / Mac
OS X.

gluon/contrib/pysimplesoap/xmlsec.py
103:        # use faster libxml2 / lxml canonicalization function if
available

gluon/contrib/pysimplesoap/client.py
97:        # extract the base directory / url for wsdl relative imports:
105:        # shortcut to print all debugging info and sent / received xml
messages

gluon/contrib/pysimplesoap/helpers.py
44:    # check / append a valid schema if not given:
156:            # extract type information from xml attributes / children:
219:                # not a simple python type / conversion function not
available
223:                # simple / complex type, postprocess later

gluon/rocket.py
1041:        self.grow_threshold = int(max_threads / 10) + 2

gluon/utils.py
159:    128 / 4: 'md5',
160:    160 / 4: 'sha1',
161:    224 / 4: 'sha224',
162:    256 / 4: 'sha256',
163:    384 / 4: 'sha384',
164:    512 / 4: 'sha512',

gluon/authapi_CODE_FOR_UPDATE_USER_GROUPS.py
126:                if (now - auth.last_visit).seconds > (auth.expiration /
10):

gluon/validators.py
285:        maxsize: maximum allowed length / size
286:        minsize: minimum allowed length / size
2956:        string) * math.log(alphabet) / 0.6931471805599453  #
math.log(2)
3206:        lastdot: which dot should be used as a filename / extension
separator:
3207:            True means last dot, eg. file.png -> file / png
3208:            False means first dot, eg. file.tar.gz -> file / tar.gz
3299:    forms (str, int, list / tuple), allowing setup of multiple address
ranges::
3633:    forms (str, int, list / tuple), allowing setup of multiple address
ranges::

gluon/packages/dal/tests/nosql.py
1166:            self.assertEqual(db(db.tt.aa / 3 == 0).select(db.tt.bb)[0].bb,
uv[2])

gluon/packages/dal/tests/sql.py
1249:            self.assertEqual(db(db.tt.aa / 3 == 0).select(db.tt.bb)[0].bb,
uv[2])

gluon/packages/dal/pydal/dialects/base.py
405:        return '(%s / %s)' % (

gluon/packages/dal/pydal/contrib/mockimaplib.py
103:        result[1][0] -> int last message id / mailbox lenght

gluon/packages/dal/pydal/adapters/mongo.py
83:            self.server_version[0] + self.server_version[1] / 10.0)

gluon/widget.py
577:            value = self.p0[1:] + [10 + 90.0 / math.sqrt(1 +
data.count('\n'))]

gluon/cache.py
304:                    Windows doesn't allow \ / : * ? "< > | in filenames.

gluon/scheduler.py
1334:        limit = len(all_workers) * (50 / (len(wkgroups) or 1))

gluon/sqlhtml.py
408:        rows = totals / cols
474:        rows = totals / cols

gluon/authapi (copie).py
126:                if (now - auth.last_visit).seconds > (auth.expiration /
10):

gluon/authapi.py
118:                if (now - auth.last_visit).seconds > (auth.expiration /
10):

handlers/cgihandler.py
15:    ScriptAlias / /path/to/cgihandler.py/
20:  ScriptAlias / /users/www-data/web2py/cgihandler.py/

**Comment by BuhtigithuB** [comment]
Silver search of ' / '

Sorry if it confused you...
