### ISSUE TITLE
a bug when installing plugin :"unable to install plugin***" with python 3.6 and web2py 2.15.1

### ISSUE THREAD

**Issue by liuyibing45** [web2py/web2py#1684]
I want to install a plugin with the admin with python 3.6 and web2py 2.15.1. However when I press the upload button, a session.flash "unable to install plugin ***" occurs. After a hard debugging I find a solution.
I modify the fix_newlines() function in /gloun/fileutils.py
```
def fix_newlines(path):
    regex = re.compile(r'''(\r|\r|)''')
    for filename in listdir(path, '.*\.(py|html)$', drop=False):
        rdata = read_file(filename, 'rb')
        # wdata = regex.sub('\n', rdata)  ## original code. rdata is bytes, this line will raise type error in python 3.6
        wdata = regex.sub('\n', rdata.decode('utf8')).encode('utf8')  ## the code I modify
        if wdata != rdata:
            write_file(filename, wdata, 'wb')
```
the above code fix the bug.

**Comment by leonelcamara** [comment]
This needs more investigation because if I test fix_newlines by itself it doesn't break under py 3.6

**Comment by liuyibing45** [comment]
@leonelcamara ,under python3.6 the original code `wdata = regex.sub('\n', rdata)` will raise an error. Because rdata is byte, '\n' is str.

**Comment by ilvalle** [comment]
@liuyibing45 according to https://codecov.io/gh/web2py/web2py/src/master/gluon/fileutils.py#L413 `fix_newlines` is not under any unittest. I'd suggest to publish a PR with the proposed changes with a specific unittest. Mind that you can use `to_bytes` and similar functions already defined in `gluon/_compat` without delving into the verbose `.decode` or `.encode` methods.

**Comment by leonelcamara** [comment]
@liuyibing45 ok then to me the bug is that we're reading the file in binary mode when we should be reading it in text mode.

**Comment by liuyibing45** [comment]
@leonelcamara ,thanks, changing reading mode from binary to text will fix the bug.
@ilvalle

**Comment by leonelcamara** [comment]
@liuyibing45 no need to close issues like this, it will be closed automatically if my fix is merged. It's better to leave it open in case my fixes do not get merged.

**Comment by liuyibing45** [comment]
@leonelcamara ,ok,thank you.
