### ISSUE TITLE
PEP8 fixes break functionality

### ISSUE THREAD

**Issue by bjones1** [web2py/web2py#1685]
**The problem**: in https://github.com/web2py/web2py/commit/590de9c8900ac1d5da58758730ad9c805c7e8429#diff-1e4f774e944ce88607f6bc3debe6f0b7R2770, PEP8 fixes transformed `if self.crypt.salt == True:` to `if self.crypt.salt:`. However, per the [docs for the function](https://github.com/web2py/web2py/blame/master/gluon/validators.py#L2750), "If a salt is specified use it, if salt is True, set salt to uuid (this should all be backward compatible)." This change means a specified `salt` will **never** be used. 

**The fix**: revert this change, leaving the line as `if self.crypt.salt == True:`, with perhaps a comment on the necessity of this syntax.

**Notes**: Based on [PEP8](https://www.python.org/dev/peps/pep-0008/#function-annotations) (see the recommendation just above this anchor), there is no way to write this nicely.

**Comment by leonelcamara** [comment]
@BuhtigithuB please no more automated PEP8 fixes

**Comment by bjones1** [comment]
Thanks for the quick fix!
