### ISSUE TITLE
a bug of translation breaks the menu hyperlink of a new simple application.

### ISSUE THREAD

**Issue by liuyibing45** [web2py/web2py#1687]
Python 3.6, web2py 2.15.1, chrome.
For testing the new version of web2py 2.15.1, I create a new simple application through the administrative interface. I find a very strange bug. When the application name length is shorter than 4 (for example 'soma') and  the T.accepted_language is zh-cn,the index.html of the application looks like the following 
![20170716001839](https://user-images.githubusercontent.com/25625873/28240997-44274a02-69be-11e7-9d32-8ee4927f8af9.png)

the caret symbol disappear and there is no child element of the hyberlink as unusual . After some debugging, I guess the language translation result in this bug when the request language is zh-cn. I am not familiar with gluon/languages.py and gluon/compileapp.py. 

You can recurrent the bug under web2py 2.15.1 with the following steps:
1. create a new simple application whose name is 'soma' or any other string whose length is shorter than 4.
2. add one line code to the index function of the default controller
```
def index():
    T.force('zh-cn') ## add this line to force your T.accepted_language to zh-cn
    response.flash = T("Hello World") 
    return dict(message=T('Welcome to web2py!'))
```
Could anyone help to fix this bug.

**Comment by leonelcamara** [comment]
This is really weird.

What's happening is that the

    <script src="{{=URL('static','js/web2py-bootstrap3.js')}}"></script>

In layout.html is being rendered like this:

    <script src="/soma/static/js/web2py-bootstrap3.js"></scrip</script>

Note the "</scrip", because of that web2py-bootstrap3.js is not running so your menu doesn't work properly.

I have no idea why this happens at this time.

**Comment by leonelcamara** [comment]
This is really weird.

What's happening is that the

    <script src="{{=URL('static','js/web2py-bootstrap3.js')}}"></script>

In layout.html is being rendered like this:

    <script src="/soma/static/js/web2py-bootstrap3.js"></scrip

Note the "</scrip", because of that web2py-bootstrap3.js is not running so your menu doesn't work properly. In fact the HTML you get in the browser ends right there, so you don't even close the <body> and <html> tag like you should.  

I have no idea why this happens at this time. Maybe a rocket bug.

**Comment by liuyibing45** [comment]
@leonelcamara , thank you very much. Your work really fix the weird bug.
