### ISSUE TITLE
ImportError: No module named fileutils w/ routes.py

### ISSUE THREAD

**Issue by misl6** [web2py/web2py#1688]
Hi,
All was working fine on my previous w2p install, then I just migrated all the environment to another server w/ ubuntu 16.04, nginx/1.10.3 and uwsgi 2.0.15.

(Tested on web2py 2.15.1) 

If routes.py is available in the web2py folder I'm having this error:
`added /home/www-data/web2py/ to pythonpath.
mounting wsgihandler:application on /
Traceback (most recent call last):
  File "/home/www-data/web2py/wsgihandler.py", line 29, in <module>
    import gluon.main
  File "/home/www-data/web2py/gluon/main.py", line 121, in <module>
    load_routes()
  File "/home/www-data/web2py/gluon/rewrite.py", line 379, in load
    load(routes, appname)
  File "/home/www-data/web2py/gluon/rewrite.py", line 319, in load
    exec(data, symbols)
  File "<string>", line 21, in <module>
ImportError: No module named fileutils
unable to load app 0 (mountpoint='/') (callable not found or import error)
`

Seems that something is breaking the import.

I'm going to test it with a previous version of web2py in a few hours

**Comment by leonelcamara** [comment]
Can't really reproduce this. If you are importing fileutils in your routes.py make sure you import it from gluon. e.g: from gluon import fileutils

**Comment by misl6** [comment]
Tested the same environment (Ubuntu 16.04 , nginx 1.10.3, uwsgi 2.0.15) with a hard copy of my old web2py installation (2.12.x) and all is working fine.

I will investigate tomorrow about the 2.15.1 (related) issue

**Comment by sherdim** [comment]
The same error (uWSGI 2.0.15, web2py 2.15.1)
after update from  2.14.6 

the error was in old web2py\applications\welcome\routes.example.py
remedy:
change to new one with 
`import gluon.fileutils`

or remove routes.py from your app folder

**Comment by venkatshukla** [comment]
Hi @sherdim @mdipierro  , I am unable to get it to work! I have my routes.py inside web2py base directory. I want to set default application using routes.py.

Web2py Version 2.17.2-stable+timestamp.2018.10.06.18.54.02

`from gluon.fileutils import abspath

routers = dict(
    BASE=dict(
        default_application='MY_APP',
    ),
)`
