### ISSUE TITLE
Issue when del_membership 

### ISSUE THREAD

**Issue by josedesoto** [web2py/web2py#1689]
Function del_membership in authapi.py:

If membership is updated by admin for example, to another user. Self admin user membeship is updated too.

The line:
```
if group_id in self.user_groups: 
 del self.user_groups[group_id]
```

Should be change to

```
if group_id in self.user_groups and user_id == self.user_id: del self.user_groups[group_id]:
 del self.user_groups[group_id]
```

Doing a pull request...

**Comment by josedesoto** [comment]
PR done: https://github.com/web2py/web2py/pull/1690

**Comment by mdipierro** [comment]
thanks!
