### ISSUE TITLE
websocket_messaging in Python 3

### ISSUE THREAD

**Issue by hirolau** [web2py/web2py#1696]
I ran into 3 problems when trying to get WebSockets working on Py3:

1.  `import gluon.utils` failed.
2. Strings were sometimes bytecode, causing mismatches of groups.
3. function `to_native` was unavailable.

For 1) All I had to was to copy the file to web2py root and run from there. Maybe a documentation change would be sufficient?

For 2) I changed line 144 and 145 in the PostHandler post function from:

```
message = self.request.arguments['message'][0]
group = self.request.arguments.get('group', ['default'])[0]
```

to:

```
message = self.request.arguments['message'][0].decode(encoding='UTF-8')
group = self.request.arguments.get('group', ['default'])[0].decode(encoding='UTF-8')
```
The log message on hello world example went from  `MESSAGE to b'mygroup':b'Hello World'` to `MESSAGE to mygroup:Hello World`.

For 3) only an additional import was required: `from gluon._compat import to_native`. Then things ran smoothly.

`Version 2.15.2-stable+timestamp.2017.07.19.12.18.41`

**Comment by leonelcamara** [comment]
Can you submit a pull request, making sure it works with py2 too of course?

**Comment by hirolau** [comment]
I will try. Trying to read up best practices on writing py2/py3 compatible code...
