### ISSUE TITLE
Error with autocomplete in version 2.15.2

### ISSUE THREAD

**Issue by domezzzzx** [web2py/web2py#1699]
Versión: web2py.exe para windows 2.15.2-stable+timestamp.2017.07.19.12.18.41
Update all js in the target application with 2.15.2 of welcome
Tested in browsers: Firefox and Chrome.

When entering data in the autocomplete field, the candidate values are not displayed.
When you enter, it indicates an invalid value.
And an image in transparent format appears and disappears from the first part of the displayed panel.
The panel, is to insert record, invoked by the (+) button of a sqlform.grid.
It worked correctly in version 2.14.6 and 2.15.1
This problem occurs in a panel that has been running for months, and has not had updates.

Regards.

**Comment by leonelcamara** [comment]
I changed autocomplete due to a security issue with the previous version. In my tests it worked fine using appadmin which does use the grid. Can you give me a sample application?

**Comment by domezzzzx** [comment]
Hi Leonel
Sorry for the delay.
I send imagen panel with problem, noting also, superimposed image.

![panel](https://user-images.githubusercontent.com/30487405/28694969-ccd9a8f2-7302-11e7-8555-74d24b89a4e1.jpg)

[objetos.zip](https://github.com/web2py/web2py/files/1181436/objetos.zip)

**Comment by leonelcamara** [comment]
@domezzzzx Thanks, looking at your sample code, I managed to reproduce the bug which happens when user_signature is True on the grid. I'm investigating.

**Comment by domezzzzx** [comment]
Ok Leonel.
With user_signature=True bypassed the problem....con la URL exposed.
Greetings, from Montevideo, Uruguay.
