### ISSUE TITLE
Can't open Graph model after upgrading to 2.15.2

### ISSUE THREAD

**Issue by Holmes70** [web2py/web2py#1706]
I just upgraded to 2.15.2 from 2.14.6 and after correcting my DAL-constructor to entity_quoting set to False, the PostgreSQL DB runs just fine...except for the graph model. I just get 
> invalid function (appadmin/d3_graph_model)

when I call it. I can't seem to find any more enlightening log-entries for this. Sorry. Any ideas, what to do?

Regards,
Oliver Holmes

**Comment by leonelcamara** [comment]
How did you update? Was the admin application updated too?

**Comment by Holmes70** [comment]
I unzipped the source over my installation. How must I go about to update appadmin?

**Comment by Holmes70** [comment]
Aha! Got it. Now I overwrote my apps appadmin.py with the admins appadmin.py, and now it won't throw the error. Just got a blank screen now :D

**Comment by BuhtigithuB** [comment]
Close your issue then!!

:)

**Comment by Holmes70** [comment]
Sorry, I don't believe a blank screen is what the model should look like ;)
Any thoughts or pointers?

**Comment by willimoa** [comment]
I just downloaded 2.15.2 and then opened Welcome in the appadmin and I can see the auth tables in the graph model.  Does that work for you ?     I think the problem is that it is expecting "db".   Your database is probably not called "db".   db is referred to elsewhere, but after calling get_databases.   I'll have a look.

**Comment by Holmes70** [comment]
Again, everything works fine except for the model thingy. I could very well do without as I only have 15 tables. But a bug is a bug and should be reported, until it turns out to be a case of BDU (brain dead user, namely me).

**Comment by willimoa** [comment]
I was asking if the graph model button works fine in the Welcome app?

**Comment by Holmes70** [comment]
Opps, sorry. Yes it does. Quite the relief. My applications db name is db. Here is the relating code:
`    db = DAL(myconf.take('db.uri'),
             pool_size=myconf.take('db.pool_size', cast=int),
             check_reserved=['all'],
             migrate=True,
             fake_migrate=False,
	     entity_quoting=False)`

**Comment by willimoa** [comment]
Well that's interesting.  It should work then.   But there is an issue in that it expects "db" which is not always the case.
Can you show at least one table in your db ?

**Comment by Holmes70** [comment]
Here's what the old model did with my tables (I manually cropped the "system tables"):
![datenmodell](https://user-images.githubusercontent.com/17042955/28863431-3248a840-7769-11e7-89cc-cea7f4e57d2d.png)

**Comment by leonelcamara** [comment]
Have you updated views/appadmin.html with the one from the new welcome?

**Comment by Holmes70** [comment]
Well, of course not. Which leads to me closing this ticket and apologizing profusely for wasting everyones time. As I stated before, cause is BDU.

**Comment by willimoa** [comment]
I'll raise another one to fix the "db" error.  Not a (complete) waste of time :)
