### ISSUE TITLE
Strange framework error after updating to 2.15.2

### ISSUE THREAD

**Issue by tB0nE** [web2py/web2py#1707]
Since switching over my website to web2py 2.15.2, which involved upgrading my Python to 2.7, and installing the latest version of mod_wsgi (4.5.17), I have been getting the strange error below. The framework is a bit out of my knowledge, but it appears to be related to wsgi, and trying to remove something that is already not there. I would suggest first checking to see if it exists, but honestly I don't know what that stuff is doing. It doesn't seem to be breaking anything on the site, that I can tell, but obviously I would prefer if there were no errors!

Below is the full error ticket:

Version
web2py™	Version 2.15.2-stable+timestamp.2017.07.19.12.18.41

Traceback (most recent call last):
  File "/opt/web-apps/web2py/gluon/main.py", line 434, in wsgibase
    session.connect(request, response)
  File "/opt/web-apps/web2py/gluon/globals.py", line 956, in connect
    session_pickled = pickle.dumps(self, pickle.HIGHEST_PROTOCOL)
  File "/opt/web-apps/web2py/gluon/packages/dal/pydal/objects.py", line 2946, in __getstate__
    del ret['fields']
KeyError: 'fields'

In file: Framework
1.

**Comment by leonelcamara** [comment]
Can you clear your sessions and see if you still have the problem?

**Comment by tB0nE** [comment]
After reading issue #1706, I decided to remove the gluon directory on my server and replace it with the latest, and it appears the errors are gone. Looks like the upgrade got a bit messed up. Problem solved!
