### ISSUE TITLE
Error with Reading/Updating List:References in web2py 2.15.2 from/to database

### ISSUE THREAD

**Issue by Jhleite** [web2py/web2py#1711]
I have just updated to web2py 2.15.2 and my site www.holidaysenses.com became unstable (unusable).

Line codes like:
image = db(db.intro_lifestyles.tourism_segment_id == segment.id).select().first()
or 
image = db(db.intro_regions.region_id == region.id).select().first()

where db.intro_lifestyles.tourism_segment_id and db.intro_regions.region_id are List:references with only one element each to tables "segment" and "region" respectively raise the following error:

File "/home/www-data/web2py/gluon/packages/dal/pydal/helpers/methods.py", line 95, in bar_encode
    return '|%s|' % '|'.join(bar_escape(item) for item in items if str(item).strip())
TypeError: 'long' object is not iterable

The site was working fine before...

**Comment by BuhtigithuB** [comment]
Please come over google group web2py-users for such kind of question and
help...

**Comment by Jhleite** [comment]
I have placed this question in google group web2py-users as asked.
I'll wait for further developments... its really critical

**Comment by leonelcamara** [comment]
@Jhleite can you provide a minimal application with this problem?  
  
Right now I'm suspecting that you changed a field which was a reference to a list:reference, I don't think that DAL migrations can deal with field type changes automatically.

**Comment by Jhleite** [comment]
I Didn't do anything just updated the web2py version!!!

Here is the code:

MODELS SNAPSHOT:

db.define_table('tourism_segment',
    Field('segment', label=T('Lifestyle Segment')),
    format='%(segment)s')

db.tourism_segment.segment.requires = IS_NOT_IN_DB(db, db.tourism_segment.segment)

db.define_table('region',
    Field('name', label=T('Region Name')),
    format='%(name)s')

db.region.name.requires = IS_NOT_IN_DB(db, db.region.name)

db.define_table('intro_lifestyles',
    Field('field_nr', 'integer', label=T('Lifestyle order')),
    Field('tourism_segment_id', 'list:reference tourism_segment', label=T('Lifestyle')),
    Field('photo', 'upload', autodelete=True, label=T('Photo')),
    Field('thumbnail', 'upload', autodelete=True, label=T('Thumbnail'))
    )

db.intro_lifestyles.tourism_segment_id.requires = IS_IN_DB(db, 'tourism_segment.id', '%(segment)s', multiple=False)
#db.intro_lifestyles.tourism_segment_id.widget   = rhmultiselect_widget
db.intro_lifestyles.tourism_segment_id.widget   = SQLFORM.widgets.multiple.widget

thumbnail = (330, 205)
db.intro_lifestyles.thumbnail.compute = lambda row: SMARTHUMB(row.photo, thumbnail, True, 'thumbnail')

#---------------------------------------------------------------------
# Table that defines intro page regions content
#---------------------------------------------------------------------
db.define_table('intro_regions',
    Field('field_nr', 'integer', label=T('Region order')),
    Field('region_id', 'list:reference region', label=T('Region')),
    Field('show_level', label=T('Show level'), requires=IS_IN_SET(['High', 'Low', 'Hide'])),
    Field('photo', 'upload', autodelete=True, label=T('Photo')),
    Field('photo_small', 'upload', autodelete=True, label=T('Photo Small')),
    Field('thumbnail', 'upload', autodelete=True, label=T('Thumbnail'))
    )

db.intro_regions.region_id.requires             = IS_IN_DB(db, 'region.id', '%(name)s', multiple=False)
#db.intro_regions.region_id.widget               = rhmultiselect_widget
db.intro_regions.region_id.widget               = SQLFORM.widgets.multiple.widget

photo_small = (660, 400)
db.intro_regions.photo_small.compute = lambda row: SMARTHUMB(row.photo, photo_small, True, 'photo_small')

thumbnail_reg = (165, 130)
db.intro_regions.thumbnail.compute = lambda row: SMARTHUMB(row.photo, thumbnail_reg, True, 'thumbnail')

------------------------------------------------------------------------------------------------
CONTROLLER SNAPSHOT:

# Select header picture and text
    
    if f_segment != 'All Lifestyles':
        segment = db(db.tourism_segment.segment == f_segment).select().first()
        image = db(db.intro_lifestyles.tourism_segment_id == segment.id).select().first() **<-- Crashes here**
         
        header_image = URL('default','download', args=image.photo)
        page_title = f_segment
        page_region = f_region
        
    elif f_segment == 'All Lifestyles' and f_region != 'All Regions':
        
        region = db(db.region.name == f_region).select().first()
        image = db(db.intro_regions.region_id == region.id).select().first() **<-- Crashes here**
         
        header_image = URL('default','download', args=image.photo)
        page_title = f_region
        page_region = ''

**Comment by Jhleite** [comment]
Thanks for your help

**Comment by leonelcamara** [comment]
@Jhleite That's not a minimal application :) Anyway, the problem seems to be that you're using == some_id with a list reference. "==" is not supposed to be used with list:reference that way.
This:  

    image = db(db.intro_lifestyles.tourism_segment_id == segment.id).select().first()
Should be:  

    image = db(db.intro_lifestyles.tourism_segment_id.contains(segment.id)).select().first()

This:  

    image = db(db.intro_regions.region_id == region.id).select().first()
Should be:  

    image = db(db.intro_regions.region_id.contains(region.id)).select().first()

You get the idea.  

The problem here stems in part from the way you named the fields which induces this kind of errors. _tourism_segment_id_ should in fact be named something like _tourism_segments_ otherwise it's easy to think it's just an id and not, in fact, a list.

Note that this is also wrong:  

    db.intro_regions.region_id.requires = IS_IN_DB(db, 'region.id', '%(name)s', multiple=False)
    #db.intro_regions.region_id.widget = rhmultiselect_widget
    db.intro_regions.region_id.widget = SQLFORM.widgets.multiple.widget

It should just be:

    db.intro_regions.region_id.requires = IS_IN_DB(db, 'region.id', '%(name)s', multiple=True)

Otherwise the IS_IN_DB validator won't actually let you use a list.

**Comment by Jhleite** [comment]
Thanks for your help. It was working in the previous versions though.
The contains did the trick.
The multiple = False is correct because I just want an element in each list.
Maybe I misused the List:reference but if it works ok for now.

**Comment by Jhleite** [comment]
I have the same error now when updating a table from a form.
There is something that is not backwards compatible......

Here is a bit of the code:
-------------------------------- CONTROLLER CODE -----------------------------------------------
form = SQLFORM(db.service, this_service, deletable=True)
    
    if form.validate():
        # If selected for deletion
        if form.deleted:
            
            db(db.service.id==this_service.id).delete()
            
            session.flash  = T("Service deleted")
            
            redirect(URL('show_services', args=this_service.operator_id))
            
        else:
            
            update_mean_rating(form.vars)
        
            this_service.update_record(**dict(form.vars))  <--- Blows Here
            
            # Record modification event
            if auth.user.id != None:
                
                db.service_modif.insert(service_id=this_service.id, user_id=auth.user.id, modif_type='Modification')
            
            session.flash = T('Service updated')
             
        redirect(URL('show_service', args=[this_service.id, this_service.operator_id]))

----------------------------------------- MODEL SUMMARY ------------------------------------------

db.define_table('service',
    Field('operator_id', db.operator, label=T('Operator')),
    #Field('name', label=T('Name')),
    #Field('code', 'string', label=T('Service Code')),
    Field('name', label=T('Name'), unique=True),
    Field('code', 'string', label=T('Service Code'), unique=True),
    Field('risk_level', 'integer', label=T('Risk Level')),
    Field('accessible', 'boolean', label=T('Reduced Mobility Friendly'), default=False),
    Field('enabled', 'boolean', label=T('Service active'), default=False),
    Field('blocked', 'boolean', label=T('Service HS blocked'), default=False),
    
    # Prices ranges for services
    Field('selling_price', 'double', label=T('Selling Price')),
    Field('operator_price', 'double', label=T('Operator Price')),
          #compute=lambda row: round(float(row['selling_price']) * (1-float(row['comission'])/100), 2)),
    Field('our_price', 'double', label=T('Our Price')),
          #compute=lambda row: round(float(row['selling_price']) - float(row['operator_price']), 2)),
    
    Field('max_selling_price', 'double', label=T('Max. selling Price')),
    Field('max_operator_price', 'double', label=T('Max. operator Price')),
          #compute=lambda row: round(float(row['max_selling_price']) * (1-float(row['comission'])/100), 2)),
    Field('max_our_price', 'double', label=T('Max. our Price')),
          #compute=lambda row: round(float(row['max_selling_price']) - float(row['max_operator_price']), 2)),
                
    Field('min_infant_price', 'double', label=T('Min. infant Price')),
    Field('max_infant_price', 'double', label=T('Max. infant Price')),
    Field('min_baby_price', 'double', label=T('Min. baby Price')),
    Field('max_baby_price', 'double', label=T('Max. bay Price')),
                
    Field('comission', 'integer', label=T('Comission (%)')),
    
    Field('mean_rating', 'double', label=T('Mean Rating')),
    
    # Meeting point for the service
    Field('address', label=T('Meeting Poiny Address')),
    Field('address2', label=T('M. P. Address Line 2')),
    Field('postal_code', label=T('Postal Code')),
    Field('town', label=T('Town')),
    #country can be a table
    Field('country_id', db.country, label=T('Country')),
    
    Field('host_id', db.contact, label=T('Host')),
    
    # Contact phones for the meeting point
    Field('phone', 'string', label=T('Contact Phone')),
    Field('mobile', 'string', label=T('Contact Mobile')),
    Field('email', label=T('Contact Email')),
    
    Field('gps_latitude', 'double', label=T('GPS Latitude')),
    Field('gps_longitude', 'double', label=T('GPS Longitude')),
    
    Field('tourism_segment_id', 'list:reference tourism_segment', label=T('Lifesyle Segments')),
    Field('region_id', 'list:reference region', label=T('Region')),
    Field('description', 'text', label=T('Description')),
    
    Field('guide_languages_id', 'list:reference transl_available', label=T('Guide Languages')),
    Field('guide_type', label=T('Guide Type'), requires=IS_IN_SET(['Human', 'Electronic'])),
    
    Field('reserv_confirm', label=T('Reservation Confirmation'), requires=IS_IN_SET([T('Automatic'), T('24 hours'), T('48 hours'), T('72 hours')])),
    
    Field('pay_accepted', label=T('Pay type(s) accepted'), requires=[IS_IN_SET(['Cash', 
                                                                               'Wire transf.', 
                                                                               'Credit Card', 
                                                                               'Debit Card',
                                                                               'PayPal'], multiple=True),
                                                                     IS_NOT_EMPTY()]),
                
    Field('voucher_type', label=T('Voucher accepted'), requires=[IS_IN_SET(['Paper', 'Electronic'], multiple=True),
                                                                 IS_NOT_EMPTY()]),
    
    Field('hits', 'integer', label=T('Number of hits'), default=0),
    Field('payed', 'integer', label=T('Number of payments'), default=0),
    Field('rejected', 'integer', label=T('Number of rejections'), default=0),
    Field('cancelled', 'integer', label=T('Number of cancellations'), default=0),
    Field('expired', 'integer', label=T('Payment expirations'), default=0),
    
    Field('ranking', 'double', label=T('Page ranking'), default=0),
    
    Field('week_opportunity', 'boolean'),

    format='%(name)s')


db.service.tourism_segment_id.requires = [IS_IN_DB(db, 'tourism_segment.id', '%(segment)s', multiple=True),
                                          IS_NOT_EMPTY()]
db.service.region_id.requires          = [IS_IN_DB(db, 'region.id', '%(name)s', multiple=False),
                                          IS_NOT_EMPTY()]

db.service.guide_languages_id.requires = [IS_IN_DB(db, 'transl_available.id', '%(language)s', multiple=True),
                                          IS_NOT_EMPTY()]

---------------------------------------------------------------------------------------------

Error message:

 File "/home/www-data/web2py/gluon/packages/dal/pydal/helpers/methods.py", line 95, in bar_encode
    return '|%s|' % '|'.join(bar_escape(item) for item in items if str(item).strip())
TypeError: 'int' object is not iterable

**Comment by leonelcamara** [comment]
@Jhleite you are using IS_IN_DB(db, 'region.id', '%(name)s', multiple=False) as the validator for region_id (which is also a list:reference), since multiple=False you are not getting a list when you submit the region, later when you try to insert the record you get problems as the list:reference field is expecting a list.  
  
This is not a backwards incompatibility problem, this was the previous version letting you create bugs without even noticing them. These would all come back to bite you on the butt.

**Comment by Jhleite** [comment]
So, what you are telling me is that List:reference will have to come always with multiple=True.
I did not understand that from the manual.
So if I want just a single record to be inserted I must restrict that in the selection widget.
Is that right?

**Comment by leonelcamara** [comment]
The thing is what you insert in list:reference should be a list. IS_IN_DB does not transform the input into a list unless you have multiple=True. What you can do is use IS_LIST_OF to turn it into a list anyway. So you would have something like requires = [IS_IN_DB(..., multiple=False), IS_LIST_OF()]

**Comment by Jhleite** [comment]
Thanks Leonel, we'll try that and see, how it works. Thumbs Up.

**Comment by leonelcamara** [comment]
No problem, glad to see more Portuguese entrepreneurs using web2py.
