### ISSUE TITLE
Can not run web2py 2.15.2 in windows with or without ssl

### ISSUE THREAD

**Issue by Jhleite** [web2py/web2py#1712]
I can't seem to run rocket server with ssl in windows (development environment - Aptana Studio).

ERR_SSL_PROTOCOL_ERROR
or
module object has no attribute ssl

Before, without SSL it was giving me a lot of ticket issues with the database initialization.

I'm compleately lost.

C:\web2py\web2py.py -i 192.168.8.100 -p 443 -c server.crt -k server.key -Y
or
C:\web2py\web2py.py -i 192.168.8.100 -p 8000 -Y

**Comment by BuhtigithuB** [comment]
Please come over google group web2py-user for help...

Richard

**Comment by mdipierro** [comment]
Duplicate if https://github.com/web2py/web2py/issues/1716
