### ISSUE TITLE
save_password function error

### ISSUE THREAD

**Issue by angeloc** [web2py/web2py#1730]
I do usually set the web2py password programmatically, this worked in older versions of web2py:

```
python2 -c 'from gluon.main import save_password; save_password("web2py",8000)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "gluon/__init__.py", line 38, in <module>
    from .dal import DAL, Field
  File "gluon/dal.py", line 17, in <module>
    from pydal.migrator import Migrator, InDBMigrator
ImportError: cannot import name InDBMigrator
```

**Comment by leonelcamara** [comment]
@mdipierro ping

**Comment by angeloc** [comment]
It all depends on the fact that web2py was released with a mismatching
pyDAL reference.

Web2py R-2.15.3 uses a class (InDBMigrator) that it's not present in
pyDAL 17.7, the latest pyDAL stable release at the time of writing.

I think that web2py stable must have the pyDAL subrepo pointing to a
tagged release and not to the master tree.


2017-08-09 13:26 GMT+02:00 Leonel Câmara <notifications@github.com>:
> @mdipierro ping
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Profile: http://it.linkedin.com/in/compagnucciangelo

**Comment by pbreit** [comment]
Seems to fix: `git submodule update --init --recursive`
