### ISSUE TITLE
Feature Request: Add bulk update_or_insert

### ISSUE THREAD

**Issue by lben** [web2py/web2py#1734]
The title says it all, I think a simple `insert into table values (c1, c2), (c1, c2)...;` could work. This sql idiom is available on almost all db engines except oracle it seems.

**Comment by leonelcamara** [comment]
@iben this feature request should be in https://github.com/web2py/pydal

**Comment by lben** [comment]
Thank you for your response leonel, I did as you suggested and now there is the issue #493 on pydal repository, I am closing this then.
