### ISSUE TITLE
after_delete set, not iterable

### ISSUE THREAD

**Issue by josedesoto** [web2py/web2py#1745]
Hi,

I have found a strange behavior in **after_delete** (db.mytable._after_delete). "queryset" is the return variable, If I do:
```
print type(queryset)
<Set (`auth_user`.`id` = 18)>
```

```
print queryset.count()
0
```

```
print queryset.select(mytable._id)
nothing
```

```
print queryset.select()
nothing
```

```
print queryset.isempty()
True
```

To get the deleted ID I have to do:
```
print queryset.query.second
18
```

Is this the right be behavior?

**Comment by leonelcamara** [comment]
I don't see the problem.  Obviously the set will be empty if you run a select (which isempty also does) since you already deleted the elements that show up in its query.  
  
If you want to do stuff with the data that is going to be deleted you should use before delete not after.

**Comment by josedesoto** [comment]
thanks leonelcamara. I close the issue.
