### ISSUE TITLE
LOAD() error which result from the python3 map function in gluon/compileapp.py line 208

### ISSUE THREAD

**Issue by liuyibing45** [web2py/web2py#1753]
I am using python3.6 and  web2py 2.15.4. When I use the LOAD() funtion I find an error "can only concatenate list (not "map") to list". After searching and debugging, I find that python3 change the behavior of map function. In python3 map() function return an map object not a list. So the gloun/compileapp line 208 `        other_request.env.path_info = '/' + \
            '/'.join([request.application, c, f] +
                     map(str, other_request.args))` throw out an error. Then I change the ‘map(str, other_request.args)’ to 'list(map(str, other_request.args))'. This make the LOAD() works fine.

**Comment by liuyibing45** [comment]
In addition, I can see that the map() function is used many times in the compileapp.py. Maybe, all the map function should be wrap with list()?

**Comment by leonelcamara** [comment]
No no, don't do **list(map**, that's terrible looking and not that good for performance, just use a list comprehension instead of map.
