### ISSUE TITLE
ignore_field_case=True, is not working in new DAL with psycopg2/Postgresql

### ISSUE THREAD

**Issue by fgalbuqu** [web2py/web2py#1759]
After updating to the newest version I got this problem with table field names with capitalized letters. It  gives an error until I change the field name to all non capitals. See the attached file with the screen error.
[Web2py Issue.pdf](https://github.com/web2py/web2py/files/1288707/Web2py.Issue.pdf)

**Comment by leonelcamara** [comment]
You can workaround this issue by setting entity_quoting=False e.g. DAL(..., entity_quoting=False)

I recommend you close the issue here and open it in https://github.com/web2py/pydal

**Comment by fgalbuqu** [comment]
Thank you Leonel. I will close and open the issue in pydal.
