### ISSUE TITLE
Problem with web2py compilation

### ISSUE THREAD

**Issue by benjaminato** [web2py/web2py#1760]
Hi there

Very simple to show this issue:

1. download latest version of web2py (I use Mac OS version for Normal users)
2. From Admin interface compile and pack the 'Welcome' application that comes as standard with web2py
3. Then from the Admin interface upload and install the compiled 'Welcome' application you have just created (calling a different name of course)
4. When you try to run this compiled application you will get an error e.g. Invalid function or similar

Kind Regards

**Comment by advh67** [comment]
I am trying to use web2py on python3 and when compiling my modules I am always getting an error:
NameError("name 'reload' is not defined",)

If I execute module files on command line I get no errors:
python3 mymodule.py
(blank, no errors)

I noticed the file gluon/appcompile.py has a "reload(module)" in line 351. The "reload" works on python2, but does not work on python3. Am I wrong?
