### ISSUE TITLE
python3.4 : can not concat bytes to str

### ISSUE THREAD

**Issue by JusticeN** [web2py/web2py#1786]
hello,
i start web2py from the source code. 

> Version 2.15.4-stable+timestamp.2017.09.01.22.38.25

after starting i receive a ticket containing this error

> File "...\gluon\html.py", line 950, in _xml
> TypeError: can't concat bytes to str

could someone tell me please what is going wrong ?
thanks in advance

**Comment by leonelcamara** [comment]
Python 3.4 doesn't support % formatting for bytes, hence the problem you're having, is there a reason you can't use a more recent python 3 version?

**Comment by JusticeN** [comment]
Thank for your Reply. Whichpython3 Version are You using for Test ?
Is There any raison not to use the {}.format Syntax. It is also supported since python2.6 ?
See : https://stackoverflow.com/questions/5082452/python-string-formatting-vs-format

**Comment by leonelcamara** [comment]
We're using 3.5 and 3.6 in our continuous integration tests, I guess there's no reason not to use the other syntax in this situation, however I don't think we really want the trouble of supporting python 3.4.  Note that I don't speak for the web2py project, this is just my opinion as a contributor.

**Comment by JusticeN** [comment]
Thanks you for for your help. i just update my python version to 3.6 and it works like a charm :-)

i will just close it because it is not really an issue. thanks for your time.
