### ISSUE TITLE
Autocomplete widgets set request.vars every request

### ISSUE THREAD

**Issue by timnyborg** [web2py/web2py#1788]
See the following lines, where request.vars.ac is set to 1 every call:

https://github.com/web2py/web2py/blob/5975e4767fd7339b5c588305ec9e8eebd9c079c5/gluon/sqlhtml.py#L685

I'm guessing it should be using copy.copy() to set urlvars = request.vars?

**Comment by timnyborg** [comment]
Fixed on my server by:
https://github.com/web2py/web2py/pull/1789

**Comment by leonelcamara** [comment]
@mdipierro this can be closed as the fix was already merged.
