### ISSUE TITLE
current object apparently empty when instantiate validator in a module file

### ISSUE THREAD

**Issue by fiubarc** [web2py/web2py#1791]
Hello, Im having a problem with the validators translation..

 I set requires to a SQLFORM in a module file and then process the form

On validators.py have_current is True but is empty.

```
try:
    from globals import current
    have_current = True
except ImportError:
    have_current = False
```

When function translate(text) call hasattr(current, 'T') return False
```
def translate(text):
    if text is None:
        return None
    elif isinstance(text, (str, unicode)) and have_current:
        if hasattr(current, 'T'):
            return str(current.T(text))
    return str(text)
```
Only work with validators instantiated in models.

Is a bug or I am missing something??
Thanks!

**Comment by dartg** [comment]
Probably that's a typo, you should import `current` from `gluon`, not `globals`:

> from gluon import current

**Comment by fiubarc** [comment]
Now is working correctly.  I always have used 

`from gluon import current`

I realy dont know wich was the fix

Thanks!
