### ISSUE TITLE
Url not found

### ISSUE THREAD

**Issue by ramstein74** [web2py/web2py#1805]
In the code
web2py/applications/admin/static/js/jqueryMultiSelect.js
there is  a reference to this url
Visit http://abeautifulsite.net/notebook.php?article=62

but the url is "not found!!!"

**Comment by amerikan** [comment]
@ramstein74 this is a third-party js plugin that web2py uses. The web2py team can't do much about that. I don't even think that plugin is maintained anymore.

@mdipierro @niphlod this should be closed.
