### ISSUE TITLE
urllib not imported for pydal

### ISSUE THREAD

**Issue by isaiahc0** [web2py/web2py#1817]
Path: /web2py/gluon/packages/dal/pydal/base.py

Line 403 uses urllib in the lambda. Causes NameError: global name 'urllib' is not defined

"import urllib" required

**Comment by ilvalle** [comment]
@isaiahc0 open an issue on https://github.com/web2py/pydal project or better open directly a pull request with the fix, replace
```            credential_decoder = lambda cred: urllib.unquote(cred)```
with 
```            credential_decoder = lambda cred: unquote(cred)```

**Comment by ilvalle** [comment]
@mdipierro @isaiahc0 https://github.com/web2py/pydal/pull/505 has been merged, would you close this issue?
