### ISSUE TITLE
Date and datetime widget broken

### ISSUE THREAD

**Issue by cccaballero** [web2py/web2py#1831]
In 2.16.1 version (and current master branch) date and datetime widgets are broken, you can see in the picture the behavior
![captura de pantalla de 2018-01-03 12-15-56](https://user-images.githubusercontent.com/3727802/34567237-6b2a202c-f12f-11e7-99e5-473e8a627ce7.png)

**Comment by cccaballero** [comment]
It seems a translation issue for Spanish in the Wellcome app

**Comment by ilvalle** [comment]
@cccaballero https://github.com/web2py/web2py/issues/1831 has been merged, would you close this issue?

**Comment by cccaballero** [comment]
Of course!
