### ISSUE TITLE
SPAN.flatten() raises UnicodeDecodeError with T-components

### ISSUE THREAD

**Issue by nursix** [web2py/web2py#1856]
Code like this crashes in Py2.7 with UnicodeDecodeError for T-languages where translate produces multi-byte utf-8 encoded strings (e.g. Japanese, Korean, etc.):
```
elem = SPAN(T("Complete"))
text = elem.flatten()
```
The problem could be here:
https://github.com/web2py/web2py/blob/master/gluon/languages.py#L433
This should probably not str(self).encode() (as it seems normal that lazyT.__str__() returns an utf-8 encoded str)?

Or maybe this:
https://github.com/web2py/web2py/blob/master/gluon/_compat.py#L72
...could try to use the __str__ method first when obj is neither a str nor a unicode?

**Comment by ilvalle** [comment]
@nursix  this issue has been fixed by https://github.com/web2py/web2py/pull/1852. I added a test for this use case.

**Comment by nursix** [comment]
I don't see that this changes anything with regard to the problem I described?

I said the problem occurred in Py2.7 - but your fix doesn't change Py2.7 behavior, does it?

I also said the problem occurred in languages where the translation gives a utf-8 encoded str containing multi-byte characters - but your test seems to check for translating "Complete" from English to English, which doesn't use Japanese characters, or does it?

----

So maybe my explanation was unclear. The code that crashes is like:
```
my_html = SPAN(T("Complete"))
my_html.flatten()
```
Obviously this does not crash for English - because T("Complete") gives "Complete", which is an ASCII string. But when the language is changed to e.g. Japanese, it becomes "完了" - which is a utf-8 encoded str containing multi-byte characters. 

And /then/ flatten() crashes, because it calls:
https://github.com/web2py/web2py/blob/master/gluon/_compat.py#L71
...which in turn calls:
https://github.com/web2py/web2py/blob/master/gluon/languages.py#L433
```
str(self).encode("utf-8")
```
This ```str(self)``` returns a utf-8 encoded str, namely "完了" - and consequently, encode fails because it cannot decode this from ASCII:
```
>>> "完了".encode("utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```
This does not call T.encode (but str.encode) - so fixing T.encode doesn't seem to make any difference here. Nor does the test confirm that it does.

----

The point is though that str(self) (i.e. ```T.__str__()```) already returns a utf-8 encoded str - so why try to encode it again?

If it would return a unicode, then yes, encode would make sense, but why should ```__str__()``` return a unicode (is that even allowed)? Okay, maybe it is possible - but in this case it doesn't. 

In this case (as with all our language files), the call to ```T.__str__()``` returns a utf-8 encoded str containing multi-byte characters, and so it can not possibly be str.encode()'d again.

**Comment by nursix** [comment]
I tested with #1852, and this is the result:
```
>>> my_html = SPAN(T("Complete", language="ja"))
>>> my_html.xml()
'<span>\xe5\xae\x8c\xe4\xba\x86</span>'
>>> my_html.flatten()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dominic/work/projects/web2py/gluon/html.py", line 1005, in flatten
    s = to_native(c)
  File "/home/dominic/work/projects/web2py/gluon/_compat.py", line 74, in to_native
    return obj.encode(charset, errors)
  File "/home/dominic/work/projects/web2py/gluon/languages.py", line 434, in encode
    return str(self).encode(*a, **b)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
>>>
```

**Comment by nursix** [comment]
What works is when I change T.encode to:
```
    def encode(self, *a, **b):
        if PY2:
            return to_unicode(str(self)).encode(*a, **b)
        else:
            return str(self).encode(*a, **b)
```

But like I said, this modification of to_native works too:
```
    def to_native(obj, charset='utf8', errors='strict'):
        if obj is None or isinstance(obj, str):
            return obj
        elif type(obj) is not unicode and hasattr(obj, '__str__'):
            return str(obj)
        return obj.encode(charset, errors)
```

I'm sure neither is optimal, so I'm posting them just to illustrate my problem - hope this gives you the right guidance.

**Comment by ilvalle** [comment]
@nursix I see the problem. Regarding the change you proposed to T.encode, running ` to_unicode(str(self)).encode(*a, **b)` isn't equal to `str(self)` when the charset is the same? `to_native` is used every where in the code, if possible I wouldn't change it.

Side note, Japanese is not available in welcome app yet. Would you post a PR for it?

**Comment by nursix** [comment]
Yes, ```to_unicode(str(self)).encode(*a, **b)``` is the same as ```str(self)``` if the charset is the same. However, at this point it is unknown whether the charset is the same or not.

Re: Japanese for welcome app - I'm afraid I can't help you there. 

I'm trying to resolve https://github.com/sahana/eden/issues/1451, which has a Japanese translation - but I doubt that its language file https://github.com/sahana/eden/blob/master/languages/ja.py would fit for the web2py welcome app?

**Comment by ilvalle** [comment]
@nursix see https://github.com/web2py/web2py/pull/1852/commits/fa31a6b61be02ed1f6ce8fd76c21776a1e09d82d

**Comment by nursix** [comment]
This seems to do the trick, yes (sorry for the delayed response, bit busy here).
```
>>> x = SPAN(T("Complete", language="ja"))
>>> print(x.xml())
<span>完了</span>
>>> print(x.flatten())
完了
```

Now waiting for the next stable release...
