### ISSUE TITLE
bootstrap4_inline doesn't produce an inline form

### ISSUE THREAD

**Issue by daniellibonati** [web2py/web2py#1857]
When using `SQLFORM.grid(db.table, formstyle='bootstrap4_inline')`, there are no effects on the rendered form (it displays stacked instead).

According to Bootstrap v4 docs, it's required to add the class `row` to the form-group div in order to achieve the desired result.

Adding the css class to the function formstyle_bootstrap4_inline_factory in gluon/sqlhtml.py solves the issue.

**Comment by mdipierro** [comment]
Does this break BS3? Has it been checked?

**Comment by leonelcamara** [comment]
@mdipierro it doesn't because he only changed a bootstrap 4 specific formstyle.

**Comment by mdipierro** [comment]
can this be closed?

**Comment by leonelcamara** [comment]
@mdipierro it sure can. The fix was merged.
