### ISSUE TITLE
Cannot open Welcome App menu in various mobile browsers

### ISSUE THREAD

**Issue by sfxxx** [web2py/web2py#1864]
STEPS TO REPRODUCE: Open web2py 2.16.1 welcome app in Safari Mobile on iOS 9.3.5 on a small iPhone, or in Internet Explorer on a Windows 8 Mobile phone. Tap the burger menu in the upper right corner.
EXPECTED OUTCOME: Menu opens.
PROBLEM: Nothing happens.

Related notes: In these browsers, web2py.com's menu appears just as a black bar. I can select items in Internet Explorer, but not in Safari Mobile.

**Comment by cccaballero** [comment]
Fixed in current master branch. Please, test it and close the issue if everything is ok.

**Comment by sfxxx** [comment]
Selecting menu items now works for me, on the two platforms mentioned in the OP. Thanks for the fix!

The Welcome App's menu CSS now(?) looks a bit messed up though, with the arrows underneath (on Firefox), or even overlapping (Safari Mobile).
