### ISSUE TITLE
virtual field issue after upgrade fro V 14 to V16.5

### ISSUE THREAD

**Issue by sbourgeois1** [web2py/web2py#1865]
Hello,
I had to remove the virtual field to work around the issue. 
Example:
code working with v 14
...
    db_txp.t_txp_company.id.readable = False
    db_txp.t_txp_company.id.writable = False
# now we want to add a virtual field to select the corresponding cny.
    db_txp.t_txp_company.select = Field.Virtual('select', lambda row: A(SPAN(IMG(_src=URL(str('static/images'), str('select.png')),  _width = 20, _class = str("button btn btn-default")), str(' '), row.t_txp_company.f_company), _href = URL(str('store_cny_id'), args = [str(row.t_txp_company.id), str(row.t_txp_company.f_address_country_code), row.t_txp_company.f_company], vars = request._get_vars)))  
    form = SQLFORM.smartgrid(db_txp.t_txp_company,
                             fields = [db_txp.t_txp_company.id, db_txp.t_txp_company.f_company, db_txp.t_txp_company.f_address_country_code  ],
...
work around:
    ...
    db_txp.t_txp_company.id.label = T('Select')
    db_txp.t_txp_company.id.represent = lambda val, row: A(SPAN(IMG(_src=URL(str('static/images'), str('select.png')),  _width = 20, _class = str("button btn btn-default")), str(' '), row.f_company), _href = URL(str('store_cny_id'), args = [str(row.id), str(row.f_address_country_code), row.f_company], vars = request._get_vars))
    form = SQLFORM.smartgrid(db_txp.t_txp_company,
                             fields = [db_txp.t_txp_company.id, db_txp.t_txp_company.f_company, db_txp.t_txp_company.f_address_country_code  ],
    ...
The error file is here attached.
[error.txt](https://github.com/web2py/web2py/files/1731767/error.txt)

**Comment by dartg** [comment]
The error seems to be `<type 'exceptions.AttributeError'> 'FieldVirtual' object has no attribute 'listable'"` which I think it's already fixed: https://github.com/web2py/pydal/commit/ccc4d4c7f8e9bfb285597d266489e169ecadbbfa#diff-68220c912f02a03fd8bce58415479334

**Comment by mdipierro** [comment]
yes. this is fixed
