### ISSUE TITLE
Suggestion: to support this: requires = IS_UPLOAD_FILENAME(extensions('webm', 'ogg'))

### ISSUE THREAD

**Issue by sbourgeois1** [web2py/web2py#1875]
The IS_UPLOAD_FILENAME validator does not support a list of extensions but a single extension with the 'extension' keyword. And as far as I can see, it is not possible to add a OR statement in the 'requires' statement.
So, when the user wants to limit the upload on the type of extension, either this is done after the upload with a control integrated in the validation process or one field per type of extension has to be defined in the db model. 
So, can I suggest either to implements the validation on a list of extensions with the keyword 'extensions' for the IS_UPLOAD_FILENAME as it is done for IS_IMAGE ?

**Comment by leonelcamara** [comment]
IS_UPLOAD_FILENAME supports regexes in the extension. So you can just do something like IS_UPLOAD_FILENAME(extension="^webm$|^ogg$")

**Comment by sbourgeois1** [comment]
Thanks for your answer. 
I thought about this turnaround, but I guess this control id done after upload, while the control with 'extension' is done before upload... Correct?

Best rergards,Serge Bourgeois
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr 

    Le mardi 6 mars 2018 à 13:11:05 UTC+1, Leonel Câmara <notifications@github.com> a écrit :  
 
 
IS_UPLOAD_FILENAME supports regexes in the extension. So you can just do something like IS_UPLOAD_FILENAME(extension="^webm$|^ogg$")

**Comment by leonelcamara** [comment]
It's always after upload for serverside validators in web2py.
