### ISSUE TITLE
navbar toggle error and correction

### ISSUE THREAD

**Issue by pwoolf** [web2py/web2py#1886]
The toggle for the navbar in layout.html doesn't work properly out of the box.  When the window is made narrow or web2py is on a phone the collapsed menu is not responsive.  This is because the div needs an id specification.

In the header, just after the navbar-brand it curretnly has:
`<div class="collapse navbar-collapse"  >`

It should be:
`<div class="collapse navbar-collapse" id="navbarNavDropdown" >`

With this change it works for me.
Thanks!
--Peter

**Comment by adrianlaraperez88** [comment]
Yes working

**Comment by masia5** [comment]
@pwoolf this issue has been already fixed in https://github.com/web2py/web2py/pull/1851/files. you can close the issue

**Comment by pwoolf** [comment]
Thanks!
