### ISSUE TITLE
Book outdated - Recaptcha will close down end of March - Recaptcha2 is the way to go

### ISSUE THREAD

**Issue by wish7code** [web2py/web2py#1887]
The book mentions the Recaptcha **V1** API, which will shut down end of March here:
http://www.web2py.com/books/default/chapter/29/09/access-control?search=recaptcha#CAPTCHA-and-reCAPTCHA

Users need to switch to Recaptcha **V2**.

I found this web2py mailing list post, which explains all the necessary adjustments, very helpful:

https://groups.google.com/forum/#!topic/web2py/yhoxNN3HL3U

Cheers
Toby

**Comment by BuhtigithuB** [comment]
Can you update the book?

We can delete the code from web2py for V1...
