### ISSUE TITLE
db.parse_as_rest don't work on python 3

### ISSUE THREAD

**Issue by JusticeN** [web2py/web2py#1894]
i am using python3.6 on windows 7 with the web2py last master branch.
when i try to build a restful API with **db.parse_as_rest** Web2py throw me a NameError exception

my code look like this
`@request.restful()
def api():
    response.view = 'generic.json'

    def GET(*args,**vars):
        patterns = [
            "/Contact[Contact]",
            "/Contact/{Contact.first_name.startswith}",
            "/Contact/{Contact.first_name}/:field"
            ]
        parser = db.parse_as_rest(patterns, args, vars)
        if parser.status == 200:
            return dict(content=parser.response)
        else:
            raise HTTP(parser.status, parser.error)`

the error look like this: 

>   File "D:\Program_Files\web2py\gluon\packages\dal\pydal\helpers\rest.py", line 289, in parse
    offset = long(vars.get('offset', None) or 0) class 'NameError' name 'long' is not defined

in python3 there is no long function anymore. is it better to use int instead ?

[see here for explanation](https://stackoverflow.com/questions/2104884/how-does-python-manage-int-and-long#2104947)

**Comment by BuhtigithuB** [comment]
You can try to put that in the top of pydal/helpers/rest.py

import sys

PY2 = sys.version_info[0] == 2
if PY2:
    pass
else:
    long = int

And see if it works.

Please report back here, will fix it that way.

Richard

**Comment by BuhtigithuB** [comment]
This issue should be closed, I open this issue against pyDAL repo : https://github.com/web2py/pydal/issues/533

**Comment by BuhtigithuB** [comment]
Please have look at the pyDAL issue, I think it fixed, but I didn't test you can try with the final solution that I go with.

**Comment by JusticeN** [comment]
i close it because it is alrady solve in PYDAL repo
