### ISSUE TITLE
.take('something', cast=bool) return a string

### ISSUE THREAD

**Issue by jicho** [web2py/web2py#1903]
Hi,

I have this in my appconfig.ini:
```
[global]
track_changes = False
development = False
number = 1
```

When I do appconfig.take('global.development', cast=bool) the result is always a string. Shouldn't it be casted to a boolean? Casting numbers to int works fine.

I've tested it with the attached files in the default controller.

Am I doing something wrong? Or is this a bug? Or maybe by design?

[example.zip](https://github.com/web2py/web2py/files/1927917/example.zip)

**Comment by cccaballero** [comment]
Hi, you should use  appconfig.get('global.development'), it will automatically cast 'true' or 'false' to boolean values.

take('global.development', cast=bool) will try to cast a string to boolean and will always return True (except when the string is empty)

**Comment by jicho** [comment]
@cccaballero thank you for your reaction. I can follow your idea, but... why is the manual saying that you can use .take()? I just followed the instructions found here: http://web2py.com/books/default/chapter/29/13/deployment-recipes#AppConfig-module and filled the cast in with my own idea.

From my point of view .take() should return true/false also... Or am I missing the complete idea behind the .take() in combination with cast= ? It really feels like a bug ;)

**Comment by jicho** [comment]
Just tested it and it works great. I must admit that I find it a idea to use this "magical" .get(), you have the idea that you're using the normal .get(), but oh well... when it works you don't hear me complaining ;)

So long story short... My conclusion:
> .get() is some sort of "auto-cast" version of .take([lookup], cast=[something])
