### ISSUE TITLE
problem export virtual field to CSV using grid

### ISSUE THREAD

**Issue by vicding** [web2py/web2py#1916]
I am having issue exporting virtual fields to CSV using grid. It displays fine though. 

I defined field in this way
`Field.Virtual('cost_value', lambda row: row.inventory.cost_price_avg * row.inventory.qty, label=T('Stock value')),`

When I export it to CSV in grid I got the following error
`<type 'exceptions.KeyError'> '"inventory"."cost_value"'`

The grid was a simple one
```
fields = [db.inventory.qty, db.inventory.cost_price_avg,db.inventory.cost_value]
grid = SQLFORM.grid(db.inventory, maxtextlength=64, paginate=20, create=False,
                    details=False, editable=editable, deletable=deletable,
                    fields=fields,
                    links=links,
                    )
```

**Comment by vicding** [comment]
DAL is not treating virtual fields as 'normal fields'. Is it possible to make virtual fields work the same way as normal ones?

**Comment by mdipierro** [comment]
This issue was closed in this commit https://github.com/web2py/pydal/commit/5bacaf785ad14e4bfee86c1db3c7349537d5f2ea due to Paolo.
