### ISSUE TITLE
deployment issues with app built on 2.16.1 running on web2py -2.14.6 python anywhere server 

### ISSUE THREAD

**Issue by WattsMatthew** [web2py/web2py#1920]
I am trying to deploy an to python anywhere using an app made with with the latest version 2.16.1. However, python anywhere is using version 2.14.6

Any ideas what's up, or how i can work around this?

Thanks

Matthew

**Comment by leonelcamara** [comment]
You need to update web2py on pythonanywhere first.

**Comment by WattsMatthew** [comment]
ok thanks!
