### ISSUE TITLE
Archives tables not created anymore 

### ISSUE THREAD

**Issue by jvanbraekel** [web2py/web2py#1939]
Good morning,

After the last update to both masters versions of web2py and pyDAL, the command 'auth.enable_record_versioning(db)' does'nt create archive tables anymore as it should be. 
May be related to web2py/pydal#536

**Comment by leonelcamara** [comment]
@jvanbraekel You need to use signature=True when you define tables for Auth for the versioning to work on auth tables.

auth.define_tables(signature=True)
auth.enable_record_versioning(db)

**Comment by jvanbraekel** [comment]
@leonelcamara  Thank you for your repply.   I have change the signature parameter before reporting the issue. Look at the link in my first post,  you will find my test case there.
