### ISSUE TITLE
hooks no longer work with crud

### ISSUE THREAD

**Issue by rif** [web2py/web2py#1940]
The db hooks no longer work with 2.16.1-stable+timestamp.2017.11.14.05.54.25
The same code works with 2.14.6-stable+timestamp.2016.05.10.00.21.47.

db.py:

```python
from uuid import uuid4

db.define_table('reseller',                
                Field('name', 'string'),
                Field('unique_code', 'string', required=True, readable=False, writable=False),
               )

def add_unique_code(fields, prefix):
    fields['unique_code'] = prefix + str(uuid4())[:6]


db.reseller._before_insert.append(lambda f: add_unique_code(f, "rs_"))
```

default.py:
```python
def index():
    form = crud.create(db.reseller)
    return dict(form=form)
```

index.html
```html
{{extend 'layout.html'}}

{{=form}}
```

when using a form  in a field I get Table: missing required field: unique_code

**Comment by leonelcamara** [comment]
It's not that they don't work, it's that pydal is calling the before_insert after checking the values it gets namely that all required fields are there and calculating the computed values.  
  
I would change this to be a computed field or simply remove the required=True. Both solutions will work.

**Comment by rif** [comment]
Thank you for the suggestions, I understand and both solutions are acceptable
