### ISSUE TITLE
Error with authentication using Gmail

### ISSUE THREAD

**Issue by miguelconde91** [web2py/web2py#1964]
I have external authentication trough Gmail in my web site using web2py v2.16.1. I'm trying to log in with my google account, however I have this error:
File "/usr/lib/python2.7/smtplib.py", line 623, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials m184-v6sm6405771vkd.53 - gsmtp')

I fixed it allowing insecure apps in my google account setting. My question: is this happened because my web2py server and application are not using HTTPS?

**Comment by leonelcamara** [comment]
No, this happened because of a google policy. You will have the same problem with any application using SMTP.

**Comment by miguelconde91** [comment]
Thanks by your answer, so with facebook external authentication it is not a problem? Is there any other type of external authentication mechanism using the google account that does not make this error?

**Comment by leonelcamara** [comment]
Yes you can use google login using oauth2 then it won't have this problem.
