### ISSUE TITLE
current.T not working in module with Python 3

### ISSUE THREAD

**Issue by jicho** [web2py/web2py#1973]
Hi,

When I use current.T in a module in combination with Python 3 and Web2Py version 2.16.1-stable I only get, in my case English text even when I switch to another the language.

The used T()'s in controllers and the views are working like a charm.

It this a bug in combination with Python 3? In Python 2 everything worked fine :)

A module example:

```
# -*- coding: utf-8 -*-
from gluon import current

class Something(object):

    @staticmethod
    def key_to_text(text):
        return {
            'accountblocked': current.T('Account blocked'),
            'blockmail': current.T('Block account'),
        }.get(text.lower(), '{0} *'.format(text))
```

Or as found a long time ago on stackoverflow:

```
# -*- coding: utf-8 -*-
from gluon import current

T = current.T

class Something(object):

    @staticmethod
    def key_to_text(text):
        return {
            'accountblocked': T('Account blocked'),
            'blockmail': T('Block account'),
        }.get(text.lower(), '{0} *'.format(text))
```

Thanks for the reaction!

**Comment by arisobel** [comment]
I dont know if it the same problem, but  I'm not able to admin Languages at Admin using Python3

**Comment by leonelcamara** [comment]
You are setting this in the module

T = current.T

So the module's T becomes the T of the first thread that accesses the module. Later you may have a different language but the module's T has already been set. You can fix this by simply putting the "T = current.T" as the first line of "key_to_text". 

> I dont know if it is the same problem, but I'm not able to admin Languages at all at Admin using Python3  
  
No, that's something else, please file an issue.

**Comment by jicho** [comment]
It didn't work, but when I changed it into:

```
# -*- coding: utf-8 -*-
from gluon import current

class Something(object):

    @staticmethod
    def key_to_text(text):
        T = current.T
        text = {
            'accountblocked': T('Account blocked'),
            'blockmail': T('Block account'),
        }.get(text.lower(), '{0} *'.format(text))

        return T(text)
```

it partially works...

When I enter the site everything is in Dutch (as expected). After switching to English everything is in English. When I switch back to Dutch everything stays English...

I think that has something to do with other stuff, but I'm no sure. Will close the ticket for now.

Thanks!
