### ISSUE TITLE
auth.profile stopped working with email widget in 2.17.1

### ISSUE THREAD

**Issue by amerikan** [web2py/web2py#1988]
After upgrading, a part of my website doesn't work anymore. Here's the situation:

**Controller**
```python
basic_form = auth.profile(next=URL('default', 'user/account', host=True, scheme=True))

return dict(basic_form=basic_form)
```

**View**
```html
{{basic_form.custom.widget.email['_class'] = 'form-control'}}
{{basic_form.custom.widget.email['_readonly'] = 'readonly'}}
{{basic_form.custom.widget.email['_style'] = 'display:none;'}}
{{basic_form.custom.widget.email}}
```

**Error**
<type 'exceptions.TypeError'>('str' object does not support item assignment)

I print out `basic_form` to see what it was returning and it seems it no longer has email input in it anymore. I think that's why when I try to assign something to email widget it throws that error. Was there some change that cause this?

**Comment by leonelcamara** [comment]
I think this is also fixed by:
https://github.com/web2py/web2py/pull/2030

Can you check?

**Comment by amerikan** [comment]
Sorry I can't test, I haven't used web2py in a while.
