### ISSUE TITLE
Improve performance for download of uploads stored in blob fields

### ISSUE THREAD

**Issue by sbourgeois1** [web2py/web2py#2023]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leonelcamara** [comment]
Is this even possible? There's not much web2py is doing (all we do is put the value in a BytesIO object), slower performance is simply a consequence of storing the files in blobs.

**Comment by sbourgeois1** [comment]
As far as I know, the argument of the 'default/download' function contains the value stored into the field of 'upload' type. Good enough when the file is stored in a folder. But when stored into an 'uploadfield' of type 'blob', then a database query is of course required to get the data back (for instance to display in image on a html page). In that query, there is no indication of the record id, since it is not given to the download function. Nevertheless, this is often known. 
So, can I suggest the following alternatives to allow adding a 'where clause' based on the row id:
1. When the data is stored into a 'blob' field, the value of the filename stored in the 'upload' field could contain the row id (format : '%s.%s.%s.%s' % (table_name, field_name, row_id, extension)). This combination is anyway always unique. I am aware that in case if creation of a new row in the db, this could need an update of the 'update' field after knowing the row id, but later, the access to the blob field could be done much more efficient...
2. or give the possibility (may be existing but I could not find it...) to pass the row id as additional argument to the 'default/download' function, and adapt the behavior of this function to include the id in the  'where clause' of the query when this id is given.
3. or create a new function in the default controller of the scaffolding application, for instance 'blobdownload', with 1 or 2 args:filename (as stored into the 'upload' field) : always mandatory , and the row_id (optional).

**Comment by leonelcamara** [comment]
I think the query performance of finding the record is a very small part of the equation here, but wouldn't it be simpler for you to simply create an index on the table for the filename? That way it should be almost exactly the same. Alternatively you can implement a custom_retrieve for your field that will work the way you want.

**Comment by sbourgeois1** [comment]
Of course, I could also create an index on the 'upload' field. When the size of the db increases, the perf impact also increases. 
I decided to create this issue while trying to develop a custom_retrieve (see function code here under). 
This function is not doing the streaming as the default/download function does, so I'm not satisfied with it. You could probably suggest a better solution? Thanks in advance for your ideas. 

def my_downstream(field_name, id):
    """
    allows retreiving of uploaded files in blobs
    This function requires the content of the filed in the 'upload' field, and the record id.
    The table name and the blob field name will be determined automatically.
    If the id is absent, the performance is drastically reduced (no where clause in the query!
    Exemple of -for calling this function: my_downstream('t_show_item.f_default_file.xxxx.ppt', 1)
    """
    import io
    try:
        table_name = field_name[:field_name.index('.')]
        rest = field_name[len(table_name) +1:]
        f_field = rest[:rest.index('.')]
        rest = rest[len(f_field) +1:]
        extension = rest.rpartition('.')[2]
        file_name = rest[:len(rest) - len(extension) - 1]
        uploadfield = db[table_name][f_field].uploadfield
        mysql = 'select %s from %s where id = %s limit 1;' % (uploadfield, table_name, id)
        #log_msg('comon.py l 77 mysql', mysql)
        rows = db.executesql(mysql)
        if rows:
            myfile = io.BytesIO(b"%s" % (rows[0][0]))
            data = myfile.getvalue()
            return data
        else:
            return ''
    except:
        return ''
# calling the above function from a controller
@cache.action()
def test_my_downstream():
    return my_downstream('t_show_item.f_default_file.b22a93ac43a32e12.50726f636573737573547269704b69745f656e2e707073.pps', '1')

**Comment by leonelcamara** [comment]
@sbourgeois1 how about this

    def download_blob_in_record():
        from gluon._compat import BytesIO, to_bytes
        from gluon.contenttype import contenttype
    
        table, record_id, upload = request.args(0), request.args(1), request.args(2)
        blobfield = db[table][upload].uploadfield
        record = db(db[table].id  == record_id).select(db[table][upload], db[table][blobfield]).first()
        if record is None or record[upload] is None or record[blobfield] is None:
            raise HTTP(404)
        filename = db[table][upload].retrieve_file_properties(record[upload])['filename']
        response.headers['Content-Type'] = contenttype(filename)
        stream = BytesIO(to_bytes(record[blobfield]))
        return response.stream(stream, request=request)

This is a download function you can put in default.py that will allow you to download blobs directly after getting their records by id. It expects as arguments the table, the id of the record and the field where the upload is.

In a view you could make a download link like this:

    <a href="{{=URL('default', 'download_blob_in_record', args=['foo', rec.id, 'image'])}}">download</a>

Where it expects that table foo has a field image which has an uploadfield which is a blob.

    db.define_table('foo',
        Field('image', 'upload', uploadfield='image_data'),
        Field('image_data', 'blob'))

**Comment by sbourgeois1** [comment]
Thanks a lot, that's exactly what I was looking for!

**Comment by sbourgeois1** [comment]
The following code makes it compatible with all kinds of upload, with :first argument : the content of the upload field and a second option argument: the id of the record containing the blob. This second optional argument is only useful when the upload file is stored in a blob.

@cache.action()
def custom_download():
    '''This is a download function allows to download blobs directly after getting their records by id. It expects as arguments the content of the upload field and optionnaly the id of the record where the upload is.
    In a view you could make a download link like this:

    <a href="{{=URL('default', 'custom_download', args=['image', rec.id])}}">download</a>
    or 
    <a href="{{=URL('default', 'custom_download', args=['image'])}}">download</a>

    Where it expects that table foo has a field image. 
    If the uploadfield is a blob and if the id is given, the download will use itto retreive the record with containing the blob field value.

    db.define_table('foo',
    Field('image', 'upload', uploadfield='image_data'),
    Field('image_data', 'blob'))
    '''
    from gluon._compat import BytesIO, to_bytes
    from gluon.contenttype import contenttype
    if request.args and 'LIST' in str(type(request.args)).upper() and len(request.args) == 2:
        field_content = request.args[0]
        row_id = request.args[1]
        comparator = '='
    elif request.args and 'LIST' in str(type(request.args)).upper() and len(request.args) == 1:
        field_content = request.args[0]
        row_id = 0
        comparator = '>'
    elif request.args:
        field_content = request.args
        row_id = 0
        comparator = '>'
    else:
        return ''
    table_name = field_content[:field_content.index('.')]
    rest = field_content[len(table_name) +1:]
    f_field = rest[:rest.index('.')]
    rest = rest[len(f_field) +1:]
    extension = rest.rpartition('.')[2]
    file_name = rest[:len(rest) - len(extension) - 1]
    uploadfield = db[table_name][f_field].uploadfield
    if type(uploadfield) == type (''): # file stored into blob field
        if comparator == '=':
            record = db(db[table_name].id  == row_id).select(db[table_name][f_field], db[table_name][uploadfield]).first()
        else:
            record = db(db[table_name][f_field]  == field_content).select(db[table_name][f_field], db[table_name][uploadfield]).first()
        if record is None or record[f_field] is None or record[uploadfield] is None:
            return ''
        else:
            filename = db[table_name][f_field].retrieve_file_properties(record[f_field])['filename']
            response.headers['Content-Type'] = contenttype(filename)
            stream = BytesIO(to_bytes(record[uploadfield]))
            return response.stream(stream, request=request)
    else:
        return response.download(request, db)
