### ISSUE TITLE
KeyError on ExportClass.represented() call

### ISSUE THREAD

**Issue by lkrn** [web2py/web2py#2049]
**Describe the bug**
When you call _represented_ method from **ExportClass**, a ticket is created with below traceback:
<type 'exceptions.KeyError'> '<name of the first column in grid>'
```
  File "\web2py\gluon\sqlhtml.py", line 3683, in represented
    value = record[f]
  File "\web2py\gluon\packages\dal\pydal\objects.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: '<name of the first column in grid>'
```

**To Reproduce**
1. Create class that inherits from **ExportClass**
2. Call self.represented() inside _export_ method in **your** class
3. See KeyError

**Expected behavior**
self.represented() returns ready-to-export array with resolved values of all columns (fields)

**Comment by lkrn** [comment]
all standard (ootb) export methods in grid (e.g., csv, tsv) actually call _Rows.export_to_csv_file_ method defined in objects.py of DAL

**Comment by mdipierro** [comment]
Would this fix work for you instead:
value = record[t+'.'+f]
Problm is that values in col may be quoted

**Comment by lkrn** [comment]
@mdipierro 
Indeed, in runtime, that's what I have in **col** variable the moment expression `record[col]` evaluated: '"MyTableName"."MyColName"'
Values are quoted as you can see.
But, keys of `_extra = super(Row, self).get('_extra', None)` object are also quoted (`class Row(BasicStorage)` in `dal\pydal\objects.py`).
When you pass it as **col** to Row indexer, value returned from `return BasicStorage.__getattribute__(self, key)`
When you pass it as **t+'.'+f** - `return BasicStorage.__getattribute__(self, key)` raises AttributeError and has to do further parsing (`m = REGEX_TABLE_DOT_FIELD.match(key)`) to get the value back, but it also works - just slower in this particular case.
If you think it's better or cleaner to pass key as **t+'.'+f**, I can change it in pull request, but I think it'll make processing a bit slower, though I absolutely understand that I might overlook some other potential issue if you pass it as **col**.
What do you think?

**Comment by mdipierro** [comment]
Hello Ikrn,

can you confirm this issue is still valid in web2py 2.18.4?

**Comment by lkrn** [comment]
Hi Massimo,

Can't reproduce the issue on 2.18.4 anymore.
We can close this issue and also remove pull request #2050.
Thank you.
