### ISSUE TITLE
IS_UPLOAD_FILENAME() takes regex for extensions -- why?

### ISSUE THREAD

**Issue by vinyldarkscratch** [web2py/web2py#2073]
So I've been spending a lot of time with `IS_UPLOAD_FILENAME` and finding out that my regex has been problematic at least once every single time.  That's when I had a realization: "why?"  Why does the `extension` parameter require regex?  Sure, there may be those rare cases where someone needs to use regex to check against an extension, but most users would probably just want to insert a list of different extensions.  I feel that introducing regex by default implies more work for website developers.

I propose adding the ability to pass a list of extensions into `IS_UPLOAD_FILENAME` (essentially what #1875 has brought up), and I would like to know if others think the same.

**Comment by leonelcamara** [comment]
Can't you just '|'.join(your_extension_list)?

**Comment by vinyldarkscratch** [comment]
Actually, `'|'.join(your_extension_list)` doesn't seem to produce the intended result as it allows for `exeuuuuuu` as an extension when checking against `exe|app`.  Parenthesis are needed around the entire list, i.e. `(exe|app)`.  My point is, why give the app developers the frustration of working around this, when the validator should just be able to handle it natively?

**Comment by vinyldarkscratch** [comment]
I feel that it's an extra step that web2py should handle rather than the app developer, and a frustrating one at that.  I still haven't been able to find the right regex expression to capture this particular issue, especially as the above expression allows for `potx` when checking against `pot|png`.  (Same with when it is surrounded in parenthesis, and/or when using `^` and `$` around the expression.)  Why have everyone re-solve the same problem, rather than just solving it once for everyone?

**Comment by vinyldarkscratch** [comment]
After some further experimentation, it seems that this problem runs deeper than expected.  I've opened up #2106 to dive into these issues.
