### ISSUE TITLE
web2py v 2.16 download

### ISSUE THREAD

**Issue by JoannaSM** [web2py/web2py#2079]
I need web2py v 2.16. When I download it from Releases https://github.com/web2py/web2py/releases becouse of error 

RuntimeError: web2py depends on pydal, which apparently you have not installed.

Where I can find proper package?  Or how I can repeare it?

**Comment by vinyldarkscratch** [comment]
`pydal` is a submodule of web2py, so if you `git submodule init`, that should fix the issue right away!  Just curious, what requires you to use 2.16 rather than 2.17 or above?

**Comment by JoannaSM** [comment]
When I dowload web2by as zip archive I cant do just do "git submodule init". However, I understand that I download web2py/pydal package it should be work properly. 

I have no influence on the choice of versions. Sometimes it happens.

**Comment by nicozanf** [comment]
Hi,

you can do it manually ;-)

Download web2py-R-2.16.1.zip from  https://github.com/web2py/web2py/releases
. Unzip it, and you can see inside the CHANGELOG file that
it's using pydal 17.11 . Hence, you can download v17.11.zip from
https://github.com/web2py/pydal/releases , extract it and copy its content
under gluon/packages/dal

Il giorno sab 26 gen 2019 alle ore 17:17 Joanna <notifications@github.com>
ha scritto:

**Comment by JoannaSM** [comment]
OK. By why just v17.11?

**Comment by vinyldarkscratch** [comment]
v17.11 is the version of `pydal` that shipped with web2py v2.16.  You can probably use an older or newer version of `pydal`, but it may produce some bugs/crashes.

**Comment by JoannaSM** [comment]
OK. Thanks for this information
