### ISSUE TITLE
Invalid Login - Redirect Not Setting "vars" to "request.post_vars"

### ISSUE THREAD

**Issue by macneiln** [web2py/web2py#2083]
**Issue**
In the Auth class login function, if an invalid login occurs (passes SQLFORM field validation), i.e. valid email format and password is appropriate length, then there is a redirect to the same login function to generate another SQLFORM but it passes in request.get_vars instead of request.post_vars. Since the invalid submission is due to a POST request, get_vars will be empty and the post_vars which the user submitted will be lost and thus return a new login form which is blank (email and password field are blank).

Solution:
 Change the redirect call to use vars=request.post_vars so the user submitted values are pushed through with the redirect.
Before Fix:
                        session.flash = self.messages.invalid_login
                        callback(onfail, None)
                        redirect(
                            self.url(args=request.args, vars=request.get_vars),
                            client_side=settings.client_side)

After Fix:
                        session.flash = self.messages.invalid_login
                        callback(onfail, None)
                        redirect(
                            self.url(args=request.args, vars=request.post_vars),
                            client_side=settings.client_side)

**To Reproduce**
1. Go to login page of welcome app
2. Submit a valid email format and a valid password length.
3. Results: email and password are currently reset to blank instead of remaining.

**Expected Results**
- Email and password should remain the same as when the user submitted them.

**Comment by vinyldarkscratch** [comment]
As @leonelcamara mentioned on #2084, leaving the password poses a possible security vulnerability, however leaving the email (or username) is convenient.  I've set up a pull request that does just that.  :wink:
