### ISSUE TITLE
IS_STRONG behavior changed in 2.15

### ISSUE THREAD

**Issue by sethkinast** [web2py/web2py#2093]
I am upgrading an app from 2.5.1 (!) to 2.17.2.

I noticed that I could not log in after the upgrade because my password "May not include any numbers", which is funny because my password had numbers in it before the upgrade.

I looked through the app and found the following in `db.py`:

```
custom_auth_table.password.requires = [IS_STRONG(min=8,special=False,number=False), CRYPT()]
```

I found that [this commit](https://github.com/web2py/web2py/commit/a5599f3eab14155d9dff589e7275665892a39eb1#diff-1e4f774e944ce88607f6bc3debe6f0b7) changed the semantics of IS_STRONG by switching type() checks to isinstance() checks-- bool is a subclass of int.

```
>>> isinstance(False, int)
True
```

**Previous behavior:** passing `number=False` meant "0 or more numbers"
**New behavior in 2.15:** passing `number=False` means "exactly 0 numbers"

There's now no way for me to tell IS_STRONG to have no requirements for numbers. If I pass something larger than 0, that's the minimum. If I pass None, the default path sets the minimum to 1. If I pass 0 or False, the meaning of the argument changes from a minimum to a prohibition (which seems weird to me).

I can submit a pull request to change the behavior but I wanted feedback on what you thought the correct behavior was.

**Comment by vinyldarkscratch** [comment]
Huh, that's very strange!  I wouldn't expect that behavior of an existing function would change in a web2py version after 1.0, due to their backwards compatibility promise.  This sounds like a bug in web2py that was introduced during the switch from `type()` to `isinstance()`.

Yeah, if you've got a pull request ready to send, then send away!
