### ISSUE TITLE
IS_UPLOAD_FILENAME(extension="pdf") accepts "foo.pdfx" as valid filename

### ISSUE THREAD

**Issue by vinyldarkscratch** [web2py/web2py#2106]
**Describe the bug**
As my concerns in #2073 expressed, I feel that the utilization of regex causes more issues than it solves them.  One that I have just discovered is that passing `extension="pdf"` into `IS_UPLOAD_FILENAME` lets the application accept `pdfx`, as a valid filename, as they both pass a `re.match()`.  However, the documentation explains this as if it must be an exact match.

**To Reproduce**
1. Create a form with an upload field.
2. Attach an `IS_UPLOAD_FILENAME(extension='png')` to the upload field.
3. Upload a file ending in `.png2000`.
4. Validator incorrectly accepts input.

**Expected behavior**
The validator should return an error when not an exact match.

**Proposed solution**
Unfortunately, this bug will most likely break backwards compatibility.  I propose creating a new validator, `IS_FILE` (or whatever we'd want to name it), to become the successor of `IS_UPLOAD_FILENAME`.  This new `IS_FILE` should accept a string, compiled regex, or list of strings/regex, rather than assuming that the input will always be a regex string.

**Comment by leonelcamara** [comment]
Well `png2000` does have a match for 'png'. 
You need to use ''^png$''

**Comment by vinyldarkscratch** [comment]
The documentation does not describe the validator as requiring `^$` around the extension, which is the whole reason I've written this issue.

**Comment by leonelcamara** [comment]
The documentation specifies it's a regex

**Comment by vinyldarkscratch** [comment]
As stated in the web2py book:

> Check if file has a pdf extension (case insensitive):
> 
> requires = IS_UPLOAD_FILENAME(extension='pdf')
> Check if file has a tar.gz extension and name starting with backup:
> 
> requires = IS_UPLOAD_FILENAME(filename='backup.*', extension='tar.gz', lastdot=False)

These examples explain the usage of the validator as "this will only allow 'pdf', not 'pdfx'," and I feel that should be the default behavior.  I should NOT have to go out of my way for this functionality.

**Comment by leonelcamara** [comment]
The book is wrong and should be corrected, as always, code is the only true specification, that said, I'm not against changing this for a "UX" reason, I think it's a good reason. I was just pointing out how to make it work correctly.

**Comment by vinyldarkscratch** [comment]
That could work.  The only unfortunate issue is that it would break backwards compatibility, but then again, if it was a bug this whole time, I guess it would be worth it?  I know the web2py motto is to always provide backwards compatibility from 1.0.  I sent a PR that provides a fix, however may be better to incorporate right into the existing validator in the way you’ve suggested.
