### ISSUE TITLE
Cannot save file in ajax webeditor with "control + S"

### ISSUE THREAD

**Issue by victorlemaire** [web2py/web2py#2111]
I created a new application throug menu. 
I choose to open "site". 
Then i choose my app "blog" to 
I open the default/index.html
Change something by adding some words. 
I tried to save it by "Control + S"
I get the message that "there is a communication error" in red. 
and the next text appears: 

An error occured, please <a href="/admin/default/edit/Blog/views/default/index.html?id=views__default__index__html">reload</a> the page

When i opened the file again the pages are merged together and the buttons old new and merge appear. 

**Expected behavior**
to save the changes in the file

**Screenshots**

browser: chrome firefox
OS: Windows 10
Asus laptop

**Comment by victorlemaire** [comment]
"""An error occured, please <a href="/admin/default/edit/Blog/views/default/index.html?id=views__default__index__html">reload</a> the page

The comlete message

**Comment by mcar9** [comment]
I am having the same issue on win 7, the latest .exe downloaded straight off the website. Always says "communication error" even when i click on save. often requests me to resolve merge conflicts

**Comment by victorlemaire** [comment]
With the new version 2.18.3 the saving works again.
