### ISSUE TITLE
Triple single quotes in insert record method causes problems in appadmin record visualization

### ISSUE THREAD

**Issue by jcrmatos** [web2py/web2py#2130]
Triple single quotes in insert record method causes problems in appadmin record visualization.
The fields in question (in my eg. they are notes and observations) show white space before and after.

With this code the problem occurs:
```
            db.wo_det.insert(wo_id=idx, product_id=2, sn=978475,
                             manual_lang_id=idx % 2 + 1, co_code='978475',
                             so_code='978475',
                             notes='''
                             lkj sldkfj slkjdf sljdf lsjdf lsjfd lsjfd lajd flksj lfdjsa
                             ''',
                             observations='''
                             lkj sldkfj slkjdf sljdf lsjdf lsjfd lsjfd lajd flksj lfdjsa
                             ''',
                             est_finish=request.now, opts=[1, 3, 5],
                             opts_names='Automation1, Door1, Power1')
```
With this code there is no problem:
```
            db.wo_det.insert(wo_id=idx, product_id=2, sn=978475,
                             manual_lang_id=idx % 2 + 1, co_code='978475',
                             so_code='978475',
                             notes='lkj sldkfj slkjdf sljdf lsjdf lsjfd lsjfd lajd flksj lfdjsa',
                             observations='lkj sldkfj slkjdf sljdf lsjdf lsjfd lsjfd lajd flksj lfdjsa ljkldfj glkdsfjg ldkjfg lkdjfg lkdjfg',
                             est_finish=request.now, opts=[1, 3, 5],
                             opts_names='Automation1, Door1, Power1')
```

**Expected behavior**
There shouldn't be any white space before and after.

**Screenshots**
This is how it looks with the problem
![wrong](https://user-images.githubusercontent.com/1813375/53892060-7dcb0180-4023-11e9-8741-c11ee2672f07.png)
This is how it looks without the problem
![right](https://user-images.githubusercontent.com/1813375/53892096-90453b00-4023-11e9-8e84-31fdd9e7077f.png)

**Desktop (please complete the following information):**
Windows 7 Pro x64 SP1+all updates
Firefox 65.0.2 x64
Python 3.7.1 x86
web2py 2.18.3

**Comment by leonelcamara** [comment]
This is just the way python works :/

**Comment by jcrmatos** [comment]
Yes, I know Python adds newlines. The problem is with the visualization of them in appadmin.
My point is that if there are new lines (and there are in the case of the triple single quotes in my example because Python adds them, that is all good) then the record visualization should show them properly, not white space before and after.
Eg.
'''
2nd line
'''
should appear

2nd line

and not
       2nd line       
which is what is happening.

**Comment by leonelcamara** [comment]
It doesn't just add newlines python adds those spaces as well

    >>> a = '''
    ...     greg egegerg
    ...     feg egferg e geg
    ...     '''
    >>> a
    '\n    greg egegerg\n    feg egferg e geg\n    '
    >>>

**Comment by jcrmatos** [comment]
Strange, not in my REPL
```
C:\Users\JMatos\OneDrive\Python>py
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Inte
l)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a = '''
...
...
... teste
...
... '''
>>> a
'\n\n\nteste\n\n'
>>>



```

**Comment by leonelcamara** [comment]
Not in your REPL because you didn't indent stuff as you did in your original code or like I did in my example :)

**Comment by jcrmatos** [comment]
Ok, you are correct (missed that).
What about the newlines? Is it correct to "remove" the newlines and not show them in the record visualization?

**Comment by leonelcamara** [comment]
They're not really removed the thing is that it's using input type="text" which doesn't show newlines, if it was using a textarea then it would show them. You can test by putting this in your models

db.wo_det.notes.widget = db.wo_det.notes.widget = SQLFORM.widgets.text.widget

Appadmin is simply using the default widget for your field types, if those fields were of type "text" instead of "string" then this widget setting wouldn't be necessary.

**Comment by jcrmatos** [comment]
OK, thanks for clarifying that.
