### ISSUE TITLE
gluon.utils.unlocalised_http_header_date returns wrong time

### ISSUE THREAD

**Issue by darkclip** [web2py/web2py#2143]
**Describe the bug**
in function unlocalised_http_header_date, line 481:
`year_and_time = time.strftime("%Y %H:%M:%S GMT")`
should be:
`year_and_time = time.strftime("%Y %H:%M:%S GMT", data)`

**Comment by leonelcamara** [comment]
Quite right!

**Comment by Faelysse** [comment]
Damn, one of my first ever open-source contributions has a bug in it. Sadface.

Thanks for finding and fixing it.

**Comment by leonelcamara** [comment]
@Faelysse it's perfectly normal, as in life, the only way not to do bugs is to stop coding.
