### ISSUE TITLE
Appadmin controler cant load CSV into DB(unable to parse csv file)

### ISSUE THREAD

**Issue by Mad-onanist** [web2py/web2py#2148]
**Describe the bug**
Unable to export CSV file into Data Base(to Table) from "administrative interface" .

**Error received**

> unable to parse csv file iterator should return strings, not bytes (did you open the file in text mode?)

**To Reproduce**

1.    Create a new project(**New simple application**).
2.   Go to Models, and  edit  **db.py**
   Add this:

`
db.define_table('contacts',
                Field('first_name'),
                Field('last_name'),
                Field('company_name'),
                Field('address'),
                Field('city'),
                Field('county'),
                Field('state_name'),
                Field('zip'),
                Field('phone1'),
                Field('phone2'),
                Field('email', requires=IS_EMAIL()),
                Field('web')
                )
`
[code.txt](https://github.com/web2py/web2py/files/2973067/code.txt)

2. Download and unpack attached CSV file:
[us-500.zip](https://github.com/web2py/web2py/files/2973002/us-500.zip) (Also you can download "us-500.csv" from  https://www.briandunning.com/sample-data/ they shall be same)
3. Return to the administrative interface, select Manage/Edit onto the project you create.
4. Press the button "**database administration**" under the **Model** label.
5. Press "db.contacts".
6. Under the label "**Import/Export**" press **Browse** button
7. Select unpacked CSV
8. Press **import** button.
9. Get same table as it was before(unchanged), and some bubble about the error(which one does not fin into buble).

**Screenshot**
![Screenshot at 2019-03-16 04-45-11](https://user-images.githubusercontent.com/47660494/54463643-5c49e280-47a6-11e9-96e2-6e8757db41b0.png)

**Expected behavior**
Load CSV into DB table.

**Desktop (please complete the following information):**
 - OS: Linux 5.0.1-arch-1-ARCH (x86_64)
 - Browser Firefox 65.0.2
-  Python 3.7.2
-  web2py  2.18.4-stable+timestamp.2019.03.13.05.27.54

**Comment by Mad-onanist** [comment]
Any help please?
I cant continue the course without it. =(
I tried to do same thing on python hosting, same problem, so that is not only on my machine, for sure.

**Comment by Mad-onanist** [comment]
Oh. I do that!

> 2.17.1-stable+timestamp.2018.08.06.01.02.56
(Running on Unknown, Python 2.7.12) 

So, on damn old python 2.7 that is works well! On 3.7 - nope.

**Comment by Mad-onanist** [comment]
Well, i assume the problem is solved, in stupid wai(pitonic?) but who cares?

**Comment by tdean1991** [comment]
The issue is that the utf8_data object is a binary stream object. Wrapping it with a TextIOWrapper resolves the issue.

**Comment by tdean1991** [comment]
In objects.py line 63 add gthe line
text_wrapper = TextIOWrapper(utf8_data,encoding)
You'll also have to import the class at the top of the module
from io import TextIOWrapper

**Comment by GermanPZ** [comment]
In the current CSV file available on the briandunning webpage, you have to change the name of the column 'state' to 'state_name', to match with your code.

**Comment by KDEE14** [comment]
@tdean1991. I am new to python and in learning phase. I am getting the same issue as listed here. I was trying to do your fix as suggested, but i do not see a objects.py file. Could you guide me on where to fix this. I am posting the picture of what i see on models and controllers. Thanks

![image](https://user-images.githubusercontent.com/37987053/79332924-a8a4ac00-7eeb-11ea-9aed-c26f3dd4c73c.png)

**Comment by AnooshaAviligonda** [comment]
In ~/path/to/⁨web2py⁩/⁨gluon⁩/packages⁩/⁨dal⁩/pydal⁩/objects.py, find the below line in function '_csv_reader_': 
_csv_reader = csv.reader(utf8_data, dialect=dialect, **kwargs)_
Replace the above line with the below line:
_csv_reader = csv.reader(TextIOWrapper(utf8_data,encoding), dialect=dialect, **kwargs)_

to import _TextIOWrapper_ add the below line:
_from io import TextIOWrapper_

**Comment by ferarm** [comment]
This is now working for me.

**Comment by ferarm** [comment]
> In ~/path/to/⁨web2py⁩/⁨gluon⁩/packages⁩/⁨dal⁩/pydal⁩/objects.py, find the below line in function '_csv_reader_':
> _csv_reader = csv.reader(utf8_data, dialect=dialect, **kwargs)_
> Replace the above line with the below line:
> _csv_reader = csv.reader(TextIOWrapper(utf8_data,encoding), dialect=dialect, **kwargs)_
> 
> to import _TextIOWrapper_ add the below line:
> _from io import TextIOWrapper_

This is not working for me.

**Comment by mahatmaheil** [comment]
I am having the same issue. 

1. If I want to change Python version in Web2Py, how do I do it?
2. I would prefer not to change Python version. How can I change my CSV file so it will upload properly. 

I've almost had it with these courses. I spend more time fixing errors than I do learning how to code.

**Comment by mahatmaheil** [comment]
The hearted one worked. You have to drop the import further up the file.

**Comment by tdrobison** [comment]
I am getting this even after making the TextIOWrapper change in objects.py.  Too bad, this looks like a great framework, but I will probably abandon it on the first day and go back to django...

**Comment by Blakester609** [comment]
@tdrobison I had the same issue, and the hearted solution worked for me.

**Comment by dougincolorado** [comment]
Same issue here even after applying hearted fix above. Any help much appreciated. 
Web2py 3
Python 3.6

**Comment by ada7070** [comment]
> @tdrobison I had the same issue, and the hearted solution worked for me.

hello, i have same issue too,  you say" the hearted solution worked for me". what is that solution. could you help me

**Comment by jpsteil** [comment]
Look at the response by AnooshaAviligonda

**Comment by ada7070** [comment]
Thank you, thank you, thank you. Now it works

22 Mar 2021 Pzt 20:33 tarihinde Jim Steil ***@***.***> şunu
yazdı:

**Comment by ada7070** [comment]
thank you very very much. now it works

**Comment by pangard** [comment]
This is closed, but the error is still alive and the fix never made it into the web2py source code :-O
Should we write a PR for this issue?

**Comment by ilcaa72** [comment]
i did exactly as the hearted solution. I copied and pasted to make sure no typing error, i added the import io as well BUT same issue

i did restart server as well... same problem... i have a very basic csv for testing and i get the error...  anything else i can check?  thanks for any help!
