### ISSUE TITLE
Grid's selectable checkboxes don't appear in Google Chrome (they appear in IE and Firefox)

### ISSUE THREAD

**Issue by jcrmatos** [web2py/web2py#2153]
Grid's selectable checkboxes don't appear in Google Chrome (they appear in IE and Firefox).

Windows 7 Pro x64 SP1+all updates
Python 3.7.1 x86
web2py 2.18.4

Firefox 65.0.2 x64
IE 11
Google Chrome 73.0.3683.75 (Official Build) (64-bit)

**Comment by Kkeller83** [comment]
How did you resolve it?

**Comment by jcrmatos** [comment]
It was a CSS configuration on my end. The strange thing is that it only affected Google Chrome.
I had this to center the grid's checkboxes columns in the web2py-bootstrap4.css
```
.web2py_grid_wo input[type="checkbox"] {
    text-align: center;
    width: 100%;
}
```
And that was causing Google Chrome to not show the selection checkboxes. They were there (in the HTML code), they simply were not shown.
I added this to solve it.
```
.web2py_grid_wo input[name="records"] {
    text-align: left;
    width: auto;
}
```
