### ISSUE TITLE
Virtualfields representation is broken in SQLFORM.grid

### ISSUE THREAD

**Issue by misl6** [web2py/web2py#2155]
**Describe the bug**
When using a virtualfield in SQLFORM.grid, raise KeyError 

**To reproduce**

`
db.define_table('demo',
                Field('stato', 'string', requires=IS_IN_SET(['Aperta',
                                                             'Chiusa']),
                      default='Aperta'),
                Field('caso', 'integer'),
                Field('codice', 'string'),
                Field('data_inserimento', 'datetime', default=request.now))
`

`
db.demo.prova = Field.Virtual('prova', lambda row: "INFO" if row.demo.caso == 3 else row.demo.stato, label="Label di prova")
`

`
SQLFORM.grid(qry,
                                        links=[...
                                        ],
                                        fields=[
                                        .....
                                            db.demo.prova,
....],
                                        maxtextlength=100,
                                        paginate=25,
                                        details=False,
                                        advanced_search=True,
                                        create=False,
                                        deletable=False,
                                        editable=False,
                                        csv=False,
                                        user_signature=True)
`

**Comment by mdipierro** [comment]
I believe that between the changes made by P.Pastori and your merged PR, this issue can be close. If not, let's discuss on the mailing list.
