### ISSUE TITLE
QR Code Printable Vote Links

### ISSUE THREAD

**Issue by HaraldPaterek** [web2py/web2py#2169]
**Is your feature request related to a problem? Please describe.**
The bylaws of our organization do require that only members physically present can vote. I need to ensure that the person present is the person casting the vote.

**Describe the solution you'd like**
Instead of mailing people a link to vote, I want to hand them a piece of paper with a QR Code which points to the voting link. I want to be able to pre-generate a defined number of QR Codes (equal to the number of eligible voters and print them with the name of the election and the question(s).

**Describe alternatives you've considered**
Sending out the e-mails at the start of the meeting to those present. This would be too cumbersome.

**Additional context**

**Comment by leonelcamara** [comment]
How is this a web2py issue?

Just generate the qrcode images using something like:
https://github.com/lincolnloop/python-qrcode

This can be as simple as in a controller function putting something like:

    import qrcode
    qr = qrcode.QRCode()
    qr.add_data(URL('default', 'index', args=['YOUR_SECRET_UUID'], extension='', scheme=True, host=True))
    qr_img = qr.make_image()
    # now do something with that image

**Comment by HaraldPaterek** [comment]
My apologies, I filed it under the wrong project. Please close this.

**Comment by leonelcamara** [comment]
@HaraldPaterek ahahah no problem :) you can close it yourself it's your issue.
