### ISSUE TITLE
Cannot handle syntax errors

### ISSUE THREAD

**Issue by unle70** [web2py/web2py#2174]
When making a syntax error in a controller, upon pressing the CTRL-S to save, web2py reports "Communication Error". If trying to press CTRL-S again, it will show the inconsistency form where you can merge Old and New versions. 

No matter how you try to handle the situation in this form, you cannot really modify the code and fix the problem. You also cannot tell where the problem actually IS. 

When trying to re-open the Admin application and go to Edit the site, it shows the error ticket and doesn't open the form with the names of Models, Controllers, Views, etc. You can open the ticket and see where the problem is.

The only way to solve the problem at this time is to use an external editor,  correct the error, and then the Admin can be opened again.

I'm using the following configuration: 
2.18.4-stable+timestamp.2019.03.13.05.27.54
(Running on Rocket 1.2.6, Python 3.7.3)

If anyone has the time an knowledge for looking into this issue, I would for sure appreciate.

Thanks,
Udi

**Comment by leonelcamara** [comment]
Can you try 2.18.5, this should be fixed.

**Comment by unle70** [comment]
Indeed problem solved!
Thank you so much.
