### ISSUE TITLE
Appconfig: protect connection string with commas within double quotes

### ISSUE THREAD

**Issue by bobim** [web2py/web2py#2176]
MSSQL connection strings can contain commas and the default appconfig reader behavior is to split the string which is not desired.

For example there is a comma between the instance name and the port:
mssql4://SERVER=server.domain.com\instance_name,40001;DATABASE=dbname;DRIVER={SQL Server};USER=username

Modifying the relevant section of gluon/contrib/appconfig.py from:

            elif value.isdigit() or (value[0]=='-' and value[1:].isdigit()):
                return int(value)
            elif ',' in value:
                return map(lambda x:x.strip(),value.split(','))
            else:
to:

            elif value.isdigit() or (value[0]=='-' and value[1:].isdigit()):
                return int(value)
            elif '"' == value[0]:
                return value.lstrip('"').strip('"')
            elif ',' in value:
                return map(lambda x:x.strip(),value.split(','))
            else:

allows to protect the string by enclosing it in double quotes in the appconfig.ini file.

**Comment by niphlod** [comment]
python is not .NET.... separating host and port with comma is absolutelly not required.....separate it with `:` (bonus points, it's supported in nearly every other adapter).

If you wanna resort to odbc style connstrings, you can use the DSN notation .

No need to alter anything on web2py/pyDAL's side.

**Comment by bobim** [comment]
I received the connection strings from the server team and never thought about challenging them. I'll go for the colon separator then, thank you for the hint and sorry for the noise.

**Comment by niphlod** [comment]
np, it happens.
