### ISSUE TITLE
Error "REGEXing" the mysql uri, making failure of connection

### ISSUE THREAD

**Issue by advh67** [web2py/web2py#2183]
I just updated my web2py version to current, 2019-04-08, and my webpages started to fail:

<type 'exceptions.RuntimeError'> Failure to connect, tried 5 times: Traceback (most recent call last): File "/home/advh67/web2py/gluon/packages/dal/pydal/base.py", line 457, in __init__ self._adapter = adapter(**kwargs) File "/home/advh67/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 39, in __call__ obj = super(AdapterMeta, cls).__call__(*args, **kwargs) File "/home/advh67/web2py/gluon/packages/dal/pydal/adapters/base.py", line 369, in __init__ super(SQLAdapter, self).__init__(*args, **kwargs) File "/home/advh67/web2py/gluon/packages/dal/pydal/adapters/base.py", line 53, in __init__ self.reconnect() File "/home/advh67/web2py/gluon/packages/dal/pydal/connection.py", line 174, in reconnect self.connection = self.connector() File "/home/advh67/web2py/gluon/packages/dal/pydal/adapters/mysql.py", line 51, in connector return self.driver.connect(**self.driver_args) File "/usr/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect return Connection(*args, **kwargs) File "/usr/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__ super(Connection, self).__init__(*args, **kwargs2) TypeError: 'password' is an invalid keyword argument for this function 

The file web2py/gluon/packages/dal/pydal/adapters/mysql.py has a different REGEX_URI string, I presume a little mistake on it provokes the 'password' parameter be unrecognized.
If I owerwrite the mysql.py/mysql.pyc of current web2py 2019-04-08 with the older web2py version 2018-10-06, my applications work again.

edit: the new gluon/contrib/redis_cache.py fails too, and gets "fixed" overwriting with files of previous version 2018-10-06.

**Comment by mdipierro** [comment]
This was fixed in pydal
