### ISSUE TITLE
site unreacheable

### ISSUE THREAD

**Issue by tyoc213** [web2py/web2py#2195]
**Describe the bug**
visit http://web2py.org/

**To Reproduce**
**Screenshots**

![image](https://user-images.githubusercontent.com/506234/57094759-ea3a4800-6cd6-11e9-9267-358730758429.png)
**Expected behavior**
Site reacheable.

**Comment by leonelcamara** [comment]
Why are going to web2py.org instead of web2py.com?

**Comment by tyoc213** [comment]
Oh my gosh, it should have been a combination or suguestion...
