### ISSUE TITLE
I get a strange syntax error if I divide a = web2py "command" in 2 lines inside a HTML file

### ISSUE THREAD

**Issue by jcrmatos** [web2py/web2py#2197]
Hello,

If I use this code, everything works

`          =A(T('You have unread notifications'), _href=URL('default', 'index', user_signature=True)) if count else ''
`

However, if I divide it in 2 lines, using proper ( ), I get a syntax error

```
          =(A(T('You have unread notifications'),
                _href=URL('default', 'index', user_signature=True)) if count else '')

```
Is this the correct behavior of web2py = "command" parsing?

Thanks,

JM

My env:
web2py 2.18.5
Python 3.7.1 x86
Firefox 66.0.3 x64
Windows 7 Pro x64 SP1+all upd

**Comment by leonelcamara** [comment]
That's due to the way = is implemented, however equal is just a shortcut
for response.write which you can use in this case.

**Comment by jcrmatos** [comment]
Ok, thanks for the explanation Leonel.
