### ISSUE TITLE
redis session with python3 throws KeyError: 'unique_key'

### ISSUE THREAD

**Issue by rastafarien** [web2py/web2py#2204]
Hello

To reproduce

Configure session support by redis in a model file as explained in the documentation 

from gluon.contrib.redis_utils import RConn
from gluon.contrib.redis_session import RedisSession
rconn = RConn(host='redis',port=6379)
sessiondb = RedisSession(redis_conn=rconn, session_expiry=False)
session.connect(request, response, db = sessiondb)

the application starts but when you want to login you get this error

Traceback (most recent call last):
  File "/usr/local/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/usr/local/web2py/applications/bobapp/models/db.py", line 23, in <module>
    session.connect(request, response, db = sessiondb)
  File "/usr/local/web2py/gluon/globals.py", line 966, in connect
    row = table(record_id, unique_key=unique_key)
  File "/usr/local/web2py/gluon/contrib/redis_session.py", line 117, in __call__
    row = q.select()
  File "/usr/local/web2py/gluon/contrib/redis_session.py", line 189, in select
    if rtn['unique_key'] == self.unique_key:
KeyError: 'unique_key'

Remarks :
- I use web2py Version 2.18.5-stable
- I use python3.7 under alpine (docker)
- i use redis  python module v 2.10.6 ( newer versions have other problems )
 
It is a different problem than bug#1987 although it looks similar and I use a 

thanks for your help

**Comment by rastafarien** [comment]
Update:
This Bug is reproducible with python3.5, 3.6, 3.7  on welcome application on a fresh ubuntu install
It does not occur with python2.7

monitoring activity on redis shows that the error comes after fetching values in redis db:
1557958512.733244 [0 172.17.0.1:54184] "HGETALL" "w2p:sess:welcome:1"

dump of db content : 

redis-cli keys *
1) "w2p:sess:welcome:serial"
2) "w2p:sess:welcome:id_idx"
3) "w2p:sess:welcome:1"

it should be (based on monitoring under python2.7 that just works fine)

1557959649.706709 [0 172.17.0.1:56680] "HGETALL" "w2p:sess:welcome:1"
1557959649.728387 [0 172.17.0.1:56680] "EXISTS" "w2p:sess:welcome:1"
1557959649.728689 [0 172.17.0.1:56680] "MULTI"
1557959649.728701 [0 172.17.0.1:56680] "HMSET" "w2p:sess:welcome:1" "client_ip" "127.0.0.1" "session_data" "\x80\x02cgluon.globals\nSession\nq\x01}q\x02U\x0f_formkey[login]q\x03]q\x04(U$9f5ec384-ef91-4ff0-90e1-b441971d7296q\x05U$01531070-5c1d-4ed7-9034-1c02e7cd2a9eq\x06es\x85Rq\a." "locked" "False" "modified_datetime" "2019-05-16 00:34:09.703162" "unique_key" "d87a37e8-5037-43be-9888-98c92f210e45"
1557959649.728774 [0 172.17.0.1:56680] "EXEC"

In (first and very partial) conclusion with python3.x session data are not successfully written in redis

**Comment by onetwomany** [comment]
I got it to work by making the following changes

index a3b95d3..3c9bf4c 100644
--- a/gluon/globals.py
+++ b/gluon/globals.py
@@ -1055,7 +1055,7 @@ class Session(Storage):
             if record_id.isdigit() and long(record_id) > 0:
                 new_unique_key = web2py_uuid()
                 row = table(record_id)
-                if row and row['unique_key'] == unique_key:
+                if row and row['unique_key'].decode('utf-8') == unique_key:
                     table._db(table.id == record_id).update(unique_key=new_unique_key)
                 else:
                     record_id = None

and

diff --git a/gluon/contrib/redis_session.py b/gluon/contrib/redis_session.py
index 8639f49..214bf90 100644
--- a/gluon/contrib/redis_session.py
+++ b/gluon/contrib/redis_session.py
@@ -13,7 +13,6 @@ from gluon import current
 from gluon.storage import Storage
 from gluon.contrib.redis_utils import acquire_lock, release_lock
 from gluon.contrib.redis_utils import register_release_lock
-from gluon._compat import to_bytes

 logger = logging.getLogger("web2py.session.redis")

@@ -182,11 +181,11 @@ class MockQuery(object):
             key = self.keyprefix + ':' + str(self.value)
             if self.with_lock:
                 acquire_lock(self.db.r_server, key + ':lock', self.value, 2)
-            rtn = self.db.r_server.hgetall(key)
+            rtn = {k.decode('utf-8'):v for k,v in self.db.r_server.hgetall(key).items()}
             if rtn:
                 if self.unique_key:
                     # make sure the id and unique_key are correct
-                    if rtn['unique_key'] == self.unique_key:
+                    if rtn['unique_key'].decode('utf-8') == self.unique_key:
                         rtn['update_record'] = self.update  # update record support
                     else:
                         rtn = None



[globals_patch.txt](https://github.com/web2py/web2py/files/3240682/globals_patch.txt)
[redis_session_patch.txt](https://github.com/web2py/web2py/files/3240683/redis_session_patch.txt)

**Comment by rastafarien** [comment]
Hi
I ended up with pretty much the same code as you.
I'm glad to see that you have pointed the same 2 culprits ( globals and
redis_sessions) because I was not 100% confident.
Nevertheless according to me we need additional corrections though to make
it work with redis 3 (latest major version)

1/ Redis does not support bool so I replaced False by 0
2/ Redis does not support datetime so I replaced datetime by str(datetime)

To avoid confusion the patch attached takes onetomany's modifications and
mine in the same patch file

To apply it go in the web2py directory and do patch -p0 --dry-run <
patch_web2py_redis3_python3

Best regards
Stephane

**Comment by rastafarien** [comment]
patch file was missing. attached below. 
[patch_web2py_redis3_python3.txt](https://github.com/web2py/web2py/files/3244253/patch_web2py_redis3_python3.txt)
