### ISSUE TITLE
IS_STRONG validator does not function right with special=0 argument

### ISSUE THREAD

**Issue by uzfred** [web2py/web2py#2209]
**Describe the bug**
With IS_STRONG  argument special=0, field entries won't pass the validation test, even if they should.

**To Reproduce**
Create form with IS_STRONG validator and argument special=0 (i.e. password validation at user registration).
Try registration with password that fulfills the requirements.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version most up-to-date versions
(Problem is probably unrelated to platform.)

**Additional context**
Looking at the web2py code of the IS_STRONG validator (we2py\gluon\packages\dal\pydal\validators.py) in my current working version (Version 2.18.5-stable+timestamp.2019.04.08.04.22.03) and in comparison with the current master on github, the probably responsible lines of code (3152-3162 in current github master) already appear to have been changed, but by looking at the new code, I suspect the problem to not have been fixed just yet.

From current master:

>        if isinstance(self.special, int):
>             all_special = [ch in value for ch in self.specials]
>             if self.special > 0:
>                 if not all_special.count(True) >= self.special:
>                     failures.append(self.translator("Must include at least %s of the following: %s")
>                                     % (self.special, self.specials))
>             elif self.special == 0 and self.special is not False:
>                 if len(all_special) > 0:
>                     failures.append(self.translator("May not contain any of the following: %s")
>                                                                  % self.specials)

The line
`if len(all_special) > 0:`
will result in true unless the standards specials string has not been cleared completly, resulting in the failure to be appended unrelated to the string that is being validated.

Our suggested fix would be to substitute that line with
`len(filter(lambda x: x, all_special)) > 0`
instead. This should result in the wished for behaviour of restricting the use of special characters in the string being validated (currently untested).

**Comment by mdipierro** [comment]
Thanks. Fixed in
