### ISSUE TITLE
Missing bootstrap4 and row class in addrow method

### ISSUE THREAD

**Issue by romicasal** [web2py/web2py#2217]
Hello, I'm using recaptcha in auth settings but form is not showing as expected.
I solved this adding bootstrap4 condition:

`elif style in ("bootstrap3_inline", "bootstrap4_inline")`

`elif style in ("bootstrap3_stacked", "bootstrap4_stacked")`

https://github.com/web2py/web2py/blob/409a499dd014195c5a7945eb3d160104bdce5341/gluon/tools.py#L987

https://github.com/web2py/web2py/blob/409a499dd014195c5a7945eb3d160104bdce5341/gluon/tools.py#L992

And adding 'row' to 

https://github.com/web2py/web2py/blob/409a499dd014195c5a7945eb3d160104bdce5341/gluon/tools.py#L991
https://github.com/web2py/web2py/blob/409a499dd014195c5a7945eb3d160104bdce5341/gluon/tools.py#L995

**Comment by mdipierro** [comment]
Sorry this took forever.
