### ISSUE TITLE
Tag R-2.18.5

### ISSUE THREAD

**Issue by angeloc** [web2py/web2py#2239]
Could you tag the latest released version R-2.18.5 ?

**Comment by fland0ch** [comment]
fully agree to angeloc, please tag the latest released version to R-2.18.5.
Highly appreciated, Thanks!

**Comment by angeloc** [comment]
Any news?

**Comment by angeloc** [comment]
Ping

**Comment by kszys** [comment]
I tried to upgrade to the latest version using a cloned repo and run into the same thing... Sadly it seems the maintenance of web2py is not what it used to be :(

**Comment by angeloc** [comment]
Is web2py dying?

**Comment by leonelcamara** [comment]
@mdipierro ping. You're probably about to do another release don't forget this one too.

**Comment by angeloc** [comment]
@mdipierro : any news?

**Comment by mdipierro** [comment]
Sorry kind of swamped at work. Will do it asap

**Comment by angeloc** [comment]
@mdipierro : any news here?
