### ISSUE TITLE
Dash-named python files do not get processed

### ISSUE THREAD

**Issue by bryanpedini** [web2py/web2py#2251]
**Described bug:**
A single dash could save my life...
Or break my Web2py website.

**Steps to reproduce the behavior:**
1. Create a new app, even an empty one
2. Create a new file in the any folder that contains python code, with a dash in the filename
3. Write a `print` line in that file
4. Nothing happens

**Expected behavior:**
File should be loaded during models evaluation

**Screenshots:**
![underscored](https://user-images.githubusercontent.com/45012292/64008447-6c683b00-cb16-11e9-9358-343d2aab37aa.png)
![dashed](https://user-images.githubusercontent.com/45012292/64008431-65412d00-cb16-11e9-82eb-f594b3fb32e4.png)
![controller](https://user-images.githubusercontent.com/45012292/64009700-9e7a9c80-cb18-11e9-8414-f6c3e0614af0.png)

**Desktop informations:**
 - OS: Doesn't matter (Tested with Linux Mint Mate 19.2 Tina and Windows 10 v1903 x86_amd64)
 - Browser: Doesn't matter (Tested with Firefox 68.0.2 (64-bit) and Chrome 76.0.3809.100 (64-bit))
 - W2P Version: Does matter (2.18.5-stable+timestamp.2019.04.08.04.22.03)

**Additional context:**
I usually prefer to use names like _000-db.py_, _001-authentication.py_ and so on so forth, to efficiently determine which file gets executed first.
Yes, I could use underscores, those in fact work just fine in web2py...
But why in the hell a single character would break an entire website if anybody one day decides to rename all the models to a dashed-filenames scheme?

**Comment by Bryanpedini** [comment]
CHANGELOG:
- Issue created
- Edited _controller_ image (didn't notice that function name was not correct, but it didn't matter)

**Comment by leonelcamara** [comment]
This is indeed a bug, but...  
  
You really should not use dashes in a python file's name. One reason this can break is that regular importing doesn't work. I understand you prefer dashes, but you should adapt your style to the language you're using, python style guide recommends underscores or nothing https://www.python.org/dev/peps/pep-0008/#package-and-module-names

If you want dashes in the URL you can use the URL rewrite features web2py has.

**Comment by bryanpedini** [comment]
Considering this issue closed due to lack of activity and the fact that Python itself has this "thing" and not just W2P.
