### ISSUE TITLE
xmlrpc python 3 error

### ISSUE THREAD

**Issue by zhang-c** [web2py/web2py#2262]
**Describe the bug**
xmlrpc error in Python 3 (not in python 2) 

**To Reproduce**
1. Run web2py 2.18.5 in Python 3.7, using either Rocket or Azure

On client side try to run the following code: 
server = ServerProxy('https://127.0.0.1/myapp/query/call/xmlrpc', context=ssl._create_unverified_context())
server.test_xmlrpc()

2. Get the error:
xmlrpclib.ProtocolError: <ProtocolError for 127.0.0.1/myapp/query/call/xmlrpc: 500 INTERNAL SERVER ERROR>

3. See the traceback error in web2py admin interface:
Traceback (most recent call last):
  File "R:\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "R:\web2py\applications\myapp\models\db.py", line 321, in <module>
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaa')
  File "R:\web2py\gluon\tools.py", line 884, in __init__
    self.request_vars = request and request.vars or current.request.vars
  File "R:\web2py\gluon\globals.py", line 316, in vars
    self.parse_all_vars()
  File "R:\web2py\gluon\globals.py", line 287, in parse_all_vars
    for key, value in iteritems(self.post_vars):
  File "R:\web2py\gluon\globals.py", line 308, in post_vars
    self.parse_post_vars()
  File "R:\web2py\gluon\globals.py", line 244, in parse_post_vars
    dpost = cgi.FieldStorage(fp=body, environ=env, keep_blank_values=1)
  File "c:\python37\lib\cgi.py", line 491, in __init__
    self.read_single()
  File "c:\python37\lib\cgi.py", line 682, in read_single
    self.read_binary()
  File "c:\python37\lib\cgi.py", line 704, in read_binary
    self.file.write(data)
  File "c:\python37\lib\tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
TypeError: write() argument must be str, not bytes

**Comment by liuyigh** [comment]
I have similar errors from cgi.py:

```Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/gapdb/compiled/models.db.py", line 187, in <module>
  File "/home/www-data/web2py/gluon/tools.py", line 884, in __init__
    self.request_vars = request and request.vars or current.request.vars
  File "/home/www-data/web2py/gluon/globals.py", line 316, in vars
    self.parse_all_vars()
  File "/home/www-data/web2py/gluon/globals.py", line 287, in parse_all_vars
    for key, value in iteritems(self.post_vars):
  File "/home/www-data/web2py/gluon/globals.py", line 308, in post_vars
    self.parse_post_vars()
  File "/home/www-data/web2py/gluon/globals.py", line 244, in parse_post_vars
    dpost = cgi.FieldStorage(fp=body, environ=env, keep_blank_values=1)
  File "/usr/local/pyenv/versions/miniconda3-latest/lib/python3.7/cgi.py", line 486, in __init__
    self.read_single()
  File "/usr/local/pyenv/versions/miniconda3-latest/lib/python3.7/cgi.py", line 665, in read_single
    self.read_binary()
  File "/usr/local/pyenv/versions/miniconda3-latest/lib/python3.7/cgi.py", line 687, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes```

**Comment by zhang-c** [comment]
I found "request.vars.type" is a bug in db.py. During xmlrpc call, the request.vars.type will be None, which will cause the cgi errors. I guess your have the similar problem. Once the request.vars.type problem is solved, there are no errors.

> I have similar errors from cgi.py:
> 
> Python 3.7.0 + Web2py2.18.5 + uWSGI 2.0.18
> 
> ```
>   File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
>     exec(ccode, environment)
>   File "/home/www-data/web2py/applications/gapdb/compiled/models.db.py", line 187, in <module>
>   File "/home/www-data/web2py/gluon/tools.py", line 884, in __init__
>     self.request_vars = request and request.vars or current.request.vars
>   File "/home/www-data/web2py/gluon/globals.py", line 316, in vars
>     self.parse_all_vars()
>   File "/home/www-data/web2py/gluon/globals.py", line 287, in parse_all_vars
>     for key, value in iteritems(self.post_vars):
>   File "/home/www-data/web2py/gluon/globals.py", line 308, in post_vars
>     self.parse_post_vars()
>   File "/home/www-data/web2py/gluon/globals.py", line 244, in parse_post_vars
>     dpost = cgi.FieldStorage(fp=body, environ=env, keep_blank_values=1)
>   File "/usr/local/pyenv/versions/miniconda3-latest/lib/python3.7/cgi.py", line 486, in __init__
>     self.read_single()
>   File "/usr/local/pyenv/versions/miniconda3-latest/lib/python3.7/cgi.py", line 665, in read_single
>     self.read_binary()
>   File "/usr/local/pyenv/versions/miniconda3-latest/lib/python3.7/cgi.py", line 687, in read_binary
>     self.file.write(data)
> TypeError: write() argument must be str, not bytes```
> ```

**Comment by zhang-c** [comment]
It seems that the request.vars.type is not existing or None for xmlrpc, which causes there errors. I am not sure if it is a bug in web2py or not,

**Comment by zhang-c** [comment]
Sorry, I reported a wrong bugfix previously. Actually, I did following and fixed the errors:

In the gluon.globals.py:
dpost = cgi.FieldStorage(fp=body, environ=env, keep_blank_values=1)
changed into:
dpost = cgi.FieldStorage(fp=body.decode(), environ=env, keep_blank_values=1)

**Comment by liuyigh** [comment]
it seems the fix breaks the admin app:

Traceback (most recent call last):  
File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted    
`exec(ccode, environment)  `
File "/home/www-data/web2py/applications/admin/models/access.py", line 143, in <module>    
`if request.vars.is_mobile in ('true', 'false', 'auto'):`
AttributeError: 'NoneType' object has no attribute 'is_mobile'

**Comment by zhang-c** [comment]
The following code works for me.
try:
    dpost = cgi.FieldStorage(fp=body, environ=env, keep_blank_values=1)
except:
    try:
        dpost = cgi.FieldStorage(fp=body.decode(), environ=env, keep_blank_values=1)
    except:
        dpost = cgi.FieldStorage(fp=body, environ=env, keep_blank_values=1)

**Comment by liuyigh** [comment]
cool it works!

**Comment by liuyigh** [comment]
@mdipierro 

it seems your fix also breaks the admin app:

Traceback (most recent call last):
File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
exec(ccode, environment)
File "/home/www-data/web2py/applications/admin/models/access.py", line 143, in
if request.vars.is_mobile in ('true', 'false', 'auto'):
AttributeError: 'NoneType' object has no attribute 'is_mobile'

**Comment by mdipierro** [comment]
Is this in the stable release?

**Comment by liuyigh** [comment]
I see. It is a part of many other release level fixes. I was only changing one file `globals.py` according to the fix above, in 2.18.5. I guess it won't work by itself.

I will update to 2.19 later and let you know.

**Comment by flavour** [comment]
I see this same issue with my GIS: WFS (Web Feature Service) layers use a Web2Py controller as a ProxyHost to fix the same origin issue.

The issue happen because we have a content-length header but no content-disposition to read a filename (there is no filename...just a Text payload)...Python's cgi.py uses the latter to decide whether to set self._binary_file but the former to decide whether to call self.read_binary()
The former causes it to create a text TemporaryFile instead of bytes
Which then read_binary() tries to write to as bytes

So to me this looks like a problem with Python (& still present in Python trunk) rather than in Web2Py.
There is nothing in the spec to say that Content-Length can only be used for Binary files:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length

**Comment by flavour** [comment]
https://bugs.python.org/issue27777
