### ISSUE TITLE
Form validation fails in 2.18.5 

### ISSUE THREAD

**Issue by kszys** [web2py/web2py#2279]
I tried to upgrade to a new version of web2py (2.18.5). I downloaded the source from the website (last stable version available 2.18.5). And the code that used to work fine before is not working any more.

When calling:
```
if form.process(keep_values=True,onvalidation=check_offer_price).accepted:
```

Even though the function is defined in the same file:
```
def check_offer_price(form):
```

This fails with the following message in the console:
```
$ Traceback (most recent call last):
  File "/opt/web2py/gluon/html.py", line 1890, in _validate
    (value, errors) = validator(value)
  File "/opt/web2py/gluon/packages/dal/pydal/validators.py", line 145, in __call__
    return self.validate(value), None
  File "/opt/web2py/gluon/packages/dal/pydal/validators.py", line 2764, in validate
    return validator_caller(self.other, value)
  File "/opt/web2py/gluon/packages/dal/pydal/validators.py", line 153, in validator_caller
    value, error = func(value)
TypeError: 'NoneType' object is not callable
```

It seems that `onvalidation` function is never called. The validation fails somewhere earlier. I downgraded back to version 2.17.2 and everything works again... I guess will have to stay with this version forever :(

**Comment by leonelcamara** [comment]
Can you try the version in master, I think this is fixed already.
