### ISSUE TITLE
"from cgi import escape" is broken in Python 3.8

### ISSUE THREAD

**Issue by dullfig** [web2py/web2py#2288]
Trying to run web2py under Python 3.8 results in an error; can't import escpape from cgi in file \gluon\languages.py line 19

I changed line 19 to 
"from html import escape"

and web2py starts up without errors

**Comment by miversen33** [comment]
Another workaround I found is using python 3.6 (without having to change the import).

**Comment by mdipierro** [comment]
this appears to be fixed.
