### ISSUE TITLE
Plugin app BUG on 2.19.1 version with python 3.7 - SOLVED

### ISSUE THREAD

**Issue by attiquetecnologia** [web2py/web2py#2317]
**Describe the bug**
A ticket generate when I try install new plugins on my app. Using the python 3.7. The web2py used is 2.19.1.

**To Reproduce**
1. Go to appadmin of app
2. Click in Plugins
3. Click in installed plugin

**Expected behavior**
Ticket number
127.0.0.1.2020-05-04.10-23-24.0c4a822a-07ec-4977-afa7-422444fe6c69
<class 'NameError'> name 'regex_tables' is not defined

Version
web2py™ | Version 2.19.1-stable+timestamp.2020.03.21.21.49.28
Python 3.7.7: C:\Python37\python.exe (prefix: C:\Python37)

**Screenshots**
https://1.bp.blogspot.com/-KdppqUKuCJg/XrAZF4Maj5I/AAAAAAAACy0/DMvCwa9UGMctXbZKN_HtxyM1c3z6FSZggCLcBGAsYHQ/s1600/ticket1.JPG

https://1.bp.blogspot.com/-K5lbD7JyfgA/XrAZGzCB_lI/AAAAAAAACy4/RKJpFRQ-H-QEE_OZOpUZgGmfMmgZBM7GgCLcBGAsYHQ/s1600/ticket2.JPG

https://1.bp.blogspot.com/-8lLMxOTR8sc/XrAZISkIDBI/AAAAAAAACy8/H-UWKpiilag3_zO5p_OB9snTPGJDiwhfQCLcBGAsYHQ/s1600/ticket3.JPG

**Additional context**

**Comment by leonelcamara** [comment]
This was fixed here:

https://github.com/web2py/web2py/commit/3f2b1fe9ca5edbc0763c257971067ab65ec91f84

**Comment by attiquetecnologia** [comment]
Thank you. I upgrade to new version. It's working.
