### ISSUE TITLE
<type 'exceptions.ValueError'> unsupported pickle protocol: 3

### ISSUE THREAD

**Issue by attiquetecnologia** [web2py/web2py#2329]
**Describe the bug**
When running web2py_src on python27 (download from web2py python27 and download from python3), a ticket is generated. Something related to auth.define_tables (username = False, signature = False).
Web2py 2.20.4 runs only with python 3.7.

**To Reproduce**
1. Run web2py using python27
2. Access default/index or anyway.
3. Ticket generate

**Expected behavior**

**Screenshots**

web2py™ | Version 2.20.4-stable+timestamp.2020.05.03.05.18.50
-- | --
Python 2.7.17: C:\Python27\python.exe (prefix: C:\Python27)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: All browsers

**Comment by leonelcamara** [comment]
This was due to incompatible pickle formats between py2 and py3, I think you just needed to fake migrate to remake the table files.
