### ISSUE TITLE
Unable to login when using redis for storing sessions

### ISSUE THREAD

**Issue by houdinihound** [web2py/web2py#2330]
Basically a new session is created on each page load so the login is never established.

Issue discussed at: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/web2py/6Ig5YVgvIsI/HpueAUELBgAJ

Confirmed with web2py versions from 2.18.5 up to 2.20.4.  Python versions 3.6 and 3.8

**Comment by dburba** [comment]
I can confirm the issue with web2py v2.20.4 ant python 3.6. Can not login when redis is used for sessions storage

**Comment by dburba** [comment]
Neither works on v2.21.1 with python 3.8. Is this bug going to get any attention?
