### ISSUE TITLE
search function in app edit broken

### ISSUE THREAD

**Issue by th-w** [web2py/web2py#2338]
The search function in the edit app is broken.

  File "/home/www-data/web2py_2.20.4/applications/admin/controllers/default.py", line 619, in match
    if keywords in read_file(filename, 'rb'):
TypeError: a bytes-like object is required, not 'str'

it works with 'r' mode.

**Comment by ronaldw97** [comment]
Man, I think that is a problem with your python version and the encoding.

**Comment by th-w** [comment]
No that's not the reason. But you are right i should mention the tested versions:
Python 2.7.16
Python 3.5.3
Python 3.7.3

If you write something to the "search" field, then it throws a "reload the page" message.

**Comment by th-w** [comment]
#2362
