### ISSUE TITLE
AttributeError: 'Monitor' object has no attribute 'isAlive'

### ISSUE THREAD

**Issue by 2spmohanty** [web2py/web2py#2354]
**Describe the bug**
Getting Error while starting web2py.py from Windows 10.

AttributeError: 'Monitor' object has no attribute 'isAlive'

Version 2.20.4-stable+timestamp.2020.05.03.05.18.50

**To Reproduce**
Downloaded the latest source files for web2py.
Version 2.20.4-stable+timestamp.2020.05.03.05.18.50
Started command : python web2py.py

The rocket server starts but the commandline console has this error:

Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\mtsutil\web2py\gluon\main.py", line 782, in start
    self.server.start()
  File "C:\mtsutil\web2py\gluon\rocket.py", line 716, in start
    while self._monitor.isAlive():
AttributeError: 'Monitor' object has no attribute 'isAlive'

**Expected behavior**

No error. The welcome page opens.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] NA
 - Web2py Version: Version 2.20.4-stable+timestamp.2020.05.03.05.18.50

**Comment by earora97** [comment]
@richboss  Any ETA for the fix to be checked-in? TIA

**Comment by richboss** [comment]
> @richboss Any ETA for the fix to be checked-in? TIA

Sorry, I haven't got a clue. I'm just the submitter of a (trivial) pull request. It's the responsibility of the repo maintainers to decide if and when the fix will be merged.

**Comment by leonelcamara** [comment]
The fix was merged
