### ISSUE TITLE
Inclusion of CSRF in forms

### ISSUE THREAD

**Issue by narendradotg** [web2py/web2py#2367]
**Is your feature request related to a problem? Please describe.**
CSRF token inclusion in web2py html forms. 
We implemented web2py based application authentication via SSO and HTML are hand crafted rather them html helpers.
Could you please help me how to implement CSRF for my application

**Describe the solution you'd like**
Expecting solution like how do we have in Django Or Flask, may be i 'm not aware. Would be good to have same feature in web2py.

**Comment by leonelcamara** [comment]
An easy way to do this is to have this in your controller
```python
def test_csrf():
    f = FORM()
    if f.accepts(request, session): # 
        # CSRF is good
    else:
        # CSRF is bad
    return {'f': f}
```
Then in your view you can do your custom form however you want, here I make a simple one with just a "foo" input. Note that none of the other fields is validated, just the CSRF token in the hidden fields.

```html
<form method="POST">
    <input name="foo">
    {{=f.hidden_fields()}}
    <input type="submit">
</form>```
