### ISSUE TITLE
websocket_meesaging digestmod parameter is now required since Python 3.8 

### ISSUE THREAD

**Issue by pepej** [web2py/web2py#2385]
For work which python 3.8 need change this lines.
96a97
> import hashlib
102c103
<     sig = hmac_key and hmac.new(to_bytes(hmac_key), to_bytes(message)).hexdigest() or ''
---
>     sig = hmac_key and hmac.new(to_bytes(hmac_key), to_bytes(message),hashlib.sha1).hexdigest() or ''
124c125
<                 actual_signature = hmac.new(to_bytes(hmac_key), to_bytes(message)).hexdigest()
---
>                 actual_signature = hmac.new(to_bytes(hmac_key), to_bytes(message),hashlib.sha1).hexdigest()
144c145
<                 actual_signature = hmac.new(to_bytes(hmac_key), to_bytes(message)).hexdigest()
---
>                 actual_signature = hmac.new(to_bytes(hmac_key), to_bytes(message),hashlib.sha1).hexdigest()

**Comment by leonelcamara** [comment]
It's fixed in trunk
