### ISSUE TITLE
DoS in SSL mode

### ISSUE THREAD

**Issue by nfedera** [web2py/web2py#2400]
**Describe the bug**
rocket's accept loop is blocked while new connection does handshake 

**To Reproduce**
1. `python web2py.py -c certificate.pem -k privatekey.pem -v -e`
2. run `nc localhost 8000` and do nothing
3. try to connect from other terminal/client: server is not accepting connections until you terminate nc

**Expected behavior**
web2py should accept/handle new connections independently of one connections handshake issues.

**Comment by jicho** [comment]
@mdipierro is this going to be added to web2py?
and a second question... is web2py still maintained? It looks like versions are completely stopped...

**Comment by leonelcamara** [comment]
@jicho the fix was merged. Closing this.
