### ISSUE TITLE
CSV Import Fails under Python 3

### ISSUE THREAD

**Issue by glimmung** [web2py/web2py#2404]
**Describe the bug**
On web2py 2.21.1-stable+timestamp.2020.11.28.04.10.44 (current as of today) under Python Python 3.8.10, a simple CSV import fails with the following error in a flash message:  "Unable to parse CSV file - iterator should return strings not bytes. Did you open the file in text mode?"

**To Reproduce**
Download current web2py zip for Python 3.
Unzip, fire up under Python 3, define simple table using default db setup (e.g. SQLite)
Go to db admin, select new table, use DBA import facility.

**Screenshots**
![Selection_002](https://user-images.githubusercontent.com/1511399/137121617-cec1bd66-fb84-4171-bbe6-b72e9edb2b91.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3
 - Browser Chrome 94

**Additional context**
Googling for the problem I see that it is a known issue and fixes are suggested, but: -
- The issue remains in the current version.
- The fixes are producing unexpected results for me.

**Comment by pcwalden** [comment]
Guessing you need to [save the csv as utf-8](https://support.assetbank.co.uk/hc/en-gb/articles/115005205928-How-to-save-a-tab-delimited-UTF-8-encoded-file-in-Excel) from excel.

**Comment by glimmung** [comment]
@pcwalden sadly, it's not as simple as that (and that was the first thing that I verified). This is a Python 2 vs. Python 3 issue - I have updated my app, and code that worked in Python 2 fails as described in Python 3.

It seems that this was reported back in 2019 as https://github.com/web2py/web2py/issues/2148 and the issue describes a fix (which is not working for me as described, which is where I am stuck), but the fix was never applied.

**Comment by leonelcamara** [comment]
@glimmung I believe this was fixed in DAL. The fixes suggested #2148 (basically using TextIOWrapper) seem to be in https://github.com/web2py/pydal/blob/d7b24a9ecf0fd7e9c1ed2aa29e0d235105006774/pydal/objects.py#L101 and I can no longer reproduce.
