### ISSUE TITLE
Support to python 3.8/3.9/3.10

### ISSUE THREAD

**Issue by Tenebor** [web2py/web2py#2413]
Hello, are there any full support predictions for python 3.8 / 3.9 / 3.10? For example I noticed that (with python3.8) the "{{else:}}" statement in the view doesn't work.

Regards

**Comment by jicho** [comment]
I download the master for Py3.9 support.
Until now I didn't find any issues.
Maybe you can try/do the same?

**Comment by Tenebor** [comment]
I asked because I need a stable release version.
For example, downloaded from web2py official site.

**Comment by jicho** [comment]
I understand.
For what it is worth... At my work we're working with the master versie in production.
The download from the web2py isn't supporting 3.8 and higher (in my experience).

**Comment by Tenebor** [comment]
Thanks for the feedback!

**Comment by mmoye** [comment]
We have a production site running Python 3.6.9. The same exact application running on my local machine with Python 3.9.10 had a lot of issues.

**Comment by Tenebor** [comment]
In the end, I solved all my issue downloading the master branch

**Comment by mmoye** [comment]
I am using the master branch :) I also tried rolling back to 2.19.1 and had the same issues. Python 3.9 and 3.10 are causing problems that Python 3.6.9 did not have?

**Comment by jpsteil** [comment]
Can you create a minimal app that exhibits the behavior and share with us?

**Comment by mmoye** [comment]
I wish I could, as I could use the help troubleshooting, but it's a very complicated application with all kinds of custom decorators and such. Creating a minimal app that mimics the issue would be fairly time consuming. What I'm seeing (if it helps at all) is that we have a view with a number of tabs (bootstrap nav-tab class) set up. When a tab is clicked, we use web2py_component to load a subform (.load file). As mentioned, this works flawlessly on our production site that runs Python 3.6.9, Web2Py 2.20.4. But when I run the app locally on my Windows box running Python 3.10, Web2Py 2.22.1 and click on the tab I get a 403 error.

**Comment by jpsteil** [comment]
From your browser can you enter the url and all related parameters to call the component? Are any tickets being generated?

**Comment by mmoye** [comment]
@jpsteil yes I can grab the url from the network tab on the inspector console and paste it into a new window. Works just fine in production, not on my local.
@leonelcamara that is exactly where we've focused our efforts. But why would the decorator work just fine in one system and not on another? The only thing that has changed is the web2py and Python versions.

**Comment by leonelcamara** [comment]
@mmoye it could be as simple as requiring https and you not having it locally, we need to see what decorator is doing it

**Comment by mmoye** [comment]
OK maybe it is not the decorator. As far as I can tell this is the issue. In the onclick function the web2py_component passes parameters using vars=dict(a=x, b=y, c=z), that is: 
`web2py_component("{{=URL('my_controller', 'my_view.load', vars=dict(a=x,b=y,c=z))}}");`
That is compiling to
`web2py_component("/my_app/my_controller/my_view.load?a=xamp;b=yamp;c=z);`
See the "amp;" in there? It is expected because of the multiple parameters in the string yes? _url?var1&var2&var3_ etc. 
On production it is the same but the "amp;" causes no problems. On my local however, the 'amp' gets passed as part of the variable name, so variables "b" and "c" come through as "ampb;" and "ampc;" so the controller that receives them doesn't know what to do with them because it is expecting simply "b" and "c".

**Comment by mmoye** [comment]
Also, a huge thank you to everyone attempting to help me. Let me know if I should move this issue to an open ticket.

**Comment by mmoye** [comment]
Update: I installed Python 3.7.9 and set up my virtual environment with that version of Python and everything works just fine! So this is definitely an issue with Python 3.10. I will create a new issue since this one is closed.
