### ISSUE TITLE
define_table not migrate

### ISSUE THREAD

**Issue by attiquetecnologia** [web2py/web2py#2414]
**Describe the bug**
Helo, I have a problem with migrations. 
I create a feature to my app, but when upload the source on server production, the w2p not migrate the models on production DB.
Check this in my PC, the problem persists, even matching migrates and fake_migrate, the w2p not generate .tables or persistes migrations.

I check the sql.log and not write alter tables.

I try with Postgres and sqlite. 

NOTE: Using last web2py and python 3.8

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows and Ubuntu

**Smartphone (please complete the following information):**

**Additional context**

**Comment by leonelcamara** [comment]
You probably overwrote the table files in production. I recommend that you revert the changes to your define tables and do a fake migration, then do the changes again and do a proper migration.

**Comment by leonelcamara** [comment]
@attiquetecnologia closing this, please reopen if I misunderstood the problem.
