### ISSUE TITLE
starting scheduler on linux throws TypeError: __call__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by mmoye** [web2py/web2py#2417]
**Describe the bug**
Running web2y 2.21.1 on Linux Ubuntu 20.04. When trying to initialize scheduler function I get an error:
```
File "/home/www-data/web2py/gluon/packages/dal/pydal/objects.py", line 2258, in validate
    (value, error) = validator(value, record_id)
TypeError: __call__() takes 2 positional arguments but 3 were given
```
**To Reproduce**

**Expected behavior**
Expecting my scheduled task to start. I have a controller called 'scheduler.py' which contains this function
```
def repeat_task(protect=None):
    """Runs every 24 hours starting from now."""
    if configuration.get('scheduler.enabled'):
        scheduler.queue_task(   'email_reminders',
                                period=86400,
                                start_time=datetime.datetime.now(),
                                repeats=0
                                )
        return db.commit()
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Chrome
 - Version Web2py v 2.21.1

**Smartphone (please complete the following information):**

**Additional context**
I should add that a worker gets created but the expected record in scheduler_task and scheduler_run does not get created. I can manually add the record to scheduler_task via appadmin but I get the same error in my application whenever the scheduler is tapped.

**Comment by leonelcamara** [comment]
I'm not being able to reproduce, do you have a longer traceback or can you provide a sample app that will reproduce it.

**Comment by mmoye** [comment]
I don't as this was a couple of months back. We found a workaround for this project. If it comes up again I will be sure to post! Thank you
