### ISSUE TITLE
No module named pydal when starting web2py

### ISSUE THREAD

**Issue by dileepkannamala** [web2py/web2py#2424]
Traceback (most recent call last):
  File "E:\web2py\gluon\__init__.py", line 31, in import_packages
    sys.modules[package] = __import__(package)
ModuleNotFoundError: No module named 'pydal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "web2py.py", line 41, in <module>
  File "E:\web2py\gluon\__init__.py", line 35, in <module>
    import_packages()
  File "E:\web2py\gluon\__init__.py", line 33, in import_packages
    raise RuntimeError(MESSAGE % package)
RuntimeError: web2py depends on pydal, which apparently you have not installed.
Probably you cloned the repository using git without '--recursive'
To fix this, please run (from inside your web2py folder):

     git submodule update --init --recursive

You can also download a complete copy from http://www.web2py.com.
[2896] Failed to execute script web2py

**Comment by leonelcamara** [comment]
Did you get web2py from github? You need to get the submodules too like the warning asks.

**Comment by dileepkannamala** [comment]
I got web2py  downloaded from    web2py.com    website

Thanks

**Comment by leonelcamara** [comment]
@dileepkannamala I misunderstood, in that case this is a duplicate of #2421 it should be fixed in the next release. In the mean time I would just get web2py directly from github.
