### ISSUE TITLE
Method for loading jquery

### ISSUE THREAD

**Issue by unle70** [web2py/web2py#2429]
This is a "question" and maybe a proposal for improvement.

In a standard configuration, the layout.html is used in by all user views. The layout.html is including web2py_ajax.html, which sets a list of  4 files (jquery.js, calendar.js, calendar.css, web2py.js) to be included into the view.

From what I see, this mechanism doesn't simply create a "<script src=....></script>" line in the view but rather copies the entire text from those included files into the html code. Other modules in the layout.html are not handled in the same way. They are just imported the normal way.

I'm wondering, isn't that really wasteful in terms of loading speed? When done this way, the browser cannot use the cache and has to really download these files again and again on each page request. These files are VERY static and really never change. Is there any reason for choosing this implementation method?

**Comment by leonelcamara** [comment]
@unle70 it does create the script tags. It does not include the entire content. This is how the files are included:
https://github.com/web2py/web2py/blob/master/gluon/globals.py#L484

**Comment by unle70** [comment]
Hi Leonel,
Thank you for your response, however I have to disagree.
When I look at the DevTool (Chrome), there is NO mentioning of jQuery (or any of the other included files) being downloaded. If you look at the Response of the main html doc (index.html in my case), you can clearly see the full text of jQuery there. Furthermore, if ever there's any exception raised inside jQuery, the DevTools will open this index.html file to show the location of the exception and not the jQuery file.

From the code you have pointed, looks like this is doing on-the-fly minifying of the js/css and including the result in the stream.

**Comment by niphlod** [comment]
@unle70 : post a screenshot of your findings, so we can see what's happening on your side

**Comment by niphlod** [comment]
jm2c: it's possible that you enabled response.optimize_css and/or response.optimize_js with "inline", but it's an opt-in not a default.

**Comment by unle70** [comment]
> jm2c: it's possible that you enabled response.optimize_css and/or response.optimize_js with "inline", but it's an opt-in not a default.

Yeah, you got it right. I did enable this optimization, not knowing that it would cause "inline" behavior.
Thank you for explaining that.
