### ISSUE TITLE
encoding issue with Python > 3.7 (amp; passed in request var strings)

### ISSUE THREAD

**Issue by mmoye** [web2py/web2py#2432]
**Describe the bug**
We have an onclick function using a web2py_component that passes parameters using vars=dict(a=x, b=y, c=z), that is:
`web2py_component("{{=URL('my_controller', 'my_view.load', vars=dict(a=x,b=y,c=z))}}");`
This compiles to
`web2py_component("/my_app/my_controller/my_view.load?a=xamp;b=yamp;c=z);`
See the "amp;" in there? It is expected because of the multiple parameters in the string yes? url?var1&var2&var3 etc.
In Python 3.7.9 and below the "amp;" causes no problems. In Python 3.9 and 3.10 (3.8 has not been tested), the 'amp' gets passed as part of the variable name, so variables "b" and "c" come through as "ampb;" and "ampc;" so the controller that receives them doesn't know what to do with them because it is expecting simply "b" and "c".

To Reproduce**
Using Python 3.7.9, if I copy and paste the URL from the network tab in the inspector console into a browser window and remove the 'amp;' then the view loads just fine.
Using Python 3.9 or 3.10 I receive either a 404 or a 403 error due to the variable not being recognized. Removing the 'amp;' loads the view successfully. In other words, in Python 3.9 or 3.10
`http://localhost:8000/my_app/my_controller/my_view.load?a=x&amp;b=y&amp;c=z`
changed to
`http://localhost:8000/my_app/my_controller/my_view.load?a=x&b=y&c=z`
loads perfectly.

**Expected behavior**
Code works in latest version of Python 3.x

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**

**Comment by mmoye** [comment]
Here is another example. We have an api function that builds a database query using a request.vars passed from the view. In Python 3.7 and below the 'amp;' included in the passed variable name had no effect. In Python 3.8 and above (tested in 3.8 and 3.10) the 'amp;' is being read.

This screenshot is from Python 3.10. You can see there is no output of request.vars.sender_uuid.

![image](https://user-images.githubusercontent.com/17770216/156263750-e7bd0e41-cf19-4f4a-8419-a26f4953fbe4.png)

And here is the exact same thing in Python 3.7.9. The output of request.vars.sender_uuid is shown.
![image](https://user-images.githubusercontent.com/17770216/156264693-066020e2-7994-481e-b3c2-1a3001c3561b.png)

**Comment by mmoye** [comment]
We found the problem. Turns out to be related to the use of the dictionary to build the url. If instead of 
`web2py_component("{{=URL('my_controller', 'my_view.load', vars=dict(a=x,b=y,c=z))}}");`
we use
`web2py_component("{{=URL('my_controller', 'my_view.load')}}?a=" + x + "&b=" + y + "&z=" + z);`
then there is no issue.

Of course, since x, y, and z were passed to the view as Python variables they'll need to be declared first as JavaScript variables for the second line of code to work.

**Comment by leonelcamara** [comment]
you can use and this will be fine

    web2py_component("{{response.write(URL('my_controller', 'my_view.load', vars=dict(a=x,b=y,c=z)), escape=False)}}")

The problem is that response.write by default escapes what it gets to sanitize the HTML. What's weird is that indeed this used to work. Anyway I've fixed it in trunk, I don't see any reason why the output of URL should need to be sanitized so I made sure it isn't.
