### ISSUE TITLE
fpdf code update

### ISSUE THREAD

**Issue by Lucas-C** [web2py/web2py#2438]
Hi!

I'm the maintainer of [fpdf2](https://github.com/PyFPDF/fpdf2)

`web2py` includes a copy of PyFPDF, which is not maintained anymore:
https://github.com/web2py/web2py/tree/master/gluon/contrib/fpdf

Would you be open to switching to `fpdf2`? I can submit a PR.

Related issues:
* https://github.com/web2py/web2py/issues/2289
* https://github.com/PyFPDF/fpdf2/issues/99

**Comment by leonelcamara** [comment]
Is it compatible with python 2? For now, I think we still want to keep compatibility.

**Comment by Lucas-C** [comment]
No, `fpdf2` is not compatible with Python 2.

Alright, closing this then 😊
