### ISSUE TITLE
UF-8 error

### ISSUE THREAD

**Issue by Pirsch** [web2py/web2py#2451]
**Describe the bug**
Translation files in Languages, f.i. language/de.py in the welcome app may contain characters that cause this error:
<type 'exceptions.UnicodeDecodeError'> 'utf8' codec can't decode byte 0xa0 in position 8: invalid start byte
Tested for German, may exist in other language files as well. 

**To Reproduce**
1. Set Browser Language to 'German' 
2. Visit Welcome index.html (http://127.0.0.1:8000/welcome)

**Expected behavior**
Page should load and not show a type exception error
**Screenshots**
![character](https://user-images.githubusercontent.com/4863529/209942450-8b7911b5-8854-40fa-97c9-7278e436ca13.jpg)

**Additional context**
After cleaning the file, the error disappears. The faulty character might be introduced into the language file, once the system adds new text marked with T(...) to the file. The character seems to stand for a whitespace

**Comment by leonelcamara** [comment]
I've fixed the german translation by replacing those with spaces, on my tests spaces don't get converted to \xa0 by the system adding strings.
