### ISSUE TITLE
SSLv3 unknown certificate

### ISSUE THREAD

**Issue by JoseTg1904** [web2py/web2py#2456]
**Describe the bug**
I'm trying to create a project with web2py 2.23.0 for python 3.7, i use ssl self signed certificates for local development, the thing is, when i run it the framework up good, but when i open the application on then navegator, the console of my os shows me the message *SSLv3 alert unknown certificate*

**Screenshots**

![error](https://user-images.githubusercontent.com/58497257/211233274-d68faa5f-bfac-4146-9794-56dc4b29b339.jpg)

**Desktop (please complete the following information):**
- Docker: [Ubuntu focal]
- Python: [3.7.4]
- Openssl: [1.1.1f]
- Browser [Chrome, Firefox]
- Version [2.23.0]

**Comment by mdipierro** [comment]
We upgraded rocket to rocket3. please reopen if issue persists.
