### ISSUE TITLE
pydal 20240427 breaks gluon/login

### ISSUE THREAD

**Issue by fambon** [web2py/web2py#2486]
**Describe the bug**

pydal 20240427 breaks gluon/login

**To Reproduce**

1./ pip install pydal  # latest=20240427.3
2./ run web2py app
3./ login

**Expected behaviour**
crash: internal error on login
expected: no crash
fix : `pip install --upgrade 'pydal<20240427'`

**Screenshots**
internal error:
```
  File "/home/pci/pci/web2py/applications/pci/controllers/default.py", line 907, in <module>
  File "/home/pci/pci/web2py/gluon/globals.py", line 430, in <lambda>
    self._caller = lambda f: f()
  File "/home/pci/pci/web2py/applications/pci/controllers/default.py", line 247, in user
    form = auth()
  File "/home/pci/pci/web2py/gluon/tools.py", line 1880, in __call__
    return getattr(self, args[0])()
  File "/home/pci/pci/web2py/gluon/tools.py", line 2895, in login
    user = Row(table_user._filter_fields(user, id=True))
TypeError: _filter_fields() got an unexpected keyword argument 'id'
```

**Desktop (please complete the following information):**
 - OS: ubuntu-22.04-4
 - Browser FF-125.0.1
 - Python: Python 3.8.19 + pip 22.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by fambon** [comment]
with current web2py source, issue is at https://github.com/web2py/web2py/blob/master/gluon/tools.py#L3273

but there is at least one other place where `_filter_fields()` is called with kw arg `id=`

**Comment by mdipierro** [comment]
this should be fixed. please reopen if you observe the error with the latest master
