### ISSUE TITLE
Internal Error when accessing web2py Online Book on the official website

### ISSUE THREAD

**Issue by 3YZW** [web2py/web2py#2505]
**Describe the bug**
Internal Error when accessing web2py Online Book on the official website.

**To Reproduce**
Navigate to the official web2py documentation page.
Click on the link to the Online Book.
An "Internal Error" message is displayed instead of the expected content.

**Screenshots**
![FireShot Capture 343 -  - www web2py com](https://github.com/user-attachments/assets/27255c56-1d69-4ead-a4de-e8b330ace674)

URL where the issue occurs: 
https://www.web2py.com/books/default/chapter/33
https://web2py.com/book

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Sequoia 15.1]

Thank you for your attention, and I look forward to your response.

**Comment by saifuddinrangwala** [comment]
Encountering same issue.

**Comment by nicozanf** [comment]
It's resolved ;-)
