### ISSUE TITLE
Fulltext search support in web2py

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#602]
_From [elff...@gmail.com](https://code.google.com/u/115166821933243869368/) on February 18, 2011 11:03:54_

sqlite supports full text search http://www.sqlite.org/fts3.html "FTS4 is an enhancement to FTS3. FTS3 has been available since SQLite version 3.5.0 in 2007-09-04. The enhancements for FTS4 were added with SQLite version 3.7.4 on 2010-12-08."

full text search is also supported in 

mysql: http://dev.mysql.com/doc/refman/5.0/en/fulltext-search.html sql server: http://msdn.microsoft.com/en-us/library/ms142571.aspx oracle: http://download.oracle.com/docs/cd/B28359_01/text.111/b28304/cqrypkg.htm postgresql: http://www.postgresql.org/docs/8.3/static/textsearch.html and so on, but I think this list is enough to add full text search capabilities in DAL

_Original issue: http://code.google.com/p/web2py/issues/detail?id=197_

**Comment by niphlod** [comment]
_From [ABasta...@gmail.com](https://code.google.com/u/103720714265511973715/) on August 07, 2012 19:26:28_

**Labels:** -Type-Defect Type-Enhancement

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on September 01, 2013 12:17:00_

Issue 1449 has been merged into this issue.

**Comment by cassiobotaro** [comment]
This should be moved to pydal issues, right? @gi0baro ?

**Comment by gi0baro** [comment]
@cassiobotaro rigth, should be moved

**Comment by niphlod** [comment]
closing this, tracking at https://github.com/web2py/pydal/issues/153
