### ISSUE TITLE
Bug  when using external folders with option -f

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#616]
_From [jredr...@gmail.com](https://code.google.com/u/114361343036436419611/) on May 11, 2012 12:35:19_

When using web2py with the "-f" option, it doesn't import correctly the files in the modules directory of the applications.
I.E.
python web2py.py -f /myprojects/web2py -a hello

starts web2py correctly, but trying to use

import test as a shortcut for from applications.appname.modules import test.

as explained at http://www.web2py.com/books/default/chapter/29/4?search=applications.appname.modules is not possible.

Actually, I think this has never worked

_Original issue: http://code.google.com/p/web2py/issues/detail?id=791_

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on May 11, 2012 06:29:33_

**Status:** Accepted

**Comment by cassiobotaro** [comment]
It's because test is already a python module name. Try to rename and it works.

We need to update this in book @mdipierro .

https://docs.python.org/2/library/test.html

**Comment by niphlod** [comment]
@cassiobotaro : can you comment it further ? from your last comment is seems that I could close this issue ...

**Comment by cassiobotaro** [comment]
@niphlod How ca I made a PR to the book? We have only to alter some things there before close this issue.

**Comment by niphlod** [comment]
the book is here https://github.com/mdipierro/web2py-book/ . do a simple PR and then @mdipierro  will merge it.

**Comment by cassiobotaro** [comment]
@niphlod only wait @mdipierro merge this https://github.com/mdipierro/web2py-book/pull/292 to the book and can close this issue.

**Comment by cassiobotaro** [comment]
https://github.com/mdipierro/web2py-book/pull/292 already merged. Now you can close this issue @niphlod
