### ISSUE TITLE
cron job request.folder is relative path name only

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#617]
_From [simo...@gmail.com](https://code.google.com/u/115616376796056978244/) on May 31, 2012 21:35:36_

Fairly minor issue but with a cron request then request.folder is applications/myap

For all other requests request.folder provides the full path e.g. C:/web2py/applications/myap/

_Original issue: http://code.google.com/p/web2py/issues/detail?id=827_

**Comment by niphlod** [comment]
_From [simo...@gmail.com](https://code.google.com/u/115616376796056978244/) on May 31, 2012 12:51:45_

Note this was for an @reboot request. Have not tried with other timed requests.

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on December 05, 2012 10:33:22_

I believe this was fixed by this linke in widget.py

options.folder = os.path.abspath(options.folder)

can you help me check?

**Status:** Started

**Comment by niphlod** [comment]
_From [simo...@gmail.com](https://code.google.com/u/115616376796056978244/) on December 05, 2012 12:48:53_

Checked and it is not fixed on latest trunk. Still shows applications\myap

**Comment by niphlod** [comment]
cron is officially deprecated, so this won't ever be fixed.

**Comment by mdipierro** [comment]
no. never.
