### ISSUE TITLE
Support for HTTP Digest Authentication

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#621]
_From [Alec.Tay...@gmail.com](https://code.google.com/u/102483133075352664946/) on July 03, 2012 17:37:36_

Problem:
I'm building mobile apps using PhoneGap, whose frontend cannot be generated server-side using web2py views (templates).

Solution:
Build the frontend using JavaScript with JSONRPC calls to the web2py server. Control authentication using the RFCified Digest Access Authentication.

Example (from http://en.wikipedia.org/wiki/Digest_access_authentication ):

• The client asks for a page that requires authentication but does not provide a username and password. Typically this is because the user simply entered the address or followed a link to the page.
• The server responds with the 401 "client-error" response code, providing the authentication realm and a randomly-generated, single-use value called a nonce.
• At this point, the browser will present the authentication realm (typically a description of the computer or system being accessed) to the user and prompt for a username and password. The user may decide to cancel at this point.
• Once a username and password have been supplied, the client re-sends the same request but adds an authentication header that includes the response code.
• In this example, the server accepts the authentication and the page is returned. If the username is invalid and/or the password is incorrect, the server might return the "401" response code and the client would prompt the user again.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=872_

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on July 06, 2012 06:51:29_

Looking into this... http://en.wikipedia.org/wiki/Digest_access_authentication Not sure what "entityBody" is.

**Comment by niphlod** [comment]
_From [smog...@gmail.com](https://code.google.com/u/100389295817816551663/) on July 06, 2012 07:20:14_

I'm trying to implement this on my client also.
Here are some resources that might help: 
- Chromium tests for auth.
- A sample c++ code https://code.google.com/p/chromium/source/search?q=username+nonce&origq=username+nonce&btnG=Search+Trunk https://code.google.com/searchframe#L7BRNLZzKBo/trunk/live555/live/liveMedia/RTSPServer.cpp&ct=rc&cd=19&q=Digest%20access%20authentication%20lang:%5Ec%2B%2B$&sq=

**Comment by niphlod** [comment]
_From [Alec.Tay...@gmail.com](https://code.google.com/u/102483133075352664946/) on July 09, 2012 02:27:50_

Looks like urllib2 has support for digest auth:

E.g. Used in the mercurial-api: http://danchr.bitbucket.org/mercurial-api/mercurial.url-pysrc.html#httpdigestauthhandler

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on July 09, 2012 19:43:22_

I can find the API to generate the digest credentials, not to validate them.

**Comment by niphlod** [comment]
_From [Alec.Tay...@gmail.com](https://code.google.com/u/102483133075352664946/) on July 11, 2012 00:20:06_

Maybe this will be of help? - https://bitbucket.org/btimby/python-digest

**Comment by niphlod** [comment]
_From [niph...@gmail.com](https://code.google.com/u/110791369705180298143/) on July 16, 2012 13:51:46_

also here http://svn.cherrypy.org/trunk/cherrypy/lib/auth_digest.py

**Comment by niphlod** [comment]
_From [ABasta...@gmail.com](https://code.google.com/u/103720714265511973715/) on August 07, 2012 20:07:02_

**Labels:** -Type-Defect Type-Enhancement

**Comment by niphlod** [comment]
IMHO there's a clash on what is required and how we handle auth. 
One of the hard requirements for supporting the digest auth is to be able to reconstruct the original password in "cleartext". 
If we stored those using md5 as we used to a long time ago, it would still be possible in some corner-cases, but I don't see how can we integrate HTTP digest with our current hashing scheme.

@mdipierro , @michele-comitini , @abastardi : opinions ?

**Comment by michele-comitini** [comment]
I agree, really chaotic.
Impossible to apply to web2py, given  an already existing set of
username/hashed-password.  One would require the client to do the same hash
before starting the challenge or as you say, have the cleartext password.

Moreover IMHO it does not add any security to Basic Auth + TLS
https://tools.ietf.org/html/rfc2617#section-4.13
https://tools.ietf.org/html/rfc2617#section-4.14


2015-03-02 22:33 GMT+01:00 niphlod <notifications@github.com>:

**Comment by niphlod** [comment]
made little sense in 2012, but in 2015 I agree, there are FAR better alternatives for API authentication. 
I'm a fan of Basic over HTTPS but hey, maybe it's just me.

**Comment by niphlod** [comment]
@mdipierro : as always, you're the one who can rule definitely if this issue is still valid or has to be closed.

**Comment by niphlod** [comment]
@mdipierro : this can be closed if you agree with @michele-comitini and me

**Comment by niphlod** [comment]
closing after 2 months of lack of replies by @mdipierro .
