### ISSUE TITLE
dal fail to query on fields other than id on couchdb

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#630]
_From [lapcc...@gmail.com](https://code.google.com/u/112961409058978860479/) on October 05, 2012 22:17:57_

What steps will reproduce the problem? db=DAL('couchdb://127.0.0.1:5984')
db.define_table('person',Field('name'))
db.person.insert(name='john')
print db(cdb.person.name == "john").select()
will alway return empty object What is the expected output? What do you see instead? return the correct object What version of the product are you using? On what operating system? web2py 2.0.9 Please provide any additional information below.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1071_

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on September 01, 2013 11:58:29_

Couchdb is not supported at this moment. There seem to be zero interest in it.

**Labels:** -Type-Defect Type-Enhancement

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on September 01, 2013 11:58:49_

Issue 1068 has been merged into this issue.

**Comment by mdipierro** [comment]
at this time there is no support for couchdb.
