### ISSUE TITLE
db.import_from_csv_file() doesn't maintain foreign keys when UUID field is present

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#632]
_From [f...@aidiq.com](https://code.google.com/u/114533118083619344414/) on October 16, 2012 15:35:24_

What steps will reproduce the problem? stable = db.define_table("source", Field("uuid"))
dtable = db.define_table("data", Field("source_id", db.source))
stable.insert(uuid="First")
stable.insert(uuid="Second")
stable.insert(uuid="Third")
db(stable.id==2).delete()
dtable.insert(source_id=3)
db.commit()
file = open("test.csv", "w")
db.export_to_csv_file(file)
file.close()
stable.truncate()
dtable.truncate()
file = open("test.csv", "r")
db.import_from_csv_file(file)
db(stable.id>0).select().json()
db(dtable.id>0).select().json() What is the expected output? What do you see instead? I would expect db(dtable.id==1).select().first().source_id to point to db(stable.uuid=="Third").select().first().id
I see:
In [16]: db(dtable.id>0).select().json()
Out[16]: '[{"source_id": 3, "id": 1}]'
In [17]: db(stable.id>0).select().json()
Out[17]: '[{"id": 1, "uuid": "First"}, {"id": 2, "uuid": "Third"}]' What version of the product are you using? On what operating system? Current Trunk ( 3a1ba53a4b86f0da79be3da78b63509fce401c7f , Mon Oct 15 21:49:43).
Have tried multiple OS (Win32, Linux) & multiple DBs (SQLite, Postgres)

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1095_

**Comment by niphlod** [comment]
_From [f...@aidiq.com](https://code.google.com/u/114533118083619344414/) on October 16, 2012 06:36:13_

As per subject line, I tested without a uuid field & all is well: ids are maintained & hence FKs point correctly.

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on October 16, 2012 08:26:34_

**Status:** Accepted

**Comment by mdipierro** [comment]
Checked. this is fixed. But db.import_from_csv_file(file) should be db.import_from_csv_file(file, id_map={})
