### ISSUE TITLE
Profile update does not update auth.user object for computed field

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#636]
_From [markruol...@gmail.com](https://code.google.com/u/114619454780239522399/) on November 14, 2012 21:46:56_

What steps will reproduce the problem? 1. Have both 'upload' field and computed field for auth_user table
2. Update the 'upload' field through auth.profile() form
3. Click on 'save profile' What is the expected output? What do you see instead? Expect that the auth.user object will be updated for all fields. Only the 'upload' field is updated; the computed field does not change in the auth.user object. What version of the product are you using? On what operating system? Web2py 2.2.1
Ubuntu 12.04 Please provide any additional information below.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1164_

**Comment by mdipierro** [comment]
Is this still current? There is no code to reproduce the issue.
