### ISSUE TITLE
AddGeometryColumn fails with a field name having capital letters

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#640]
_From [paolo.va...@gmail.com](https://code.google.com/u/107767337307670204068/) on January 08, 2013 18:38:55_

What steps will reproduce the problem? 1. Define a table as follows:
db.define_table('test_geo1_name',
    Field('name_P', 'string'),
    Field('location_P','geometry()'),
)
2. in the db you will get the field name_p and location_P respectively What is the expected output? What do you see instead? to have the field name_p and location_p respectively What version of the product are you using? On what operating system? trunk Please provide any additional information below. See the discussion on the web2py group: https://groups.google.com/d/msg/web2py/6DDLVv4jt0w/E3NIhFEUrgsJ

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1259_

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on September 01, 2013 11:40:44_

Why?

**Comment by niphlod** [comment]
_From [paolo.va...@gmail.com](https://code.google.com/u/107767337307670204068/) on September 04, 2013 03:07:09_

sorry it took so long to answer.
The problem I see is that there isn't a equal behavior in the field
definition at database level. As far as I understood, for 'ordinary' fields
type DAL creates their name without capital letters while when the type is
a geometry the field name is used as is (capital letters are kept, as shown
in the example).
I'd test it again against trunk

 Paolo

**Comment by ilvalle** [comment]
Fixed by https://github.com/web2py/web2py/commit/bda101d43f783bf0dd49d47adc2e6e4c1d1862ca
