### ISSUE TITLE
List sites powered by web2py

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#655]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on April 15, 2013 06:10:36_

https://groups.google.com/forum/#!topic/web2py/DNg0Ibn8-UQ

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1450_

**Comment by niphlod** [comment]
@mdipierro : either we close this, or we make a link, e.g. "see also" pointing to http://www.shodanhq.com/search?q=web2py . 2 years worth of open issue for a link seems too much :-P

**Comment by niphlod** [comment]
@mdipierro : this one can be closed too, either providing shodanq listing or just ignoring it.

**Comment by mdipierro** [comment]
http://web2py.com/poweredby
