### ISSUE TITLE
SQLFORM.smartgrid: Bug in links

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#662]
_From [jjachuf_at_gmail.com](https://code.google.com/u/jjachuf_at_gmail.com/) on June 14, 2013 02:12:26_

What steps will reproduce the problem? 1. Given the following model:

from gluon.contrib.populate import populate

tb_a = db.define_table('ta',
    Field('name', 'string'),
    format='&#37;(name)s',
)

tb_b = db.define_table('tb',
    Field('fa', tb_a),
    Field('name', 'string'),
    format='&#37;(name)s',
)

if db(tb_a).isempty():
    populate(tb_a, 2)
    populate(tb_b, 8)

And the following function in controller:

def f():
    grid =SQLFORM.smartgrid(tb_a,
            csv=False,
            user_signature=False,)

    return dict(grid=grid)

Performing the steps shown in the image ok.png, this works well!

2. Modifying the model table "ta" (name is changed by name2)

tb_a = db.define_table('ta',
    Field('name2', 'string'),
    format='&#37;(name2)s',
)

Fails, as shown in the image fail.png 
. 

Environment:
SO: Freebsd 9.1
Web2py: 2.5.1-stable+timestamp.2013.06.13.15.30.17

**Attachment:** [ok.png fail.png 127.0.0.1.2013-06-13.21-08-50.229aa122-bb03-4360-b256-fe445410b3f8](http://code.google.com/p/web2py/issues/detail?id=1528)

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1528_

**Comment by niphlod** [comment]
_From [jjachuf_at_gmail.com](https://code.google.com/u/jjachuf_at_gmail.com/) on June 13, 2013 17:22:36_

I forgot. As shown this new figure, if you use the link on the top bar, it works fine.

**Attachment:** [fail.png](http://code.google.com/p/web2py/issues/detail?id=1528#hc1)

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on June 13, 2013 21:38:22_

**Status:** Fixed

**Comment by niphlod** [comment]
_From [massimod..._at_gmail.com](https://code.google.com/u/103194153896633626871/) on June 13, 2013 21:42:32_

This issue was closed by revision f19a32233abe .

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on July 15, 2013 07:30:35_

According to José, this is happening again but the fix was never reverted.

**Status:** Started

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on September 01, 2013 09:25:32_

I cannot reproduce this problem since the fix in trunk. I am using the code you posted.
Please reopen a different ticket with another example.

**Status:** Done

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on September 03, 2013 09:01:39_

Checking again:

db.define_table('contracts',
   Field('costumer', 'reference costumers', label=T('Costumer')),
   Field('name', 'string', label=T('Name')),
   Field('description', 'text', label=T('Description')),
   Field('start_date', 'date', label=T('Start Date')),
   Field('end_date', 'date', label=T('End Date')),
   Field('upload_data', 'upload', label=T('Attachment')),
   \#Field('priority', 'integer', label=T('Order')),
format = '%(name)s')

db.define_table('products',
   Field('costumer', 'reference costumers', label=T('Costumer')),
   Field('name', 'string', label=T('Name')),
   Field('description', 'text', label=T('Description')),
   \#Field('category', 'reference categories',label=T('Category')),
   Field('currency', 'reference currencies', label=T('Currency')),
   Field('price', 'double', label=T('Price')),
   Field('status', 'integer', label=T('Status')),#, default=1),
format = '%(name)s')

Also in my controller i have:

def costumer_profile():
   form = SQLFORM.smartgrid(db.costumers,
       linked_tables=['products', 'contracts',
           'services', 'protocols'
           ],
       fields=[
               db.costumers.legal_name,
               db.costumers.short_name,
               db.costumers.commercial_id,
           ],
           )
   \#form = SQLFORM.grid(db.work_places)
   return dict(form=form)

**Status:** Accepted

**Comment by mdipierro** [comment]
There is error here. If is just that if you specify a list of fields (as opposed to a dict of list of fields), then you must include fields for each tables. In this case there are no fields for the linked tables.
