### ISSUE TITLE
Misleading error:relation "auth_user" already exists'

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#664]
_From [mjmare31..._at_gmail.com](https://code.google.com/u/114349152275557912536/) on June 22, 2013 22:07:09_

Using the trunk version (2.5.1-stable+timestamp.2013.06.22.01.45.55) of web2py I'm getting with both MySQL and Postgresql the error message "table/relation auth_user already exists" when providing an incorrect password for the database user. 
Correcting the password in the connection string makes the error go away. 

Although the error might be technically correct (wrong credentials will prevent access to tables) it is not helpful in fixing a configuration error.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1554_

**Comment by niphlod** [comment]
_From [ABasta..._at_gmail.com](https://code.google.com/u/103720714265511973715/) on August 09, 2013 09:06:23_

Another problem is changing the username and/or password of the database connection.

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on September 01, 2013 07:36:25_

**Labels:** -Type-Defect Type-Enhancement

**Comment by niphlod** [comment]
IMHO this has been fixed. feel free to reopen in case it's still there.

**Comment by SamuelBonilla** [comment]
I'm having the same problem with postgres, and some time does not create tables.... is it a bug ?
