### ISSUE TITLE
LDAP issue

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#671]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on August 21, 2013 10:50:57_

https://groups.google.com/forum/#!topic/web2py/sEpOWYk0mFA

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1645_

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on September 17, 2013 12:58:06_

patch posted: https://groups.google.com/forum/#!topic/web2py/sEpOWYk0mFA

**Comment by BuhtigithuB** [comment]
Do you want I make a PR for this?

I was about doing just that, to make sure we respect the principle of "only
one way of doing thing" by using the get_or_create_user()

I will make some test and send a PR.

Richard

**Comment by niphlod** [comment]
+1 for refactoring and taking care of it (if it's an issue). If it comes with a better explanation and a section on the book, even better.

PS: Sorry but I'm triaging tickets and frankly a ticket more than 2 year old without any "interaction" just amounts to no activities to be done. Feel free to reopen since it seems you're fiddling with the same piece of code in these days :-P

**Comment by BuhtigithuB** [comment]
You right and I just read the code that I submit and I was completly wrong... Leave it close... I will try a PR, if I succeed in importing get_or_create_user() which will at least avoid doing an custom update from ldap_auth.py
