### ISSUE TITLE
Janrain/RPX widget migration

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#673]
_From [molhokwai](https://code.google.com/u/molhokwai/) on August 31, 2013 10:12:09_

What steps will reproduce the problem? 1. Integration of Janrain/RPX login method 2. 3. What is the expected output? What do you see instead? Seemingly unstable widget... the legacy version of the janrain/rpx login widget is no longer supported: http://developers.janrain.com/documentation/widgets/legacy-sign-in-widget/ What version of the product are you using? On what operating system? Version 2.3.2 (2012-12-17 15:03:30) stable
Windows 7, SP1, x64 Please provide any additional information below. The migration guide: http://developers.janrain.com/documentation/widgets/legacy-sign-in-widget/social-sign-in-migration-guide/ Thanks...

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1656_

**Comment by niphlod** [comment]
is this still valid ? I hope not! @mdipierro : do you recall something done about it ?

**Comment by niphlod** [comment]
@abastardi, @mdipierro , @michele-comitini  : is this still valid ? is the code published at http://web2py.com/books/default/chapter/29/09/access-control?#Integration-with-OpenID--Facebook--etc- fine ?

**Comment by mdipierro** [comment]
No. The documentation is wrong. Will fix it.
