### ISSUE TITLE
DAL: Add support index creation 

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#675]
_From [michele...._at_gmail.com](https://code.google.com/u/104551602623805320646/) on September 04, 2013 18:00:06_

Add new call or paramenters to define_table to allow creation of SQL indexes on Table and/or Field or tuple of Fields.

some examples:

db.create_table('t1', Field('f1'), Field('f2'), indexes=['f1', ('f1','f2')])
db.create_index(db.table, [db.field1, db.field2])
Field('uuid', create_index=True)

Discussed here: https://groups.google.com/d/msg/web2py-developers/Bm80JcZoz_g/QK4TMqeqM9cJ

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1665_

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on September 04, 2013 09:01:21_

I like the first option best.

**Comment by sp1d3rx** [comment]
I feel that this is best left out, database administrators should manage indexes and whatever database you use, you have more than indexes to choose from such as statistics, materialized views, indexes including columns, etc. Indexes shouldn't be required or relied upon, as that's up to the dba whether they want to keep an index or not.

**Comment by niphlod** [comment]
if I want a model with an index, it's because I'd like it on the table. It's an option, not an enforcement.
And, I'm a DBA. And, a web2py-user

**Comment by sp1d3rx** [comment]
I understand that, but if you are putting it in the models, you are making it a requirement.  What I mean is that if the index does not exist, it will create it, and migrate it... I get you are a DBA and a web2py user, there may be people who have a different dba and someone else for web2py. In any case, if you are the dba, just create the indexes as you need them using whatever dba tools are available to you, or use the db.executesql. I see no need to special index handling in web2py. I suppose it could be added, but has there been much of a call for this kind of feature?

**Comment by michele-comitini** [comment]
I suppose niphlod is right, but the problem are migrations, and the point
is that migration code need some more intelligence to make robust handling
of constraints on the db.  Probably migrations should be versioned so that
they know what is the state of the db before trying to migrate.

2015-03-26 23:29 GMT+01:00 sp1d3rx <notifications@github.com>:

**Comment by sp1d3rx** [comment]
Anyway, perhaps I should make a request for 'check constraints' added to the database. I mean, we have constraints in web2py such as 'is_a_number' and stuff, what about 'is_a_zipcode' and have the constraint not only checked by web2py but also by the sql server itself via the constraints on columns? for example...

zip LIKE '[0-9][0-9][0-9][0-9][0-9]'

from here: https://msdn.microsoft.com/en-us/library/ms190377(v=sql.90).aspx

That said, where does it stop? Should we have this be in DAL or put it in a special mssql5 handler?

**Comment by jklundell** [comment]
A small first step would be to make a DAL create-index call, and leave it to the user to call it as a more portable alternative to db.executesql. Among other things it could hide the non-existence of IF EXISTS clauses and syntax differences.

**Comment by niphlod** [comment]
@sp1d3rx : every backend has the notion of indexes. If the developer codes an app that needs an index, it's because the developer felt it's needed. Any "serious" app that ships with a database comes with its own structure and its own indexes.
Shipping an app with a model that contains an index is not bad-per-se. Enforcing an index where is not needed is a bad design choice, but it's not hurting anyone.
It's the same of coding an app with "suboptimal" types (e.g. a double instead of a decimal to store something related to "money"): the app still does what it needs to do, but it could have been handled better both in code an in the backend: if you can access the source code you can alter it to match your standards.

That being said, it's true that there are a lot of intricacies involved, but we're not asking to support anything else than the two standards that are pretty common and will close 90% of the deals: clustered or not, unique or not.
as @jklundell says, it's not going to be easy and it's going - probably - to be handled initially as table migrations are now: we store somewhere the current state, if it's there don't issue any statement, if it's not there issue the creation of the index.

**Comment by niphlod** [comment]
@sp1d3rx : on "check constraints".... it's not making much sense. you check the value already in python BEFORE storing the value. making the database do the same check is a waste of time.

**Comment by sp1d3rx** [comment]
Since the DAL is split off on it's own project, I suggest the DAL issues here be moved to pydal and these closed with a reference to the new issues list on the pyDAL page.

**Comment by niphlod** [comment]
this is now tracked at https://github.com/web2py/pydal/issues/152
