### ISSUE TITLE
The Bayesian classifier turns 'one to one' into 'one-to-many' relationship

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#690]
_From [matheus...._at_gmail.com](https://code.google.com/u/117634160511727602807/) on January 16, 2014 23:20:05_

What steps will reproduce the problem? 1. Use the populate.py module and populates TABLE A that is referenced by TABLE B
2. Populates with the same module the TABLE B with the same quantity of TABLE A What is the expected output? What do you see instead? TABLE B should have the same ids of TABLE A on the reference column. Instead of it, appears some repeated ids on TABLE B, turning a possible 'one to one' relationship (like a house and its address) between these tables onto a 'many-to-many' relationship (like a house with many addresses). What version of the product are you using? On what operating system? 2.7.4-stable+timestamp.2013.10.14.15.16.29
(Running on Rocket 1.2.6, Python 2.7.4) Please provide any additional information below. Code sample

\#house_address has a reference column that points to house table

n = 9
populate(db.house,n=n)
populate(db.house_address,n=n)

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1856_

**Comment by niphlod** [comment]
_From [matheus...._at_gmail.com](https://code.google.com/u/117634160511727602807/) on January 16, 2014 14:23:13_

I would change the priority to Low, but I could not find how after I have saved the issue.

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on February 23, 2014 21:04:46_

The DAL does not distinguish a one-to-many from a one-to-one relation therefore populate does not. Please bing this up on web2py-developers.

**Comment by mdipierro** [comment]
No way to fix this.
