### ISSUE TITLE
SQLFORM Insert Fails with SQLCustomType

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#692]
_From [mca..._at_gmail.com](https://code.google.com/u/109910092030153265550/) on February 24, 2014 18:22:37_

I've got this error, trying to insert with SQLCustomType, with both 2.8.2 and trunk version under Ubuntu 10.04):

    \<type 'exceptions.AttributeError'> 'str' object has no attribute 'utctimetuple'

It fails with SQLFORM, SQLFORM.grid and SQLFORM.smartgrid. It works fine if you replace type=ut_dt with 'datetime'.

* How to reproduce:

1. Code in a controller:

def custom():
    from gluon.dal import SQLCustomType
    from datetime import datetime
    from calendar import timegm
    
    ut_dt = SQLCustomType(
        type    = 'datetime',
        native  = 'integer',
        encoder = (lambda dt: timegm(dt.utctimetuple())),
        decoder = (lambda ut: datetime.utcfromtimestamp(ut))
    )
    
    db = DAL('sqlite:memory:')
    db.define_table('event',
        Field('day_and_time', type=ut_dt)
    )
    
    form = SQLFORM(db.event)
    
    if form.process().accepted:
        db.event.insert(day_and_time=form.vars.day_and_time)
    
    return dict(html=form)

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1879_

**Comment by mcamel** [comment]
I've found a workaround: explicit validator

You can set 'validator=IS_DATETIME()' at SQLCustomType definition or can set 'requires=IS_DATETIME()' at field definition.

SQLCustomType source code says default validator for 'type' is used if not specified, but seems it's not that way.

**Comment by mdipierro** [comment]
Yes. You need to set your own validators for SQLCustomType.
