### ISSUE TITLE
Can't define referenced table after it's referencing from web2py v2.9.3

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#699]
_From [d.bu..._at_gmail.com](https://code.google.com/u/106126117366631760005/) on March 08, 2014 12:14:54_

What steps will reproduce the problem? 1. Define referenced table after it's referencing
2. Set lazy_tables=False (means don't activate lazy_tables)
3. Call any app url What is the expected output? What do you see instead? In web2py v2.8.2 everything is fine - you see the controller's result. From version 2.9.3 (including 2.9.4) you see only "KeyError: 'Cannot resolve reference ... in ... definition'" What version of the product are you using? On what operating system? Ubuntu server 12.04 / Ubuntu desktop 13.10; web2py v2.9.4 Please provide any additional information below. Sample error log:
Traceback (most recent call last):
  File "/home/donatas/web2py/gluon/restricted.py", line 217, in restricted
    exec ccode in environment
  File "/home/donatas/web2py/applications/welcome/models/db.py", line 87, in \<module>
    Field('subject_id', 'reference subject')
  File "/home/donatas/web2py/gluon/dal.py", line 8223, in define_table
    table = self.lazy_define_table(tablename,*fields,**args)
  File "/home/donatas/web2py/gluon/dal.py", line 8260, in lazy_define_table
    polymodel=polymodel)
  File "/home/donatas/web2py/gluon/dal.py", line 925, in create_table
    raise KeyError('Cannot resolve reference &#37;s in &#37;s definition' &#37; (referenced, table._tablename))
KeyError: 'Cannot resolve reference subject in contract definition'

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1896_

**Comment by niphlod** [comment]
_From [t..._at_growthpath.com.au](https://code.google.com/u/104905927789215169353/) on March 08, 2014 22:00:52_

First bad commit a big commit

franklin:web2py tim  ((no branch, bisect started on 7703d95)) git bisect bad 14bcad629eb2b73266b11b4c9dbf63499c73d38b is the first bad commit
commit 14bcad629eb2b73266b11b4c9dbf63499c73d38b Date:   Fri Nov 8 17:11:36 2013 +0100

    quoting of tablenames and field names
    
    fix for wrong sequence name quoting
    
    fix for wrong sequence name quoting 2
    
    reverted test to quoted rname
    
    rname passed asis. freedom in table names and field names. Case sensitivity in field and table names
    
    removed test of allowed char sequence in table and field names, there is no limit anymore

...

**Comment by niphlod** [comment]
_From [michele...._at_gmail.com](https://code.google.com/u/104551602623805320646/) on March 14, 2014 03:39:17_

The issue is due to the fact that web2py has to create also the foreign keys at the RDBMS level.  The difficulty is managing the foreign keys in a deferred fashion, but until that is implemented, there are 3 ways:
- do not manage foreing keys 
- manage foreign keys only when tables and references are in proper order (old behavior)
- keep the current behavior and have the user reorder the tables.

**Comment by niphlod** [comment]
_From [d.bu..._at_gmail.com](https://code.google.com/u/106126117366631760005/) on April 23, 2014 02:24:53_

If keeping current behaviour, what should be order of tables if I have:

auth.settings.extra_fields['auth_user'] = [
    ...
    Field('contract_document_id', 'reference document_document', ondelete='SET NULL'),  # means 'user employment contract document'
    ...
]

and

db.define_table('document_document',
    ...
    Field('file', 'upload', uploadseparate=True, autodelete=True),
    Field('user_id', 'reference auth_user', default=auth.user_id, ondelete='RESTRICT'),  # means 'which user added document'
    ...
)

I can't figure out if myself.

**Comment by niphlod** [comment]
_From [badweath..._at_gmail.com](https://code.google.com/u/107429560404984418044/) on July 11, 2014 19:05:00_

I too have a similar situation with the following:

db.define_table('companies', 
    Field('name', 'string', unique=True), 
    Field('contact_name', 'string'), 
    Field('contact_phone', 'string'), 
    Field('contact_email', 'string', requires=IS_EMPTY_OR(IS_EMAIL())),
    Field('lrt_bio_contact', 'reference auth_user'))    

auth.settings.extra_fields['auth_user']= [ Field('company', 'reference companies', represent=lambda id, row: row.company.name if row.company else "")]
auth.define_tables(username=False, signature=False)

**Comment by dburba** [comment]
Any progress in current situation? As I understand web2py v2.9.12 works in the same way.

**Comment by ilvalle** [comment]
I'll open a discussion on the dev list

**Comment by niphlod** [comment]
@ilvalle : do you recall were we are for this ?

**Comment by ilvalle** [comment]
This is the discussion on the dev-list https://groups.google.com/d/topic/web2py-developers/ZnqC0GZiTd8/discussion
Do know if we want to work to fix it or just leave with the current approach.

**Comment by niphlod** [comment]
IMHO consistency is the thing to reach for. A model should result in the same underlying structure (idempotent). 
If right now we can't achieve that (i.e. until the machinery to create table first and FK at a later stage is done) IMHO "better safe than sorry" is the way to go.

**Comment by ilvalle** [comment]
@niphlod see https://github.com/ilvalle/pydal/tree/deferred-references
The creation of a reference pointing to table not already defined is postponed when the referenced table is created (the common table migration is triggered).
It passes all tests (+ the ones I wrote) but it fails on sqlite:memory because it doesn't support migration.

**Comment by ilvalle** [comment]
rname is at a lower level, the trick is at define_table. A reference field
is simply removed from the one that should populate the sql 'CREATE TABLE
...'. When the referenced table is created, a migration for the former
table is fired and an ALTER TABLE with the reference field is executed.
At python level the reference field is not touched at all, you can still do
db.table.reference_field.somethimg = ...

You are right, there is no way to detected you have referenced a non
existing object.

At the moment, it works when lazy_table=False, I've to test the
lazy_table=True


 Paolo

2015-05-05 21:06 GMT+02:00 niphlod <notifications@github.com>:

**Comment by niphlod** [comment]
>>> You are right, there is no way to detected you have referenced a non
existing object.

fifty shades of bad ...

**Comment by ilvalle** [comment]
To sum up, I think this is an important missing feature of https://github.com/web2py/pydal. 
As described above, my proposal is to postpone the creation of a reference pointing to a table not already defined when the referenced table is created.
The limits are:
- it doesn't work with sqlite:memory (because this backend doesn't support migration)
- it doesn't detected references pointing to a non existing table. (still an error will be raised when you access that reference)
do you see any alternative approach for it?
@gi0baro @mdipierro thoughts?

**Comment by niphlod** [comment]
leaving sqlite:memory aside for a ton of reasons (not even good for testing) IMHO it's a pile of problems waiting to happen not being able to tell if your model is right (and tight).
Users will get screwed by this "lazy checking" of referential integrity: it's definitely not a thing to propose/enforce as a default behaviour, especially for the large unexperienced userbase web2py and pydal have.

**Comment by gi0baro** [comment]
IMHO this is not a missing feature, is a wrong design pattern. I think pyDAL should not alter the "normal" table creation flow, and should push developers to use good design patterns for their applications.

All the examples users gave on this should be implemented using 3 tables, not 2:
```
db.define_table('companies', 
    Field('name', 'string', unique=True), 
    Field('contact_name', 'string'), 
    Field('contact_phone', 'string'), 
    Field('contact_email', 'string', requires=IS_EMPTY_OR(IS_EMAIL()))
)
db.define_table('companymemberships',
    Field('company', 'reference companies'),
    Field('user', 'reference auth_user')
)
```

In conclusion: I think we should not spend any time trying to build a solution for this.

**Comment by niphlod** [comment]
I take full responsibility for closing this. 
It has been discussed over and over with all interested parties chiming in stating the obvious, which is "the user should define tables in the correct order".
