### ISSUE TITLE
T.is_writable cannot be disabled

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#708]
_From [mca..._at_gmail.com](https://code.google.com/u/109910092030153265550/) on May 20, 2014 21:48:48_

* What steps will reproduce the problem?

 -Test this in a controller:

T.is_writable = False
def index():
    db = DAL('sqlite:memory:')
    db.define_table('event',
        Field('date_time', 'datetime')
        )
    return dict(html=SQLFORM.grid(db.event, user_signature=False))
 

* What is the expected output? What do you see instead?

 -Expect no changes at language file, but this entry is automatically added:

    'Date Time': 'Date Time',

* What version of the product are you using? On what operating system?

 -Ubuntu 10.04 Version 2.9.5-trunk+timestamp.2014.05.09.15.41.38

* Please provide any additional information below.

 -Related discussion: https://groups.google.com/forum/#!topic/web2py/xlLmnw8cBvg

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1936_

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on May 26, 2014 21:40:31_

Can you help me. Can you check that current.T == T?

**Comment by niphlod** [comment]
_From [mca..._at_gmail.com](https://code.google.com/u/109910092030153265550/) on May 27, 2014 01:18:14_

bool(current.T == T) returns True.

Just in case it helps:
sometimes i don't see changes at language file (e.g. with 'cat es.py'), but changes are there if i access through the admin interface (e.g. http://127.0.0.1:8000/admin/default/edit_language/tests/languages/es.py

**Comment by cassiobotaro** [comment]
I think it's fixed in #404. Can we closed that?

**Comment by niphlod** [comment]
right away.
