### ISSUE TITLE
Work with MSSQL with codepage other than latin1 or unicode

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#716]
_From [aleksey...._at_gmail.com](https://code.google.com/u/106784686348199015381/) on August 11, 2014 02:59:47_

What steps will reproduce the problem? 1. In models
dbsol = DAL('mssql2://user:password__at__w2ptkts/SacuraOnline', db_codec = 'cp1251', migrate_enabled = False)
auth = Auth(dbsol)

In default.py
def sol_users():
    grid = SQLFORM.grid(dbsol.auth_users)
    return locals()

In default/sol_users.html
{{extend 'layout.html'}}
\<h1>Пользователи SOL</h1>
{{=grid}} What is the expected output? What do you see instead? Grid work as expected, show and save data with cyrillic letters.

But when try to save profile data from (right top corner) got an error
\<type 'exceptions.UnicodeEncodeError'> 'charmap' codec can't encode characters in position 0-5: character maps to \<undefined> What version of the product are you using? On what operating system? Windows 7
2.9.5-trunk+timestamp.2014.03.29.21.54.41
(Running on Rocket 1.2.6, Python 2.7.6) Please provide any additional information below. Why it may be happened ? The data in grid and profile is same. Profile data showing correctly. 
May be procedure saving data from grid and saving data from profile are different ?

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1964_

**Comment by niphlod** [comment]
_From [massimo...._at_gmail.com](https://code.google.com/u/111721297562664670951/) on August 28, 2014 10:19:54_

Why are you doing this? db_codec = 'cp1251' web2py expects unicode in db.
Please bring this up on the mailing list.

**Comment by niphlod** [comment]
_From [aleksey...._at_gmail.com](https://code.google.com/u/106784686348199015381/) on September 01, 2014 17:01:13_

I have a legacy DB with cp1251 encoding. And in Official Documentation I read following. This is just my case. What's wrong ?

The database abstraction layer
Notice that by default web2py uses utf8 character encoding for databases. If you work with existing databases that behave differently, you have to change it with the optional parameter db_codec like 
db = DAL('...', db_codec='latin1')
otherwise you'll get UnicodeDecodeError tickets. http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer?search=db_codec

**Comment by valq7711** [comment]
I think It's not web2py's problem  but DB-driver's. I had got the same trouble with MSACCESS+ODBC and I've solved it. I'll post my solution after weekend. As far as I remember this is due to an attempt to re-encode/decode already encoded/decoded string or  something like that

**Comment by valq7711** [comment]
This is my solution:
```python
 def MSACCESS_adapt(s,f):
     for it in f.items():
     if type(it[1])==str:
          f[it[0]]=it[1].decode('utf8').encode('1251')
     elif type(it[1])==datetime.datetime:
          f[it[0]]=it[1].strftime('%Y-%m-%d %H:%M:%S')

 mdb.table_cp1251._before_update.append(MSACCESS_adapt)
 ```
