### ISSUE TITLE
Allow auth.login() to return a specific error message

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#726]
_From [markruol..._at_gmail.com](https://code.google.com/u/114619454780239522399/) on September 17, 2014 19:29:40_

Currently, auth.login() only returns a generic "invalid error" upon login error. 

However, the generic error message is no more secure than an error message detailing whether the password or username/email was incorrect, because the registration page already reveals whether or not a username/email is taken.

Returning a more specific error message upon login error would be a big usability improvement at no cost to security:
1. Is the username/email in the database?
2. Is the password correct for that username/email?

I understand that this is done to be compliant with OWASP, but as discussed here: https://groups.google.com/forum/#!topic/web2py/0zCjs2G9ucE , it seems it's possible to implement this feature without breaking OWASP compliance.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1984_

**Comment by frog42** [comment]
Yeah, that'd definitely be cool.

**Comment by leonelcamara** [comment]
@amerikan yeah I can do it, I've just came back from vacation so I have a tough week ahead with the work that piled up but I'll try to get to it as soon as possible.

**Comment by amerikan** [comment]
It’s not an urgency at all. I actually don’t need this myself, but I was just reviewing issues and saw your name.

**Comment by leonelcamara** [comment]
@amerikan as promised the pull request is made, sorry it took so long.
