### ISSUE TITLE
Open Redirection Vulnerability

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#731]
_From [bhati.fe..._at_gmail.com](https://code.google.com/u/108896182498744010339/) on October 01, 2014 06:46:01_

Issue - Open Redirection TO Any Domain 
Dependency - For Successful Redirection We Need Administration Password 
Only Unauthenticated Users Are Affected , If an user is already authenticated on web2py then he will not get redirec , Apart from this , Users who are non authenticated like "End Users" Will get redirection successfully"

Severity - Medium ( According To Me ) =D Correct me if i am wrong
Tested On - Web2py Tester Version From Official Site
Reported By  - Narendra Bhati

======================================================================
Here i have tested this issue on Tested version provided by Web2py Official Site What steps will reproduce the problem? 1. http://127.0.0.1:8000/admin/default/index?password=sumasoft123&send=http&#37;3A&#37;2F&#37;2Fgoogle.com
( successful redirection tested on "Tester" Version Of Web2py Latest Version)
2. Replace the password parameter value to your administration password 
3. After replacing the valid password enter any domain and you will ger redirected What is the expected output? What do you see instead? What version of the product are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1992_

**Comment by niphlod** [comment]
_From [bhati.fe..._at_gmail.com](https://code.google.com/u/108896182498744010339/) on September 30, 2014 21:53:11_

Sorry i forget to mention other information , Here it is

What is the expected output? What do you see instead?

Expected out is to prevent users to redirect to other domain , But
Instead of preventing the user to redirect to other domain , it is actually allowing me to redirect to any external domain 

What version of the product are you using? On what operating system?
Web2py - Version 2.9.11

Please provide any additional information below.
OS- Windows 8
Browser - Mozilla , Chrome ( Updated )

**Comment by niphlod** [comment]
_From [bhati.fe..._at_gmail.com](https://code.google.com/u/108896182498744010339/) on October 17, 2014 03:48:38_

More update on this issue
Below mention open redirection is depend on admin crdentials
But this URl can redirect users to external domain without need of any credentials

http://127.0.0.1:8000/user/logout?_next=http://attacker.com

this is the clear open redirection vulnerability which i found recently

**Comment by narendrabhati** [comment]
Any acknowledgement for reporting this ?

**Comment by niphlod** [comment]
would it be enough to check for "http(s)" in _next and not redirecting at all in case it's found ?

**Comment by niphlod** [comment]
actually, there's a whole machinery to prevent open redirections in login() but not on logout(). we should extend that machinery to logout() too.

**Comment by BuhtigithuB** [comment]
And by the way, why not making it reusable for user to help them managing
flow in app without having to revinvent the wheel and create security hole
as I am doing right now :D
