### ISSUE TITLE
web2py DAL bug: OperationalError - MySQL server has gone away while closing a connection in pool

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#733]
_From [Babu.Ann..._at_gmail.com](https://code.google.com/u/117901553787749562675/) on October 10, 2014 06:54:02_

Environment: Ubuntu 12.04; Web2py 2.9.11-stable

Let me describe the problem as below:

- We use 2 DAL instance talking to 2 different databases, each with a connection pool of 10
- We make many frequent DAL calls using both the DAL connections which results in many objects in the connection pool
- At some point, web2py starts throwing an OperationalError with MySQL server has gone away when closing a connection. The stack trace is as below:

S'Traceback (most recent call last):\n  File “.../app/gluon/main.py", line 543, in wsgibase\n    BaseAdapter.close_all_instances(\'rollback\')\n  File “.../app/gluon/dal.py", line 611, in close_all_instances\n    db._adapter.close(action)\n  File “.../app/gluon/dal.py", line 591, in close\n    getattr(self, action)()\n  File “…/app/gluon/dal.py", line 1922, in rollback\n    return self.connection.rollback()\nOperationalError: (2006, \'MySQL server has gone away\')\n'

This made the whole app very unstable with error tickets occurring almost for every action. 

We had tried wrapping all our DAL calls with exception handlers for this error but we were unable to get this sorted. Eventually, the only way I could fix this is to put an exception handler around the code block which is throwing the error as below:

\# added this to line 611 in dal.py
try:
    db._adapter.close(action)
except:
    pass

Note that, this error is reproducible in older versions of web2py as well.

I would like to bring this forward to the group for further action on the same.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1995_

**Comment by gi0baro** [comment]
I would like to start a depth analysis and discussion about this with @mdipierro and @niphlod

**Comment by ilvalle** [comment]
this issue can be closed
