### ISSUE TITLE
Common filter not applied if query table implicit

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#740]
_From [mca..._at_gmail.com](https://code.google.com/u/109910092030153265550/) on October 31, 2014 21:08:18_

* What steps will reproduce the problem?

    db.define_table('blog_post',
        Field('subject'),
        Field('post_text', 'text'),
        Field('is_public', 'boolean'),
        common_filter = lambda query: db.blog_post.is_public==True
    )
    
    db.blog_post.insert(subject='one', post_text=str(request.utcnow), is_public=True)
    db.blog_post.insert(subject='two', post_text=str(request.utcnow), is_public=False)
    
    return dict(message=db().select(db.blog_post.ALL, limitby=(0,5)))

* What is the expected output?

1 record.

* What do you see instead?

2 records.

* What version of the product are you using? On what operating system?

web2py v2.9.5 and v2.9.11 at Ubuntu 14.04. Sqlite and Mysql backends tested.

* Please provide any additional information below.

I think this a security bug because user could access whole table.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2010_

**Comment by niphlod** [comment]
_From [mca..._at_gmail.com](https://code.google.com/u/109910092030153265550/) on October 31, 2014 13:11:09_

Related discussion: https://groups.google.com/d/msg/web2py/c2FZojsmlsU/4alH4qHnOw8J

**Comment by niphlod** [comment]
put it in better words, if anyone hasn't still fixed this, this is not going to be fixed. 
In retrospect, introducing the shortcut of not passing a Query to db() introduced a LOT of side-cases. 
I'd go for slowly discouraging it alltogether. @gi0baro, @mdipierro  : thoughts ?

**Comment by gi0baro** [comment]
@niphlod ouch! it's the first time I hear about the common filters :D
Anyway, I think we should move this to pyDAL and get it fixed.

**Comment by niphlod** [comment]
tracked from here on at https://github.com/web2py/pydal/issues/388
