### ISSUE TITLE
Odd IS_LIST_OF behaviour

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#742]
_From [manuele...._at_gmail.com](https://code.google.com/u/103187076317995702211/) on November 20, 2014 11:15:03_

What steps will reproduce the problem? 1. In [6]: IS_LIST_OF(IS_NOT_EMPTY())(None)
    Out[6]: ([None], 'Enter a value')

2. In [7]: IS_NOT_EMPTY()('')
    Out[7]: ('', 'Enter a value')

3. In [5]: IS_LIST_OF(IS_NOT_EMPTY())('')
    Out[5]: ([], None)

* What is the expected output? What do you see instead?

I expect:

IS_LIST_OF(IS_NOT_EMPTY())('')
([''], 'Enter a value')

but I obtain:

IS_LIST_OF(IS_NOT_EMPTY())('')
([], None)

* Please provide any additional information below.

The problem is that every time you don't insert any value in the field using a form a null string is validated (i.e. "").
As I can see from code[1] it seams to me the validator expects any kind of value and if it's not a list/tuple it insert into a list and validate it.
Another problem is that if the result of the operation str(item).strip()[2] is evaluated as False no validation is applied... so there's no way to oblige the user not to pass a null value (i.e. to insert any value).

Could it be a solution to remove the mentioned test[2]? Or maybe there's another reason I cannot see not why it is there?

Thank you very mutch
Best regards

    Manuele

[1] https://github.com/web2py/web2py/blob/master/gluon/validators.py#L2508 [2] https://github.com/web2py/web2py/blob/master/gluon/validators.py#L2520

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2019_

**Comment by niphlod** [comment]
uhm. There's a problem with this validator and how it's intended.....
The check on ```str(item).strip()``` is done because usually you'd use IS_LIST_OF with a list:string field, and it could happen that a field is submitted as empty (e.g. with the default widget, pressing the + button but not filling anything). 
Since usually '' in forms equals "there's nothing here", web2py doesn't interpret a ['', 'something'] list for this.... ultimately, ['', 'something'] in form.vars.something gets "translated" to ['something'] in python.

That being said, you should be - theoretically - allowed to use IS_LIST_OF(minimum=1) if the goal is users not being able to leave a list:string field "empty in all fields". 
However I spotted a little problem in the validator itself... the length of the list (the one checked with minimum/maximum parameters) is not stripped from the '' values.... To that matter, the simplest solution (and more linear) would be to rewrite the validator in this way

```python
    def __call__(self, value):
        ivalue = value
        if not isinstance(value, (list, tuple)):
            ivalue = [ivalue]
        ivalue = [i for i in ivalue if str(i).strip()]
        if self.minimum is not None and len(ivalue) < self.minimum:
            return (ivalue, translate(self.error_message) % dict(min=self.minimum, max=self.maximum))
        if self.maximum is not None and len(ivalue) > self.maximum:
            return (ivalue, translate(self.error_message) % dict(min=self.minimum, max=self.maximum))
        new_value = []
        other = self.other
        if self.other:
            if not isinstance(other, (list, tuple)):
                other = [other]
            for item in ivalue:
                v = item
                for validator in other:
                    (v, e) = validator(v)
                    if e:
                        return (ivalue, e)
                new_value.append(v)
            ivalue = new_value
        return (ivalue, None)
```
@mdipierro : opinions ?

**Comment by mdipierro** [comment]
I think I agree with you
