### ISSUE TITLE
Web2py broken language files

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#744]
_From [jjachuf_at_gmail.com](https://code.google.com/u/jjachuf_at_gmail.com/) on December 05, 2014 16:38:57_

Web2py:
2.9.11-stable+timestamp.2014.09.15.23.35.11

SO: FreeBSD 10.1-RELEASE

Message from the console:

ERROR:root:Syntax error in /usr/home/jose/web2py/applications/admin/languages/es.py (invalid syntax (<unknown>, line 473))
ERROR:root:Syntax error in /usr/home/jose/web2py/applications/joyas/languages/es.py (invalid syntax (<unknown>, line 435))
ERROR:Rocket.Errors.Thread-8:Unhandled Error when serving connection:
Traceback (most recent call last): What steps will reproduce the problem? 1. I copy in my app/languages es.py from welcome
2. I run my application
3. Is broken the file es.py

The file has this structure:
\# -*- coding: utf-8 -*-
{
'!langcode!': 'es',
...
}

After running the application the initial structure is repeated twice

\# -*- coding: utf-8 -*-
{
'!langcode!': 'es',
...
}
\# -*- coding: utf-8 -*-
{
'!langcode!': 'es',
...
}
\# -*- coding: utf-8 -*-
{
'!langcode!': 'es',
...
}

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2023_

**Comment by niphlod** [comment]
_From [paolo.va..._at_gmail.com](https://code.google.com/u/107767337307670204068/) on December 18, 2014 01:44:40_

I can't reproduce the issue. 
Can you try to update all language files from admin app?
Copy the file from welcome
Update all languages using the admin app button
Run your application

**Comment by josejachuf** [comment]
1) I edited gluon/languages.py
2) If I need to edit my languages/es.py, I do it "by hand"

In gluon/languages.py commented these lines:

 811       # update language file for latter translation
 812       #if self.is_writable and is_writable() and \
 813       #        self.language_file != self.default_language_file:
 814       #    write_dict(self.language_file, self.t)

this solved my problem, but I'm not sure it can be broken elsewhere.

**Comment by josejachuf** [comment]
The problem is corrected by applying the following patch to 

file /web2py/gluon/portalocker.py

```patch
--- portalocker.py.old	2015-05-30 13:33:10.000000000 -0300
+++ portalocker.py	2015-06-25 15:46:24.000000000 -0300
@@ -119,7 +119,7 @@
             lock(self.file, LOCK_EX)
             if not 'a' in mode:
                 self.file.seek(0)
-                self.file.truncate()
+                self.file.truncate(0)
         else:
             raise RuntimeError("invalid LockedFile(...,mode)")
```

**Comment by niphlod** [comment]
fixed a long time ago.
