### ISSUE TITLE
sep = separator or current.response.form_label_separator

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#747]
_From [AnneVe..._at_googlemail.com](https://code.google.com/u/108003144278457342529/) on December 19, 2014 18:14:27_

I have the following code:

form = SQLFORM(db.nd_node_tag, record, deletable=True, showid=False,
                       formstyle=bootstrap3, separator='', hidden=dict(nodeID=nodeID))

separator='' no longer removes the separator from the label, separator=False neither.

I am using web2py 2.9.11 has separator='' been replaced? Please provide any additional information below. Anthony posted yhe following reply:

Looks like a backward incompatible change was made in SQLFORM.__init__. This:

sep = separator or ''

was changed to:

sep = separator or current.response.form_label_separator

That line should instead be:

sep = current.response.form_label_separator if separator is None else separator

Please submit an issue about this. In the meantime, you can do:

response.form_label_separator = ''

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2028_

**Comment by ilvalle** [comment]
@kirsn are you providing a new patch based on https://github.com/web2py/web2py/issues/794 ?

**Comment by kirsn** [comment]
@ilvalle, thanks for bringing this up. I have issued a pull request https://github.com/web2py/web2py/pull/841

**Comment by ilvalle** [comment]
this issue can be closed
