### ISSUE TITLE
latest Version 2.9.12 doesn't work with Apache using wsgi  

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#753]
_From [omi..._at_gmail.com](https://code.google.com/u/117551687292950814124/) on January 22, 2015 20:11:46_

Error ticket "'NoneType' object is no callable in gluon/globals.py" What steps will reproduce the problem? 1. Download the latest souce and run under apache
2. Running with Rocket server works fine What version of the product are you using? On what operating system? 2.9.12 Windows 2012 Please provide any additional information below. See forum post https://groups.google.com/forum/#!topic/web2py/yBM8Ybl_xGA

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2036_

**Comment by mdipierro** [comment]
I know we do not like Apache but this is a major issue for many users. Ideas?

**Comment by jklundell** [comment]
FWIW, I'm running 2.9.12 under Apache and having no trouble with admin. Maybe it's Windows, or the version of Apache it's using?

**Comment by dburba** [comment]
I have no problems on ubuntu server as well.

**Comment by niphlod** [comment]
I'll close this after 4 months of inactivity if nobody replies in a week.
