### ISSUE TITLE
SQLTABLE ignores truncate if headers also specified

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#754]
_From [psebby1..._at_gmail.com](https://code.google.com/u/107274190071983881964/) on January 22, 2015 23:45:10_

What steps will reproduce the problem? 1. In my controller, I get a set of rows via select() and put them in the returned dictionary.
2. In my view, I want to show the rows as a table, using the field labels in the table header and truncating long string values in the table cells:
{{=SQLTABLE(myRows, headers='labels', truncate=40)}} What is the expected output? What do you see instead? I expect to see the rows in a table with truncated cell values; instead the long string values are displayed in the cells without any truncation.  If I remove the "headers" parameter to SQLTABLE then cell truncation works as expected, so somehow the headers value causes the truncate value to be ignored. What version of the product are you using? On what operating system? Web2py 2.9.11 with Python 2.7 on Mac OSX.

Thanks - Web2py is a great framework!

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2037_

**Comment by niphlod** [comment]
_From [ABasta..._at_gmail.com](https://code.google.com/u/103720714265511973715/) on January 25, 2015 06:54:59_

Note, as a workaround, the "headers" argument can be a dictionary of dictionaries. The dictionary for each text/string column can include a "truncate" key specifying the truncate size for that column.

**Comment by niphlod** [comment]
_From [subbaram..._at_gmail.com](https://code.google.com/u/116822970470025815642/) on January 25, 2015 11:03:53_

submitted PR: https://github.com/web2py/web2py/pull/600

**Comment by kirsn** [comment]
Fixed. Can be closed.
