### ISSUE TITLE
Sanitizer is closing <br> and <img> tags too.

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#755]
_From [c..._at_cemeren.com](https://code.google.com/u/102223031108363556982/) on January 23, 2015 06:47:19_

What steps will reproduce the problem? 1. Sanitize any html content with these tags with permitted_tags defined as no close \<br/> What is the expected output? What do you see instead? Since it is closing basically all tags, you can notice the output is not what you have designed specially if there are br tags causing doubling the spaces. What version of the product are you using? On what operating system? 2.9.12-stable+timestamp.2015.01.17.06.11.03
(Running on Apache/2.4.9 (Unix) mod_wsgi/4.3.0 Python/2.7.3, Python 2.7.3) Please provide any additional information below.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2038_

**Comment by ilvalle** [comment]
fixed by https://github.com/web2py/web2py/commit/9ebc6d5ca7c025322cff7bc3cced61028348fdd1
