### ISSUE TITLE
Rss feed

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#757]
_From [dam..._at_gmail.com](https://code.google.com/u/101094302681590029076/) on January 25, 2015 19:51:23_

M. Di Pierro say: Please open a ticket and we will fix it soon. What steps will reproduce the problem? What string type pass for this work?

file: gluon/serializers.py (from 25 Sep 2014)
line: 182

    def safestr(obj, key, default=''):
        return str(obj[key]).encode('utf-8', 'replace') if key in obj else default

This code fail for me if have special characters.

Example:

if:
obj[key] = u"ó"  #unicode
fail

if:
obj[key] = "ó"  #string
fail

if change encode for decode in this line work if obj[key] is a unicode.
        return str(obj[key]).decode('utf-8', 'replace') if key in obj else default

Is this a possible bug?

Controlle example:

def rss():
    
    import gluon.contrib.feedparser as feedparser
    d = feedparser.parse(' http://rss.slashdot.org/Slashdot/slashdot/to' )  # this work

    d["entries"].insert(0, {"link": "", 
            "title": "title", "description": u"example description"})  # with this line work
    
    d["entries"].insert(0, {"link": "", 
            "title": "titlé", "description": u"example description"})  # with this line not work (é)
    from gluon.serializers import rss   
    test = rss(d)
    response.headers['Content-Type']='application/rss+xml'
    
    return test What version of the product are you using? On what operating system? 2.9.12 and before
from 25 Sep 2014 Please provide any additional information below. Very thanks.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2040_

**Comment by niphlod** [comment]
see also #732 . We should fix the issue once and for all. I'm closing #732 as a duplicate

**Comment by mdipierro** [comment]
perhaps not the next solution but a decent solution is in trunk.
