### ISSUE TITLE
Contrib adapters integration test

### ISSUE THREAD

**Issue by gi0baro** [web2py/web2py#759]

**Comment by ilvalle** [comment]
I'm not an expert of tox, how can we run both web2py and pydal tests ?
we should have tests on web2py for at least the contrib version of pg8000

**Comment by niphlod** [comment]
it's not a problem of tox. it's a problem of identifying what test needs to run.

**Comment by gi0baro** [comment]
I will try to work on something in the weekend.

**Comment by mdipierro** [comment]
Can this be closed?

**Comment by gi0baro** [comment]
No, until we find a way to run pydal tests inside web2py.

**Comment by niphlod** [comment]
@gi0baro : is this still opened ? can we assume that if we update contrib dependencies in web2py correctly, all of travis-ci testing (and, limitedly, appveyor's) that pull in the latest pypi available packages, would result effectively in stating that whatever we put in contrib would work "by design" ?

**Comment by gi0baro** [comment]
@niphlod the issue is still open because the idea was to "hack" unitttest library to import pyDAL tests and manually run them using the contrib drivers. I had no enough time to work on that.
Practically speaking, if web2py uses drivers which has the same APIs of the external ones (so, basically if there were no broken backward compatibilities in drivers included in web2py) everything will work, since we're already successfully testing the drivers injection.

I would like to leave this open until I inspected carefully a way to run pyDAL tests from web2py.

**Comment by niphlod** [comment]
@gi0baro : this is getting old. Either we circumvent it triple-checking that web2py ships what CIs test as dependencies, or I fear this would remain open for eternity...

**Comment by gi0baro** [comment]
@niphlod you're right. I will double check this in the next days to find out a solution

**Comment by niphlod** [comment]
@gi0baro : just reminding, because I'm cycling all issues with bleeding eyes ^_^ .
