### ISSUE TITLE
gluon/contrib/webclient.py doesn't work anymore

### ISSUE THREAD

**Issue by jredrejo** [web2py/web2py#767]
This useful tool doesn't work when the app uses the @auth.requires_login() decorator. 
This is due to the way the login form sends its data. 
    # login
    data = dict(email='homer@web2py.com',
                password='test',
                _formname='login')

_formname ='login' does not exist, and _formkey is not filled with webclient.

**Comment by niphlod** [comment]
uhm... I can't replicate the issue. Can you post an example where you show us where it's failing ?

**Comment by niphlod** [comment]
@jredrejo : news ?

**Comment by niphlod** [comment]
after more than two weeks without any news, I'm closing this. @jredrejo : if you need further assistance, please provide a piece of code that fails so we can replicate the issue and see what's going on
