### ISSUE TITLE
Update official_top_level_domains list in validators.py

### ISSUE THREAD

**Issue by cryaboutit** [web2py/web2py#773]
As noted here: https://groups.google.com/forum/#!topic/web2py/C52iIdEr_hQ the .ninja tld is not recognized in the IS_URL() validator.

**Comment by kirsn** [comment]
(posted in the web2py-users group. re-posting here)

Maybe it will make sense to programmatically update, and cache, the tlds from here: http://data.iana.org/TLD/tlds-alpha-by-domain.txt, rather than from here (as stated the validators.py code comment): https://github.com/web2py/web2py/blob/5a0ee722605164f1eae4064d0d1dd0d72b5eb14b/gluon/validators.py#L1584

**Comment by kirsn** [comment]
Or should we just use the tld module: https://pypi.python.org/pypi/tld ?

**Comment by ilvalle** [comment]
I propose to:
* create a contrib with an updated official_top_level_domains.
* wrap the current list into a set
* create a script for future updates

**Comment by leonelcamara** [comment]
what about this?

try:
    official_top_level_domains = fetch('http://data.iana.org/TLD/tlds-alpha-by-domain.txt').strip().split('\n')[1:]
except:
   # Couldn't fetch for some reason, use the list we already know
    official_top_level_domains = [...

It will only run once when the module is loaded and you'll have an updated list if you have a web connection.

**Comment by niphlod** [comment]
no, no, no and then no. come on. even if tlds are changing fast, there's no need to fetch them every time I start web2py.

**Comment by leonelcamara** [comment]
Fair enough, probably just update the list then.

**Comment by abastardi** [comment]
Maybe also add an allowed_tlds argument to __init__ so the user can specify a list (either to limit the allowed TLDs or to ensure the list is always completely up-to-date without having to upgrade web2py).

**Comment by hiho-** [comment]
Hi.
It seems that there is not some of the top domain on validators.py
(ex. "site")
Please update.
