### ISSUE TITLE
Web editor footer toolbar creates a trouble ticket each minute (2.9.12)

### ISSUE THREAD

**Issue by ASalazarMX** [web2py/web2py#779]
The web editor toolbar in web2py 2.9.12 (2.9.12-stable+timestamp.2015.01.17.06.11.03) has a new "Hooks" tabs which just crashes and generates a trouble ticket each minute.

**Steps to reproduce the problem**
* Install web2py 2.9.12 (2.9.12-stable+timestamp.2015.01.17.06.11.03)
* Start the web editor on any source
* The web editor notification should read "An error occurred, please reload the page"
* The Errors page shows new instances of **"IOError: could not get source code"** each minute.

**Workaround**
* Ignore the repeating notifications and tickets.

**Comment by niphlod** [comment]
that comes probably because you don't have the latest appadmin.py in your application (that provides what the admin interface calls). it comes from https://github.com/web2py/web2py/commit/63d8785918722b5e311e9a3b7b3155992c7c1eca, so probably @ilvalle can comment further

**Comment by ASalazarMX** [comment]
It happens with a clean installation of 2.9.12 for Windows, which is the one available right now for stable download. The exception happens at appadmin.py indeed. I can include the ticket detail, I didn't deem it neccesary because the bug is really easy to replicate.

**Comment by ilvalle** [comment]
I'll try to understand what's going wrong; it works on ubuntu, I suspect
it's windows related

 Paolo

2015-02-08 4:11 GMT+01:00 ASalazarMX <notifications@github.com>:

**Comment by ilvalle** [comment]
I reproduced the issue on windows with the binary version, from source everything worked as expected. I'll post a PR with a general fix in order to skip this errors when source code is not available.

**Comment by ASalazarMX** [comment]
Tried the patch on my installation and it solves this issue.
