### ISSUE TITLE
pg8000 has support for json now

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#783]
_From [remco.boerma](https://code.google.com/u/remco.boerma/) on January 30, 2015 01:16:01_

See: https://github.com/mfenniak/pg8000/commit/6d2d87c4c09873e3057a5c5152b6870933700efc and maybe https://github.com/mfenniak/pg8000/issues/68 Currently gluon/contrib/dal/adapters/postgres.py __at__ line 174: 
    def try_json(self):
        \# check JSON data type support
        \# (to be added to after_connection)

        \# until pg8000 supports json, leave this commented
        \#if self.driver_name == "pg8000":
        \#    supports_json = self.connection.server_version >= "9.2.0"

please enable pg8000 and upgrade the one in contrib

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2042_

**Comment by ilvalle** [comment]
This has been already fixed in pydal

**Comment by niphlod** [comment]
let's close it then
