### ISSUE TITLE
db.blog_post(row_id) returns NONE

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#784]
_From [Lezginoh..._at_gmail.com](https://code.google.com/u/111105538789540405417/) on February 03, 2015 14:21:48_

What steps will reproduce the problem? 1.  defin new table blog_post.
2. added several records.  
3. "db.blog_post(1)" returns NONE. tried all numbers for present records. What is the expected output? What do you see instead? I started learn web2py. in this video http://vimeo.com/104822115 (lesson 05)
expected object record in blog_post table on indicated position. What version of the product are you using? On what operating system? tried on source code:
2.9.11-stable+timestamp.2014.09.15.23.35.11
 (Running on Rocket 1.2.6, Python 2.7.8)
and windows version Please provide any additional information below. database sqllite

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2043_

**Comment by ilvalle** [comment]
Tested on 2.9.12, both linux and windows. it works
```
def test():
    db = DAL('sqlite://storage.sqlite')
    db.define_table('tt',
        Field('ff'))
    _id= db.tt.insert(ff='ok')
    print db.tt(_id)
    return 'ok'
```
Unless further info are provided, the issue can be close.
