### ISSUE TITLE
Double scrollback in web editor because does not properly calculate display height

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#787]
_From [francois..._at_gmail.com](https://code.google.com/u/103398054893183874790/) on February 07, 2015 13:20:01_

What steps will reproduce the problem? 1. Log in to the admin interface
2. Edit a file. In the screenshot I used: http://localhost:8000/admin/default/edit/examples/models/feeds_reader.py?id=models__feeds_reader__py
3. A second scroll bar appears for the page, regardless of the initial size, the page has always the same extra length forcing a page scrollbar, in addition of the editor scrollbar. What is the expected output? What do you see instead? We expect to only have the editor scrollbar. What version of the product are you using? On what operating system? I tested on the stable (2.9.12) and git version.
The behavior is the same with Firefox and Chromium. Please provide any additional information below. The problem seems caused by a new "toolbar" or footbar that would have been added without adapting the calculation of the height of the page to prevent the scrollbar from appearing. Not sure of the solution, but it might be just a CSS change as well.

Regards,

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2046_

**Comment by niphlod** [comment]
_From [francois..._at_gmail.com](https://code.google.com/u/103398054893183874790/) on February 07, 2015 04:58:09_

I think I have a solution, by turning the offset from 1 to 60 in the line 90 of /admin/views/default/edit.html: 
editor_height = $(window).height() - $(tab_id + " .well-small").offset().top - $(tab_id + " .well-small").outerHeight(
true) - $('.navbar-fixed-bottom').outerHeight() - 60;

**Comment by ASalazarMX** [comment]
Tried the patch on my installation and it solves this issue.

**Comment by ilvalle** [comment]
This issue can be closed, see https://github.com/web2py/web2py/pull/780
