### ISSUE TITLE
need to add signature to url after login

### ISSUE THREAD

**Issue by weheh** [web2py/web2py#789]
I have a URL that I want to direct to after login. Something like `_next_url = URL(c, f, v, signature=True)`.

The problem is this. The signature is computed before login. After login, the signature isn't valid.

We need a way to recompute the signature for a URL after the fact ... after the URL is already computed. Something like `_next_url = URL(c, f, v)` ... then after login, `_next_url_updated = add_signature_to(_next_url)`?

**Comment by mdipierro** [comment]
Fixed.

auth.settings.login_next = lambda: URL(.... signature=True)
