### ISSUE TITLE
ImportError: No module named gluon.main with Python 2.7.9

### ISSUE THREAD

**Issue by smrutim01** [web2py/web2py#791]
Win 7
Python 2.7.9 32 Bit
Apache HTTP Server, version 2.2, 32 bit
Downloaded the latest web2py
mod_wsgi from mod_wsgi-4.4.8+ap22vc9-cp27-none-win32.whl

Error: 

[Fri Feb 13 20:27:23 2015] [warn] mod_wsgi: Compiled for Python/2.7.9+.
[Fri Feb 13 20:27:23 2015] [warn] mod_wsgi: Runtime using Python/2.7.9.
[Fri Feb 13 20:27:23 2015] [notice] Child 5780: Child process is running
[Fri Feb 13 20:27:23 2015] [notice] Child 5780: Acquired the start mutex.
[Fri Feb 13 20:27:23 2015] [notice] Child 5780: Starting 64 worker threads.
[Fri Feb 13 20:27:23 2015] [notice] Child 5780: Starting thread to listen on port 443.
[Fri Feb 13 20:27:23 2015] [notice] Child 5780: Starting thread to listen on port 80.
[Fri Feb 13 20:27:38 2015] [error] [client 127.0.0.1] mod_wsgi (pid=5780): Target WSGI script 'C:/web2py/wsgihandler.py' cannot be loaded as Python module.
[Fri Feb 13 20:27:38 2015] [error] [client 127.0.0.1] mod_wsgi (pid=5780): Exception occurred processing WSGI script 'C:/web2py/wsgihandler.py'.
[Fri Feb 13 20:27:38 2015] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Feb 13 20:27:38 2015] [error] [client 127.0.0.1]   File "C:/web2py/wsgihandler.py", line 37, in <module>
[Fri Feb 13 20:27:38 2015] [error] [client 127.0.0.1]     import gluon.main
[Fri Feb 13 20:27:38 2015] [error] [client 127.0.0.1] ImportError: No module named gluon.main

**Comment by niphlod** [comment]
is the folder gluon in c:\web2py ?

**Comment by smrutim01** [comment]
No it is not there...

**Comment by smrutim01** [comment]
I am using 2.9.12 web2py

**Comment by niphlod** [comment]
that's the problem: you probably downloaded the windows binaries, but you need the source version if you want to run web2py in apache...
