### ISSUE TITLE
Drop python 2.5

### ISSUE THREAD

**Issue by ilvalle** [web2py/web2py#798]
The last security bug fix release (source only) of python 2.5 has been publish in 2011.
https://www.python.org/download/releases/2.5.6/
There are no tests on travis-ci for python 2.5.

**Comment by leonelcamara** [comment]
I really support this, there are a ton of features that 2.5 simply does not have.

**Comment by jklundell** [comment]
I notice that two of the web2py setup scripts explicitly reference 2.5.

**Comment by niphlod** [comment]
+1 on dropping. setup scripts are often unmaintained but we can ditch them in case those can't be "upgraded" to use at least 2.6. Last time I pushed for dropping 2.5 I was told "someone will test the code for 2.5" but frankly it's a PITA having it around.

**Comment by ilvalle** [comment]
@niphlod has surely a better view of what to do, as far as I can see dropping python 2.5 means:
- update scripts as mentioned by @jklundell 
- remove unnecessary crontrib (ex: simplejson)
- remove unnecessary try-except (if any)

**Comment by niphlod** [comment]
we can simply start by just saying we drop it, and then search through the code for specific thingies (as https://github.com/web2py/web2py/blob/master/gluon/widget.py#L43). Once we face it, we strip it. if the travis-ci works, then we're good.

**Comment by gi0baro** [comment]
+1 for dropping too.

**Comment by niphlod** [comment]
let's hear what @mdipierro thinks about it. At this point it's more a "political" choice than a matter of operational actions to do on the core code.

**Comment by mdipierro** [comment]
Not quite ready for this

**Comment by niphlod** [comment]
who's asking for 2.5 ?

**Comment by mdipierro** [comment]
let’s ask.

**Comment by mdipierro** [comment]
I asked. But why dropping it? What are the pros?

**Comment by leonelcamara** [comment]
Well, one is that we could drop a few modules that we include like simplejson since they're available in later versions.

**Comment by niphlod** [comment]
just for starters, right now I'm not sure web2py works with 2.5 in all of its features. 
There are tons of places in code that can be simplified, and tons of things that can be implemented without thinking to backport something just for the sake of 2.5 compatibility.

**Comment by gi0baro** [comment]
+1 on @niphlod

**Comment by mdipierro** [comment]
OK. I agree we can drop 2.5

On Sun, Mar 8, 2015 at 8:43 AM, Giovanni Barillari <notifications@github.com

**Comment by mdipierro** [comment]
This is not a bug. I close it. It is agreed anyway.

**Comment by lablua** [comment]
I can confirm web2py already fails to work on Python 2.5.2. Syntax error in gluon/sqlhtml.py. (On line 1822 in Version 2.9.12-stable+timestamp.2015.01.17.06.11.03)

Could you please update web2py.com to no longer list 2.5 as a supported version?
