### ISSUE TITLE
Crash when we create a new file from the left hiding pane of the admin app.

### ISSUE THREAD

**Issue by Pivert** [web2py/web2py#799]
When we create a new file from the left pane with the "Create" Button, this generates the following error:

[Wed Feb 18 18:30:22 2015] [error] [client 10.242.0.10] mod_wsgi (pid=29130): Exception occurred processing WSGI script '/home/www-data/web2py/wsgihandler.py'.
[Wed Feb 18 18:30:22 2015] [error] [client 10.242.0.10] ValueError: embedded newline in response header with name 'web2py-component-command' and value '
[Wed Feb 18 18:30:22 2015] [error] [client 10.242.0.10]             $.web2py.invalidate('#files_menu');
[Wed Feb 18 18:30:22 2015] [error] [client 10.242.0.10]             load_file('/admin/default/edit/init/models/test.py');
[Wed Feb 18 18:30:22 2015] [error] [client 10.242.0.10]             $.web2py.enableElement($('#form form').find($.web2py.formInputClickSelector));
[Wed Feb 18 18:30:22 2015] [error] [client 10.242.0.10]         '

And on the web page, we can read:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
....

The problem is only if created from the left hiding pane in edit mode, and despite the error message, the file is correctly created. We just need to reload the full page to see it appearing in the left hiding pane.

The problem does not occur if the file is created directly from the "Edit" application page.

**Comment by ilvalle** [comment]
@mdipierro, the issue can be closed
