### ISSUE TITLE
C-b not working in Vim editor

### ISSUE THREAD

**Issue by Pivert** [web2py/web2py#803]
C-b (ctrl+b) shortcut to go up by one page in vim does not work.

This is working on Codemirror sample page in vim mode, and this is not part of the reference short-cuts on the page.
So I suspect the key stroke is first catched by the emmet plugin. (even if non html editing).
If my assumptions are correct, we just need to remap the C-b key to an other one, and by the way document the short cut(s) on the bottom of the editor.

**Comment by ilvalle** [comment]
Is any ctrl+* working?
If so, I can check if upgrading codemirror to 5.0.x fix it

**Comment by Pivert** [comment]
Hi, 

Yes, other ctrl+* are working. Just the ctrl+b to go up by 1 page (ctrl+f for instance is working).

But ctrl+b is referenced as being an emmet plugin shortcut. So it would be interesting to test by disabling the emmet plugin first, and possibly remap the key to an unused combinaison.

Regards,

**Comment by niphlod** [comment]
@ilvalle : is this still valid ?

**Comment by ilvalle** [comment]
yes, I don't know how to easily fix it

 Paolo

2015-05-03 15:46 GMT+02:00 niphlod <notifications@github.com>:

**Comment by niphlod** [comment]
if it's not fixable, can't we just remove the binding shown at the bottom and live without ctrl+b up/downing pages ?

**Comment by ilvalle** [comment]
This binding is not shown in the panel at the bottom. Given that, you could
close the issue as not supported.

 Paolo

2015-05-03 16:20 GMT+02:00 niphlod <notifications@github.com>:

**Comment by Pivert** [comment]
Hi,
Too bad. This is a frequently used shortcut. Let's think about no pgup/pgdown...
Thanks,
