### ISSUE TITLE
feature request: 

### ISSUE THREAD

**Issue by remcoboerma** [web2py/web2py#806]
Append 
```
touch-reload=/home/www-data/web2py/routes.py
```
to `/etc/uwsgi/web2py.ini` in the `setup-web2py-ubuntu.sh`

Even if the file doesn't exist uwsgi will not break on it, but if the files exists it saves quite a lot of time having to restart the uwsgi server over and over on testing and changing the routes.py

**Comment by niphlod** [comment]
I didn't ever want to touch my routes.py in production, but this is not going to hurt. a PR is on the way

**Comment by remcoboerma** [comment]
Maybe you have a point on that for production. Is there an easier way to restart uwsgi in the setup described? Maybe another touch file would suffice as well. Something like `touch_to_restart_web2py` in the same folder. What do you think Niphold?
