### ISSUE TITLE
request.args returns double underscore instead of unicode character (.url, .vars behave ok)

### ISSUE THREAD

**Issue by zvolsky** [web2py/web2py#815]
Example:
http://www.utf8-chartable.de/unicode-utf8-table.pl?start=256&unicodeinhtml=hex&htmlent=1
U+010C == %c4%8c == Č

If I enter: a/c/f/ABC%c4%8cD
as URL into browser, browser will properly show: a/c/f/ABCČD
request.args[0] ABC__D --failure - double underscore instead of the unicode character
request.url a/c/f/ABCČD --ok
request.vars --ok

So the problem is just in request.args

Version 2.9.12-stable+timestamp.2015.01.17.06.11.03
Lubuntu, Firefox/Chromium/urllib2/.. --or-- Debian, Chrome ....

**Comment by niphlod** [comment]
seems connected to #813

**Comment by mdipierro** [comment]
Merged with #813
