### ISSUE TITLE
The Ubuntu Apache 2.4 install script makes the server https only

### ISSUE THREAD

**Issue by tim333** [web2py/web2py#823]
I'm not sure if this is intentional but the earlier Apache 2.2 script and the install scripts for Ngnix and Fedora do not do force https, it is not mentioned in the documentation and it took me ages to figure why the issue came up when I upgraded Ubuntu. It's the lines: 

<VirtualHost *:80>

  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]

in the http://web2py.googlecode.com/hg/scripts/setup-web2py-ubuntu.sh script that do it. 

There is discussion here https://www.mail-archive.com/web2py@googlegroups.com/msg138827.html

I managed to get a workaround that I posted on http://stackoverflow.com/questions/28116754/how-can-i-make-part-of-the-website-not-use-https-in-web2py/28435772#28435772

but I think that uses the old Apache 2.2 code and could be done better if anyone is up on Apache 2.4?

**Comment by niphlod** [comment]
that addition is on the latest revision of the script. I don't think at scripts/setup* more that just a blueprint. The same argument can be made if one prefers, e.g., mysql over postgresql. I'm not sure if default scripts should stick to some "basic" assumptions or not...

**Comment by tim333** [comment]
Yeah but that particular script is the first one mentioned in the chapter 13, Deployment recipes section of the web2py manual so as it is anyone new may well use that to instal on a server and then wonder why http://mysite.com gives error messages.  You could always have a second script say setup-web2py-ubuntu-ssh-only.sh for those who want that?

**Comment by jklundell** [comment]
Having returned recently to web2py development, I've been running into deployment issues. I have an idea for a different approach, and I'll talk about it on the dev list shortly.

**Comment by niphlod** [comment]
@jklundell : news ?

**Comment by niphlod** [comment]
guess not. Once https://github.com/web2py/web2py/pull/1057 gets merged, this can be closed.

**Comment by tim333** [comment]
Guess so. I fixed the script on my own server and forgot about it. I don't know if Massimo has any opinions if the script should set up the server support http or be https only?

**Comment by niphlod** [comment]
It's all been taken care of
