### ISSUE TITLE
Cas redirect loop

### ISSUE THREAD

**Issue by sbourgeois1** [web2py/web2py#824]
After adding these 2 lines in a model file (0.py), I entered a CAS loop each time I required @auth.requires_login():
#from datetime import datetime as dt
#request.now = dt.utcnow()

**Comment by remcoboerma** [comment]
There is a request.utcnow which does exactly this.

**Comment by sbourgeois1** [comment]
Thanks al lot for this info! 
Anyway, my point could maybe help understanding some looping issues with the CAS...Best regards,Serge
 
      De : remcoboerma <notifications@github.com>
 À : web2py/web2py <web2py@noreply.github.com> 
Cc : sbourgeois1 <serge.bourgeois@yahoo.fr> 
 Envoyé le : Lundi 2 mars 2015 9h17
 Objet : Re: [web2py] Cas redirect loop (#824)
   
There is a request.utcnow which does exactly this. —

**Comment by niphlod** [comment]
the point more or less (we should state somewhere) is that in web2py, the datetime is imported as a module, as 

    import datetime

if your app overwrites this with

     from datetime import datetime

web2py starts thinking bad things.
