### ISSUE TITLE
Linkedin login integration

### ISSUE THREAD

**Issue by josedesoto** [web2py/web2py#825]
Testing the linked intgeration explained in the book: 
http://www.web2py.com/books/default/chapter/29/09/access-control?search=LinkedInAccount

I could not make it works. It use python-linkedin lib and it looks this lib has change some methods or class names. I am using  python-linkedin (4.1). Here is what I get:

```
  File "/var/www/web2py/gluon/contrib/login_methods/linkedin_account.py", line 33, in __init__
    self.api = linkedin.LinkedIn(key, secret, return_url)
AttributeError: 'module' object has no attribute 'LinkedIn'
```

Based in facebook oauht2 doc I have created this post:
http://www.web2pyslices.com/slice/show/2011/integrating-linkedin-with-web2py

I hope it helps...

**Comment by ilvalle** [comment]
I think is time to integrate 'python social auth'

**Comment by michele-comitini** [comment]
The book needs to be updated, use OAuth (1 or 2 as specified on linkedin)
it works

2015-03-02 9:15 GMT+01:00 Paolo Valleri <notifications@github.com>:
