### ISSUE TITLE
TypeError in modules/dal.py line 85: because GoogleDatastoreAdapter is None

### ISSUE THREAD

**Issue by AMueckl** [web2py/web2py#826]
I have tried both, usage of the release version for Windows http://www.web2py.com/examples/static/web2py_win.zip as well as the latest git checkout 

>>>>Revision: befb5b286af50bce325a4075999826e5065690ea
Author: mdipierro <massimo.dipierro@gmail.com>
Date: 01.03.2015 18:04:53
Message:
Merge branch 'master' of github.com:web2py/web2py

>>>>Modified: applications/admin/controllers/default.py
Modified: applications/welcome/static/js/web2py.js
Modified: gluon/scheduler.py
Modified: gluon/tests/test_is_url.py
Modified: gluon/tests/test_validators.py
Modified: gluon/validators.py
Added: scripts/parse_top_level_domains.py
Modified: gluon/packages/dal
Modified: gluon/tools.py

I started web2py as a local server on 127.0.0.1:8000 on Win7 (using Python 2.7.9 in the case of the checked-out files). An initial application using the wizzard was created (using the release version web2py_win.zip). After that I want to enter some initial datasets into the tables that were just created. I tried to log in on the application front end. I could load the index page, but when trying to access http://127.0.0.1:8000/ProductionDB/default/components_manage (where ProductionDB is the application name and components is a table created via the wizzard), a ticket was created stating:

Traceback (most recent call last):
  File "<web2py_base_folder>\gluon\restricted.py", line 224, in restricted
    exec ccode in environment
  File "<web2py_base_folder>\applications\ProductionDB\controllers/default.py", line 88, in <module>
  File "<web2py_base_folder>\gluon\globals.py", line 393, in <lambda>
    self._caller = lambda f: f()
  File "<web2py_base_folder>\gluon\tools.py", line 3449, in f
    return action(*a, **b)
  File "<web2py_base_folder>\applications\ProductionDB\controllers/default.py", line 65, in urls_manage
    form = SQLFORM.smartgrid(db.t_urls,onupdate=auth.archive)
  File "<web2py_base_folder>\gluon\sqlhtml.py", line 2968, in smartgrid
    user_signature=user_signature, **kwargs)
  File "<web2py_base_folder>\gluon\sqlhtml.py", line 2643, in grid
    value = field.represent(value, row)
  File "<web2py_base_folder>\gluon\dal.py", line 85, in list_ref_repr
    if isinstance(db._adapter, GoogleDatastoreAdapter):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

Variables
builtinisinstance 	<built-in function isinstance>
db._adapter 	<pydal.adapters.sqlite.SQLiteAdapter object>
db 	<DAL uri="sqlite://storage.sqlite">
GoogleDatastoreAdapter 	None

After the first test failed using the release version for Windows http://www.web2py.com/examples/static/web2py_win.zip I switched over to the latest GitHub check-out, but got the identical error message. (I recycled the application folder <web2py_base_folder>\applications\ProductionDB from the windows distribution to the GitHub checkout).

In the source code <web2py_base_folder>\gluon\packages\dal\pydal\adapters\__init__.py, line 87 the GoogleDatastoreAdapter is set to None if not on a Google AppEngine server (which I am certainly not).

So I guess that there is an issue with the <web2py_base_folder>\gluon\dal.py code that IMHO should not test with isinstance() when there is the possibility to get a TypeError due to an uninitialized second argument.

**Comment by niphlod** [comment]
did you fetch recursively pydal too ? Try starting from

git checkout git@github.com:web2py/web2py.git --recursive

**Comment by AMueckl** [comment]
I just retried:

test2>git clone https://github.com/web2py/web2py.git --recursive
Cloning into 'web2py'...
remote: Counting objects: 29997, done.
remote: Compressing objects: 100% (23/23), done.
Receiving objects: 100% (29997/29997), 30.66 MiB | 403.00 KiB/s, done

Resolving deltas: 100% (17995/17995), done.
Checking connectivity... done.
Checking out files: 100% (885/885), done.
Submodule 'gluon/packages/dal' (https://github.com/web2py/pydal.git) registered for path 'gluon/packages/dal'
Cloning into 'gluon/packages/dal'...
remote: Counting objects: 29213, done.
remote: Total 29213 (delta 0), reused 0 (delta 0), pack-reused 29212
Receiving objects: 100% (29213/29213), 29.95 MiB | 300.00 KiB/s, done.
Resolving deltas: 100% (17427/17427), done.
Checking connectivity... done.
Submodule path 'gluon/packages/dal': checked out '2f513d830cbe3ec1c2b3670bc04de509e52fe21e'

test2>

Then I copied the application to the test2\web2py\applications folder and repeated the steps => the same error occured again.

**Comment by niphlod** [comment]
please pack an app that reproduces the issue. IMHO there's something wrong with your web2py version

**Comment by AMueckl** [comment]
Since only image files are allowed as attachements here, I uploaded the file to:

http://downloads.chartup.com/web2py.app.ProductionDB.w2p

**Comment by ilvalle** [comment]
@AMueckl GoogleDatastoreAdapter works on pydal (pydal executes specific tests on travis-ci). Given that I guess there should be something going wrong on web2py imports or on your local setup.
I'd start by debugging this try-except https://github.com/web2py/pydal/blob/master/pydal/adapters/__init__.py#L57

@niphlod do you know why we need this https://github.com/web2py/pydal/blob/9bc003583a164c59d77f31c7c31e22ab81c259ee/pydal/adapters/base.py#L1568 ?

**Comment by niphlod** [comment]
apparently, it's a 

    # temporary hack to deal with
    # GoogleDatastoreAdapter
    # references

(lines 1606 and following)

**Comment by ilvalle** [comment]
@niphlod do you agree in checking for ```self.dbengine == 'google:datastore'``` in order to remove the dirty import ?

**Comment by mdipierro** [comment]
Can you check this is fixed in latest trunk?

**Comment by AMueckl** [comment]
Confirm FIX (Revision: 29b58ff70cb7646ca71d9a7d2adee11555335e70):
Test with the revision mentioned above succeeded - no ticket was generated when accessing the link http://127.0.0.1:8000/ProductionDB/default/components_manage
