### ISSUE TITLE
crud.search does not return any results when searching using a reference field

### ISSUE THREAD

**Issue by psr8** [web2py/web2py#844]
Other users have reported this same problem in the past:-
. https://groups.google.com/forum/#!searchin/web2py/crud$20search$20no$20results$20reference$20/web2py/6Q-pBbqxtwE/BP-FcflbgSMJ

Running  2.9.11-stable+timestamp.2014.09.15.23.35.11 on windows, python 2.6.7

This used to work on older versions of web2py and was broken in an upgrade

The bug is in tools.py, class Crud, function get_format

the code calls format = rtable.get('_format', None)

there is no such .get method on a table object (looks like this must have worked on older versions of DAL !?), this causes get_query() to fail, this exception is caught and returns None to crud.Search, the exception is caught and as the comment says '# hmmm, we should do better here', and returns None as the result.

original code:

    def get_format(self, field):
        rtable = field._db[field.type[10:]]
        format = rtable.get('_format', None)
        if format and isinstance(format, str):
            return format[2:-2]
        return field.name

 a fix would be:-

    def get_format(self, field):
        rtable = field._db[field.type[10:]]
        format = rtable._format or None
        if format and isinstance(format, str):
            return format[2:-2]
        return field.name

**Comment by ilvalle** [comment]
as far as I know, crud is no longer supported, I suggest upgrading your code in favor of sqlform/sqlform.grid

**Comment by psr8** [comment]
I'm sure many people have crud code in their websites and would like the
search to work correctly - just trying to fix an annoying bug :-)

**Comment by niphlod** [comment]
uhm. even if not specified, get() should work, 'cause Field is like a dictionary holding attributes.

**Comment by psr8** [comment]
get does not work on a field:

In [10]: type(f)
Out[10]: gluon.dal.Field

In [11]: f.get('test')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
D:\web2py-2.4.5\web2py\applications\veeam_backup\models\menu.py in
<module>()
----> 1 f.get('test')

AttributeError: 'Field' object has no attribute 'get'

**Comment by ilvalle** [comment]
This should be fixed in master branch because now Table inherits from BasicStorage. 
@psr8 Can you double check ?

**Comment by niphlod** [comment]
@psr8 : can you get back with an answer ? I'm going to close this in a few days if nobody replies
