### ISSUE TITLE
row.some_bool == True # when the boolean is False

### ISSUE THREAD

**Issue by zenite** [web2py/web2py#845]
# When doing the condition
if row.some_bool:
    # this code runs even if the bool is false, however set to 'F', at least in mysql

# this is a workaround, but confusing
if row.some_bool == 'T':
    ...

**Comment by abastardi** [comment]
Is "row" a DAL Row object produced via a DAL select()? If so, I cannot reproduce this problem. In Row objects booleans are Python `True` and `False` values, not string "T" and "F" values. They are stored as strings in the database itself, but that doesn't lead to the issue shown above. Can you show the exact code you are using to generate the table definition and row object?

**Comment by zenite** [comment]
This is what I've got:

# definition
db.define_table('someref',
        Field( 'name' ),
        Field( 'another_bool', 'boolean' ),
    format='%(name)s',
    )

db.define_table('tbl',
        Field( 'something'),
        Field( 'priority', 'integer' ),
        Field( 'someref', 'reference someref', notnull=True ),
        Field( 'another_bool', 'boolean', default=True ),
        Field( 'some_bool', 'boolean', default=True ),
    format='%(something)s',
    )


# query
query = (db.tbl.another_bool == 'T') & (db.tbl.someref == db.someref.id) & (db.someref.another_bool == 'T')
return db(query).select( db.tbl.something, db.tbl.someref, db.tbl.another_bool, db.tbl.some_bool,
orderby=~db.tbl.priority, cache=(cache.ram,999), cacheable=True )

**Comment by abastardi** [comment]
What is the rest of the code (i.e., what does the query return, and what are you doing with it)? You said `if row.some_bool:` runs even if `some_bool` is False, but your query only selects records with True values. Anyway, I cannot reproduce the problem -- if I do `if row.some_bool:`, the `if` clause does not execute when the boolean value is False.

As an aside, you should do `db.tbl.another_bool == True` (rather than `== 'T'`).

**Comment by BuhtigithuB** [comment]
Which web2py version?

**Comment by zenite** [comment]
It seems like the issue is false. I apologize for that!

Maybe it's strange though that the 'T' is working? Well, never mind.

Thanks for your help, anyway!
