### ISSUE TITLE
group controllers by folders

### ISSUE THREAD

**Issue by tianxiaxi** [web2py/web2py#848]
I have dozens of controllers in a web2py project, also include views, modules, models. 
But they can split by several functions, is there any solution for grouping controllers by folders.

**e.g.**
I have 6 files in controllers: 
- func1_main.py
- func1_user.py
- func1_show.py
- func2_print.py
- func2_user.py
- func2_show.py

and the expected path as the following:
- *func1\func1_main.py*
- *func1\func1_user.py*
- *func1\func1_show.py*
- *func2\func2_print.py*
- *func2\func2_user.py*
- *func2\func2_show.py*

I also have some similar requirements:
+ one controller can have views multiple folders
+ third-part modules can have their own folders in the path *modules*

**Comment by mdipierro** [comment]
No there is no way to this right now.

**Comment by tianxiaxi** [comment]
Thanks for your reply. I wonder web2py would add this new functions in future.
