### ISSUE TITLE
DAL queries in appadmin

### ISSUE THREAD

**Issue by ramstein74** [web2py/web2py#850]
in appadmin it could be possible to query the database using DAL queries.
It will have big advantages.

1 allows me to select only the columns that i want to see.
If i have 40 columns its dificult to go to the last column to check its value.Gets more dificult if i have 800 records as i can only see 100 at a time.

2 it would be a great place to try the dal syntax.

3 its a new feature in appadmin. dont let it die... 

...

Regards

**Comment by mdipierro** [comment]
for the query should can already try any dal syntax. Am I wrong?

**Comment by niphlod** [comment]
the query, yes. OP wants to pass a select with fields, or even joins.

**Comment by ramstein74** [comment]
in appadmin i cannot use DAL queries on my tables.

for ex

db(db.auth_user.id>0).select(db.auth_user.first_name)

does not work



2015-03-19 19:53 GMT+00:00 niphlod <notifications@github.com>:

**Comment by ramstein74** [comment]
[image: Imagem inline 1]

2015-03-19 22:21 GMT+00:00 António Ramos <ramstein74@gmail.com>:

**Comment by niphlod** [comment]
I'd close this as we won't ever be able to fix it, and it's hardly something appadmin should accomplish... @mdipierro : feel free to chime in

**Comment by niphlod** [comment]
ok, I'll do the BDFL for issues... we can't manage 150+ open issues that nobody is adopting.

**Comment by mdipierro** [comment]
LOL. I support this.
