### ISSUE TITLE
Arabic Translatrion

### ISSUE THREAD

**Issue by Kalmuraee** [web2py/web2py#865]
I've manged add Arabic translation in languages folder
https://github.com/Kalmuraee/web2py/blob/84b8be34ec6613d1fb39c70d49165c6cfb0d7b4b/applications/welcome/languages/ar.py

**Comment by ilvalle** [comment]
would you create a PR ? see http://web2py.com/books/default/chapter/29/15/helping-web2py#Contributing-code-and-documentation-changes

**Comment by Kalmuraee** [comment]
Done ,
Thanks ilvalle
