### ISSUE TITLE
request with wrong Content-Length to web2py cause 500 reply from apache

### ISSUE THREAD

**Issue by andy-liang** [web2py/web2py#878]
A request with wrong Content-Length will cause a 500 reply from apache.

I use the following script to generate the request:

``` Python
#! /usr/bin/env python

import socket

sock = socket.socket()
sock.connect(("localhost", 8001))
sock.send("GET /welcome/default/index HTTP/1.1\r\n")
sock.send("Host: localhost\r\n")
sock.send("Content-Length: 10000\r\n")
sock.send("\r\n\r\n")
sock.shutdown(socket.SHUT_WR)

print sock.recv(1024)
sock.close()
```

This show up in apache error log:

> [Thu Mar 26 15:59:18 2015] [error] [client 127.0.0.1](70014)End of file found: mod_wsgi (pid=13239): Unable to get bucket brigade for request.
> [Thu Mar 26 15:59:18 2015] [error] [client 127.0.0.1] mod_wsgi (pid=13235): Exception occurred processing WSGI script '/opt/web-apps/web2py/wsgihandler.py'.
> [Thu Mar 26 15:59:18 2015] [error] [client 127.0.0.1] Traceback (most recent call last):
> [Thu Mar 26 15:59:18 2015] [error] [client 127.0.0.1]   File "/opt/web-apps/web2py/gluon/main.py", line 532, in wsgibase
> [Thu Mar 26 15:59:18 2015] [error] [client 127.0.0.1]     if request.body:
> [Thu Mar 26 15:59:18 2015] [error] [client 127.0.0.1]   File "/opt/web-apps/web2py/gluon/globals.py", line 270, in body
> [Thu Mar 26 15:59:18 2015] [error] [client 127.0.0.1]     raise HTTP(400, "Bad Request - HTTP body is incomplete")
> [Thu Mar 26 15:59:18 2015] [error] [client 127.0.0.1] HTTP: 400 BAD REQUEST

it appear that HTTP exception handler in gluon/main.py:448 is not handling the exception raise in gluon/globals.py:270 correctly. The same property getter keep getting call by multiple exception handlers and the exception eventually fall into mod_wsgi which cause the 500 response.

**Comment by mdipierro** [comment]
Need to check whether this is apache only. In that case we do not care. Who uses apache any more? Else this much be fixed.

**Comment by leonelcamara** [comment]
@mdipierro pretty sure this was a bug with mod_wsgi and mod_reqtimeout at the time of this issue.

See:
https://github.com/GrahamDumpleton/mod_wsgi/issues/58

Much like in the example given on that issue, the request on this web2py issue is also badly formed since the content-length is bigger than the body of the message so the server waits for the rest until it timesout.

**Comment by mdipierro** [comment]
Good closing
