### ISSUE TITLE
2.10.1 upgrade problem

### ISSUE THREAD

**Issue by rif** [web2py/web2py#892]
Traceback (most recent call last):
  File "/home/rif/Downloads/web2py-R-2.9.12/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/rif/Downloads/web2py-R-2.9.12/applications/welcome/models/db.py", line 56, in <module>
    auth = Auth(db)
  File "/home/rif/Downloads/web2py-R-2.9.12/gluon/tools.py", line 1383, in __init__
    self.define_signature()
  File "/home/rif/Downloads/web2py-R-2.9.12/gluon/tools.py", line 1769, in define_signature
    label=T('Modified By'),  ondelete=ondelete))
  File "/home/rif/Downloads/web2py-R-2.9.12/gluon/packages/dal/pydal/objects.py", line 330, in __init__
    'define_table argument is not a Field or Table: %s' % field)
SyntaxError: define_table argument is not a Field or Table: <no table>.is_active

How to reproduce:

1. Download https://github.com/web2py/web2py/archive/R-2.9.12.zip 
2. Start it and go to admin
3. Perform a upgrade from the admin
4. Restart
5. Go to welcome app

**Comment by mdipierro** [comment]
Which OS? Which python version? Which version are you upgrading from?

**Comment by mdipierro** [comment]
Do you have gluon/dal folder when the problem exist?
Can you confirm this goes away with a fresh install?

**Comment by rif** [comment]
I am using a fully updated arch linux with python 2.7.9.

Did you notice the reproducing steps? 

You start from a web2py 2.9.12 unziped without anything else done to it. Just perform an upgrade from admin and you get the issue.

I can confirm that if you are using the latest version zip the issue is absent. It's an upgrade issue.

**Comment by rif** [comment]
I manualy changed the gluon/tools.py with the diff from commit 2a7e9c0c and it does NOT solve the problem. The gluon/dal folder is present.

-from pydal.objects import Table, Row, Set, Query
+from pydal.objects import Row, Set, Query
 
 import gluon.serializers as serializers
 
+Table = DAL.Table
+Field = DAL.Field
+

**Comment by mdipierro** [comment]
The gluon/dal folder is the problem. It must be removed.

**Comment by rif** [comment]
Yes, I just did that and the problem is fixed. The upgrade process should delete that folder.

**Comment by rif** [comment]
Another minor issue with the upgrade is that after the upgrade is preformed the admin page with the "web2py upgraded; please restart it" message does no longer have correct css. 

But it's ok after the restart.
