### ISSUE TITLE
2.10.1-3 / Windows / cache errors

### ISSUE THREAD

**Issue by kirsn** [web2py/web2py#895]
Following the discussion here: https://groups.google.com/d/msg/web2py/Ukk5FTy17is/RQVx6sv8jkoJ
I put together a small script to recreate the "issues while using the cache"
```
$ python web2py.py -S test

>>> db = DAL('sqlite://cache_test.db', pool_size=0)
>>> db.define_table('t1', Field('name',type='string'))
>>> db.t1.insert(name='A1')
>>> cache_settings = dict(cache=(cache.disk, 30), cacheable=True)
>>> rows = db(db.t1.id > 0).select(**cache_settings)
>>> rows = db(db.t1.id > 0).select(**cache_settings)
```
The screenshot illustrates the result
![cache_test](https://cloud.githubusercontent.com/assets/11280/6957754/46739d48-d91e-11e4-90e7-f09d06de56a9.png)

**Comment by leonelcamara** [comment]
I can't replicate this issue with the codebase after my #891 fix I would say this should be closed.

**Comment by kirsn** [comment]
Hmm, am on the latest codebase too. My git log lists your fix too. Not sure what is going on here. 
My environment (if that helps)
* Windows 8.1 64bit / Microsoft Windows [Version 6.3.9600]
* Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32

Let me take another shot at this.

**Comment by leonelcamara** [comment]
That's exactly the environment where I tested it. Is it possible that you did not restart web2py after updating?

**Comment by kirsn** [comment]
Yes, I did. 
In any case, went ahead and downloaded the Windows binary, and the source from the http://web2py.com/init/default/download (for Normal Users)
Tried this out again on these versions, and I see the same error.
![cache_test](https://cloud.githubusercontent.com/assets/11280/6978706/b7ebc810-d9f5-11e4-9e32-9725ad187333.png)

I decided to try this on my **Ubuntu VM**. I didn't see this error in the Ubuntu VM, but a different one. Have listed this here: #899

**Comment by niphlod** [comment]
oddly enough, the source version has no issues. On Windows with the current binaries, I see the same error.

**Comment by kirsn** [comment]
Hmm, so it works in src, and not in bin. Weird. 
Summarizing the findings so far

tested by | issue in src | issue in bin
-------------|-----------------|-----------------
@leonelcamara | No | ?
@niphlod | No | Yes
@kirsn | Yes | Yes

**Comment by kirsn** [comment]
Have created a simple script to test this out. The script is here: https://gist.github.com/kirsn/27d50c2863cde0376022
Save this script as `cache_test_script.py`

Run this: `python web2py.py -S test_cache -R cache_test_script.py`

**Comment by leonelcamara** [comment]
I run that script without any issue using the source version.

**Comment by niphlod** [comment]
2.10.3 source AND binary ends with a permission denied error. current trunk behaves the in the same way.

**Comment by niphlod** [comment]
@leonelcamara : found the error, will post a PR soon.

**Comment by niphlod** [comment]
and if you try to run system tests on windows......... they fail. @mdipierro : will open a new PR soon, but I'd encourage appveyor on web2py too to test web2py on windows. (codecov too, since we used it on pydal)

**Comment by leonelcamara** [comment]
Ahhh good job. Stupid mistake.

**Comment by kirsn** [comment]
Tested this on the latest codebase, and works fine. Thanks for the fix.
