### ISSUE TITLE
2.10.3 / Linux/ cache inconsistent

### ISSUE THREAD

**Issue by kirsn** [web2py/web2py#899]
Downloaded the latest source from http://www.web2py.com/examples/static/web2py_src.zip (2.10.3 source)
Tried the following script, to see if the cache works fine - basically insert records, and see if it is reflected in the cache, when the query is executed repeatedly. I didn't check to see if the contents match, just the number of elements in the cache reflect the number in the table.
```
$ python web2py.py -S test_cache

db = DAL('sqlite://cache_test.db', pool_size=0)
db.define_table('t1', Field('name',type='string'))
db.t1.insert(name='A1')
cache_settings = dict(cache=(cache.disk, 30), cacheable=True)
rows = db(db.t1.id > 0).select(**cache_settings)
rows
db.t1.insert(name='A2')
rows = db(db.t1.id > 0).select(**cache_settings)
rows
db.t1.insert(name='A3')
rows = db(db.t1.id > 0).select(**cache_settings)
rows
```
I noticed that the number of records returned in the `rows` is not consistent. Take a look at the screenshot, and notice the number of records returned after query execution.
![cache_test_linux](https://cloud.githubusercontent.com/assets/11280/6978795/4b6a23e2-d9f7-11e4-8b5d-6a399a4027df.png)

**Comment by niphlod** [comment]
this is not happening on my system. It's always returning one row as expected. Are you sure that you're executing those lines sequentially ? The only explanation to that behaviour is that when you try to fetch the cached value, it's already expired, and so the result is recalculated (when it's "2 rows" effectively)

**Comment by kirsn** [comment]
Well, I have inserted records - 3 in this specific case - and I always noticed that the cached content reflected one less record. The screenshot should have captured the step where I execute the query once more, at which time the cached rows shows 3. 
So, just to clarify, when I have inserted the "nth" record, and then perform a query, and view the number of records in the cache, it displays n-1. Or rather, it does not include the last inserted record(s)
All this is done sequentially, yes. 

I'll increase the cache LRU timeout, and see if this does not occur because of the possibility you suggest

**Comment by kirsn** [comment]
Am printing the values contained in the rows (basically the ones from the cache), via the user defined `print_rows()` method. 
You will see that the results are inconsistent. Specifically see the last few `print_rows()` output. It takes a while for the cache to reflect the last inserted row. Sort of an *eventually consistent* story here. 
![cache_issue](https://cloud.githubusercontent.com/assets/11280/6981470/bdb0cc3a-da1f-11e4-9b68-c4b2abe0ed9c.png)

**Comment by niphlod** [comment]
are you sure you're pruning the cache before beginning any test ? it still seems a perfectly fine behaviour IF the 30 seconds pass between a call that returns n rows and a call that returns n+1 .

**Comment by michele-comitini** [comment]
can you make a .py script and add time.sleep() at your needs, and print
time.ctime() before each output?
this will make things more reproducible.
pls avoid posting screenshots just cut&copy text from the terminal window:
it is easier to read


2015-04-03 13:34 GMT+02:00 niphlod <notifications@github.com>:

**Comment by kirsn** [comment]
@niphlod I had a confused understanding of what was going on. Went back and re-read the cache related documentation. The "time in seconds" parameter is one where the cache goes back to the DB to refresh its query results. Duh!

Feeling rather silly now. Thanks for the feedback. Closing this issue now. 

@michele-comitini point noted. Have written a script for this, and will use text output from here on, and make a more judicious use of screenshots, if at all.
script: https://gist.github.com/kirsn/27d50c2863cde0376022
