### ISSUE TITLE
form buttons forcing btn-default

### ISSUE THREAD

**Issue by KabluBR** [web2py/web2py#903]
some times you want to define different btn-something to your button... but does not matter if you manual creates the button in form it gets override to btn-default.

so in the js file:

web2py-bootstrap3.js line 9 should be something like:

    if(!$('button', target).hasClass('btn')) {
        $('button', target).addClass('btn btn-default');
    }

**Comment by diogommartins** [comment]
On a fresh web2py 2.10.4 installation i tested defining a controller function like:
```python
def test():
    form = FORM(
        BUTTON('Teste button 1', _class='btn btn-danger'),
        BUTTON('Test button 2', _class='btn btn-primary')
    )
    return dict(form=form)
```

Everything worked as expected, 'danger' and 'primary' overwritten the btn-default. Could you provide some code in order to check your specific case ?

**Comment by niphlod** [comment]
@KabluBR : can you comment further on this ? I'm going to close this in a few days if nothing new comes in.

**Comment by niphlod** [comment]
closing as promised. feel free to reopen (with an actual example) if something is not working as expected

**Comment by sesenmaister** [comment]
On a fresh web2py 2.12.3 installation, the same test as @diogommartins posted is failing.

    <form action="#" enctype="multipart/form-data" method="post">
        <button class="btn btn-danger btn-default">Teste button 1</button>
        <button class="btn btn-primary btn-default">Test button 2</button>
    </form>

**Comment by amerikan** [comment]
I see this happen too. For example any .load that I include, if it has a <button> element in it, it'll automatically add the btn-default class, which sometimes I don't want.

**Comment by CarlosCorreiaM16e** [comment]
Having the same problem (Version 2.12.3-stable+timestamp.2015.08.18.19.14.07).
Fixed it by removing 'btn-default' from element class in web2py-bootstrap3.js (lines 9 and 11).
