### ISSUE TITLE
field format show an id instead of proper format in grid on 2.10.3 version

### ISSUE THREAD

**Issue by sugizo** [web2py/web2py#904]
https://groups.google.com/forum/#!topic/web2py/Tog4tdUl400

**Comment by wish7code** [comment]
Same issue with me (although not restricted to the auth table, but also 'regular' lookup tables).
Everything worked properly prior to version 2.10.3..

If you need to know details let me know..

**Comment by niphlod** [comment]
duplicated on https://github.com/web2py/pydal/issues/135 . Closing this as it should have been opened on pydal. @sugizo , @wish7code , please follow the linked issue on pydal instead of this.

**Comment by gi0baro** [comment]
I'm re-opening this until the track of fixed pyDAL.
