### ISSUE TITLE
Dropping reference field of mysql table

### ISSUE THREAD

**Issue by RobinManoli** [web2py/web2py#905]
# Suppose this model has been migrated
db.define_table('tbl',
		Field( 'name' ),
		Field( 'ref', 'reference tbl' ),
	format='%(name)s',
)

# Now I delete the reference field
db.define_table('tbl',
		Field( 'name' ),
	format='%(name)s',
)

# I end up with this error
<class 'gluon.contrib.pymysql.err.InternalError'> (1025, u"Error on rename of './db/#sql-1227_25' to './db/tbl' (errno: 150)")

# Which is the same error as this mysql query generates
ALTER TABLE `tbl` DROP `ref`

# This is the necessary step to drop ref

1.
Do this in mysql
	SHOW CREATE TABLE tbl

	Result:
	CREATE TABLE `tbl` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`name` varchar(512) DEFAULT NULL,
		...
		CONSTRAINT `tbl_ibfk_1` FOREIGN KEY (`ref`) REFERENCES `tbl`...
2.
Do this in mysql:
	ALTER TABLE tbl	DROP FOREIGN KEY tbl_ibfk_1

3.
Now just visit the site and web2py can drop the ref field by itself.

**Comment by mdipierro** [comment]
closing because moved to DAL issues.
