### ISSUE TITLE
Access to web2py plugins

### ISSUE THREAD

**Issue by zvolsky** [web2py/web2py#908]
Seems web2pyslices are unmaintained, without published sources, and generally not working as plugins repository: It is not clear, how to
- access plugin registration (hard),
- what and how fill in in plugin registration (hard),
- how to repair a mistake (not possible?)
From that reason many existing plugins are not registered and most items in plugin list are mistakes.

Could we redirect admin/default/plugins to something which is easier and can be maintained?
Or solve the problem with updating sources of web2pyslices?

**Comment by zvolsky** [comment]
Here more about the problem, from the google group:
https://groups.google.com/forum/#!topic/web2py/cRxPrR1e34Q

========= Niphlod:
Dne čtvrtek 9. dubna 2015 20:52:23 UTC+2 Niphlod napsal(a):
uhm. usually I just:
- login to web2pyslices
- click on "wrote n slices" button (redirects to something like http://www.web2pyslices.com/slice/list?author=some_integer)
- click on my slice title (redirects to something like http://www.web2pyslices.com/slice/show/an_integer/title_slug)
- click on the edit link (redirects to something like http://www.web2pyslices.com/article/edit/an_integer/title_slug)
- update the slice accordingly
- push "publish"

========= me:
Ok.
1) web2pyslices - login   -- Ok, no problem
2) clicking photo togo to profile   -- Ok, no problem
3) clicking "wrote 0 slices"   -- leads to http://www.web2pyslices.com/slice/list?author=2198     # Results: 0
and of course nothing more is possible.

By debugging admin/default/plugins/<myapp> I can get data from web2pyslices about my plugin:
author.id = 2198
article.id = 2018
package_data.id = 38

http://www.web2pyslices.com/slice/show/2018/plugin_manage_groups        # redirects to /home
and same happens with all (=8) possible combinations of:
  2018 - 38
  plugin_manage_groups - plugin-manage-groups
  slice/show - article/edit

So, what next?
Maybe the problem is when author publishes plugin without slice? article? I don't understand the difference between slice and article.

Such published plugin is visible in web2py admin application (as you can see for plugin_MANAGE_GROUPS).
I think most authors of plugins ends in same pitfall, in result leaving the list of plugins completly destroyed.

Of course this is frustration and demotivation for plugin users (such unusable list of plugins) and plugin authors (publish into such list & no possibility change own mistakes),
and in result damage for the name of web2py framework.

So we need to do something here. But I don't know what? Update the web2pyslices application (where are sources? who maintain it?). Change the server and application?
Here could I create a very simple application on pythonanywhere with tables plugin+auth_user and web2py grid - but I don't know if this is proper step. Maybe repairing the problem on web2pyslices is better way?

**Comment by niphlod** [comment]
this should have been fixed by @spametki

**Comment by niphlod** [comment]
closing as @spametki is now aware.
