### ISSUE TITLE
Enable Record Versioning

### ISSUE THREAD

**Issue by gulineli** [web2py/web2py#909]
When enable_record_versioning is enabled records that are referenced by another tables are deleted (is_active=False) without delete the referenced records as expected.

db.define_table('table1',
    Field('field1'),
    auth.signature,
    format = "%(field1)s"
)

db.define_table('table2',
    Field('field1','reference table1'),
    auth.signature
)

auth.enable_record_versioning(db)

t1 = db.table1.insert(field1=1)
t2 = db.table1.insert(field1=t1)

db(db.table1.field1==1).delete()

**Comment by ilvalle** [comment]
Mind that the second insert should be ```t2=db.table2.insert(field1=t1)```
anyway, this is a bug. Record_versioning should fire a cascade delete on the referenced tables as well.
Don't know how many side effects that could have thought.

**Comment by gulineli** [comment]
Sorry you are right.
I have a problem when I try to access the elements of second table I got an error

If you put after the code something like this:
for t in db(db.table2).select():
    print db.table1._format %t.field1

You probably will get the error:
Using a recursive select but encountered a broken reference

**Comment by niphlod** [comment]
this happens because record_versioning happens at the app level, not at the db one.
pydal relies on the database for the referential integrity, so when a row on field1 gets deleted "on the app" it doesn't trigger the actual deletion of all referenced records.
Without versioning that operation is delegated to the database, pydal does nothing about it.

**Comment by gulineli** [comment]
But versioning can be this?

**Comment by niphlod** [comment]
sorry, I don't understand the question... versioning ATM does not take into consideration the referenced tables, for the reason explained before....

**Comment by gulineli** [comment]
Sorry for delay, 
When I use versioning I supposed that if a record is deleted all the linked records are deleted to like this occur without versioning. But, as the deletion as delegating to database I think that when the user use versioning the auth should mark the related records as is_active = False to compensate this problem. 
For fix this I'm using something like this:

class DeleteRelated(object):
    def __init__(self,table):
        self.table = table
  
    def before_delete_callback(self,s)
        # For each record delete all the refered records
        for record in db(s).select():
             for (related_table,*fields) in db[self.table]._referenced_by:
                 q = db[related_table].id>0
                 for field in fields:
                      q = q & db[related_table][field]==record.id
                 db(q).delete()

# Assign a callback for all tables;
for table in db.tables:
    db[table]._before_delete.append(lambda s: DeleteRelated(table).before_delete_callback(s))

Thank you

**Comment by niphlod** [comment]
tracked https://github.com/web2py/pydal/issues/387 from here on
