### ISSUE TITLE
encoding error writing unicode string to postgre

### ISSUE THREAD

**Issue by monotasker** [web2py/web2py#910]
**web2py version**: 2.10.3-stable release
**host environment**: rocket server running on Ubuntu 14.10

I'm running into an error with when I try to write unicode text (outside the Latin ranges) to a regular string field in a postgre database. Since my app is a greek language-learning application this error breaks things completely for me. 

## Unwanted behaviour

When I try, for example, to insert the string 'ἀγοραζε' I get the following error, triggered at pydal/adapters/base.py:

```python
Traceback (most recent call last):

  File "applications/paideia/modules/paideia.py", line 168, in start
    pre_bug_step_id=pre_bug_step_id)
  File "applications/paideia/modules/paideia.py", line 384, in reply
    response_string)
  File "applications/paideia/modules/paideia.py", line 655, in _record_step
    log_record_id = db.attempt_log.insert(**log_args)
  File "/home/ian/web/web2py/gluon/packages/dal/pydal/objects.py", line 745, in insert
    ret =  self._db._adapter.insert(self, self._listify(fields))
  File "/home/ian/web/web2py/gluon/packages/dal/pydal/adapters/base.py", line 729, in insert
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 105: ordinal not in range(128)
```

## How to reproducing the error

I've created a simple app that duplicates the error and attached the packed app here: [web2py.app.unicode_bug_test.w2p](https://files.zenhub.io/5529368e1d1f0c3550ec51c9). After installing the sample app and setting up a postgre db for it:

1. navigate to appadmin
2. attempt to create a new record in the 'lemmas' table 
3. enter non-Latin unicode text in the 'lemma' field (something like 'βλα')

## Version where problem appeared

I'm not certain. The error isn't raised on my production server which is still running 2.9.11

## Setup for minimal sample app "unicode_bug_test"

Since the error doesn't happen with sqlite, I've set up db to connect with a postgre database with the following connection details:

username = 'postgres'
postgre host = 'localhost'
postgre db_name = 'unicode_bug_test'

I've left the db password field empty in the db.py file for obvious reasons (i.e., my local password wouldn't do anyone any good anyway).

[web2py.app.unicode_bug_test.w2p | uploaded via ZenHub](https://files.zenhub.io/5529368e1d1f0c3550ec51c9)

#### The error isn't raised when using a sqlite3 database

So it seems to be postgre specific. Maybe it's actually a problem in the pg8000 adapter?

#### The raw SQL sent by pyDAL to the adapter is fine

The SQL being sent by adapters.base.insert() to the postgre adapter was this:

```sql
INSERT INTO attempt_log(name,user_response,step,score,modified_on,dt_attempted,in_path,uuid) VALUES (19,'ἀγοραζε',773,1.0,'2015-04-10 12:33:25','2015-04-10 16:33:26',657,'5918a65a-6d6f-42c6-9af2-f5d0e313701e') RETURNING id;
```
When I copy that SQL command into pgAdmin execute it the new row is created fine. No errors are raised.

**Comment by kirsn** [comment]
Just tried this out on postgresql db, with psycopg2 driver, and this seems to work. Like you mentioned, this may be a pg8000 issue.

```
d:\code\git\web2py>python web2py.py -S unicode_test
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2015
Version 2.10.4-beta+timestamp.2015.04.18.15.43.12
Database drivers available: psycopg2, pymysql, imaplib, sqlite3, pg8000, pyodbc, mysqlconnector
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: db = DAL('postgres://postgres:password@localhost/unicode_test')

In [2]: db.define_table('t2', Field('name',type='string'))
Out[2]: <Table t2 (id,name)>

In [3]: db.t2.insert(name="ἀγοραζε")
Out[3]: 2L

In [4]: db.t2.insert(name="ἀγοραζε!")
Out[4]: 3L
```

**Comment by monotasker** [comment]
So if it's a pg8000 issue, what does that mean in terms of using web2py until it's fixed upstream? Does it just mean that unicode-heavy apps have to use psycopg2 until the pg8000 maintainers fix the problem?

**Comment by niphlod** [comment]
just need to raise an issue on pg8000, so they can fix it and web2py can pull the fixed version in.........

**Comment by tlocke** [comment]
Hi all, when communicating with the server, pg8000 uses the character set that the server asks it to use (the client encoding). By default the client encoding is the database’s character set (chosen when the database is created), but the client encoding can be changed in a number of ways (eg. setting CLIENT_ENCODING in postgresql.conf). Another way of changing the client encoding is by using an SQL command. For example:

>>> cur = conn.cursor()
>>> cur.execute("SET CLIENT_ENCODING TO 'UTF8'")
>>> cur.execute("SHOW CLIENT_ENCODING")
>>> cur.fetchone()
['UTF8']
>>> cur.close()

I hope this answers the question.

**Comment by niphlod** [comment]
hi @tlocke , thanks for chiming in. Seems that we're already covered ...

https://github.com/web2py/pydal/blob/master/pydal/adapters/postgres.py#L153

**Comment by ilvalle** [comment]
With pg8000 the following:
```
db._adapter.cursor.execute("INSERT INTO tt(vv) VALUES ('ἀγοραζε') RETURNING id;")
```
fails, while
```
db._adapter.cursor.execute(u"INSERT INTO tt(vv) VALUES ('ἀγοραζε') RETURNING id;")
```
works. However pydal sends the first one to the driver. The exception is raised here https://github.com/mfenniak/pg8000/blob/master/pg8000/core.py#L1945

Should we update pydal pg adapter or is it an issue of pg8000?

**Comment by niphlod** [comment]
not sure about "dbapi" specs. maybe @tlocke can chime in, as well as @mfenniak

**Comment by tlocke** [comment]
I think this is a consequence of how Python 2 handles strings. With Python 3 there wouldn't be any confusion. With Python 2, the str type is an ascii encoded binary string. In order to get to a unicode string you'd need to call .decode('ascii'). However that will cause a problem if there are non-ascii bytes in the string, and that's what's happening in this case.

So I don't think there's a problem with pg8000 or web2py, it's just a general Python 2 thing that if you want to use strings that contain non-ascii characters you have to use the unicode string type.
