### ISSUE TITLE
wiki documentation suggestion

### ISSUE THREAD

**Issue by CenterForGovernmentInteroperability** [web2py/web2py#911]
I don't know how to submit or implement tickets.  Can someone please do the follow up for this or delete if not a good suggestion?  Thanks, Alex

SUGGESTION: Add information to wiki documentation stating that migration should be set to "True" when first building wiki so tables can be auto created.

LOCATION: http://web2py.com/books/default/chapter/29/03/overview#The-built-in-web2py-wiki

OLD PHRASING: Here we assume we are starting from scratch from a simple clone of the "welcome" application called "wikidemo". Edit the controller and replace the "index" action with

RECOMMENDED NEW PHRASING: Here we assume we are starting from scratch from a simple clone of the "welcome" application called "wikidemo". FIRST, MAKE SURE IN DB.PY, THE MIGRATION STATEMENT STATES "MIGRATION=True", NOT MIGRATION="FALSE". Edit the controller and replace the "index" action with... 

AFTER THE WIKI IS UP, YOU CAN RESET MIGRATION = False" in db.py

%%%%%%%%%%%%%%%%%%%%

OTHER POSSIBLE ISSUES WITH WIKI

Can't get search to work.  Result is always "no records found"

Seems that any logged on user automatically has edit and manager rights to all pages without being added to auth_groups: "wiki_editor" and "wiki_author".  If I create a new fake user and they are not given admin rights, and they access the wiki page, somehow they automatically get added with "wiki_editor" role in auth_membership.  Could this be something weird that I've done in auth groups or something?

Am using 2.9.11-stable+timestamp.2014.09.15.23.35.11 on windows

thanks!

Alex Glaros

**Comment by CenterForGovernmentInteroperability** [comment]
new info: To make search work, add a tag to one of the pages. Seems search doesn't work for empty tag table.

**Comment by niphlod** [comment]
once https://github.com/mdipierro/web2py-book/pull/286 is in, we may be good to go. Since the "search issue" seems to be fixed, and the title of this issue mentions only documentation, I'll close this. Feel free to reopen in case there are bugs in wiki code.
