### ISSUE TITLE
bootstrap3 formstyle too wide, with popup

### ISSUE THREAD

**Issue by harpingon** [web2py/web2py#917]
Using version:
2.10.3-stable+timestamp.2015.04.02.21.42.07
(Running on Rocket 1.2.6, Python 2.7.5) 

With this code:
    xadb = DAL('sqlite:memory:')
    xadb.define_table('regiontable', Field('region', length=20,label='Region'))

    for r in session.regions:
        print r
        xadb.regiontable.insert(region=r.name)

    form = SQLFORM.factory(SQLField('Region', label='Select a region', length=20,
        requires=IS_IN_DB(xadb,'regiontable.region',orderby=xadb.regiontable.region))
       ,formstyle='bootstrap3_inline'
    )

Both the table and form specify length=20

But the render looks like this:

![wide](https://cloud.githubusercontent.com/assets/2019656/7167457/f93ba13a-e3ac-11e4-8547-d020441e0070.png)

Same with all forms using bootstrap 3, everything looks very wide, (in firefox and chromium)

Looks okay, actually, on a mobile phone and tablet, but on the desktop, not so much.

**Comment by niphlod** [comment]
bs3 is "mobile-first" . you should simply wrap your form within a proper "col-...-number" div.

**Comment by harpingon** [comment]
So this is something we need to do now for all forms, in the latest web2py , by default, for desktop deployments? Because the bootstrap3-inline formstyle is the default now.

**Comment by niphlod** [comment]
I'm not saying is set in stone, but how could web2py rule out a default width that is fine for both large desktops AND narrow mobile screens ? The formstyle is ubiquitous and sets no widths by default, so it adapts to the container you put the form in. What's the problem behind this ?

**Comment by harpingon** [comment]
It took me by surprise because the forms looked very different (w.i.d.e) on the latest w2p bootstrap3, than on the previous release, and initially I didn't know what to do about that, or if it was intentionally that way.
