### ISSUE TITLE
with_alias()

### ISSUE THREAD

**Issue by butsyk** [web2py/web2py#932]
Version 2.10.3-stable+timestamp.2015.04.02.21.42.07

I want to join same table multiple times
so have to make an alias like (as per doc
web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#Inner-joins)
c1 = db.category.with_alias('c1')
...
it hangs on copy.copy(table) at:
pydal/adapters/base.py
def alias(self, table, alias):
  other = copy.copy(table)   # this point 
  
 Traceback (most recent call last):

**Comment by ilvalle** [comment]
can you post the Traceback ?

**Comment by butsyk** [comment]
Tere is no traceback,
only this line:
Traceback (most recent call last):
and the thread stuck - never returns (like recursion issue)
I tried to add __copy__ method to Table class in dal/pydal/objects.py:
class Table(object):
....
    def __copy__(self):
        pass

and this problem is gone (just for testing)

**Comment by butsyk** [comment]
I updated to Version 2.10.4-stable+timestamp.2015.04.26.15.11.54
and the issue is still no fixed.
Explanation:
when copy checks for __setstate__ method
and falls to __getitem__ of the newly created 
copy instance.

pydal/objects.py line 511:
def __getitem__(self, key):
...
	try:
         isgoogle = 'google' in self._db._drivers_available and \
					isinstance(key, Key)

Maybe 'if' instead of 'in', typo?


if hasattr(y, '__setstate__'):

**Comment by ilvalle** [comment]
Do you mind to test this issue against
https://github.com/ilvalle/pydal/tree/storage ?

 Paolo

2015-04-26 20:01 GMT+02:00 butsyk <notifications@github.com>:

**Comment by butsyk** [comment]
I was able to run this without issues:
```python
from pydal import DAL, Field


db = DAL('sqlite://storage.db')
db.define_table('person',
                Field('name'),
                Field('father_id', 'reference person'),
                Field('mother_id', 'reference person'))
 
Father = db.person.with_alias('father')
Mother = db.person.with_alias('mother')
db.person.insert(name='Massimo')
db.person.insert(name='Claudia')
db.person.insert(name='Marco', father_id=1, mother_id=2)
rows = db().select(db.person.name, Father.name, Mother.name,
                   left=(Father.on(Father.id==db.person.father_id),    
                         Mother.on(Mother.id==db.person.mother_id)))
for row in rows:
    print row.person.name, row.father.name, row.mother.name
```

**Comment by butsyk** [comment]
Version 2.10.4-stable+timestamp.2015.04.26.09.05.21
The issue is still open.
