### ISSUE TITLE
Wsgi does not parse request.vars

### ISSUE THREAD

**Issue by HarryR7** [web2py/web2py#937]
I was using FreeBSD9.3/lighttpd/fastcgi/web2py 2.4.5. When I updated my server to Web2py 2.10.3, any variable passed in url after ? was nowhere to be found in request.vars. Including in a new created app.
I tracked down the problem in  having both query_string and QUERY_STRING in the environment displayed by response.toolbar() env.
The one being parsed is 'QUERY_STRING', which is empty,  and 'query_string' which holds the neccesary variables. Seems to be a lower/upper case mixup. 
I managed to fix the problem by adding 2 lines after

                 ...                
                fixup_missing_path_info(environ)
                env['QUERY_STRING']=environ['QUERY_STRING']             #my fix
                env['PATH_INFO']=environ['PATH_INFO']                   #my fix
in gluon/main.py at line 323. 
Please check the implications of the code I added or find another proper fix.

**Comment by niphlod** [comment]
web2py code is fine: it definitely should be the upper-case to be filled (and parsed). I guess it's a problem on lighttpd-fastcgi config on freebsd.

**Comment by HarryR7** [comment]
I was worried on security implications, since QUERY_STRING is an important piece in the security chain. 
If safe, please commit the change, as I don't know (yet) how to do it.

**Comment by HarryR7** [comment]
It may be specific to my configuration, but previous versions had no problems with FreeBSD. It also works on rocket. Maybe the new code wasn't tested with lowercase query_string in environment.
You may close the issue if nobody else complains.

**Comment by niphlod** [comment]
got that, but that piece of code didn't change in the last two years. And the other piece of code that may be involved, that is on gluon/rewrite.py, isn't changed in the last year. It's definitely some config issue (or simply "old" configurations kept around) in your lighttpd/fastcgi combo.
