### ISSUE TITLE
Multiple autocomplete widgets in one form store only in one field

### ISSUE THREAD

**Issue by HarryR7** [web2py/web2py#940]
When a table has more than one field, represented using autocomplete widget, **referencing the same other table**, the generated wigets get confused in which field they have to store the result. 
When you autocomplete the second field, the result is written in the first.

Example:
`db.define_table('point',Field('name','string'))
db.define_table('route',Field('route_name','string'),
               Field('start_point','reference point',widget=SQLFORM.widgets.autocomplete( request, db.point.name, id_field=db.point.id,
	limitby=(0,10),min_length=2)),
                Field('end_point','reference point',widget=SQLFORM.widgets.autocomplete( request, db.point.name, id_field=db.point.id,
	limitby=(0,10),min_length=2))
               )`
Add a few points in db.point using the admin interface then try to add a route in db.route
using the same admin interface or in a controller
`def index():
    grid=SQLFORM.smartgrid(db.route,create=True,editable=True, details=True)
    return dict(grid=grid)`

The javascript magic in SQLHTML.py for the fix should also contain the destination field name,  in my opinion.

**Comment by mau86** [comment]
Hi Harry. I had exactly the same problem. By looking at the code, i found out that the constructor of the AutoComplete widget has a 'keyword' parameter that does just that. Use that parameter by giving two different names to the widgets... et voila!

**Comment by BuhtigithuB** [comment]
Confirm : https://groups.google.com/d/msg/web2py/YBv-gk_D7-U/MPnT4p7pDwAJ

**Comment by BuhtigithuB** [comment]
label:bug
Should be labeled with Bug and Comfirmed

**Comment by BuhtigithuB** [comment]
It can be fix by making id of the authocomplete widget unique 

id=_autocomplete_REFERENCETABLE_FIELDNAME_div

It should use the name of the table and foreing key field name instead of referenced table name and field name to make it unique for a single form...

**Comment by BuhtigithuB** [comment]
Someone can workaround that problem by defining a specific keyword for each foreign key fields:

db.define_table('person',
                Field('name', unique=True, requires=IS_NOT_IN_DB(db,'person.name')),
                Field('country', 'string'),
                Field('age', 'integer'))

db.define_table('thing',
                Field('name', 'string'),
                Field('persona', 'reference person', requires=IS_IN_DB(db, 'person.id', '%(name)s')),
                Field('personb', 'reference person', requires=IS_IN_DB(db, 'person.id', '%(name)s'))
                     )

db.thing.persona.widget = SQLFORM.widgets.autocomplete(request, db.person.name, id_field=db.person.id, **keyword='_autocomplete_thing_persona'**)
db.thing.personb.widget = SQLFORM.widgets.autocomplete(request, db.person.name, id_field=db.person.id, **keyword='_autocomplete_thing_personb'**)

Which was maybe the intent of having keyword attribute... I don't know...

**Comment by BuhtigithuB** [comment]
@mdipierro : This one could be closed depending if the workaround is considered to be what should be done to support the feature request or not... And since their is a workaround refactoring maybe postponed.

**Comment by mdipierro** [comment]
For now the use of the keyword parameter is the best course of action. We will have a new autocomplete form logic eventually.
