### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by mbelletti** [web2py/web2py#941]
It seems that the feature described [here](http://web2py.com/books/default/chapter/29/09/access-control?search=auth#Access-Control-and-Basic-Authentication) in the book doesn't work.

I tried both methods 

    auth.settings.allow_basic_login = True

and

    auth.basic()

 without results.

I tried on the standalone web2py rocket on osx 10.10.3 and on nginx + uwsgi on debian wheezy.

**Comment by mbelletti** [comment]
It is a client problem.

wget doen't work, curl it does.

**Comment by michele-comitini** [comment]
It is a documentation problem I suppose, since the basic auth is without challenge by default (not the standard by HTTP/1.1).

Do following tests:
1.  use --auth-no-challenge invoking wget
2. try to enable by setting basic_auth_realm=True.

in gluon/tools.py:


       def basic(self, basic_auth_realm=False):
            """
            Performs basic login.

           Args:
            basic_auth_realm: optional basic http authentication realm. Can take
                str or unicode or function or callable or boolean.

           reads current.request.env.http_authorization
           and returns basic_allowed,basic_accepted,user.

           if basic_auth_realm is defined is a callable it's return value
           is used to set the basic authentication realm, if it's a string
           its content is used instead.  Otherwise basic authentication realm
           is set to the application name.
           If basic_auth_realm is None or False (the default) the behavior
           is to skip sending any challenge.

           """

**Comment by mbelletti** [comment]
--auth-no-challenge
