### ISSUE TITLE
ldap_auth not working with NoSql databases

### ISSUE THREAD

**Issue by stephenrauch** [web2py/web2py#942]
ldap_auth has a query which contains a join, which will not work on NoSql databases.

Suggested patch, add:

```python
from pydal.adapters.base import NoSQLAdapter
```

change:

```python
db_group_search = db((db.auth_membership.user_id == db_user_id) &
                     (db.auth_user.id == db.auth_membership.user_id) &
                     (db.auth_group.id == db.auth_membership.group_id))
```

to:

```python
if isinstance(db._adapter, NoSQLAdapter):
    # no joins on NoSQL databases, perform two queries
    db_group_search = db(db.auth_membership.user_id == db_user_id)
    group_ids = [x.group_id for x in db_group_search.select(
        db.auth_membership.group_id, distinct=True)]
    db_group_search = db(db.auth_group.id == group_ids)
else:
    db_group_search = db(
        (db.auth_membership.user_id == db_user_id) &
        (db.auth_user.id == db.auth_membership.user_id) &
        (db.auth_group.id == db.auth_membership.group_id))
```

**Comment by jklundell** [comment]
For this kind of thing, I'd rather see an explicit capability test. Perhaps db.canJoin, which looks at a corresponding adapter property. For now, BaseAdapter could return True, and NoSQLAdapter override it to False. The benefit are the typical once of this kind of approach: the test is self-explanatory, and future adapters can override as required.

**Comment by ilvalle** [comment]
@stephenrauch would you create a PR with the proposed fix?
@jklundell, I agree with you, feel free to create a PR in https://github.com/web2py/pydal

**Comment by stephenrauch** [comment]
OK, I'll do a pull request and add the suggested capability test.

```python
def can_join():
    return True
```

**Comment by stephenrauch** [comment]
See https://github.com/web2py/web2py/pull/944 and https://github.com/web2py/pydal/pull/146

**Comment by ilvalle** [comment]
ok, well done.
Just wondering, which nosql backend are you using?

 Paolo

2015-04-24 20:10 GMT+02:00 stephenrauch <notifications@github.com>:

**Comment by ilvalle** [comment]
@stephenrauch since the PR has been accepted, can you close the issue?
