### ISSUE TITLE
show_if raise RuntimeError("Not Implemented Error")

### ISSUE THREAD

**Issue by leonardopf** [web2py/web2py#945]
Using web2py 2.10.4-beta and Python 2.7.9
 a show if raise that exception.
More details on http://pastebin.com/eyP2Jcj0

**Comment by ilvalle** [comment]
The exception is correct because, at the moment the ```>``` operator is not supported by show_if

**Comment by diogommartins** [comment]
show_if is directly connected with css`s Attribute Selectors http://www.w3.org/TR/css3-selectors/#attribute-selectors with does not support the LT (less than) operator. Adding this feature would result if something more than adding 

``` python
if cond.op.__name__ == 'LT':
        return base, "[value<'%s']" % cond.second
```

to show_if(cond) body. By doing so, it would be needed to use some javascript, which i don't think it would fit in the scope of show_if

**Comment by mdipierro** [comment]
You can do it with your own JS 

http://stackoverflow.com/questions/2613648/jquery-selecting-all-elements-where-attribute-is-greater-than-a-value
