### ISSUE TITLE
reset_password changed: adapt documentation

### ISSUE THREAD

**Issue by dbielz** [web2py/web2py#947]
Hi all,
we recently ran into an issue not so easy to identify: on our service site we made the link for the reset password function according to the book on http://web2py.com/books/default/chapter/29/09/access-control#Mail-and-Auth like this: 
`auth.messages.reset_password = 'Click on the link http://' +     request.env.http_host +     URL(r=request,c='default',f='user',args=['reset_password']) +     '/%(key)s to reset your password'`
This worked for the last couple of years until our update from 2.9.12 to 2.10.4. As we finally found, the line in tools.py being responsible for getting the reset key changed: 
```
    diff <new version >old version
    ....
    3015a3014,3015
    >             if not key and len(request.args)>1:
    >                 key = request.args[-1]
    3022c3022
    <             key = request.vars.key
    ---
    >             key = request.vars.key or getarg(-1)
```
So obviously the above passage in the book (and of course in every users installation ...) has to be changed into
`auth.messages.reset_password = 'Click on the link http://' +     request.env.http_host +     URL(r=request,c='default',f='user',args=['reset_password']) +     '?key=%(key)s to reset your password'` 

Please note the change from
    *'/%(key)s ...'*
to
    ***'?key=%(key)s ...'***

By the way: where's the benefit in this change anyway?

Greets, D

**Comment by niphlod** [comment]
if I remember correctly it's less error-prone when dealing with rewrites and such. Having a "var" instead or an "arg" made it more resilient.

**Comment by niphlod** [comment]
PR on the way https://github.com/mdipierro/web2py-book/pull/275
