### ISSUE TITLE
load with ajax=false ignored if url parameter set

### ISSUE THREAD

**Issue by simonm3** [web2py/web2py#948]
{{=LOAD(c='referee', f='grid.load', ajax=False, ajax_trap=True, vars=dict(customer=id), target='referee')}}
{{=LOAD(url=URL(c='referee2', f='grid.load', vars=dict(customer=id)), ajax=False, ajax_trap=True, target='referee2')}}

referee2 is requested with ajax=True despite the parameter ajax=False.

**Comment by niphlod** [comment]
if ajax is false, why are you seeking for ajax_trap = True ?!

**Comment by simonm3** [comment]
i want a component that can be loaded with the page (to save time) but
updated or refreshed via ajax.

**Comment by niphlod** [comment]
not ever been supported!

**Comment by simonm3** [comment]
well it used to work. and if it doesn't then what would be the point in
having ajax_trap=True? If ajax=True then ajax_trap would be true anyway.

**Comment by niphlod** [comment]
Straight from from the book

    ajax_trap is ignored and assumed to be True if ajax=True

**Comment by niphlod** [comment]
If one explicitly sets ajax=False then it seems very odd that this is treated as
ajax=True when the url parameter is set; but not when the url is set with
c=controller, f=function.

**Comment by niphlod** [comment]
@simonm3 : there's another hiccup here, guess due again to the lack of fine-prints in the docs that state

    url, if specified, overrides the values of c, f, args, vars, and extension and loads the
    component at the url. It is used to load as components pages served by other 
    applications (which may or may not be created with web2py).

How can we load url=http://www.google.com without ajax ?

**Comment by simonm3** [comment]
Well in my case I am not loading www.google.com. I am doing this:

url=URL(c=...,f=...)
LOAD(url=url, ajax=False, _url=url)

The expected behaviour would be to "override the values" as stated in the
docs. One would not expect it to ignore the setting ajax=False even if that
were the most common usage.

**Comment by niphlod** [comment]
granted, the docs aren't clear, altough they specify that url is for "pages served by other applications". 

Anyway your usecase is not the only one allowed. Are you saying web2py would need to parse the url and resolve magically if it's loaded from your app or another one ? How could it ?

**Comment by simonm3** [comment]
I think it should just use the parameters provided. No need to parse it or validate it. if url is set use that; or use c,f etc. to form the url.

It should not arbitrarily assume ajax  true when it was explicitly set false.

**Comment by niphlod** [comment]
again, PLEASE note the hiccup: we can't load without ajax something that is external to web2py. 
**if url is set use that** won't work in the majority of cases, EXCEPT for your personal usecase scenario.

**Comment by simonm3** [comment]
Agree it is only a problem where the URL is internal and ajax=False. But
looks like it would be just as easy to make it to work in all cases rather
than just the majority; and to be consistent whether you set url or c,f
etc..

**Comment by niphlod** [comment]
maybe you're missing how much different it is to render a component with ajax or not. When ajax is not involved web2py creates a new environment where the corresponding request is rendered, and then it injects it into the "main" page, to make it happen within a single request. There is a lot of machinery involved that works out ONLY if the request comes from web2py. 

You're asking for "more" consistency for a 10% case scenario that would effectively not be more consistent than the actual even if we can get to implement it, because right now url='something' ALWAYS forces ajax=True. Even if you implement what you're asking, url='something' AND ajax=False would use ajax in some cases and not ajax for others.
I think we'd better stick with proper documentation rather than an hack that will resort in more inconsitency.

**Comment by simonm3** [comment]
>There is a lot of machinery involved that works out ONLY if the request
comes from web2py.

Yes I get that but that is not relevant here as the request DOES come from
web2py so no major change required - just to treat the request the same
whether the address is from the url parameter or the c/f etc.. I am
surprised that would be complex to do but you know the code so you can make
a judgement on that.

>Even if you implement what you're asking, url='something' AND ajax=False
would use ajax in some cases and not ajax for others.

I am suggesting if ajax=False then there should be NO cases where ajax
should be used.

**Comment by niphlod** [comment]
do you prefer raising a syntaxerror right away ?

**Comment by mdipierro** [comment]
@niphlod. Suggestions? I think this is an issue with documentation more than code. Agree?

**Comment by niphlod** [comment]
either a note on the doc suffice, or the code needs to raise something like Syntaxerror. I'm biased towards "we are all consenting adults" and so, towards a note on the book.

**Comment by niphlod** [comment]
Once https://github.com/mdipierro/web2py-book/pull/285 is in, this can be closed.
