### ISSUE TITLE
when ajax_trap=True then component is only partially initialised

### ISSUE THREAD

**Issue by simonm3** [web2py/web2py#949]
For components:

When ajax=True then w2p-data_remote is set to the url. Also you can call component.reload().

When ajax_trap=True then w2p-data_remote is not set and reload does not work.

**Comment by niphlod** [comment]
as for https://github.com/web2py/web2py/issues/948 , reloading a component that has not been loaded though ajax in the first place has never been officially supported, nor documented.

**Comment by simonm3** [comment]
It is not being reloaded. It is being loaded for the first time with
parameter ajax=False which it apparently ignores.

If on the other hand the individual c, f parameters are set then it works
correctly.

**Comment by niphlod** [comment]
I'm a bit lost then. Can you provide a real-case scenario with what is working and what is not, complete with your expectations......taking into consideration that ajax_trap=True exists just to make a form submit via ajax instead of reloading the entire page in case the component was loaded with ajax=False ?

**Comment by simonm3** [comment]
OK. I have a page with customer information that also shows a list of
contacts. The contacts are in a component loaded via LOAD.

I click the add button and add a contact. I want the list of contacts to
then refresh to show the updated list. I may even want other components to
refresh as well.

This all works fine with ajax=True. However it is a bit slow loading the
page as there are 10 components. Much faster with ajax=False.

**Comment by simonm3** [comment]
Apologies that comment above re "being loaded for the first time" relates to a issue 948. So not surprisingly it made no sense here!

**Comment by niphlod** [comment]
so, can we close this ?!

**Comment by simonm3** [comment]
If not currently supported and you do not think useful then yes. I have an
easy workaround anyway.

However for the other one (948) this really should be fixed. If one
explicitly sets ajax=False then it seems very odd that this is treated as
ajax=True when the url parameter is set; but not when the url is set with
c=controller, f=function.

**Comment by niphlod** [comment]
man, you should REAAALLY state clearly:
- what you expect
- what is working
- what is not

when you open a ticket.
