### ISSUE TITLE
gluon.storage.List does not support reverse slicing (i.e. with negative step)

### ISSUE THREAD

**Issue by nursix** [web2py/web2py#955]
Unlike normal lists, gluon.storage.List instances do not support slicing with negative step like [::-1]:

Normal list:

    >>> x = [1,2,3]
    >>> print x[::-1]
    [3, 2, 1]

gluon.storage.List:

    >>> x = List([1,2,3])
    >>> print x[::-1]
    None

This breaks our code, unfortunately :/

**Comment by nursix** [comment]
In fact, it doesn't support step at all:

    >>> x = List([1,2,3,4])
    >>> print x[1:4]
    [2, 3, 4]
    >>> print x[1:4:2]
    None

The problem is probably that __getitem__ doesn't check whether i is a Slice - but simply assumes it's a simple index.

**Comment by nursix** [comment]
Our problem is btw with request.args - we're not using gluon.storage.List otherwise. But we would like to step (backwards) through request.args, and in earlier versions it did behave like a normal list - now that has changed.

**Comment by nursix** [comment]
Please allow me also to say that for request.args the gluon.storage.List behavior is rather confusing and obscuring defects.

Most of our code expects request.args to indeed behave like a list and raise an IndexError when the index is out of bounds - but where it returns None, this would lead to TypeErrors in later passages instead, which are hard to trace back to the actual error.

We have already banned Storage for this exotic behavor - it's much harder to debug these "convenience" objects because they do not raise exceptions like the objects they replace - and for most developers it is totally unexpected that request.args[x] would give None under any circumstances rather than raising an IndexError.

I'm not convinced that this is actually an improvement - I think it makes it less safe and harder to debug.

**Comment by cassiobotaro** [comment]
About slice, you are right, i added these tests  and i fix early as possible. But about args[x], docs say: " Like a regular python list but a[i] if i is out of bounds returns None instead of `IndexOutOfBounds`."   Then i don't think it's unexpected.
But you have a interesting point:

"
We have already banned Storage for this exotic behavor - it's much harder to debug these "convenience" objects because they do not raise exceptions like the objects they replace - and for most developers it is totally unexpected that request.args[x] would give None under any circumstances rather than raising an IndexError.

I'm not convinced that this is actually an improvement - I think it makes it less safe and harder to debug.
"

Let's discuss that.

**Comment by nursix** [comment]
Ok, maybe I missed the updated docs about request.args. We've been using web2py for many years, and at some point I've just stopped reading it.

However, for request.args[x] in particular I don't think it is very intuitive to have it return None for an invalid index while it's mutable.

Secondly, there is no way to distinguish between a real None in the list, and an invalid index - unlike for Storage where Storage[x] = y always works regardless whether x is a valid key or not, this doesn't quite work for a List instance. It's a bit inconsistent to have List[x] return None, but List[x] = y raise an IndexError.

Anyway, it is still problematic that these objects do not behave like their Python pendants.

Library functions which normally operate on Python dicts or lists can not generally be passed Storage or List instances (unlike your docs suggest) - because these library functions where they are not made specifically for web2py may rely on certain exceptions to be raised.

The None that is returned often leads to exceptions in a later passage where that type isn't expected (like the TypeError that I mentioned), and is then hard to trace back to the original IndexError and the fact that this was caused by an invalid index.

But much worse than that is the situation where None is actually acceptable within the library function, in which case no error is raised but an invalid result produced. That is a major risk for database integrity - and *that* is the reason why we have banned Storage. 

I think it is generally risky to increase the distance to impact of exceptions - and if you look at it from that perspective, the convenience pattern to not raise an exception but return None is nothing but delaying the exception: the extra handling of the case where the index is out of bounds (List) or the key doesn't exist (Storage) is still required in many cases.

But the "like a Python dict/list" suggestion obscures that fact and makes people believe that this is taken care of while in fact it is not (to the contrary, it is /intentionally/ not). Moreover - there is no easy option to suppress that behavior and actually distinguish the case without introspecting the object (which in the case of Storage in particular isn't as easy as it sounds).

Therefore, we have decided to enforce dicts for Storage wherever dict-behaviour may be expected, and we may need to do so with List as well. Unfortunately, that doesn't exactly contribute to better performance :/

**Comment by nursix** [comment]
However - don't get me wrong: not intuitive doesn't mean wrong.

I just wonder whether it is really necessary for List to not raise IndexErrors at all. I could see it as just equally convenient to have:

    request.args(2)

suppress the exception and return None, whilst:

    request.args[2]

would behave like a normal Python list and still raise the IndexError. It did so anyway until recently when it got "fixed" ;) so no major impact just yet?

Anyway - slicing with step would be what we need right now. The rest is theory at the moment ;)

**Comment by nursix** [comment]
Note that the IndexError was still raised by List instances as recently as in 2.10.4-stable ;) so your documentation may have been a wee bit ahead of the facts.

**Comment by cassiobotaro** [comment]
@nursix  I agree with you, lets raise IndexError. I 'll change this and add more tests .
I have to change the documentation too to avoid any confusion. thanks for you feedback.

**Comment by nursix** [comment]
Yeah, many thanks for your support ;) [always critical: http://nepal.sahana.io]

**Comment by ilvalle** [comment]
@nursix, do you think the issue has been fixed ?

**Comment by nursix** [comment]
I'll test again later today and get back to you (sorry, can't action immediately)

**Comment by nursix** [comment]
Yes, the problem is fixed now. Closing this.
