### ISSUE TITLE
RecordUpdater in gluon/packages/dal/pydal/helpers/classes.py does not trigger _before_update and _after_update

### ISSUE THREAD

**Issue by pangard** [web2py/web2py#957]
the RecordUpdater.__call__ method in gluon/packages/dal/pydal/helpers/classes.py does not call the functions in _before_update and _after_update, like Set.update does, for instance.

I think it would be more consistent to call those functions.

The same applies to RecordDeleter.

**Comment by cassiobotaro** [comment]
@pangard  pydal now is a separated project, move this issue to https://github.com/web2py/pydal/issues

**Comment by niphlod** [comment]
closing this, as it's tracked in https://github.com/web2py/pydal/issues/177

**Comment by pangard** [comment]
sure, you may close it. thanks!
