### ISSUE TITLE
Overhaul of cache.redis connection algorithm / 'fail-gracefully-if-server-unavailable' flag.

### ISSUE THREAD

**Issue by houdinihound** [web2py/web2py#958]
Original issue reported as cache.redis fails with a traceback when the server is unavailable.  Expected behaviour was to have it fail gracefully and respond with the "key doesn't exist" behaviour and continue processing.

Niphlod pointed out use case for it to fail with traceback but also agrees that a flag can be added to allow user choice of failure mode on establishing the Redis connection.  For example, a new flag `fail_gracefully=True` would not cause a traceback and would respond as if key didn't exist if the redis server is unavailable.  If set to False then the traceback would occur.

There was also an issue pointed out in the connection delay on unavailable being 30 seconds before action taken, which, for the fail gracefully option should be a lot shorter (5 seconds, say).

Niphlod then pointed out that he would like to overhaul the whole Redis connection algorithm at which point the flag could be added and requested an issue be opened here.

Original conversation thread on Google Groups:   
https://groups.google.com/forum/?fromgroups#!topic/web2py/3lvoUmzuo3o

**Comment by mdipierro** [comment]
@niphlod was this taken care of.

**Comment by niphlod** [comment]
not yet
