### ISSUE TITLE
Deadlock in cache.py/CacheOnDisk in R 2.10.4

### ISSUE THREAD

**Issue by bletourmy** [web2py/web2py#966]
found a blocking issue in our app with some image download after upgrading from 2.9.12 to 2.10.4
deadlock in CacheOnDisk class in case of exception in our cache callback function, normally handled in our app
without any issue until now.

the new file_locks introduced in 2.10.1, (3e46e985bf15) acquired before the cache app callback ( value = f() )
with self.storage.acquire(CacheAbstract.cache_stats_name) 
Is never released in case of exception in f()
then next call to the CacheOnDisk during same request will block the thread indefinitely.

(CacheInRam should not have the same issue as self.locker.release() is released before f())

- proposed fix to follow

Bernard Letourmy

**Comment by ilvalle** [comment]
Can you write a test for this issue in ```gluon/tests/test_cache.py```
