### ISSUE TITLE
IS_MATCH validator bug with unicode

### ISSUE THREAD

**Issue by alex0834** [web2py/web2py#968]
there is a bug when the IS_MATCH validator is used with is_unicode=True
If the input contains non-ascii characters and is already unicode an UnicodeEncodeError occurs:

    def __call__(self, value):
        if self.is_unicode and not isinstance(value,unicode):
            match = self.regex.search(str(value).decode('utf8'))
        else:
            match = self.regex.search(str(value))

this happens because the else branch is executed. A possible fix:

    def __call__(self, value):
        if self.is_unicode:
            if not isinstance(value,unicode):
                match = self.regex.search(str(value).decode('utf8'))
            else:
                match = self.regex.search(value)
        else:
            match = self.regex.search(str(value))

**Comment by mdipierro** [comment]
thanks. fixed
