### ISSUE TITLE
Can't type lowercase "b" in the interactive console on OSX

### ISSUE THREAD

**Issue by ailnlv** [web2py/web2py#969]
I just tried running the interactive console for the first time by doing

    ➜ ./web2py.py -S welcome -M
    ...
    >>>
The first thing I tried typing was "db", but as soon as I hit "b" I just got an alert. Uppercase B works fine. [This seems to be a common issue with python](https://superuser.com/questions/297527/cant-type-the-b-letter-in-python-shell-in-os-x), but so far I've been unable to fix it, as it only occurs withn web2py.

**Comment by mdipierro** [comment]
This is not a web2py issue. What shell are you using? Anaconda?

**Comment by ailnlv** [comment]
The default shell:

    >>> import sys
    >>> sys.version
    '2.7.9 (default, Dec 19 2014, 06:00:59) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]'

The fix I posted was accepted and merged a while ago, so the issue should probably be closed.

**Comment by mdipierro** [comment]
ok. Thanks.
