### ISSUE TITLE
with_alias()

### ISSUE THREAD

**Issue by butsyk** [web2py/web2py#971]
https://github.com/web2py/pydal/issues/143
https://github.com/web2py/web2py/issues/932
Closed non-fixed issue.

Version 2.10.4-stable+timestamp.2015.04.26.09.05.21
The issue is still open.

**Comment by ilvalle** [comment]
Web2py 2.10.4 doesn't contain the mentioned fix yet. Did you try the master version of pydal before re-opening the issue? Mind that web2py master doesn't contain the fix either. you have to manually update pydal.

**Comment by butsyk** [comment]
I replaced gluon/packages/dal with master of https://github.com/web2py/pydal
Yes, its fixed. It would be great to have in web2py.
Thank you.
