### ISSUE TITLE
Autotypes and unicode strings

### ISSUE THREAD

**Issue by remcoboerma** [web2py/web2py#978]
Couldn't find anything on this on the list. But found that the `SQLFORM.dictform()` doesn't function properly when providing a `dict(key=u"some unicode")` since the unicode type isn't recognized in the `SQLFORM.AUTOTYPES` dictionary and therefor will drop the key,value pair. 

Here's a patch to solve it: 

```diff
--- gluon/sqlhtml.py	(revision 1e66fa3a93560aa5d32c27a6b1b7251e0dd8a428)
+++ gluon/sqlhtml.py	(revision )
@@ -1691,6 +1691,7 @@
 
     AUTOTYPES = {
         type(''): ('string', None),
+        type(u''): ('string',None),
         type(True): ('boolean', None),
         type(1): ('integer', IS_INT_IN_RANGE(-1e12, +1e12)),
         type(1.0): ('double', IS_FLOAT_IN_RANGE()),
```

**Comment by mdipierro** [comment]
Thanks. fixed.
