### ISSUE TITLE
Admin application: can't access directories with space in directory name

### ISSUE THREAD

**Issue by mmihaltz** [web2py/web2py#980]
This bug concerns the default admin application (web2py administrative interface).

If there is a directory on the host within the application's directory whose name contains a space character (eg. "/home/user/web2py/applications/example/private/a b/") then when editing the application using the admin application in a browser (eg. https://hostname.com/admin/default/design/example), I cannot access the contents of the directory "private/a b/". 

In the admin application I can see under section "Private Files" that there is a folder named "a b/". However, clicking on the folder name "a b/" will not open up its contents, as opposed to when there's no space in the directory name.

Note: inspecting the HTML source of https://hostname.com/admin/default/design/example I can see that the contents of folder "a b/" are already included ("a b/test.txt"):

```html
<li class="folder">
            <a href="javascript:collapse('private__a b');" class="file">a b/</a>
            <ul id="private__a b" style="display: none;" class="sublist">
        <li>
            <span class="filetools controls">
                <a class="button editbutton btn btn-mini" href="/admin/default/edit/examples/private/a%20b/test.txt?id=private"><span>Edit</span></a> <a class="icon delete" data-original-title="Delete this file (you will be asked to confirm deletion)" data-placement="right" href="/admin/default/delete/examples/private/a%20b/test.txt?id=private&amp;id2=private&amp;sender=design%2Fexamples" rel="tooltip"><img src="/admin/static/_2.10.4/images/delete_icon.png" /><span>Delete this file (you will be asked to confirm deletion)</span></a>
            </span>
            <span class="file">
                <a href="/admin/default/peek/examples/private/a%20b/test.txt?id=private">a b/utc8_test.txt</a>
            </span>
        </li>
            </ul>
        </li>
```

So it seems there's a Javascript error opening that `<ul>` in the browser.

Note2: I am using a 3rd-party library in my web2py application that expects a certain directory name containing a space character so using a different name is not an option unfortunately.

web2py version: 2.10.4-stable+timestamp.2015.04.26.15.11.54
host OS's tested: MAC OS X, Ubuntu Linux

thanks

**Comment by sp1d3rx** [comment]
So this is an error related to an invalid ID being assigned to the UL.

HTML4 is more restrictive, but HTML5 says pretty much it can be anything but it must not contain spaces.

http://www.w3.org/TR/html5/dom.html#the-id-attribute

*The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters.*

**Comment by mmihaltz** [comment]
Thanks for the fix! :)

**Comment by mdipierro** [comment]
No. Thank you!
