### ISSUE TITLE
grid loaded with LOAD(..., ajax=False) raise a TypeError: sequence item 0: expected string, long found

### ISSUE THREAD

**Issue by mbelletti** [web2py/web2py#982]
Web2py `2.10.4-stable+timestamp.2015.04.26.15.11.54`

For example:

    db.define_table('parent',Field('nome','string'))
    db.define_table('childs',Field('idparent','integer'),Field('nome','string'))

if in my view I do something like that:

    {{for p in parent:}}
    {{=LOAD(c='default', f='childs', extension='load', args=[p.id], ajax=True)}}
    {{pass}}

all is ok, BUT if I set **ajax=False**:

    {{for p in parent:}}
    {{=LOAD(c='default', f='childs', extension='load', args=[p.id], ajax=False)}}
    {{pass}}

I get an exception in `sqlhtml.py` around line 2110:

        if user_signature:
            if not (
                '/'.join(str(a) for a in args) == '/'.join(request.args)

    TypeError: sequence item 0: expected string, long found

**Comment by niphlod** [comment]
if the error is coming from sqlhtml.py it has nothing to do with LOAD and much to do with grid....

**Comment by mbelletti** [comment]
I'm sorry. Wrong title. 
The problem show up when the grid is loaded with LOAD(..., ajax=False)

model: db.py
    
    db.define_table('parent',Field('nome','string'))
    db.define_table('childs',Field('idparent','integer'),Field('nome','string'))

controller: default.py
```
def index():
    parent = db(db.parent).select()
    return dict(parent=parent)

@auth.requires_login()
def childs():
    idparent = request.args(0)
    q = (db.childs.idparent==idparent)
    grid = SQLFORM.grid(q)
    
    return grid
```

view: default/index.html

```
{{left_sidebar_enabled,right_sidebar_enabled=False,('message' in globals())}}
{{extend 'layout.html'}}

{{for p in parent:}}
{{=LOAD(c='default', f='childs', extension='load', args=[p.id], ajax=True, user_signature=True)}}
{{pass}}

{{for p in parent:}}
{{=LOAD(c='default', f='childs', extension='load', args=[p.id], ajax=False, user_signature=True)}}
{{pass}}
```

**Comment by niphlod** [comment]
figured as much. Did you read this section of the book already http://web2py.com/books/default/chapter/29/07/forms-and-validators#Using-requests-args-safely ?

**Comment by mbelletti** [comment]
Maybe I missed the point. 
What I'm trying do is to render my grids all together and ajax=False seems to be the way to go, **but** simply changing ajax=False doesn't work. Is that the designed behaviour?

Anyway filtering args as you suggested:

   grid = SQLFORM.grid(q, args=request.args[:1], formname='t%s' % idparent)

raise the same exception:

```
Traceback (most recent call last):
  File "/Users/max/Documents/ Work/python/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/Users/max/Documents/ Work/python/web2py/applications/test/controllers/default.py", line 67, in <module>
  File "/Users/max/Documents/ Work/python/web2py/gluon/globals.py", line 403, in <lambda>
    self._caller = lambda f: f()
  File "/Users/max/Documents/ Work/python/web2py/gluon/tools.py", line 3583, in f
    return action(*a, **b)
  File "/Users/max/Documents/ Work/python/web2py/applications/test/controllers/default.py", line 63, in childs
    grid = SQLFORM.grid(q, args=request.args[:1], formname='t%s' % idparent)
  File "/Users/max/Documents/ Work/python/web2py/gluon/sqlhtml.py", line 2110, in grid
    '/'.join(str(a) for a in args) == '/'.join(request.args) or
TypeError: sequence item 0: expected string, long found
```

**Comment by mdipierro** [comment]
fixed
