### ISSUE TITLE
web2py-2.11.1 linked to a broken PyDAL (UnicodeEncodeError with postgres/psychopg2)

### ISSUE THREAD

**Issue by nursix** [web2py/web2py#986]
web2py-2.11.1 is linked to a broken PyDAL version.

The particular issue is that the postgres adapter with psychopg2 returns a unicode for expressions, which then breaks BaseAdapter.expand for all WHERE expressions containing non-ASCII characters:

In adapters/postgres.py:

    def adapt(self, obj):
        if self.driver_name == 'psycopg2':
            rv = psycopg2_adapt(obj).getquoted()
            if isinstance(rv, bytes):
                return rv.decode("utf8") # <= here, returns a unicode
            return rv
        elif self.driver_name == 'pg8000':
            return "'%s'" % obj.replace("%", "%%").replace("'", "''")
        else:
            return "'%s'" % obj.replace("'", "''")

In adapters/base.py:

        return str(rv) # <= breaks for unicode with non-ASCII characters

Obviously, this is a bit of a blocker for PostgreSQL-based deployments with psychopg2 (99% of all our deployments).

A patch for Python 2.x could be this:

In adapters/postgres.py:

    def adapt(self, obj):
        if self.driver_name == 'psycopg2':
            rv = psycopg2_adapt(obj).getquoted()
            if isinstance(rv, unicode):
                return rv.encode(self.db_codec) # <= make sure it always returns an encoded str
            return rv
        elif self.driver_name == 'pg8000':
            return "'%s'" % obj.replace("%", "%%").replace("'", "''")
        else:
            return "'%s'" % obj.replace("'", "''")

I've tried to report the issue to PyDAL, but there doesn't seem to be any priority for fixing this, so I was told that it will take weeks before a fix becomes available in web2py :/

Hence, question: should 2.11.1 be downgraded to the previous PyDAL release?

**Comment by nursix** [comment]
I should probably say that apart from this bug, web2py-2.11.1 with PyDAL-15.05.26 did pass all our tests, so this is the only problem we found. Thus, if it could be fixed in PyDAL quickly, that would be even better.

**Comment by niphlod** [comment]
I see no major issues on fixing it, making a test that will helpthe bug not come back (regression test) and release a new web2py version.

**Comment by niphlod** [comment]
this has been fixed with 2.11.2
